### ISSUE TITLE
Adding Optional Kanban Features

### ISSUE THREAD

**Issue by orges** [wekan/wekan#116]
Adding Kanban features (with some settings parameter enable/disable) would be really cool.  Otherwise we can't call it a Kanban Board.

Settings allows you to do:

*  Control resource sharing [ That person can not work on this card A at the same time with card B ] 
*  Control workload capacity for the card and column [ That card/column can hold x people ]
*  Restrict Flow [ card A can not be dragged to column 3 without visiting column 2 ]
*  Release planer [ According to current cards earliest release can be on dd.mm.yyy ]
*  etc...

**Comment by andreioprisan** [comment]
+1 to restrict flow and release planer.
Resource and workload planning is an entirely different feature set that requires user management functionality.

**Comment by mquandalle** [comment]
Since the release of Wekan v0.9, I try to keep the GitHub issues tracker exclusively for bug reports and specified feature requests — the goal for me being to close the issue as soon as possible. For more general discussions about Wekan (that will stay open) I encourage you to post on [our new forum] (http://discuss.wekan.io).
