### ISSUE TITLE
Using the server separate from client?

### ISSUE THREAD

**Issue by danielmhair** [wekan/wekan#1208]
NOTE: I understand that I did not use the format suggested for an issue, but since this is a question more than an issue, I wrote it without the format.

I really love Wekan, however, I would like to contribute, but in a different way. I have a lot of experience in Angular and I could see a lot of integrations with Wekan if it was in Angular. I would love to use the server implementation as a standalone server and then use its endpoints to develop an open-source angular app that uses Wekan's features.

Note: the client would not be a replica of Wekan. Because it would be a separate angular app, the design would be tweaked to match Material standards (using Angular Material) and of course, tweaks to my liking. I think this would interest those with the Angular passion. I have looked into Meteor Client Bundler that might accomplish this:
https://blog.meteor.com/leverage-the-power-of-meteor-with-any-client-side-framework-bfb909141008

But since I have no experience with Meteor, I'm hoping someone can at least help me know:

**Would it be easy to separate Wekan's server?** This way any client can be used

**Comment by ocdtrekkie** [comment]
_Beyond being a little mystified why anyone would intentionally apply Material to something... like... intentionally..._

There has been some work on an API for Wekan, though right now I believe it has a single authentication capability with admin-like ability, so users can't really use it. Presumably the ideal thing would be to expand the capabilities of this API so that users can easily get the appropriate access rights to their boards over it, and then build third party apps on that API.

I have no idea how much would need to be changed to use Meteor Client Bundler. Presumably if there isn't a lot (any?) code change to the server side required to use it, you could just... point your client at the Wekan install? I suspect either way, you're going to have to learn how Meteor works in order to implement this. The primary thing your client needs to be able to consume is the Meteor DDP: https://blog.meteor.com/introducing-ddp-6b40c6aff27d

**Comment by ocdtrekkie** [comment]
Having a good "official" way to built clients for Wekan is probably a really good idea, since mobile apps are commonly requested. Though I am not sure that requires separating the Wekan web UI from the server components.

**Comment by danielmhair** [comment]
I agree. It probably doesn't require separation of the server and client. I just wondered whether having them separate could help others integrate their client easier. Actually, to not worry about changing code but still have the ability to run the server separately, have a command in package.json that will run only the server, allowing other clients to use do. This way, only the server code runs.

**Comment by danielmhair** [comment]
And thank you for the information. This is my first time with meteor. So far, I'm intrigued. Especially Meteor  DDP.

**Comment by xet7** [comment]
@danielmhair 

**1.** 

Meteor etc frameworks used bring so much functionality, that way actual Wekan code is only about 9000 lines. I'm not sure is meteor style code replaceable with Vanilla Javascript or Typescript.

I would recommend that you start with adding info to [Developer Documentation](https://github.com/wekan/wekan/wiki/Developer-Documentation) about Wekan directory structure, inner workings etc, so there would sometime be enough info to actually do some replacement. Currently we have only done incremental improvements, because [original author of Wekan already got tired trying to reimplement Wekan](https://github.com/wekan/wekan/wiki/FAQ#what-was-wekan-fork--wefork), so I needed to continue as a new maintainer. I would recommed you to think how much time you have available.

**2.**

https://github.com/wekan/wekan/wiki/Features#api

https://github.com/wekan/wekan/labels/API%3AREST

**Comment by danielmhair** [comment]
Sorry, what I was meaning, is to use Angular (for the UI), and then make it to where you can use Wekan's API, then add a few files that allow Typescript servers to import the library and use it (once that is possible). So its not vanilla js or ts. Its with a framework that will dramatically reduce the amount of work to make it.

Yeah, I have been contemplating how much time I have. I have already started building my own Trello/Wekan UI in angular, so that is already underway. Its more the API/Server part that I am trying to decide on (Wekan, Restyaboard, etc). I would want to add some more features to Wekan, if I do decide to go this way. 

Thank you for those links. I will look into them and see what I can do.
