### ISSUE TITLE
Cover cannot be edited on copied card

### ISSUE THREAD

**Issue by ryangorley** [wekan/wekan#1218]
## Issue
**Impacted version**: 0.37

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method: Docker (via Cloudron.io)

**Problem description**:
When copying a card with an attachment applied as a cover, the cover is copied to the new card, but there are no attachment options to remove the cover.

**Comment by ocdtrekkie** [comment]
This is probably a CC: @frmwrk123 thing.

**Comment by GhassenRjab** [comment]
@frmwrk123 

At the moment only checklists and comments are being copied to new card.
We see the cover in the newly copied card because it took the coverId (a card field) from original card and it references to the cover of the original one. If any changes happen to the attachment (cover) of the original card, it will affect the cover of the copied one.

So the solution would be to copy attachments of original card into the new card and edit the coverId with the new id of copied attachment (which is the cover in the original). I hope this gives you a heads up.

Also, I have a suggestion. When copying checklists, comments and attachments from original card, use direct method to circumvent before and after hooks of corresponding models. In other words use this `Checklists.direct.insert(checklist)` instead of this `Checklists.insert(checklist)`. This way you will prevent creating new activities automatically and you will be able to copy old card activities too without the risk of duplicating data. So after copying the old activities, you may add a new activity at the end saying '_user_ copied _cardName_ from _oldList_ to _newList_'.
The scenario looks very similar to when importing Wekan boards, you may look at wekanCreator file in wekan/models/wekanCreator.js it will be of help.

**Comment by xet7** [comment]
@ryangorley 

Please test newest Wekan. Is this already fixed?

**Comment by ryangorley** [comment]
Sorry for not reporting back earlier, it's working great. Thanks!
