### ISSUE TITLE
Wekan member mapping in Trello import

### ISSUE THREAD

**Issue by soerenk** [wekan/wekan#1230]
## Issue
**Impacted version**: 0.37.0~2017-09-09 (Sandstorm)

**Server Setup Information**:
* Operating System: Debian 9
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): sandstorm 214

**Problem description**:
- Setup a new server
- Use (only) LDAP as a login provider.
- Don't have all users from the Trello board as a user in sandstorm.
- Create a new Wekan grain and add users for later mapping.
- Import an old board from Trello with 1 or more users which don't have a sandstorm user.
- Map all possible users. Leave the other users on default.

**Result:** Every activity is mapped to the import user. Other users are removed in Wekan and can't be add again. They still should have access shared over sandstorm but get “board not found” if they try to load the board. Remove access and sharing again doesn’t work.

**Expected behaviour:** Map activities to the configured user. Leave all users in Wekan overview or at least access through sandstorm. Map not existing users to the name of the old Trello user name.

**Comment by dzampino** [comment]
I'm having the same "board not found" after a Trello import.

On both 0.37.0.2017-09-09 (Sandstorm) and 0.41.0.2017-09-25 (Sandstorm)

**Server Setup Information:**
Operating System: CentOS 7
Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): sandstorm 214

**Problem description:**
Setup a new server
Use (only) LDAP as a login provider.
Import an old board from Trello.
Map the one user (myself) to myself.

**Result:**  
Board seemingly acts normally. Open closing grain and reopening it, I get the "board not found" error.

**Expected behavior:** 
Expected board to load.

**Comment by xet7** [comment]
Moved to #1430
