### ISSUE TITLE
"You have an unsaved description" doesn't go away after saving

### ISSUE THREAD

**Issue by uusijani** [wekan/wekan#1287]
## Issue
**Impacted version**: 0.49

**Server Setup Information**:

* Operating System: Ubuntu 16.04
* Deployment Method: snap
* ROOT_URL environment variable (Is there a subfolder?): https://my-domain.com/kan (yes)

**Steps to reproduce**:
1. Create a card
2. Click the description field's Edit link, enter some text
3. Click (for instance) on the comment field, prompting Wekan to show "You have an unsaved description" in the description (with View it/Discard links)
4. Click the description field's Edit link again, click Save

**What happens:**
The description field still shows "You have an unsaved description" with the just saved description text. The only way to make the warning go away is to select the "Discard" link.

**What I expect to happen:**
I'd expect the "You have an unsaved description" notice to disappear when the description is saved.

**Comment by TK009** [comment]
This bug is still reproducible, at least by pressing escape. I managed to lose some of my edits the first time it happened, with the following steps:
1. Create a card
2. Click the description field's Edit link, enter some text
3. Press Esc, prompting Wekan to show "You have an unsaved description" in the description (with View it/Discard links)
4. Click the description field's Edit link again, edit or enter more text, click Save
5. Click "View it", shows the older version of description
6. If you don't notice the wrong version and click Save instead of X, you will lose the newer edits.
