### ISSUE TITLE
Critical failure when file missing from tempstore

### ISSUE THREAD

**Issue by GavinLilly** [wekan/wekan#1298]
## Issue
**Impacted version**: 0.41

**Server Setup Information**:

* Operating System: Red Hat Enterprise Linux 7.4
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): 3x Wekan instances on separate servers deployed using tarball release. Nginx load balancer. 3x MongoDB instances as replicaSet
* Node Version: 4.8.4
* MongoDB Version: 3.2.10
* ROOT_URL environment variable (Is there a subfolder?): https://wekan.internal.Corporate.Domain/

**Problem description**:
Today we experienced a critical failure with Wekan. The Wekan process had failed and was unable to restart due to a missing entry in MongoDB. The following error message was printed from Wekan [Error message](https://gist.github.com/GavinLilly/94f8a51722bf2cb4a1112f3e11055dac).

During debugging I found that the following query was the cause of the error message (note this was taken from the MongoDB system profile [Query](https://gist.github.com/GavinLilly/65b700e05110f12f2b7bfefd32a98034).

I believe Wekan found the fileId to search for by running this [this](https://gist.github.com/GavinLilly/c22b1e1c7c8e17111b1c06528d7613a4) query. This appears to list all files that have started to upload but did not finish.

It appears that a document for the upload existed in the cfs.attachments.filerecord collection but the corresponding document did not exist in the cfs_gridfs._tempstore.files collection, causing the failure.

The workaround to get Wekan operating again was to manually delete the corresponding document from the cfs.attachments.filerecord collection.

Expected behavior would be for Wekan to either remove the document from the cfs.attachments.filerecord if it can't find the corresponding record in the cfs_gridfs._tempstore.files collection or to flag the temporary files as missing to the end user inside the Wekan interface. The Wekan application as a whole shouldn't be failing from a missing upload/attachment.

**Comment by xet7** [comment]
@GavinLilly 

Thanks a lot for tracking this down this bug!

Fixing this would probably also help with Wekan on Sandstorm, because we are currently tracking down bug why Wekan grain does not start on Sandstorm. There has also been couple of cases where Wekan grain on Sandstorm gets "corrupted" and does not work anymore. I hope fixing this will help in all those cases.

We will try to fix this in near future.

**Comment by nztqa** [comment]
Related 
 - https://github.com/CollectionFS/Meteor-CollectionFS/issues/408
 - https://github.com/CollectionFS/Meteor-CollectionFS/issues/731

**Comment by xet7** [comment]
@nztqa 

Would it be possible to somehow catch the error before Wekan crashes and delete the corresponding document from the cfs.attachments.filerecord collection ?

**Comment by nztqa** [comment]
@xet7 
I’m afraid I don’t know.

**Comment by nooitaf** [comment]
There is a pull request  to fix those issues. https://github.com/CollectionFS/Meteor-CollectionFS/pull/914
Would appreciate some extra eyes on it  :)

**Comment by xet7** [comment]
Today this bug happened to someone that notified me. Because of this bug, WeKan did not start.

This error is related to duplicate keys in cronHistory table https://github.com/wekan/wekan/issues/3378 . It was fixed by deleting duplicate entries.

From @nooitaf above:

> There is a pull request  to fix those issues. https://github.com/CollectionFS/Meteor-CollectionFS/pull/914
> Would appreciate some extra eyes on it  :)

Looking at those changes at https://github.com/CollectionFS/Meteor-CollectionFS/pull/914/files ,
it looks like changes to `temp.keys` etc like this https://github.com/wekan/wekan/blob/master/packages/wekan-cfs-temp-store/tempStore.js#L304 are already in WeKan.

If someone knows how to prevent these duplicates, PRs very welcome. Thanks!

**Comment by xet7** [comment]
To fix this:

> We've deleted the entries from cfs.attachments.filerecord and their chunks from the chunk collection.
> We've used the following query to determine which files were the culprits.

```
db.getCollection('cfs.attachments.filerecord').find({"uploadedAt" : {
"$exists" : true
},
"copies.attachments" : null,
"failures.copies.attachments.doneTrying" : {
"$ne" : true
}})
```

**Comment by xet7** [comment]
That above command only lists those unfinished uploads. For example, if there is one, it needs to be deleted like this:
```
db.getCollection('cfs.attachments.filerecord').deleteOne({'_id': 'abcd1234'})
```

**Comment by xet7** [comment]
Better solution is to sometime try to delete all of those that are found automatically, when starting WeKan.
