### ISSUE TITLE
Docs: How do/should attachments work?

### ISSUE THREAD

**Issue by richb-hanover** [wekan/wekan#1328]
**Update, and sort of solved:** See the next message to see my current thinking.

## Issue
**Impacted version**: Current (9Nov2017) Wekan on Docker from https://github.com/wekan/wekan-mongodb

**Server Setup Information**:

* Operating System: OSX 10.12.6
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): docker image
* Node Version: default
* MongoDB Version: default
* ROOT_URL environment variable (Is there a subfolder?): localhost:8080

**Problem description**:

- It occurs to me that I would like to attach documents (images, Word or Excel) to a card, then let it percolate through the Wekan flow. I could then make cards with, say, the "Latest Projection spreadsheet" for others to study
- I don't see an obvious "front door" way to do this - it would be simple to drag a document to the card, and have it automatically added.
- I found the card's Edit Attachment, which leads to Computer/Clipboard/Drag and Drop, but don't see that the attachment has "stuck" to the card in any way that others could find the attachment.

Do attachments work like this? Am I doing it wrong? 

PS I should say that the underlying GUI of Wekan is _very_ sexy, and I like it a lot...

**Comment by richb-hanover** [comment]
**Update: Never mind...** I don't know what I was doing wrong with my earlier tests. I see that Edit Attachment _does_ allow you to attach multiple attachments to a card.

That said, I still want to drag a document to a card as a shortcut to the Edit Attachment -> Computer/Clipboard/Drag&drop choice. This seems a sufficient "gesture" to indicate that I  want to add the file as an attachment.

**Comment by richb-hanover** [comment]
One last thought: I was confused by "Edit attachments" menu label. If it had said, "Add attachments", I would have understood what it does immediately. (The resulting GUI only allow you to add attachments - not remove ("edit") them.)

**Comment by xet7** [comment]
From @ocdtrekkie https://github.com/wekan/wekan/pull/1391

> I am not super fond of this change. It takes up like an inch and a half, since the current "Add attachment" button is a giant box. It pushes the most recent comment to nearly always be below the scroll point.
>
> Is it possible we could shorten how large this section is if there's no attachments, while still making the Attachments section visible all the time?
>
> I understand why. But as someone who rarely uses attachments in Wekan, the change has a very painful cost. I am not personally comfortable trying to improve it myself, but hoping perhaps my suggestion on how it can be improved might be useful to the person who made the PR.

Should there be slider for hiding attachment box? Or how should it work?

**Comment by lichtamberg** [comment]
I think there should be a small box, which automatically resizes to a bigger box when I drag and drop a file. Also I think the current workflow of not being able to drag and drop directly (but have to click add attachment) is not optimal, since at least in Firefox it just loads the dragged file (and quits wekan) in the tab - but doesnt upload it in Wekan.. 

I did a short screenscapture on how we do it in our own project with the JQuery File upload plugin (https://blueimp.github.io/jQuery-File-Upload/), its also only 60 lines of JS-code (https://gist.github.com/lichtamberg/7dcbd62f74b697adf4d1094e6bd82e4d):

![screencast 2017-12-21 11-44-21 gif sb-3892e7de-lg12pn](https://user-images.githubusercontent.com/10075/34252582-2d7b760c-e63c-11e7-9c2f-02c1fdb17c56.gif)
