### ISSUE TITLE
No more invitation code field on sign-up

### ISSUE THREAD

**Issue by fwachtel** [wekan/wekan#1361]
## Issue
**Impacted version**: v0.56.0

**Server Setup Information**:

* Operating System: linux x64
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): tar
* Node Version: v6.12.0
* MongoDB Version: v3.4.10
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- Just updated to v0.56.0
- Inscription set to invitation only
- When new user want to sign-up the invitation code field is not displayed but still required (see below)

Workaround for the user :  remove the style "display: none;" in div "invitation code" on current page to be able to fill it.

![wekan_signup_bug](https://user-images.githubusercontent.com/7559671/33263054-af23748e-d368-11e7-972a-f3f0fc7ad0b4.png)

**Comment by xet7** [comment]
This is already fixed in Wekan v0.59 that can be used with build from source or docker hub tag.

Wekan uses MongoDB 3.2.x , you may have problems uploading images etc with MongoDB 3.4.x.

Also that new Node.js version could cause 100% CPU usage etc bugs.

Check wekan/wekan repo Dockerfile for versions currently in use.

**Comment by fwachtel** [comment]
Thank you for these information !
