### ISSUE TITLE
Trying to change wekan logo in our instance setup via snap

### ISSUE THREAD

**Issue by hupptechnologies** [wekan/wekan#1493]
## Issue
**Impacted version**: 0.75

**Server Setup Information**:

* Operating System: Ubuntu 16.04 LTS
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Snap

**Problem description**:
- I want to replace snap logo with our logo in our installation.
- The path where we are trying to replace logo is : /snap/wekan/124/programs/web.browser/app/
- I followed steps given here by one of the user to find the logo directory and try to change it : https://github.com/wekan/wekan/issues/1196
- When I try doing it, it says that it's read only directory.
- I want a solution in which I can keep updating wekan via snap and still retain the logo change that I have done.

Please suggest correct way to do this.

**Comment by xet7** [comment]
Please wait for change logo feature to be finished, I have it in progress, see Roadmap:
https://github.com/wekan/wekan/projects/2

There will sometime also be bugfix for keeping snap settings when upgrades happen, then cron workaround is not needed anymore:
https://github.com/wekan/wekan-snap/issues/29

**Comment by xet7** [comment]
You can support change logo work with adding bounty to https://github.com/wekan/wekan/issues/1196 , instructions at https://wekan.team

**Comment by jshupptechnologies** [comment]
ok thanks. We'll wait.

**Comment by Buliwif** [comment]
Hi !
Is there a way to do this now ?
    >Changing logo
    >Changing favicon
    > Changing color from the main page

Thank You

**Comment by xet7** [comment]
@Buliwif

No. Wekan is mostly whitelabeled. Which ones of these do you mean?

1. Logo
- [ ] /sign-up logo
- [ ] /sign-in logo
- [ ] All Boards page logo
- [ ] Board page logo

2. Favicon
- [ ] change current favicon
- [ ] change current favicon in all possible favicon sizes

3. Color
- [ ] /sign-up background color
- [ ] /sign-in background color
- [ ] All Boards page background color per user

4. Background image
- [ ] /sign-up background image
- [ ] /sign-in background image
- [ ] All Boards page background image
- [ ] Board Background image #486

If someone would like to have these, someone can pre-pay 1000 euro at https://wekan.team/commercial-support/ so I will code these.

**Comment by Buliwif** [comment]
@xet7 
Hi,
I hope I did not offend you with my request because it was innocent.

I was just wondering for :
    > Logo on login page
    > Custom Color for default elements (like button, background etc...)
    > Default favicon.

But I understand it means dev for you so if it don't exist, no prob :)

About prepaid, It can be mutualized with other company but to organize it, it will be long. And I'm not sure anyone want to pay for a customized logo option...

Thanks, bye

**Comment by xet7** [comment]
@Buliwif 

Yes of course it was innocent, you did not offend. I also did not know are you serious in asking that. I do usually add price in case someone really is serious about needing all those features.

There is also some workarounds. For example, with Sandstorm https://sandstorm.io there is ability to change logo that is at top left corner.

Another possibility is to have custom login form with for example PHP login backend, that authenticates to OAuth2 server. That PHP login page could be custom, and after login there to be Wekan in a iframe, and at left or top of that iframe logo, menu etc.

At UCS (as mentioned at https://github.com/wekan/wekan/wiki/Platforms) there is single login and UCS Admin Panel where can be added also Wekan users to same Virtual Appliance LDAP server, so that it's possible to login to Docker-based wekan with same UCS credentials.

At Friend (at https://wekan/wekan/wiki/Friend) there is web desktop where Wekan can work in desktop window. That window can be resized and dragged around.

**Comment by Buliwif** [comment]
I say thank you,
Sorry to close the ticket late but with the current events, I had put that in the back of my mind.

I still have a question of order ldap so I open a separate issue.
