### ISSUE TITLE
Swimlane issues at Sandstorm

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#1494]
Swimlane is not visible at upcoming Sandstorm Wekan v0.76.

When creating new board, also default swimlane needs to be created, like in Standalone Wekan.

I'll probably try to fix this later, looking at previous commits.

**Comment by ocdtrekkie** [comment]
Specific details I figured out:

- The swimlane is not created on a new board.

- Upgraded boards seemed to more or less work and had a default swimlane.

- Upgraded boards defaulted to swimlane view, even though previous boards obviously did not use swimlanes.

- No matter what name you gave a swimlane, the feed on the right column didn't correctly retrieve the name of the swimlane being archived.

**Comment by ocdtrekkie** [comment]
Some of these and other issues are fairly noticeable right now to the non-swimlane user, I don't want to push 0.76 to the main market, but we can leave it on the experimental market for testing until we have a cleaner build.

**Comment by ocdtrekkie** [comment]
Does non-Sandstorm Wekan also default to Swimlane view? And is that preferred? Shouldn't it start in Lists, and then a user can switch a board into Swimlanes?

**Comment by ocdtrekkie** [comment]
It looks like Swimlane view is default both for new and upgraded grains, I got confused because you click on Swimlanes to switch to Lists, and click on Lists to switch to Swimlanes, which is very confusing.

On upgraded grains, it looks like there's a Default Swimlane that all existing cards are in, though its name appears "undefined" when you archive it. New grains do not have or show a Swimlane, and you need to switch to Lists to do anything with Wekan.

**Comment by ocdtrekkie** [comment]
This issue and #1506 constitute all the things I currently see as a blocker to approving the update for everyone. And realistically, if we at least switch the default view back to Lists, that's probably good enough until Swimlanes is fixed.

**Comment by xet7** [comment]
@ocdtrekkie 

Most Swimlane issues are already added to Roadmap:
https://github.com/wekan/wekan/projects/2

Those will get fixed when contributing companies get up-to-speed in helping with HTML/CSS issues etc, it's in progress, but can take some time.

Wekan web UI will also sometime be organized better, so settings are not in so many submenus, but combined to some organized settings pages.

**Comment by ocdtrekkie** [comment]
This is just overall notes on my testing of the latest Sandstorm build. Not knowing which is Sandstorm-only and which is general, I didn't want to so spreading issues or comments everywhere. :) And then I opened 1506 because it was a problem with Lists view.

The default view being Swimlanes vs. Lists is probably the one I'd say isn't really covered anywhere, and probably a topic of discussion that I am not sure is Sandstorm specific or not.

**Comment by xet7** [comment]
@ocdtrekkie 

When I tried creating new board in newest Wekan for Sandstorm, I was unable to add cards.

**Comment by ocdtrekkie** [comment]
@xet7 Drop into List view, and you should be able to add lists, and then cards.

**Comment by ocdtrekkie** [comment]
Oh, you're right, the Add button isn't clickable!

**Comment by ocdtrekkie** [comment]
`TypeError: Swimlanes.findOne(...) is undefined` is the JavaScript console error I see when I try and hit the add button, so this is probably a "Default swimline not created" issue.

**Comment by andresmanelli** [comment]
@xe7 can you try https://github.com/andresmanelli/wekan/commit/f470323ee746c4e79f07d166d511867408194eb6 (The swimlane is not created on a new board) and https://github.com/andresmanelli/wekan/commit/bb37d8fa964c0d03721a664387e74300fde09eef (No matter what name you gave a swimlane, the feed on the right column didn't correctly retrieve the name of the swimlane being archived)
