### ISSUE TITLE
metor crash when trying to upload an avatar image , Mongodb 3.6 version  Node js 4.2.6 Wekan is v0.73

### ISSUE THREAD

**Issue by gsachin1809** [wekan/wekan#1535]
## Issue
**Impacted version**: xxxx

**Server Setup Information**:

* Operating System:
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable (Is there a subfolder?):

**Problem description**:
- *be as explicit as you can*
- *describe the problem and its symptoms*
- *explain how to reproduce*
- *attach whatever information that can help understanding the context (screen capture, log files)*

**Comment by xet7** [comment]
This is the recommended way to install Wekan, it's very fast and easy:
https://github.com/wekan/wekan-snap/wiki/Install

Current supported versions of Node, Mongo etc are listed at:
https://github.com/wekan/wekan/blob/devel/Dockerfile

If you want to use MongoDB 3.4, you need to pay for
my commercial support https://wekan.team 
so that Wekan can be upgraded to Meteor 1.6.1,
more details at #1522
