### ISSUE TITLE
Feature Request : Adding Items to a Card without the need to add a Checklist first, and UX of checklists to be like Material Design

### ISSUE THREAD

**Issue by 2Belette** [wekan/wekan#1568]
Today the workflow is:
-Opening a Card
-Add a Checklist
-Add an item to the Checklist

Sometimes adding a Checklist is useless and only adding checked items straight to the Card would be useful.
The Checklist organization is useful when multiple items have to be added and organized on the same Card and in case of Trello import, but this would be better if adding a Checklist would be optional.

Workflow would be:
-Opening a Card
(optionally adding a Checklist like today)
-Add an item to the Card

**Comment by xet7** [comment]
Possible use case also:
- Forms in a card
- Or: Markdown form to live form with checklists etc options

This need some thinking what would be most useful way for any of this to work.

Should there be:
- just a way to hide checklist names
- could there be other types of "checklists" like text fields, images, etc items that can be selected instead of checklist, like in questionnaire forms.

**Comment by quantazelle** [comment]
I was going to add here my issue. The icon for checklist names is a checked-off icon. It makes it looks like the checklist is complete:
![img-2018-04-04 10 55 55](https://user-images.githubusercontent.com/13591815/38325138-07e863a2-37f7-11e8-9036-26f30fe8a470.png)

@xet7 Right now the workflow in Trello is one checklist per card and it is unnamed. Which makes sense because the checklist items are kind of sub-tasks under the card. 

If there needs to another checklist for the card, it could be added as another item, and then you can name that one, or name both. But creating a named checklist every time for every card is pretty clunky, and I agree with @2Belette.

**Comment by xet7** [comment]
@quantazelle 

What would be better icon? From:
https://fontawesome.com/icons

Currently when I changed it, it looks this way. Is this good enough? I did not find better icon yet. If I take icon away, it looks too funny, when checklist name is more right than checkbox below.

![checklists](https://user-images.githubusercontent.com/15545/38327470-f6d7b310-3850-11e8-9466-4be1197f2c1f.png)

**Comment by quantazelle** [comment]
Both of those icons imply a state, either "completed" (with a check) or "uncompleted" (a box without a check.) 

I would say just use the bold typeface and indent it.

Material Design has one of the best UI resources I've seen, and [they have come to a similar conclusion](https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls):

![](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsaGczdEdTVmQ2T0k/components-lists-keylines-two3.png)

A second option would be a "[Collapse](https://fontawesome.com/icons/minus-square?style=regular) / [Expand](https://fontawesome.com/icons/plus-square?style=regular)" icon set:

![](https://gccontent.blob.core.windows.net/gccontent/blogs/legacy/c1/2014/05/C1TreeView_SL_ExpandCollapse.gif)

**Comment by quantazelle** [comment]
(We've diverted from the original issue, but I like UX and have a minute so here we are. I still think the multiple lists are overkill and a workflow roadbump.)

**Comment by xet7** [comment]
I figured out how to have that Material Design look on checklist. I will add that change soon.

![checklists2](https://user-images.githubusercontent.com/15545/38359160-29411272-38d0-11e8-9665-8e3317c37321.png)

**Comment by quantazelle** [comment]
Great!

**Comment by SiGmAX666** [comment]
I apologize in advance for posting my comment here, maybe it should go in another thread. I dug around for markdown/checkbox threads quite a bit and this one seems reasonably on subject and also the most recent.  
Would it be possible to add checkbox items like the Github markdown syntax allows for? Or some other way to make the existing checklist shown on the face of the card vs within the card? I have some cards that are a multi-part task and it would be nice to see what parts are done from the face. Eg:

### Item List Header
- [ ] Item 1, undone 
- [x] Item 2, done   

`### Item List Header  
    - [ ] Item 1, undone  
    - [x] Item 2, done

**Comment by xet7** [comment]
@SiGmAX666 

Wekan uses [perak:markdown](https://atmospherejs.com/perak/markdown) package for markdown. Not GitHub markdown. You could look there what it supports.

You could alternatively:
- use HTML to format checklist to look like that
- use in progress Custom Fields current, upcoming, or new feature request at #807
