### ISSUE TITLE
Why release bundle tar.gz stopped after v0.63

### ISSUE THREAD

**Issue by carlos22** [wekan/wekan#1628]
The last build release is: https://github.com/wekan/wekan/releases/download/v0.63/wekan-0.63.tar.gz
Why? I used the FreeBSD HowTo [1] which requires the build version (as meteor does not work there out of the box). Is there a reason why? Or changed to place where to get these builds?

[1] https://github.com/greinbold/install-wekan/blob/master/v0.32/freebsd-11.0-RELEASE.md

**Comment by xet7** [comment]
@carlos22 

That's because GitHub introduced release file size limitations.

Newest releases are at:
https://releases.wekan.team

Docker, Source etc instructions are at:
https://github.com/wekan/wekan/releases

I don't know how well Docker works on FreeBSD, can you use it:
https://wiki.freebsd.org/Docker

**Comment by carlos22** [comment]
Ah ok thank you. I prefer to run it native and not via any Linux emulation layers. I currently try to get it working on SmartOS: https://gist.github.com/carlos22/5e19bf124eb52512db430cccf73476d6

**Comment by xet7** [comment]
@carlos22 

I copied your gist to Wekan GitHub wiki, please add modifications directly to there. Thanks!
https://github.com/wekan/wekan/wiki/SmartOS
