### ISSUE TITLE
Caddy licensing

### ISSUE THREAD

**Issue by franksiler** [wekan/wekan#1640]
## Issue
Running in commercial environment, don't need SSL at the moment and have corporate process for acquring; don't want to pay for Caddy.

Is there any opposition to PRs switching to a more open-source webserver for the snap?  It's an issue I need to research to see what other packages are using.

**Server Setup Information**:

* Operating System: Hopefully Ubuntu, possibly CentOS
* Deployment Method(snap/sandstorm/mongodb bundle): ideally snap

**Comment by xet7** [comment]
When installing Wekan snap, Caddy is not enabled by default, and Wekan works without SSL and without enabling Caddy. Is it a problem that snap includes Caddy ?

**Comment by xet7** [comment]
If I remove Caddy from current Wekan snap, that will break every server where Caddy snap is enabled, including https://releases.wekan.team server that is running Wekan snap's enabled Caddy. I don't know how current Caddy configs could automatically be migrated to other webserver configs.
I could maybe create another snap with other name, but that would be a lot of work, and create confusion.

I'm open to any suggestions how all this could be solved, and what the benefits are.

**Comment by franksiler** [comment]
Certainly I don't want to break anyone's deployment- I'm not intimately familiar with snaps, and it sounds as though there are configurations which will abate the licensing issues I'm raising.  I appreciate the conversation and good thoughts- I'll do some research but from what I've learned here, it doesn't sound like a showstopper for me.

**Comment by xet7** [comment]
There is also [possibility to use proxy](https://github.com/wekan/wekan/issues/1480)

**Comment by xet7** [comment]
It's also possible to use Docker version, that does not include Caddy.
Docker version does not have automatic updaters, so it requires some update script, or managing with DockerBunker, that has Wekan support:
https://github.com/chaosbunker/dockerbunker
or alternatively, any other software that manages Docker containers.

I don't think there is any actual problem here. If someone still likes to discuss this, add comment to this issue.

Closing issue.
