### ISSUE TITLE
Archiving board/card; current version

### ISSUE THREAD

**Issue by FranciscoBarros** [wekan/wekan#165]
First of all, I'm not sure if there is a more appropriate place to ask this kind of question... is there a forum?

I couldn't find how to archive a board or a card? I've checkout master and it's different from version at libreboard.com.

What's the current version: 0.9? (as seen in http://libreboard.com/boards/MeSsFJaSqeuo9M6bs/libreboard-roadmap) But here milestore v0.9 is open.

Thanks a lot.
Best Regards!

**Comment by mquandalle** [comment]
The last released version is v0.8. The next version is a work in progress and developed in the open on the master branch. Since it’s a major rewrite some features are missing from v0.8, and I need to re-implement them before the release.

Currently there are no forums, but I plan to set a discourse instance after the v0.9 release.

**Comment by mquandalle** [comment]
In Wekan 0.9 it’s now possible to archive and restore a card or a board. And by the way the forum was deployed at http://dicuss.wekan.io, would be happy to see you there :-)
