### ISSUE TITLE
Add feature: REST API

### ISSUE THREAD

**Issue by martinhbramwell** [wekan/wekan#166]
Hi.  I am completely new to Libreboard.  I want to evaluate it for a project I have to do.

I have forked and cloned what appears to be the latest version, but it seems to be far behind in functionality compared to the demo at libreboard.com.

Is there a partially complete rewrite in progress that does things better but has yet to reinstate all functionality?

A few issues I am seeing : 
- the path to /settings gets me "Couldn't find a template named "AuthLayout" or "authLayout". Are you sure you defined it?"
- cards have no widgets for adding Labels or Attachments
- no menu at the top of the sidebar
- (etc.)

Could someone please tell me what is going on?

How can I help?

**Comment by mquandalle** [comment]
> Is there a partially complete rewrite in progress that does things better but has yet to reinstate all functionality?

Yes. The next release (v0.9) is a ~70% re-write. It’s probably better to way a bit for things to stabilize before diving into LibreBoard.

**Comment by martinhbramwell** [comment]
I really would like to be of assistance.  Please try to identify some parts of Libreboard where I could start contributing.

**Comment by mquandalle** [comment]
So it’s seems that you know JavaScript programming. One thing you could work on (because it is mostly not affected by the current UI changes) is the REST API. There is an important community demand for this API (#128).

If that something you are also interested in you can clone the project and create a  `restApi.js` file on the server directory, then take a look at the collections schemas and interface them with a REST API (it’s probably good to follow https://trello.com/docs/api/ so that so people could inter-operate plugins written for the two applications). You may want to use a meteor package to help writing this interface such as [restivus](https://atmospherejs.com/nimble/restivus).

If you don’t like this idea, what else would you like to do?

**Comment by martinhbramwell** [comment]
It looks like my first task would be **authorization**.

Restivus seems to go only as far as _authentication_ of a remote client.  Trello provides 3rd party **authorization**, whereby users can permit services like Slack to dig into their Trello account, on their behalf. 

For example, this link, opened by a user, would ask them to accept that "My+Application" have free use of their libreboard account for 30 days : 

    https://www.mylibreboard.com/1/authorize?name=My+Application&key=My+Application+Key&expiration=30days&response_type=token

I don't see that functionality in restivus.  Is there a more advanced alternative? If not, my first task contributing to libreboard may turn out to be a collaboration on restivus to duplicate the functionality of Trello's "authorize" method.

btw, There is a [NodeJS wrapper library](https://github.com/adunkman/node-trello) available on GitHub that would facilitate validating our efforts to duplicate Trello's OAuth steps.

I can work out those details if they are not already addressed, but I would like to know what you think.

**Comment by mquandalle** [comment]
No you don’t really *need to* start with authorization. We currently don’t have a oAuth infrastructure and as you have seen I don’t know any package to provide a simple solution for this. So we’ll probably need to design most part of the oAuth system ourselves including the UI to generate and revoke access keys.

I believe mapping a REST API with collections methods is a much simpler task. Even without the authorization system it will be useful for public boards and in environments that handle access control themselves (such as sandstorm). Once this API work, we will be able to add this authorization extra step.

**Comment by ocdtrekkie** [comment]
This is the documentation for how Sandstorm handles APIs: https://github.com/sandstorm-io/sandstorm/wiki/Exporting-HTTP-APIs and the only app currently using it: https://github.com/jparyani/Tiny-Tiny-RSS

I don't know if it's useful to @martinhbramwell or not, but ideally the API should work well with Sandstorm as well as without.

**Comment by martinhbramwell** [comment]
Hmmm.

On that page you mention -- ( [Exporting HTTP APIs](https://github.com/sandstorm-io/sandstorm/wiki/Exporting-HTTP-APIs) )  -- I see a remark : `In the future, we will implement an OAuth flow allowing a third party to initiate a request for access to the user's apps.` 

I had only heard of Sandstorm a few days ago, and don't really have a clear idea of the scope of their offering, but I can see why you'd prefer to wait for Sandstorm to implement it.

However, clearly, not all Libreboard projects will run on Sandstorm, so that begs the question : does the design of `restivus` permit or prohibit implementing 3rd party authorization in the future?  If it cannot be made to do it, how horrible will it be to rip out restivus and replace it with something else?

(just playing devil's advocate here)

**Comment by martinhbramwell** [comment]
Huh.  I just looked the code of restivus.  It's quite small really, so perhaps there's nothing to be concerned about.  I think I would like to tinker with it a bit and try to get an idea of how hard/easy it will be to use.

**Comment by ocdtrekkie** [comment]
FYI, isn't my page (I don't work on Sandstorm, I just like playing with it). But right now Sandstorm implements API keys, and has a UI for creating them and revoking them, rather than an OAuth flow.

LibreBoard could benefit from either an API key-based or OAuth-based solution depending on what the API is being used for. Though from my understanding, OAuth workflows tend to assume you're talking to a known centralized entity on one side of the equation (Google, Facebook, Github, etc.) and the setup for that may not be as straightforward for something like LibreBoard, where it may be hosted anywhere.

**Comment by martinhbramwell** [comment]
"... tend to assume you're talking to a known centralized entity on one side of the equation (Google, Facebook, Github, etc.) "

Or Trello, for that matter, no?

The question is whether the Libreboard community is panting for an API, an authenticated API or a full-fledged 3rd party authorized API?

**Comment by martinhbramwell** [comment]
I think I am going to do the following : 

 1. Set up `node-trello`, the [NodeJS wrapper library](https://github.com/adunkman/node-trello) for the Trello API (that I mentioned earlier) and try to manipulate my own Trello acct with it, just to get familiarized.
 2. Set up a completely bare bones `restivus` server and attempt to configure it to respond coherently to calls into it from `node-trello`.
 3. See if adding 3rd party authorization to `restivus` is viable
 4. Take what I've learned and start in on some initial calls of the API for Libreboard
 5. Make a test suite out of `node-trello` and get it *green* for those initial calls.
 6. Invite the libreboard community to help turn the rest of it green.

**Comment by mquandalle** [comment]
Sounds good! Don’t forget to share your work in progress for the `restivus` server so that others in the community could follow the development.

Also I should mention that I didn’t take a close look at `restivus` yet, so if you encounter any limitation with its API it may be worth to take a look at the alternatives.

**Comment by mquandalle** [comment]
Also,

> However, clearly, not all Libreboard projects will run on Sandstorm

Yes, absolutely. We support multiple targets (sandstorm, docker) and I plan to add more in the future (AMI, deb, etc.). I was just evoking sandstorm because it’s a case where we don’t need to manage authorizations even for “private” boards.

**Comment by ocdtrekkie** [comment]
@martinhbramwell Being able to import from Trello (a centralized entity) via their API is pretty important, but I was also thinking in terms of allowing other things to import/export to and from LibreBoards. Potentially other open source apps that might integrate, or a mobile app someday, etc. Each LibreBoard running it's own OAuth service in that case would be a bit odd perhaps.

**Comment by martinhbramwell** [comment]
I hope we are not talking at cross-purposes.  The way I see it Libreboard targets a niche of people who want to run their own Trello and have total control over how it behaves.    If Trello runs its own OAuth service, then Libreboard should too.  Is that idea blinding me to a deeper issue?

**Comment by ksavoie** [comment]
mquandalle, 
> Yes. The next release (v0.9) is a ~70% re-write.
Is there an ETA on v0.9?

**Comment by rwatts3** [comment]
Yes I second @ksavoie I see the http://libreboard.com/ project's new desigin however when I downloaded this repo it looked very different. Is this the new 0.9 ?

**Comment by ePirat** [comment]
@rwatts3 Yes, 0.9 is a redesign, in order to not infringe the Trello copyright anymore.

**Comment by martinhbramwell** [comment]
@mquandalle 
So ... a progress report.

I have created a screen scraper to create a Swagger document from [the Trello API documentation](https://trello.com/docs/api/index.html).  You can review it using the Swagger UI ...
 - go to the address :  [Swagger UI Demo](http://petstore.swagger.io/)
 - in the field at the top of the page replace [the Pet Store API file URI](http://petstore.swagger.io/v2/swagger.json) with [my Trello API file URI](https://raw.githubusercontent.com/warehouseman/trello-swagger-generator/master/TrelloAPI.json)

I think you'll agree that it's far superior to [this indecent shambles](https://trello.com/docs/api/index.html)

I have begun to create a Meteor package that wraps [the Swagger JS library](https://github.com/swagger-api/swagger-js).  "... the fastest way to enable a javascript client to communicate with a swagger-enabled server".  On Meteor startup it will publish the entire Trello API as developer friendly commands like Trello.board.getBoardById or Trello.card.getCardsMembersVotedByCard(). 

I am doing this so that ...
 - we can create a Meteor test tools suite using the Swagger JS library that pre-validate tests of the Libreboard API against the Trello API.
 - we can generate the Libreboard server-side API from the Trello swagger file and stub all the bits that have yet to be developed.
 - we can ensure that anyone with an API client for Trello can use it unaltered to interact with Libreboard.
 - we can ensure that anyone with a Libreboard installation can fully interact with anyone else's Libreboard installation.



Unfortunately I have hit an obstacle.  Perhaps the Javascript and NodeJS wizards in this community can help me get past it.  [Am I pushing Meteor._wrapAsync beyond what it can do?](https://forums.meteor.com/t/am-i-pushing-meteor--wrapasync-beyond-what-it-can-do/5901)

You can see [the test code in GitHub](https://github.com/FleetingClouds/asyncwraptest/blob/master/asyncwraptest-tests.js) and [the test results in Travis](https://travis-ci.org/FleetingClouds/asyncwraptest).

Thoughts?

**Comment by ePirat** [comment]
It would be great if this issue could be renamed to a proper title, as the current one is actually wrong, given what the issue has turned into.

**Comment by martinhbramwell** [comment]
Further report . . .   I solved the wrap_Async problem, and was obliged to focus on other things for a while.

However since my prior report was completely ignored and this thread closed without apology or explanation, I have to assume my participation here is unwelcome.  It might not be a deliberate insult, but it sure feels like one.

**Comment by ocdtrekkie** [comment]
@martinhbramwell I think @mquandalle was universally quiet for a while.

**Comment by ePirat** [comment]
@martinhbramwell This issues, as far as I can see, was never close but the referenced issue about another REST API issue was closed. I don't think anyone meant to insult you by not answering. I had a look at the Swagger thing using your JSON and I am a bit confused how this thing works, but it looks interesting.

**Comment by martinhbramwell** [comment]
Thank you for your clarifications. I now realize, pink about the ears, that I'm annoyed about something else entirely unrelated and let it leak into my reading of this situation.

A Swagger specification is machine readable, so the NodeJS module I wrap for Meteor automatically creates local functions that are immediately callable as proxies for the remote API.  Change the spec, reload it and the functions change to match.

You can generate server side code just as easily.  So, I plan to generate both Wekan's server side REST API methods, and unit tests for each one, from the same Swagger spec I used to create the client side.

With that done, it should be possible to throw the entire thing open to Wekan's community stating, "Here are 300 or more API methods, 10% of which test green.  We'd be most grateful if you'd pick a red one, code it green and submit a PR."

**Comment by mquandalle** [comment]
@martinhbramwell I apologize for not having reviewed you work, it's definitely not a “deliberate insult”. I've been working pretty much alone on this project, which mean that when I don't work, nothing gets done (at least on the code base, it's not true for the documentation and translations). Some people have been asking me (by e-mail) about a REST API, and I've always redirected them to your work, if you needed a proof that it was not my intention to ignore you.

Lately I've also been thinking a lot about the mutation model, I was very inspired by the Facebook and Netflix talks about Relay and Falcor and I think this is the kind of API we will want going forward. At the same time we currently have a DDP API (and there is no clear consensus in the meteor community about how we should mutate collections, whether directly with minimongo on the client, or systematically using DDP methods), and thirdly some people ask for a REST API as discussed in this issue. Handling this set of three significantly different APIs will be something non-trivial, and I've been maintaining the status quo (ie, DDP only) waiting for the ecosystem to mature.

I did also hope that other people interested in a REST API could help you, but since it seems to not be the case, I'll review your work and help when I finish fixing the little bugs blocking the 0.9 release.

**Comment by martinhbramwell** [comment]
@mquandalle Thank you for clarifying your situation.  I would like read up on  Relay and Falcor.  Do you have links to the talks you mention?

I hope my previous message clarifies what I was doing.  I have been sidetracked recently, and it may take me quite a while to get back to it.

**Comment by mquandalle** [comment]
Wekan v0.9 is released so I started working on the REST API. I really don't have a lot of experience building these kind APIs. I looked at your Swagger specification (didn't know Swagger) and it looks great! I guess that will be useful to test the API and to generate client-side library if needed.

On the server part, I started to centralize all mutations at the model level (in 45b662a1ddb46a0f17fab7b2383c82aa1e1620ef) to avoid logic duplication between the DDP and the REST API. I then tried to implement a few REST methods but it turns out the Trello API (that I never used by the way) is more complex than I expected, and I need to understand it better (how does `actions` work for instance)

About Relay and Falcor, I looked at a lot of material about it, I started with https://www.youtube.com/watch?t=1439&v=9sc8Pyc51uU and it was a great introduction.

To me, the goal of the REST API isn't to be the primary interface to interact with a Wekan server, but mostly to be compatible with Trello ecosystem, to facilitate the switch. The primary interface will stay DDP for now (that means that the web client will continue to use that, and not the REST API), and will probably evolve to Relay once they figure out a few missing required pieces (eg, how to handle real time values).

**Comment by capensisma** [comment]
REST is pretty is get the value from the models and send it as JSON that's all ?

Queries may be?

So things can be like get boards, log users in and out, select all online users and do all the actions...

Thanks merci :)

**Comment by jibe-b** [comment]
+1

**Comment by flowli** [comment]
+1

**Comment by ePirat** [comment]
Please use the new Github feature that allows adding reactions to comments/issues and use the thumbs up: 👍 instead of all the +1 comments, which are incredibly annoying.

**Comment by capensisma** [comment]
@ePirat thanks +1

**Comment by xet7** [comment]
@martinhbramwell @mquandalle 

How about using DreamFactory platform for APIs ?

https://twit.tv/shows/floss-weekly/episodes/391

https://www.dreamfactory.com

**Comment by AlexanderS** [comment]
@xet7 This would be a completely different architecture (PHP vs. NodeJS), has a separate user management and different permission model. I think this would be very hard to maintain.

**Comment by xet7** [comment]
@AlexanderS 

Probably adding DreamFactory platform support would be similar to adding Sandstorm support. All authentication, database handling or moving to other database, etc is handled by DreamFactory, that creates REST API's that Wekan would call. There is no need to touch DreamFactory code etc, just use it's admin UI, and have Wekan as frontend calling REST APIs.

Does this differ how current plans is with REST API ?

Is there difference is REST API backend provided by NodeJS or PHP ?

**Comment by ePirat** [comment]
I am not sure but I think it would not be so easy to still benefit from all meteor features if we would need to call the rest api for all things. And requiring to install a nodejs and a PHP application just to use a tool is not really easy deployment, imho. If I understood correctly the plan was to add a REST API to get out some of the information in machine readable format, not to build all of Wekan on top of a REST API.

**Comment by Xaptor** [comment]
Hello, is somebody still working on this issue? I am looking for an interesting project to contribute to. Currently i am learning Javascript / NodeJS since 2 months. So i am new to Meteor, but i am a professional programmer and very familiar with api development.

**Comment by ForNeVeR** [comment]
Is there any general plan on creating the REST API? If no, then maybe let's start from some low-hanging fruits: implement a bunch of methods to authenticate and retrieve some primitive data pieces, and afterwards start working on more complex scenarios?

**Comment by ForNeVeR** [comment]
Also, does anyone here familiar with how REST API should work on Meteor? I think we could really use your advice!

**Comment by swettk** [comment]
👍

**Comment by xet7** [comment]
@martinhbramwell @Xaptor @ForNeVeR 

Please see:
https://github.com/wefork/wekan/wiki/FAQ
https://github.com/wefork/wekan/blob/devel/CHANGELOG.md

And create new issue about REST API to discuss more:
https://github.com/wefork/wekan/issues

**Comment by Kaligule** [comment]
[This project](https://github.com/LINKIWI/wekan-api) might be of interest.

**Comment by tugal** [comment]
Hi all,

I don't Think meteor's architecture suits an API.. maybe we are more interested by a mongodb API .. There is many plugins out there doing the job..

Is a mongodb API living in a séparate docker a good choice ? I can work on it and évaluate each on them 

Thanks Nelson

**Comment by tugal** [comment]
@kaligule: you already linked a project providing an API on top or mongodb :)

**Comment by xet7** [comment]
@tugal

Please continue discussion about API at Wefork:
https://github.com/wefork/wekan/issues/43

Original Wekan has not received updates for 4 months.

**Comment by xet7** [comment]
Wefork has been merged to Wekan and is under active development.

Discussion moved back to here.

**Summary**

Asked on original Wekan Gitter by @RaviRokkam_twitter

RaviRokkam wanted to integrate website with Wekan, so if task is added to website, it should be added as a card to Wekan.

This would require API to access Wekan data.

There is related Python-based project, but it seems to have read-only access, so adding a card is not included:
https://github.com/LINKIWI/wekan-api

**Comment by huneau** [comment]
Hi, 

I have to work on this issues (I can work full time ). 

I started on `/users` and `/users/:id`. 

My first problem here is when I post a new user, I would like to create a default password but I don't know how to instantiate correctly this: https://github.com/wekan/wekan/blob/devel/models/users.js#L98

I post a user with an empty password and I was hoping that should work but no :/ . So for the first thing, I would like to create a user with a default password. 

Any idea for my password instantiation ?

**Comment by huneau** [comment]
> My first problem here is when I post a new user, I would like to create a default password but I don't know how to instantiate correctly this: https://github.com/wekan/wekan/blob/devel/models/users.js#L98

Ok I wrote that and it's work
``` javascript
    const id = Accounts.createUser({
      username: req.body.username,
      email: req.body.email,
      password: 'default',
    });
```

**Comment by huneau** [comment]
https://github.com/huneau/wekan/tree/meteor-1.4

In progress...

**Comment by xet7** [comment]
@huneau 

Please work on pull requests on wekan meteor-1.4 branch where it's easier to test.

**Comment by xet7** [comment]
Already merged. For additional features to API, moved to #1037
