### ISSUE TITLE
Why has the ability to view in an iframe blocked

### ISSUE THREAD

**Issue by john-pallissard** [wekan/wekan#1676]
![iframe](https://user-images.githubusercontent.com/37344546/40819643-c0854fc2-6521-11e8-9683-f180e9fbead5.png)
v1.02 "Feature"
I have a development environment showing four Wekan boards (hosted in an iframes) on displays throughout the office.  The newest version (or some version after .77) has explicitly blocked this.  can this be reversed or can someone point me at what to edit to change this "feature" from breaking my production environment.

**Comment by ocdtrekkie** [comment]
It'd be the browser-policy Meteor package. It's likely configurable.

**Comment by ocdtrekkie** [comment]
https://atmospherejs.com/meteor/browser-policy

**Comment by xet7** [comment]
@john-pallissard 

What version of Wekan you use? Snap, Docker, or something other?

iframes were blocked because of security vulnerability:
https://wekan.github.io/hall-of-fame/

There is currently Docker image where iframes are not blocked, but it will move to elsewhere sometime:
```
image: quay.io/wekan/wekan:friend
```

Friend platform is special, because it will have Friend auth to protect Wekan, so allowing iframe is not issue there.

Are you using Wekan only in internal network? Or do you have other ways to protect from security issue?

**Comment by xet7** [comment]
I have adding iframe settings in progress:
https://gist.github.com/xet7/09d84ee2fd91649ecd75bae42461460d

TODO: Add Snap, Docker etc settings

**Comment by xet7** [comment]
browser-policy docs are here:
https://atmospherejs.com/meteor/browser-policy

**Comment by xet7** [comment]
Related:
https://stackoverflow.com/questions/20924532/running-a-meteor-app-in-an-iframe-from-a-different-domain
