### ISSUE TITLE
Custom background color of swimlanes

### ISSUE THREAD

**Issue by Kels** [wekan/wekan#1688]
Hello,

Thanks a lot for the Swimlane feature !
However, it would be nice to allow users to custom the background color of their swimlanes.
At least, swimlanes should not have the same background color but 2 different ones.

**Comment by xet7** [comment]
@Kels

I have mentioned about Swimlane color here, but nobody has started developing it yet:
https://github.com/wekan/wekan/pull/1592

You can see what different Swimlane color would look like here:
https://github.com/wekan/wekan/issues/1160

There are existing features in Wekan how to change board and label color.

Main problem is that this would need someone that has time to read the code and add changing color to swimlane menu.

You can see code for boards, cards, swimlanes etc here:
https://github.com/wekan/wekan/tree/devel/client/components

It's easy for anyone that has used any programming language to figure it out, as you can see here:
https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html

You can add Swimlane color feature, I can help with any questions you have. You can add questions as comments to this issue.

**Comment by xet7** [comment]
@bentiss 

Can you try adding swimlane background color, with Set Color option in Swimlane hamburger menu? Similar like there is card color?

**Comment by bentiss** [comment]
> @bentiss
>
> Can you try adding swimlane background color, with Set Color option in Swimlane hamburger menu? Similar like there is card color?

I can try to have a look. Having per list color would be interesting too, but then, how can we integrate both??? (alpha blending would give some strange effect :P )

**Comment by xet7** [comment]
@bentiss 

List color is described here at feature request here: https://github.com/wekan/wekan/issues/328#issuecomment-396431410

From @DeGroote99

> I have requested this feature, instead of the entire section being colored, just the list name in a colored box. much cleaner look

**Comment by bentiss** [comment]
Alright, I can't help but share my designer skills ;-) :
![screenshot from 2019-01-23 14-16-31](https://user-images.githubusercontent.com/2705518/51620956-cf1ba780-1f33-11e9-94e1-6caabecaf1ca.png)

(I just edited the CSS on Firefox to see how this can be done)

I do not really like the thing because we will end up with a Christmas tree quite easily.

So I googled a bit the various designs the other kanbans have and here is a few options:
https://leankit.com/learn/kanban/kanban-board-examples-for-development-and-operations/:
![image](https://leankit.com//uploads/images/general/_xLarge/5a-TeamMemberSpecialties-af33c92b.png)

They seem to have a per swimlane background pattern, but no colors.

There is an other one at https://kanbanize.com/kanban-resources/kanban-software/kanban-board-examples/
![image](https://kanbanize.com/wp-content/uploads/website-images/kanban-resources/second_level_support.png)

I like the kanbanize option (just above) as this would not cripple the board with terrible colors. Also I wonder if the choice of having the swimlane name on the side was just the default or if you used to have it horizontally stretched accross all of the swimlane.

With an horizontal swimlane header, we could just colorize this header, and we could in the same way colorize the lists headers too.

**Comment by xet7** [comment]
@bentiss 

Yes, colorizing headers is much better. Filling background makes it look terrible. It would be better to get nice background image to Wekan board, like in your kanbanize option.

**Comment by xet7** [comment]
Here is related background image issue #486

**Comment by xet7** [comment]
There is also related card-specific avatar color issue #2110

**Comment by xet7** [comment]
In general, there has been a lot of work done to make Wekan beautiful enough. Wekan users do stare Wekan boards all days along, so Wekan should look like something usable.

**Comment by bentiss** [comment]
@xet7 

Here is my version of the horizontal layout for the swimlanes headers (no colors yet), would that be OK?
![screenshot from 2019-01-24 12-16-48](https://user-images.githubusercontent.com/2705518/51674780-f1fc9900-1fd1-11e9-9424-b7a8a0b88c3a.png)

The header now act as a separator between the swimlanes and can be colorized without much trouble.
Note also that the `+ Add Simlane` button gets moved to the bottom of the board

**Comment by xet7** [comment]
@bentiss 

`+ Add Swimlane` should be just `+` button at left side of every swimlane hamburger menu button.

**Comment by xet7** [comment]
And that `+` button would create new swimlane below of current swimlane.

**Comment by bentiss** [comment]
Getting closer:
![screenshot from 2019-01-24 17-02-35](https://user-images.githubusercontent.com/2705518/51690876-ed4bdb00-1ff9-11e9-97c8-5779da0c42db.png)

I just need to insert the swimlane at the correct place (below the one that was clicked on), and the PR will be ready

**Comment by namacoconut** [comment]
@xet7 Good evening mr.lauri, I have a question , can we change the website default color ? in wekan snap?

**Comment by xet7** [comment]
@namacoconut 

Not yet.
