### ISSUE TITLE
1.04 regression: Socket connection error and boards not loading

### ISSUE THREAD

**Issue by almael** [wekan/wekan#1694]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 1.04
* Operating System: Ubuntu 18.04 LTS (snap)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: the one supplied by snap
* MongoDB Version: the one supplied by snap

**Problem description**:
After the auto-upgrade of the snap last night the app starts normally and you can see all boards on the "all boards" page … but if you click any board or try to access it directly you only get the "three bars" busy animation and it never shows the actual board.
I have since successfully reverted to 1.03 and it works flawlessly so I don't have many error messages to show but javascript console showed something along the lines of "could not connect to socket" which led me to old sockjs issues and was of no help. Neither did the obvious things like rebooting/reloading/using different browser/trying different network.

As said before 1.03 works perfect. Sorry for the sparse problem description.

**Comment by d3dbit** [comment]
Hello all,
I have the same issue in a Docker environment.
After reverting to v1.3 all becomes OK again.
I do not recommend the upgrade to v1.4.

**Comment by xet7** [comment]
@almael @d3dbit

I am unable to duplicate this on my Wekan 1.04 snap. Wekan works for me: boards do open. Please give more details.

Please try these:

Export from 1.03 as Wekan JSON, and import to new install of 1.04 as Wekan JSON.

Keep backups.

Docker backup / restore:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

Snap backup / restore:
https://github.com/wekan/wekan-snap/wiki/Backup-and-restore

Sandstorm backup / restore. Note: Sandstorm has import "Board nor found" bug that is not fixed yet. So you need to modify MongoDB database and upload grain as .zip file, if you need it back.
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by xet7** [comment]
To fix a bug, I would need help to reproduce it.

**Comment by Fran-KTA** [comment]
FWIW, I faced the described behaviour today as I decided to update our wekan deployment, but it only seemed to affect one board (not a clue about any possible reason).

Thing is... I kind of remember the board showing up perfectly fine soon after upgrading the docker container to v1.04 image, but it must have stopped working at some point (couldn't say to which action might that be associated, was shifting from cockpit-ws created containers to docker-compose and learning docker-compose.yml at the same time, so multiple regenerations, stops, starts, etc). 

Tried investigating, but no suspicious message was to be found on either mongodb, wekan or nginx (reverse proxy) logs.

Also, changing docker-compose definition for using v1.03 triggered container regeneration and the board was accessible without issue while going back to latest rendered the board inaccessible (later on pulled v1.04 and removed the image tagged with "latest", but that behaviour persisted going back and forth between v1.03 and v1.04)

Tried going to v1.03, exporting board and importing back in v1.04... The process showed me a "400" string in a pale yellow box at the end and the result was that I had 4 copies of the board (and of every card).

Finally, dropped the wekan database from mongodb and did a mongorestore from a backup I took before starting the conversion + upgrade and the board works in v1.04 again... 

Hmm... Quite a long post for a "my 2 cents" idea in the end... sry.

Cheers!

**Comment by xet7** [comment]
@Fran-KTA 

Thanks for your story :+1: 

It's same thing with any database, etc any data: backups are important to have, in all possible formats. There are bugs in MongoDB, MySQL, PostgreSQL, etc any database and any software. SSD and HDD disks get bad sectors, etc.

**Comment by xet7** [comment]
There is some directory at Linux server where Docker layers are, in different directories. So old versions of MongoDB database can be in some directory there.

**Comment by Fran-KTA** [comment]
Hi @xet7! Indeed, backups can (and will) save your as* for sure :)

However, the thing that bothers me most is the consistency in results when switching to v1.03 and back. Including, of course, standard procedures in-between like browser data/cache/cookies cleanup, forced cache refreshes and trying at least two different browsers... Couldn't access the board in 1.04 no matter what (neither from other board members' computers).

Btw, one extra detail is that I had switched the board's background color to black and that was changing ok. It seemed to me that, somehow, what was not happening was the transition from the loading animation to the board view. Again, due to the lack of seemingly relevant error messages in any container log and no debug messages from wekan that I could find.

On the database side of things... No error was shown in the logs and I accessed the boards and cards collections from the host without any problems (I verified the number of copies of the board and one specific card when I tried the v1.03 import on v1.04). 

Oh!! The imported copies were accessible in v1.04! That I forgot to mention before, sry. I dropped and restored the database as a fast cleanup from that mess.

In any case, since I decided to stay in v1.04 I'll come back if the issue shows up again.

Cheers!

**Comment by CafSentryGnome** [comment]
I have the same problem, reverting to 1.03 brings everything is back again. If I go to 1.04 the contents of the board never load.

**Comment by xet7** [comment]
@CafSentryGnome 

Try exporting your boards to Wekan JSON in v1.03 and importing to new install of v1.04.

**Comment by Niptide** [comment]
We got the same problem, but on a Sandstorm environment. After updating to 1.04 the board still loads fine, only until someone makes a change to the board, like adding a card or a comment. Then the board canvas is empty while header and sidebar, including labels and activities, still work.
Restarting the app in the Sandstorm menu doesn't help.

**Comment by Fran-KTA** [comment]
Hi! I just remembered I had taken a cold file backup of my database, so reconfigured the MongoDB container for using that copy and the issue was there!! 

Then I got the database back to functional one and wekan container back to v1.03 for JSON exporting the board for file comparison.

With vimdiff I found just activity differences... Different dateLastActivity values, etc. And some little differences regarding added attributes to docs in the non-functional database export (so, yes, that board seemed to be ok for some time after initial upgrade).

In particular, there was a card that had "receivedAt" attribute added and it turns out that when I repeated the action the board was inaccessible again!! So, tried dropping the attribute from mongo and the board came back!

> db.cards.update({"_id":"AKcaMDhXCDS8zrkHu"},{ $unset: { "receivedAt": "" } })
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

Tried different date (next day) with same result. However... There are already 2 cards in that board with that attribute set and no problems. Also, created a specific test card and moved it around lists, swimlanes, etc. Didn't seem to reproduce the behaviour... But added receivedAt attribute and there it was (again, removal from database restored board access).

Add and remove receivedDate without trying to reload the board inbetween does not affect operations like moving cards, etc. So, it may not be related to the update action but the retrieval??

And, last thing... Adding a receivedDate AND an endAt attributes to the same card seems to avoid the behaviour.

So... My guess is that any board with cards having received date and no other date set may be the ones failing to load?? At least in my standalone, docker-based deployment.

Cheers!
