### ISSUE TITLE
[Issue] MongoError: file with id xxxxxxx not opened for writing

### ISSUE THREAD

**Issue by d3dbit** [wekan/wekan#1740]
## Issue

**Server Setup Information**:

* Wekan version: v1.11.0 (wekan-mongodb - Docker)
* Operating System: Ubuntu 18.04 LTS (VM - Google Computer Engine)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Node Version: v8.11.1
* MongoDB Version: v3.2.20

**Problem description**:
- I can not export a Board (but I can export all the other Boards).
- If I try to export the board I get the next error:
```$ sudo docker logs -f wekan-app
[...]
MongoError: file with id 5b39e8d6015db60001df4796 not opened for writing
    at Function.MongoError.create (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
    at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
    at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
    at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
    at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
    at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
    at setCursorNotified (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
    at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
    at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Thanks.

**Comment by d3dbit** [comment]
*Workaround*: I have migrated all the cards from this issue board to another board, and now I can export the new board to a JSON file. I do not know why, but now my issue is resolved. I can close the issue.

**Comment by GYKADSC** [comment]
Thanks for the workaround @d3dbit! Saved my board!

**Comment by sebastianha** [comment]
I have the same problem right now, is there any fix or does someone know what is wrong? I am not very pleased with the workaround as my "corrupted" board is rather large.

Anything new here? Perhaps we should keep this issue open?!

**Comment by xet7** [comment]
@sebastianha 

Sure, there is new stuff, although still not finished in progesss cutting edge.

1) At newest [Wekan v2.02](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v202-2019-01-22-wekan-release) (see also OpenAPI issue for new API docs) there is using REST API to export whole board, after [logging in to API as form data](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data). So if export of that board still works with API, you could try that.

2) There is way to [fix MongoDB and export to JSON text and image etc files](https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file) so you could see all of your data, but there is not yet ready-made script to insert data back to Wekan. That fix MongoDB data info is for all Wekan versions, not just Sandstorm Wekan.

3) There are some [cleanup code](https://github.com/wekan/wekan-cleanup) that could possibly help.

4) There are some Wekan bugs with Custom Fields, Subtasks etc, that can cause Wekan board to not work, so by removing data related to those from MongoDB could work, or just waiting when some future Wekan version has that data fixed. Fixing import/export bugs is planned for [Milestone 35 during next month February](https://github.com/wekan/wekan/milestone/35) and continues also after that because one month is quite a short time for the amount of issues there.

5) For Docker Wekan users, there newer Wekan Docker image `image: quay.io/wekan/wekan:meteor-1.8` that works with MongoDB 4.x that most likely more MongoDB bugs fixed than previous versions of MongoDB. More details are at https://github.com/wekan/wekan file docker-compose.yml .

6) If you are running at some cloud that provides hosted MongoDB, like recently announced MongoDB 3.6.x compatible service at [AWS DocumentDB](https://aws.amazon.com/documentdb/) that has implemented in a such way that it implements MongoDB client API, but all of the backend code is scalable, safe and custom-made, you could use that as your MongoDB URL with Wekan Docker image mentioned at 5) above.

7) Probably sometime Wekan could have support for some other databases, for example I have [issue in progress at FoundationDB forums](https://forums.foundationdb.org/t/how-to-connect-to-foundationdb-with-mongodb-cli/977) how to get Wekan working with FoundationDB, that has MongoDB compatibility layer. There is also [FoundationDB fault tolerance demo at YouTube](https://www.youtube.com/watch?v=oLGYMdo2q2g). More info at [FoundationDB website](https://www.foundationdb.org/). Although FoundationDB usually requires cluster, so it's not usual for smaller amount of data.

## Summary

Keep at least daily backups. Well, for one client I did set backup for every 15 min, just to make sure.

**Comment by cimm** [comment]
Is there a way to find the broken document in the database?

If I know the broken card I can manually remove it which would hopefully fix my broken board (it's a big board and impossible to move manually).

```
wekan.wekan: MongoError: file with id 5d10eab3d4965208d6153249 not opened for writing
wekan.wekan:     at Function.MongoError.create (/snap/wekan/548/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
tasks wekan.wekan:     at /snap/wekan/548/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
```

How do I find document `5d10eab3d4965208d6153249`? I searched in each of the mongodb collections but couldn't find it. Any ideas?

**Comment by xet7** [comment]
@cimm

Well, you could export database to JSON, try to grep it, or something:
https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file

**Comment by cimm** [comment]
@xet7 Great suggestion, still didn't find anything though. :disappointed: I manually deleted a few 100 cards from the archive in the board which seems to have solved the problem. Progress. Annoying since I lost data we still needed but the only way to export the board.

Two suggestions after this experience:

1. It would  be nice to also find archived cards via the API, it's currently not including those (or I didn't find how to do it).
2. The export could be a bit more fault tolerant and skip cards with errors but still export the other cards instead of showing a blank page.

Thanks for the help!

**Comment by xet7** [comment]
There has been improvements in import/export, and more is coming.
