### ISSUE TITLE
Archive card feature disappear ?

### ISSUE THREAD

**Issue by Kels** [wekan/wekan#1789]
## Issue

**Server Setup Information**:
* Wekan version: 1.20
* Operating System: Debian 8
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): bundle

**Problem description**:
Hello, I were looking for the button to archive a card without any success.
Did the feature were removed ?

Regards,

Kelson

**Comment by xet7** [comment]
Archives have been renamed to Recycle Bin #1429 , because it's more familiar to users than archives.

Click card / hamburger menu / Move card to Recycle Bin.

Also lists and swimlanes can be moved to Recycle Bin.

There is Board / hamburger menu / Recycle Bin, where you see what is at Recycle Bin, and can restore.

There will be later Empty Recycle Bin #1625

On All Boards page, there is also Recycle Bin for Boards. Currently there is bug about Delete board from Recycle Bin #833 , it will be fixed later.

**Comment by hever** [comment]
> Archives have been renamed to Recycle Bin #1429 , because it's more familiar to users than archives.


Hi, I'm not sure for this (as I mentioned in #1429). In time management world, there's always be archive at the end. Gmail has archive and it's great. Trello has archive. Etc. 

When you push something into archive, you'll know it's been there forever. When you push something into recycle bin, you know that after moment it will be probably still there. But you're never know what will happens in future. 

In kanban board I think there must be two places for card that has been done. Archive for that you never want to lost. And recycle bin for that you'll know that in future you will not want. If there's only one place, it may be archive, in my opinion.

**Comment by 360fun** [comment]
> When you push something into archive, you'll know it's been there forever. When you push something into recycle bin, you know that after moment it will be probably still there. But you're never know what will happens in future.

Totally agree: I arrived to this comment because I was crazy looking for "Archive" since I'm used to have it in Trello and Gmail!

Hope is coming back! :\

**Comment by TiibCD** [comment]
If you don't want to see a card anymore you can also delete it instead of moving it to recycle bin.
Archive vs recycle bin, I think this debate won't have an end. The most important is the way it works not the name :)

**Comment by 360fun** [comment]
Well, in real life the recycle bin is where you throw garbage to be "soon eliminated" :P archive is where you "store things" ;) if the recycle bin works like an archive...well...that's just weird for me, but now that I know I will use it without worrying to see tasks disappear! :)

**Comment by OliverWielandBR** [comment]
I also agree with 360fun. 'Archive' would be a better name for a long time storage than 'recycle bin'.
The best solution would be both... ;-)

**Comment by Boldie** [comment]
As I am a developer and from this passion I know: Names are very important, or do you put your backups in a recycle bin and wait till someone will empty it by accident? I will sleep better if I can put something in an archive if I want to keep it and have a recycle bin for rubbish.
I recently started with wekan, and search for a while on how to archive things. I have never thought to archive things in a recycle bin since it can be emptied at any time from anyone.

**Comment by eriksornes** [comment]
I agree. Recycle bin and archive are to entirely different functions. You should empty a recycle bin regularly, where as an archive should rarely be touched.

**Comment by zertrin** [comment]
Same confusion here, the name Recycle Bin does not make sense for cards that I want to archive... I feared that they would be deleted in 30 days or something until finding this issue.

**Comment by vjrj** [comment]
Thanks indeed @xet7 for renaming this again to "Archive" in v1.71.0
https://github.com/wekan/wekan/commit/b919eb23ab807f0ec60c8ba722094bb0743a8af4
