### ISSUE TITLE
Feature Request : Ability to disable API

### ISSUE THREAD

**Issue by GuiGuiSoft** [wekan/wekan#1791]
Hello,

It would be nice if we could disable the API, thanks to a checkbox in the admin panel for example.

_For installations where API is not needed, it seems to be a simple and efficient way to reduce the surface of attack._

Regards.

**Comment by xet7** [comment]
@GuiGuiSoft 

If you are in a hurry, you can use Caddy / Nginx / Apache config to show some empty webpage in API URL.

**Comment by xet7** [comment]
afaik @Akuket is currently looking into adding ability to disable API

**Comment by GuiGuiSoft** [comment]
Thank you for your feedback. No hurry on this point, just looking for the best way to do it :)

**Comment by xet7** [comment]
There is now ability to disable api using WITH_API=false.
Disabling API does disable also exporting Wekan board, because that does use API.

Snap:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

Docker:
https://github.com/wekan/wekan-mongodb/blob/master/docker-compose.yml#L121-L125

Source:
https://github.com/wekan/wekan-maintainer/blob/master/virtualbox/start-wekan.sh#L17-L18
