### ISSUE TITLE
Feature Request: Paste checklists like Trello - each line becomes new item

### ISSUE THREAD

**Issue by coursemyhorse** [wekan/wekan#1846]
Tested on instant sandstorm demo from Wekan website Version 1.20.0~2018-07-18

A very powerful feature of Trello is to be able to quickly create task lists/project plans by copy pasting cells from say excel/project or some such list, into a Trello checklist. When you do this and the list has multiple lines (as any list would) the behaviour in Trello is to recognise a new line in the pasted list and create a new checklist item for each one. So say we have a list like this:

1: Start
2: Do stuff
3: Finish

In Trello if you copy paste the above list you get them as 3 tickable checklist items like this:

![trello_checklist](https://user-images.githubusercontent.com/18658093/44406577-e2c17d00-a553-11e8-9faf-523bc80b235a.jpg)

But in Wekan if you copy paste that you get it all under one single checklist item like this:

![wekan_checklist](https://user-images.githubusercontent.com/18658093/44406648-0e446780-a554-11e8-8221-1e4750d1cdf6.jpg)

In Wekan, you have to manually hit enter/return after every single checklist item, for it to be submitted as an item under that checklist. This is slow. When the first checklist item field/box is populated with data by pasting in a list, upon submitting it by hitting save or hitting enter on the keyboard, it should detect each new line and build a multi item list.

**Comment by xet7** [comment]
Wekan works this way, because Wekan allows multiline checklist items, markdown etc. I think these features are not in Trello. Wekan and Trello are completely different, Trello is not Open Source.

In this case, it depends what would be logical and user-friendly way to paste many checklist items, without losing Wekan multi-line functionality. Should where be some checkbox that would indicate to Wekan that pasted content is in certain format, so Wekan would convert pasted content to multiple checklist items. Pasting multiple checklist items should still allow pasting multiline checklist items.

I have also looked a little about adding wysiwyg editor to card details, maybe with different views for markdown and wysiwyg editors in different tabs. Then it would be possible to copy that edited markdown format content to somewhere else where Wekan accepts markdown, like checklist items.

This all still needs thinking what would be most user friendly way to do these.

**Comment by coursemyhorse** [comment]
@xet7 Thanks for the reply. I am aware that Wekan is open source and I appreciate the work that has gone in to it. I would like to adopt full usage of it but require this feature to be able to quickly build a long task list of work that can be pasted in. The alternative approach is to manually copy/paste or type each one then hit enter which is obviously not desirable. This is a very powerful and useful feature request which would allow for many Trello users to fully adopt usage of Wekan.

If you require to keep the multi lines for one single checklist item, then I can understand this but I think the community would vote for the priority to be to implement this feature request as priority. 
However, perhaps there is a way we can maintain both by implementing this feature request as a new toggle mode switch. The user can select a button on the checklist called something like "turn fast add mode on" whereby the behaviour would change to allow users to paste in a list which gets added as multiple checklist items for each new line in the list.

**Comment by jdaviescoates** [comment]
I just wanted to do exactly this, i.e. paste a big long list and get a checklist item for each line, but it as it didn't work I searched to see if there was a way to do it and then found this issue.  Would love this feature.

**Comment by kszydelko** [comment]
I would like to return to feature requested by **coursemyhorse** (21 Aug **2018). In my opinion it would be great to have checklist working like this. 
Is there any chance to get this available?

**Comment by xet7** [comment]
@kszydelko 

Checklists code is here: https://github.com/wekan/wekan/tree/master/client/components/cards

It does have code how to save checklist to database. So, it would need to use Javascript to split lines of `\n` and add those as separate checklist items.

Here is how to build Wekan and make pull request:
https://github.com/wekan/wekan/wiki/Emoji#how-you-could-add-another-plugin

I mean, is this so important that someone could use their time to figure it out, and add pull request?

Sure there is alternative to pay me at https://wekan.team/commercial-support/ so I could pay some of my monthly bills, and implement this feature. I'm in progress of implementing other features for those that have already paid me.

**Comment by xet7** [comment]
BTW, having current Meteor based software is a lot of effort, to have it available and working with huge amount of features. For example:

- Wekan is 18 years of effort https://www.openhub.net/p/wekan
- Meteor is 51 years of effort https://www.openhub.net/p/meteor-js
- Rocket.Chat is 108 years of effort https://www.openhub.net/p/Rocket-Chat

For those above, imagine:
 `[monthly salary of all those contributors contributors] x [years of work] = [total cost of software]`.

And still, most of Wekan coding I have done for free, as a hobby, because I use Wekan myself, I have many boards in my personal Wekan I run on my laptop. Only small part of Wekan coding is paid. Although, it's nice to sometime be able to pay some of my monthly bills.

Having more contributors would speed up solving those all 650 issues. Sometimes I feel like a bottleneck, if it's just me doing majority of coding.

**Comment by xet7** [comment]
I'm very grateful to all Wekan contributors during these years of Wekan development, and expecially currently most active about 10 developers, you make me very happy.
