### ISSUE TITLE
Wekan 1.35 save SMTP in admin panel not effected

### ISSUE THREAD

**Issue by nguyentrongbang** [wekan/wekan#1856]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 1.35
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux 
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: v8.12.0
* MongoDB Version: 3.2
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://domain.com

**Problem description**:
- *Save SMTP configuration in admin panel but it was not saved in snap*
- *I tried to save SMTP info in admin panel, but when I check SMTP info by snap, the new info was not changed.*
- *Attach log files in .zip file)*

**Comment by xet7** [comment]
I did add SMTP settings back to Admin Panel, because @TNick asked it at #1790 .

@TNick are you interested in fixing this?

There are also many other settings that are set using snap commands, and do not exist in Admin Panel:
https://github.com/wekan/wekan-snap/wiki/Supported-settings-keys

I don't know yet when I do have enough time to add those to Admin Panel.
