### ISSUE TITLE
Feature Request: Easier moving completed card (less clicks)

### ISSUE THREAD

**Issue by bgmnt** [wekan/wekan#1858]
**Server Setup Information**:

* Did you test in newest Wekan?: yep
* Wekan version: 133.0
* Operating System: ubuntu 16.04, localhost on fedora laptop
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker image, mongodb
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache2.4
* Node Version: 8.12
* MongoDB Version: latest - i swear
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): domain.net:83/localhost:83

**Problem description**:
(did search, found nothing, so new issue)

it would be nice to have simple button in the detail view of a card, to mark it completed and have it thrown away from a list. at the moment i need to open one more menu (context menu in the card details - the right one in the screenshot) and choose "move to recycle bin". it's okay, but not that comfortable for people like me, who do not work with "done" lists - e.g. for private todo boards.

of course, when cards do not have any other status than "active" or "trash bin", than i seem to be asking for a shortcut to get rid of a card. a "completed" status would be nice also, but i don't know, how this fits in the concept of wekan (sorry, i am still exploring it).

perhaps someone else find this useful.

**Comment by xet7** [comment]
@bgmnt 

You can use Custom Fields. I added documentation to wiki:
https://github.com/wekan/wekan/wiki/Custom-Fields

Would this work for you well enough?

**Comment by bgmnt** [comment]
Now these custom field thing looks like a powerful feature, thanks for documenting it! I oversaw it. But it is not easier in this setting, since one has to make many actions on every new card, to get it - or did I do something wrong?
What I would expect, is, that a custom field could be added to all cards and even new cards, like a global thing or changing the global template - for the whole wekan installation. This is not implemented so far, right? If possible, it would be great, but Wekan is a great piece of software already, so this is a humble feature request.

**Comment by therampagerado** [comment]
@bgmnt - you got it right - you have to do it for every card - it's quite useless in this case if you're creating few cards per day...

About your idea of 'done' button - it should at least create popup to confirm the action because it will create cases where incidentally someone move the card and it's gone for good until someone return it from the trash or the other 'trash' dedicated board. Nice idea inho but I would like to see it as follows first:

- when you move cards to the trash they don't slow down the board - now if I have more than 200 cards there the board slows to the point it does not refresh the card possition on other users, etc.. The loading is very slow too. The fix sugested by @xet7 to create 'Trash' board and move the cards there is great workaround but can the trash be by default a new 'Trash' board whish is accessible by all other boards in terms of searches? So one does not have to go to the trash and return or search there.
- easy search based on all input fields of a card both in the board and in the trash (separatelly or not)
- popup window for this button to confirm action.

**Comment by KuenzelIT** [comment]
How about a trash bin icon somewhere on the page and dragging completed cards there to put the in the trash bin? I think this would fit in well with the behaviour of wekan.

**Comment by xet7** [comment]
@therampagerado 

It is possible to speed up Wekan board by:
- Deleting activities from Wekan database using [Robo 3T](https://github.com/wekan/wekan/wiki/Forgot-Password)
- Using [cleanup script](https://github.com/wekan/wekan-cleanup)

But those are not integrated to Wekan Web UI yet.

@KuenzelIT 

No, I think dragging would not be right way, and implementing it would probably be complicated.
The right way is to use IFTTT #1160 to move done cards automatically, when IFTTT feature is done.

**Comment by bgmnt** [comment]
Thx for the replys! For me it would be enough to speed up the manual cleanup process like in - sorry for this probably annoying comparison - Trello. There you have the "archive" button on every card. Click - done and still not deleted (trash bin). In Wekan it may be only one click more, but you still have to search the right entry at the end of a long list... and you have to scroll, when the card is near the bottom of the screen. So this is mainly about usability and comfort.

An separate Trash-List would be workaround, but since I use all the space on the screen, the Trash list would need horizontal scrolling, and this is not so fine. And you have to move the card all the way over to the trash list.

Perhaps a solution comes by time, I would enjoy it :)

**Comment by lonix1** [comment]
I want to +1 the recycle bin idea.

To delete a card (not "done", just delete it), it would be nice to drag it to a recycle bin icon. Much faster than going through that very long menu which needs lots of scrolling.

**Comment by xet7** [comment]
Moved to #1996
