### ISSUE TITLE
OAUTH2/OIDC example documentation

### ISSUE THREAD

**Issue by danpatdav** [wekan/wekan#2052]
I would like to update the [documentation](https://github.com/wekan/wekan/wiki/OAuth2) for OAUTH2 and provide examples on how standalone deployments can configure this feature.  However, after bouncing back and forth between the various issues and branches, I am not really sure of the current status.

The oidc package and code seems to be present in the current release (v1.85).  However the Dockerfile sets OAUTH2_ENABLED to false, suggesting you have to build your own image to make it work, rather than pulling from dockerhub/quay.  Is that the case?

`salleman:accounts-oidc`

    OAUTH2_ENABLED=false \
    OAUTH2_CLIENT_ID="" \
    OAUTH2_SECRET="" \
    OAUTH2_SERVER_URL="" \
    OAUTH2_AUTH_ENDPOINT="" \
    OAUTH2_USERINFO_ENDPOINT="" \
    OAUTH2_TOKEN_ENDPOINT="" \

Any insight on the state of OAUTH2/OIDC for standalone installations?

**Comment by xet7** [comment]
OIDC does work, with these conditions:
- you use [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) as identity provider. And not using any other like google/rocketchat/other oauth2, because only doorkeeper works.
- for doorkeeper, [current docs](https://github.com/wekan/wekan/wiki/OAuth2) are correct, and do work work with Wekan
- there is no need to build custom docker image. OIDC is included. Setting environment variables at docker-compose.yml does not mean building custom docker image. It's the same prebuilt docker image with settings from environment variables.

**Comment by xet7** [comment]
you can use newer meteor-1.8 image, it does have OIDC and less CVEs.

**Comment by xet7** [comment]
Oops I clicked close issue button by accident, so I reopened this.

**Comment by danpatdav** [comment]
Can I ask what makes doorkeeper the only option?  I would have thought (always dangerous, I know!) that with OIDC/OAUTH2 being standards, any compliant provider would work.

**Comment by xet7** [comment]
Each OAuth2 works differently, depending on setting fields, internal implementation of OAuth2 etc.
That's why Rocket.Chat also has Google OAuth2, Custom OAuth2, etc.

Yes, I have tried that OIDC with Wekan, and it always logins as first admin users, not as any other user. That is the bug in that issue, that it's not general, and can not be general It's all differerent.

Some accounts packages are listed at:
https://guide.meteor.com/accounts.html

Adding new auth package is mainly just adding that to list of other auth packages. Like adding couple lines of code to have rocketchat login in Wekan. It's not like it's difficult. It just needs someone to have some time to add it.

**Comment by tiagoefreitas** [comment]
See my comment here for more info on how to fix it for another provider:

https://github.com/wekan/wekan/issues/1874#issuecomment-446922469
