### ISSUE TITLE
Card scrollbar ignores mousewheel

### ISSUE THREAD

**Issue by rinnaz** [wekan/wekan#2058]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: **yes**
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? **yes**
* Wekan version: **v1.91.0**
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: **Ubuntu 18.04**
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): **snap**
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version: **v8.14.0**
* MongoDB Version:
* ROOT_URL environment variable http://localhost

**Problem description**:

Steps:

- Open card with many comments 
- Try to scroll using mouse wheel

Dragging scrollbar with cursor works fine.

Scrolling with PageUp/PageDown works only after mouse click on card area.

Maybe related to #2056

![scrollbar0](https://user-images.githubusercontent.com/36293513/50018290-d9b35a80-ffdf-11e8-9ca0-e407552b8227.gif)

**Comment by xet7** [comment]
I just [added mquandalle:perfect-scrollbar back](https://github.com/wekan/wekan/issues/2057#issuecomment-447596107) so the result is:

**Pros**
- visually Wekan looks better
- clicking and dragging scrollbar still works
- there is no errors at browser dev console
- scrolling cards on list works

**Cons**
- scrolling comments etc on single card does not work. This could be because [I changed mousewheel file path](https://github.com/wekan/wekan-scrollbar/commit/1c4a47e5c60347f948e70421cca391d7429749ff) so that I could include it locally #2056 but I think I messed up file path. File jquery.mousewheel.js [is in repo](https://github.com/wekan/wekan-scrollbar).

**Comment by xet7** [comment]
Firefox console shows this message:
> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by xet7** [comment]
And now I also duplicated this, it seems that it tries to load file from cdn always. When I had Wekan install at localhost, disconnected internet, mousewheel does not scroll on card.
