### ISSUE TITLE
tiered/child boards

### ISSUE THREAD

**Issue by hsduk** [wekan/wekan#207]
Hi
viva libreboard!
I'd like to suggest the ability to support tiered/child/hierarchical/multi-level boards.
This would allow you to place a card on a board which relates to another lower level or external board.
On click/drill down, the full details of the underlying board is displayed, in-line, in a new tab or in summary.
This will facilitate high-level/birds-eye/management type views of complex boards/projects.
e.g. on highest level board, add a new card. Select new option to generate child board. New child board link generated. Click that, add detail. Child detail help build summaries to populate higher board info.
Logical progression from this would be for child boards to have a status - which bubbles up to the higher level to show overall status for a given card/child board.
This will help on larger projects - I currently use a link to the child board in the description - would be best to incorporate something like this in code.
Happy to help if i can
hsdch

**Comment by snolahc** [comment]
Brilliant.
This idea should merge with the issue #211 :)

++

**Comment by mikkelking** [comment]
I agree, great for managing multiple workstreams or projects

**Comment by mquandalle** [comment]
This is a good idea!

However since the release of Wekan v0.9, I try to keep the GitHub issues tracker exclusively for bug reports and specified feature requests — the goal for me being to close the issue as soon as possible. For more general discussions about Wekan (that will stay open), I recommend using our new forum. May I ask you @hsduk to copy/paste your post on [the forum] (http://discuss.wekan.io)?

**Comment by hsduk** [comment]
Moved to http://discuss.wekan.io/t/tiered-child-boards-207

**Comment by hsduk** [comment]
I had a go - https://github.com/hsduk/wekan/tree/linked-boards
