### ISSUE TITLE
After moving cards from board B to board A, Board A no longer loads

### ISSUE THREAD

**Issue by ashgoodman** [wekan/wekan#2073]
## Issue
After moving cards from board B to board A, Board A no longer loads, instead it just shows the loading icon continously

Server: Ubuntu 18.04
Wekan v1,96.0
snap install

Add these issues to elsewhere:
- LDAP: https://github.com/wekan/wekan-ldap/issues
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?:
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version:
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System:
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source):
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version:
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *Explain steps how to reproduce*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ?*
- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
- *If logs are very long, attach them in .zip file*

**Comment by xet7** [comment]
@ashgoodman 

When I move cards from board B to board A, both boards still load correctly.

I tested this with existing Wekan boards in snap, and new Wekan v1.96 snap install.

Please give more details:
- Are both boards normal boards?
- Or is some of them subtask board?
- Is this upgraded from old Wekan install, or new Wekan install?
- Does cards you moved have subtasks or custom fields?

**Comment by ashgoodman** [comment]
@xet7 

I've done some further testing to try to duplicate it
+ It seems to be an issue with having custom fields on the card on the originating board I'm moving the card from. Custom fields on the target board dont seem to be an issue.
+ In mobile view I can load the target board, but, the list the card was moved to wont open while the other lists on that board will
+ there are no tasks or subtasks on the origination board nor the target board
+ Its a fairly new install via snap (about 3 weeks old)  afaik there haven't been any updates to the snap version since I installed it
+ Exporting the target board, renaming it,  and then importing it to the same installation recovers the board in full except all custom fields are gone (apparently custom fields are not included in the export?)

**Comment by ashgoodman** [comment]
More info  when I run sudo snap logs wekan.wekan I get the logs in the previous mesage

But when I run sudo snap logs wekan I gte the same with the addition of:
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.

However when I run ulimit -s I get 8192

For snap is there something different about how the ulimit is set?

**Comment by rlach** [comment]
I have the same problem and I've looked into what's happening.

The customField is assigned to a board, and tasks link to a custom field. When you move/copy the card to different board the card is still linking to the same customField. That customField doesn't exist in new table. The view, when trying to build itself gets all customFields for current board(which doesn't contain new field) and then tries to render cards. Because cards link to custom field which is undefined in this context the whole view crashes.

For now I've fixed my broken boards by removing customFields assigned to cards trough database, since I didn't have a lot of them.

I see some solutions to fix the issue:

1) When card is copied/moved all customFields are removed from the instance on new board
2) When card is copied/moved we try to find customField with same name and type in new board. If it doesn't exist we create such customField. Then we update the card to link to new customField. We do it for all custom fields.
3) We update model of customFields so they can be connected to multiple boards. When we copy/move card we check if target board has current customField and if not we add new board to customField.boardIds collection. This would mean we have to update delete customField function, so it doesn't get removed from all boards.
4) Change the rendering methods so they don't crash if board doesn't have some customfields and just get that custom field by id.

Personally I think 2nd option is the safest option and most consistent with how tags behave.

**Comment by xet7** [comment]
@rlach 

Yes 2nd option would be safest. You can submit PR.

**Comment by iuliaj** [comment]
I have the same problem. When copying or moving a card, the destination project does not load. I export the project, remove the custom fields of the project and import it. And it works…

**Comment by Samunosuke** [comment]
I had the same problem. I solved it by reverting the database to a backup - a daily backup saved my day.

**Comment by dbertolo** [comment]
We've experienced this bug as follows: Board A has custom fields, Board B does not. When we copy or move a card from A to B, board B stops working. When we delete the customField entries of that card in the MongoDB, it loads again. Second option was to create a customField for board B on the DB with the same "name" property and change the linked customField "_id" on the card. This should be checked when copying/moving the card (e.g. create customField on the destination board and apply the new customField _id to the card).

**Comment by nerminator** [comment]
It seems like this bug is already fixed in devel branch.  I have tried moving a card with a custom field to another board without that custom field and it copied the custom field to the destination board.  I could open the destination board without any problem. But I couldn't try it in snap or edge branch.
