### ISSUE TITLE
Feature Request: Mobile drag handles. Option to enable desktop drag handles.

### ISSUE THREAD

**Issue by BrianD91** [wekan/wekan#2081]
I'm running the wekan snap on Kubuntu 18.04

When I create a card the little compass icon on the right side of the card doesn't appear, and if I click on the card to try to open the dialog that *should* open it just tries to load for a while and then the page breaks with a connection timeout error. 

Attached is an image that shows what a list of cards looks like on my machine currently.
![wekan-not](https://user-images.githubusercontent.com/37163937/50526792-70891800-0ab2-11e9-8c90-ca946b1508b0.png)

**Comment by xet7** [comment]
@BrianD91 

I presume with options compass you mean drag handles #1772 that was implemented at https://github.com/wekan/wekan/pull/2067 in [Wekan v1.95](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v195-2018-12-21-wekan-release).

They currently work only on mobile webbrowser this way:
- It's possible to use finger to move board around
- When long pressing drag handle it's possible to move card

Currently on dektop browser:
- Drag handles are visible when webbrowser window is made small enough
- It's not possible to move board with mouse by dragging non-handle part, like it's possible by using finger on mobile browser.

@hupptechnologies 

Is it possible that you could implement drag handles, long press and moving around with mouse pointer also for desktop? So that drag handles would be always visible? I tried to implement it, but I did not get moving with mouse pointer working yet.

**Comment by BrianD91** [comment]
Yeah I can still click on any part of the card & drag the card to move it around, in the desktop browser version. But when I click on the card, it attempts to open the URL to edit that specific card and eventually just hits a timeout error. So I can only add a title to a new card, I can't really edit the cards in any way.

**Comment by BrianD91** [comment]
Ok, so it seems what's actually happening is some sort of mis-match. The URL that the minicard links to is the IP address, 192.168.x.x. if I inspect element and replace that part of the URL with `localhost` then click on the minicard it brings up the window to edit the card in-depth.

**Comment by xet7** [comment]
@BrianD91 

If you don't have your ROOT_URL correctly set, you can not even open card and all kinds of stuff is broken.
https://github.com/wekan/wekan/wiki/Settings

**Comment by BrianD91** [comment]
:+1: thank you Xet! I don't know how I messed up the ROOT_URL, but I reset set it and everything seems to be working perfectly now!

**Comment by xet7** [comment]
Drag handles for:
- Swimlanes
- Lists
- Cards
- Checklists
- Subtasks

Based on [feedback](https://github.com/wekan/wekan/issues/2704), my plans for near future are:
- At mobile, drag handles always enabled.
- At desktop, drag handles disabled by default. Per user option to enable drag handles.
- Try to make handles to not overlap.
- Change handle icon to hand image.

**Comment by compumatter** [comment]
Would consider contributing some funds to development of improving **mobile device accessibility** of existing desktop version if this helps.

**Comment by xet7** [comment]
@compumatter 

It's possible to contribute at https://wekan.team/commercial-support/
Or email me at support@wekan.team

**Comment by xet7** [comment]
@compumatter 

How mobile device accessibility should be improved?

**Comment by xet7** [comment]
Moved to here from #2823 

From @saschafoerster

I still have problems with scrolling vs. drag and drop on mobile devices, when there is a long list of cards. I see there is the new drag-button on the right side, but when I try to scroll in the middle or left from the middle, then suddenly cards start moving instead of scrolling. Only when I go to the very left side, I can scroll on mobile.

**Comment by mfilser** [comment]
Hello dev's
i liked the drag-handles feature very much, it solved a lot of problems of using wekan at my mobile.
I had the version 3.56 installed a long time.
Today i updated to version 3.97 and saw the feature is gone, i have no drag-handles at the cards anymore.

Furthermore it would be great to add drag-handles to checklists as well :)

Thank you in advance for any reply.

**Comment by xet7** [comment]
@mfilser 

1. At mobile Chrome, click menu / show desktop view. Or use desktop webbrowser.

2. Open some board. Click right top corner your username / Change Settings / Show desktop drag handles.

Not everything has drag handles yet.

**Comment by xet7** [comment]
There are differing opinions about drag handles:
a) Some do like drag handles.
b) Some do not like drag handles.
c) Some would like that at mobile, dragging should not be possible at all.
d) Some would like that dragging would start after delay, like in Trello mobile app. Although, some think dragging immediately with handle is better.
e) Some would like that drag handles should be removed completely.

It really depends on each person, what that person prefers.

**Comment by xet7** [comment]
Without visible drag handle, it's not possible to quess where to drag from.

Drag handle positioning could be improved, so that handle is not at top or under some text or image.

**Comment by mfilser** [comment]
@xet7 
Thank you a lot for your reply.

I tried your suggestion at mobile Chrome, but the drag handles are not visible at mobile after i enabled it, the drag handles are only visible at the desktop version.

I can absolutely understand that many people have different thinking how a software should work,
but also i want to mention that with version 3.97 i can't use wekan at mobile anymore. If i have many lists i can't scroll them anymore, everytime i try to scroll i move a list up or down.

I also tried at mobile the Web-App version of Chrome, but also the same result that i can't scroll at list view.

Maybe you can give it a try to use wekan at mobile Chrome?

**Comment by mfilser** [comment]
I found out that i can't scroll at mobile Chrome anymore since this commit, even the drag handles are visible in mobile view.
**96abe3c6 New feature: Now there is popup selection of Lists/Swimlanes/Calendar/Roles**

The commit is too big for me to find why, i think it's something with the cookies maybe ...
I only tried to setup a dev environment, i am not familiar with meteor, jade, mongo-db and all the stuff.

**Comment by xet7** [comment]
@mfilser 

That commit is about these major features:
- Allow public board to open correctly in many browsers
- Allow change board view of public board, with select and reload page, using cookies

There could be some changes also related to drag handles, that would need a closer look.

**Comment by marc1006** [comment]
@mfilser 
Can you please check out the newest version of Wekan? I've re-enabled that the drag handles are always activated on mobile devices/small screens (see https://github.com/wekan/wekan/pull/3040 for details).

**Comment by xet7** [comment]
@marc1006 

I will make new Wekan release today, so I can then start closing these mobile web issues.

**Comment by marc1006** [comment]
@xet7 Would it be possible that you can take a look at https://github.com/wekan/wekan/pull/3045/commits/f1b18d79cdbfd9c9edecf4f93a89e88ee1c6faea before doing that? I think the current behavior is really annoying (interpret a <= 20px distance drag-and-drop as a mouse click).

**Comment by xet7** [comment]
@marc1006 

Do you mean that https://github.com/wekan/wekan/pull/3045 I merged?

**Comment by marc1006** [comment]
@xet7 Yep, thanks :)

**Comment by mfilser** [comment]
@marc1006  @xet7 
Thank's a lot for the wekan 4.00 release, it's a big big mobile version milestone :man_dancing: 
Drag Handles are back again, scrolling works at list view, and also the much better handling at the checklists :)
Of course, also to mention the whole wekan projects, it's a great work of all.
