### ISSUE TITLE
Problem with root-url and Favicon

### ISSUE THREAD

**Issue by letmp** [wekan/wekan#2094]
I installed wekan by following these instructions:
https://github.com/wekan/wekan-snap/wiki/Install
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

I configured nginx to have wekan running at https://serverdomain/wekan
and I also set the root-url accordingly:
sudo snap set wekan root-url="https://serverdomain/wekan"

Everything is working fine except the favicon. Using the networkanalysis of firefox I can see that wekan-favicon.png is requested under "https://serverdomain/wekan-favicon.png" instead of "https://serverdomain/wekan/wekan-favicon.png"

**Comment by Meeques** [comment]
Hi @xet7 is this something you're still working on? 
Kind regards!

**Comment by xet7** [comment]
@Meeques 

I added some fix. Not tested yet, but it should work.

**Comment by xet7** [comment]
In that fix, I removed `/` from URs so that it would work with relative paths like https://serverdomain/wekan

**Comment by Meeques** [comment]
Thank you! I assume this is fixed in a Version after 6.09?

**Comment by xet7** [comment]
This fix is not in any release yet, I would like to improve upgrade experience before releasing automatic updates etc https://github.com/wekan/wekan/issues/4423#issuecomment-1197245681

 It's possible to test it now anyway: https://github.com/wekan/wekan/issues/4423#issuecomment-1197919398

**Comment by dsvk** [comment]
@xet7 https://github.com/wekan/wekan/commit/1b95f9f167a021ac0d0c9392ced6a9cd888ffe2d has broken favicon loading on the boards themselves though. If you navigate to a board directly wihout having the favicon already cached then instead of loading `wekan.example.com/favicon-16x16.png` the browser tries to find it under `wekan.example.com/b/[BOARD_ID]/favicon-16x16.png` and despite being returned an `HTTP 200` the favicon file is not actually there, it's just a fallback redirect to the board itself.

I imagine using an absolute path to the favicon automatically prepended by the the admin-configured root URL would cover all cases (subdir installations, navigating to boards directly or both conditions combined).
