### ISSUE TITLE
Feature Request: Duplicate Board

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2100]
To All Boards page, add to each board right side of `star` Font Awesome icon new Font Awesome `copy` icon that will duplicate board, when it's clicked. And also add related code to duplicate board.

**Comment by Angtrim** [comment]
The first version of this feature should be ready.
I have decided to add the icon in the bottom right corner, since it has a different "flow" w.r.t the star icon.
The icon is shown only after the mouse over event, as for the star (should we make it always visible?).
When the icon is clicked a copy of the board is created with the same title but with a " - Copy" appended.
The back-end code is basically a connection between the export and import code.
The user is redirected to the copied board.

See the preview attached. (Duplicate icon is bigger because the mouse was over it)
<img width="907" alt="screenshot 2019-02-13 at 19 33 05" src="https://user-images.githubusercontent.com/4083396/52735034-e8f65a80-2fc6-11e9-904b-31d0badbf9ec.png">

**Comment by sfahrenholz** [comment]
can be also closed
