### ISSUE TITLE
Wekan Token Creation

### ISSUE THREAD

**Issue by dhanuk05** [wekan/wekan#2129]
We are trying to implement a single sign on from our web app to Wekan. When a user is created it will create the same user in the Wekan via REST API. But when logging in using the REST API you will have to provide username and password to get a token with an expiry date. Storing unencrypted or decryptable password is not an option for us. So how can we still use the API after the token is expired without a password?

**Comment by xet7** [comment]
Only Admin user can use REST API with username and password of Admin user. Passwords are stored encrypted on Wekan database. I would presume that you would only create users that have some other role like Normal/No Comments/Comment Only, like described at Wekan GitHub Wiki REST API Roles page.

Adding feature like using some API KEY instead of username would most likely not make any difference, because it still has access to everything, including changing passwords.

If you have some other webserver like Nginx/Apache/Caddy in front of wekan, you can add additional restrictions to /api path, like allowing only from some IP addresses, or denying that address completely and accessing /api path through VPN.

If you use PHP to access API then you can have Ioncube PHP Encoder to obfuscate PHP source code where is your Admin user username and password.

Is this enough for you? Or how should it work?

**Comment by xet7** [comment]
Sure you can also use MongoDB database directly too, changes will be applied immediately to Wekan, but it's not recommended, because database schema can change.
