### ISSUE TITLE
Bug: Wekan does not allow for moving cards between and within lists on Sandstorm

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2143]
Moved to here from https://github.com/sandstorm-io/sandstorm/issues/3113

From @pantraining

With the last update of the Wekan API, it is impossible to move any cards between lists, but also to move them up or down manually (only top or bottom via menu is possible), drag-and-drop does not work at all.
Thanks for any solution, as it limits the usability of the whole Wekan instance...

**Comment by xet7** [comment]
@pantraining

What version of Wekan you have?

**Comment by pantraining** [comment]
@xet7 
2.01.0~2019-01-06

**Comment by ocdtrekkie** [comment]
I am reasonably confident 2.01 works fine for these features, as I use them and am currently using 2.01 myself on Sandstorm. 2.09 is available on the Experimental Market[1] (I haven't tested it), but since I know I don't have this issue on 2.01, I kind've doubt 2.09 will help.

What browser are you using, and what is your Sandstorm version?

[1] https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true

**Comment by juanluisbaptiste** [comment]
I'm seeing this with latest version 3.44 on docker image from quay.io. After upgrading from 3.00 I cannot move cards between lists or even in the same list. Going back to 3.00 works again.

**Comment by xet7** [comment]
@juanluisbaptiste 

Try 3.45.

**Comment by juanluisbaptiste** [comment]
> @juanluisbaptiste
> 
> Try 3.45.

It worked, thanks !
