### ISSUE TITLE
Feature Request:  Swimlane/List/Board/Card templates

### ISSUE THREAD

**Issue by rterwedo** [wekan/wekan#2165]
Would be great if you could template swimlanes.

For example, say a swimlane represents a client, and for every client you have the same 15 cards/tasks.

When creating a new swimlane, you could chose from a template instead of making same cards every time.

If there is interest, I will register a bounty of $350.  If this exists and I am an idiot (could not find in docs) - I will pay $100 to update docs. =)

**Comment by xet7** [comment]
@rterwedo 

Yes there is interest, you can add bounty of $350 to
https://www.bountysource.com/issues/69626180-feature-request-swimlane-templates

This feature does not exist in Wekan yet.

**Comment by rterwedo** [comment]
Added bounty of $350

**Comment by rterwedo** [comment]
Added $300 more to reach target request of $650.

**Comment by xet7** [comment]
@andresmanelli is currently working on this.

**Comment by rterwedo** [comment]
@xet7 Thanks for the heads up.  I will lean on the community for proper code review/following your guidelines for submission.

@andresmanelli if you could submit a few screenshots/concepts when you have a moment, would be fantastic.

**Comment by andresmanelli** [comment]
I'll share my concepts/progress as soon as I can. I'm just starting on this :D

**Comment by rterwedo** [comment]
@andresmanelli Cool.  My general idea is to then further extend templating to boards followed by users if that helps from a code point of view.

**Comment by andresmanelli** [comment]
@rterwedo Yes, I was actually planning to add templating as a general case, at least from a model point of view (Cards/Lists/Swimlanes/Boards).

I'm working on my data model. Once I have a minimal mock-up I'll push to my fork so you can take a look :smile:

**Comment by rterwedo** [comment]
@andresmanelli Ok cool - you rock.  Consider also the concept of templated users (ie with boards that contain swimlanes, etc)

**Comment by andresmanelli** [comment]
Hello, here is a gif showing the progress so far.

![wekan_demo_templates](https://user-images.githubusercontent.com/7302217/53292378-bec04c00-37c1-11e9-80c4-401a4fd22dd6.gif)

## Short wiki

- Every user has a templates board
- There are 3 fixed swimlanes:
  - Card templates
  - List templates
  - Board templates
- You can add swimlane templates: Just add a swimlane in this board
- The templates board (and all template-boards) are hidden from the main list
- To access the templates, you can click on "Templates" on the main list header, or by going to the user's menu => Templates (as shown below)

![selection_001](https://user-images.githubusercontent.com/7302217/53292401-4312cf00-37c2-11e9-8cf4-305946ed83ae.png)

![selection_002](https://user-images.githubusercontent.com/7302217/53292403-4d34cd80-37c2-11e9-8a62-98865fcae615.png)

### Important
As swimlanes and lists are managed by their `Id`, if you try to add, for example, two template swimlanes, the lists would be duplicated. In order to solve this I added a title check: *If there is a list with the same name as the template list to be added, we use this same list to put our cards into*.

## Try it out
I pushed my commits to my [fork](https://github.com/andresmanelli/wekan/tree/edge). Using the [wekan-dev](https://github.com/wekan/wekan-dev/) environment it should be fairly easy to try this out.

## What's missing
- Menus to create a board from a template
- Templated users (Not really started, thinking about it)

@rterwedo @xet7 Let me know what you think !

**Comment by xet7** [comment]
@andresmanelli 

- Merge latest commits from upstream wekan edge

- Fix lint errors:
```
sudo npm -g install eslint
cd wekan
npm run lint
eslint --fix filename
```
and if something is not automatically fixed, do some web searches how to fix it.

**Comment by xet7** [comment]
@andresmanelli 

With my existing Wekan boards, after fixing lint errors, All Boards page has only Add board button etc, but no boards listed at all. So I can only change to those boards that have shortcuts.

**Comment by andresmanelli** [comment]
@xet7 Pushed the rebased branch (I did not fix lint errors on wekanCreator.js and filter.js because I didn't modify these files.

I didn't add migrations yet, so your boards are missing the `type: 'board'`

Could you try it with a fresh database?

**Comment by xet7** [comment]
@andresmanelli 

Yes I can try. Please add migrations.

**Comment by xet7** [comment]
@andresmanelli 

In mobile view, that you see by making browser window less wide, Card/List/Swimlane templates duplicated so that for example Cards templates lists all Card/List/Swimlane templates, etc.

**Comment by andresmanelli** [comment]
@xet7 Fixed the miniscreen render issues

**Comment by andresmanelli** [comment]
@xet7 Pushed migrations

**Comment by xet7** [comment]
@andresmanelli 

I merged your changes to Wekan edge branch and added Finnish translation.

At templates board words Templates/Card/Swimlane/Board Templates are not translated. There is similar issue #1601 that Welcome board is not translated. Although, it is good that it's possible to change name of board Templates. I would think that if Templates and Welcome board has default texts, if user language is different, those text could be translated to different language.

![template-translations](https://user-images.githubusercontent.com/15545/53316028-dcc7a280-38ce-11e9-877a-ca3af69bcfa8.png)

**Comment by xet7** [comment]
@andresmanelli 

You can merge latest changes from Wekan edge branch to your edge branch.

When I add new template boards to Templates, click linked template board, then in Lists mode I can not add new List, Enter and Save button of list name does not work. It's only possible to modify template board after changing from Lists mode to Swimlanes mode.

![template-board-list-save-not-work](https://user-images.githubusercontent.com/15545/53316604-34ffa400-38d1-11e9-8f77-ab23203cbb31.png)

**Comment by xet7** [comment]
@andresmanelli 

After above, Lists view is always empty on Welcome board and other boards. This also make public boards show empty, because public boards show only List view. When logged in, if I try to add new lists, it does not show in Lists mode, but they are created anyway and are visible in Swimlanes mode.

Also, I'm thinking, that maybe it's better that there would be no Welcome board at all. That way it would not need to be translated. Most users import or create custom board anyway. It should just be possible to create new board (or import), and have default swimlane.

It would also be good to fix #1959 so that when default swimlane is deleted, it would be possible to create new swimlane anyway.

**Comment by andresmanelli** [comment]
Hello @xet7, thanks for the feedback.

I pushed the fix to my fork, and added board creation from templates.

What do you think about copying labels if same color and text is found on the target board? It would be handy.

## TODO
- [ ] Ask for new name before element creation
- [ ] Copy attachments from templates
- [ ] @xet7 / @rterwedo ?

**Comment by xet7** [comment]
@andresmanelli 

Yes labels etc should be copied.

Is there some way to copy existing board/list/card to template?

**Comment by andresmanelli** [comment]
I forgot that ! Not for the moment, but should be quite straight forward. Added to the list of todos

**Comment by xet7** [comment]
@andresmanelli 

Would it be possible to export/import cards/lists/swimlanes as JSON ? It would help a lot. Although I don't know would it be out of scope. There is some open issues about those already.

**Comment by andresmanelli** [comment]
@xet7 I'm not really sure, at least not before finishing the templating inside wekan. I'd have to take a look at the board export-import methods and find a way to have a consistent export-import behavior.

**Comment by xet7** [comment]
@andresmanelli 

Ok.

Also, @Angtrim has coded some of Duplicate Board feature #2100 and currently is looking about some related import/export fixed, but there is no PR about that yet. I don't know are these someway related to templates.

**Comment by andresmanelli** [comment]
We must have added some common code yes, as my `copy` helpers in the models
are meant for that.

I'll change a little bit those functions to make them for generic and
clean. I should probably talk to him and synchronize the two issues :)

Le lun. 25 févr. 2019 à 23:32, Lauri Ojansivu <notifications@github.com> a
écrit :

**Comment by andresmanelli** [comment]
We must have added some common code yes, as my `copy` helpers in the models are meant for that.

I'll change a little bit those functions to make them for generic and clean. I should probably talk to him and synchronize the two issues :)

**Comment by xet7** [comment]
@andresmanelli 

Yes you can chat with @Angtrim at Vanila Chat. That Duplicate Board code is something that was possible to do because of all the work @Angtrim did with IFTTT Rules.

**Comment by xet7** [comment]
@rterwedo 

Wekan v2.29 is now released, it includes current version of Templates feature. Please test.

@andresmanelli will add remaining TODO items later.

**Comment by rterwedo** [comment]
@xet7 I will not be able to test for sometime due to family/travel schedule, etc.  If the community thinks its ok, I will not hold the bounty hostage and can release - hopefully if there are issues later that I find they will be fixed by @andresmanelli ?

**Comment by xet7** [comment]
@rterwedo 

Yes Docker image is updated, v2.29 and latest tags are here:
https://quay.io/repository/wekan/wekan?tag=latest&tab=tags

I did test that templates do work, it's possible to add templates and insert those.

I will close this issue now and move remaining to new issue, they will be fixed by @andresmanelli . I will also give info to @andresmanelli how to claim bounty.
