### ISSUE TITLE
Slow scroll in card detail

### ISSUE THREAD

**Issue by Alex131089** [wekan/wekan#2179]
## Issue

**Server Setup Information**:

* Wekan version: v2.19
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snapd

**Problem description**:
When viewing a card, scroll is very laggish, I guess there's some "smooth scroll" ""feature"" here, but could it be possible to disable this?
~Using Wekan already feels laggish (especially the reload on card opening) and this doesn't help :/~
Edit: nevermind, it seems the full reload was caused by one missing ressource because of misconfiguration (https) ; slow scroll remains however

**Comment by xet7** [comment]
Wekan loads only visible cards. When cards are scrolled, more cards are loaded from server on the fly. Without this newest fix previously it was not possible to load big Wekan board that has thousands of cards. That board was imported from Trello, and Wekan kept on loading all of it to browserside, hanging infinitely.

Ideas and PRs welcome how to speed up this.

**Comment by Alex131089** [comment]
Oh, sorry for the misunderstanding: I'm talking about the scroll inside a card (I should not have used the plural here), when viewing it's properties, checklists, subtasks, activities, ...

**Comment by Soltares** [comment]
I also noticed that the scroll seemed slower than expected for card details (as if it took extra "work" to get to the bottom), but I only just discovered this amazing piece of software last week, so I wasn't sure if this was by design.

Speed is somewhat subjective, but the behavior of scrolling the activity details in the sidebar seems closer to what I'd expect.

I threw together a quick screencapture comparing the two and attached it to this comment.  I saw the "delayed scroll" Alex131089 referred to when clicking and dragging as opposed to using the mousewheel -- as if the content of the card needed to catch-up.

While testing, I happened to notice that for a very brief period after the card details load scrolling is much faster, but then quickly resets to the slower speed and the scrollbar moves back to the top (the scrollbar thumb/scrollbox also seems to shrink at this time for what it's worth).

I'm using Firefox 64.0 snapd Wekan v2.20.0.  Also observed on Chromium Version 71.0

Just my two cents in case it helps!  Thanks for all the hard work!

![wekan-scroll-min](https://user-images.githubusercontent.com/40914111/52600511-deeb2500-2e29-11e9-8626-27253be5319d.gif)

**Comment by rinnaz** [comment]
As far as I remember that's the result of applying *MaazAli/Meteor-Malihu-Custom-Scrollbar* (now forked as *wekan-scrollbar*)

**Comment by xet7** [comment]
Adding that scrollbar did fix #1404

**Comment by rinnaz** [comment]
Maybe we could just tune it a bit, and it'll be fine.

**Comment by superlou** [comment]
It definitely seems browser specific with the custom scrollbar. In a scientifically rigorous test, I measured the number of mouse wheel scrolls to go from the top to the bottom of the same card with my typical technique:

Edge 41.16299.15.0: 3 scrolls
Firefox 65.0.1: 11 scrolls

**Comment by xet7** [comment]
@cafeoh 

Well, I'm so happy that the real hero @hupptechnologies was able to to fix `Clicking the scrollbar closes the card on Chrome` https://github.com/wekan/wekan/pull/2050 , and also scrollbars looking good, with also all the other UI fixes. Because I was not able to fix that myself. So if some Wekan contributor has time to dig into scrollbar code, and make it better, pull requests very welcome!

**Comment by xet7** [comment]
I think @hupptechnologies can fix this, so please someone add some bounty for this issue so that @hupptechnologies can start working on this.

https://www.bountysource.com/issues/69887572-slow-scroll-in-card-detail
https://wekan.team/bounties/index.html

**Comment by cafeoh** [comment]
https://github.com/wekan/wekan/blob/a33cad0d13c25cc01604802337a920e3975f6365/packages/wekan-scrollbar/jquery.mCustomScrollbar.js#L114
This here is where the default inertia is set (I wasn't quite accurate when saying it takes a full second, it's actually 950ms). I believe that setting this value to 0 in the meantime would be an easy fix (I'm not a web developper so I wouldn't really know where to start, forking it and building it myself but I'm pretty positive this should work).

https://github.com/wekan/wekan/blob/a33cad0d13c25cc01604802337a920e3975f6365/packages/wekan-scrollbar/jquery.mCustomScrollbar.js#L435

This line seems to set the minimum value to 17 for some reason, even though the doc does say to set it to 0 to disable it.

> scrollInertia: integer
>
>     Set the amount of scrolling momentum as animation duration in milliseconds.
>     Higher value equals greater scrolling momentum which translates to smoother/more progressive 
>     animation. Set to 0 to disable.

**Comment by xet7** [comment]
@cafeoh 

Thanks, I'll try that change.

**Comment by maedoc** [comment]
Just to add a datapoint, I tried this,
```
scrollInertia: 0
```
and it's definitely scrolling more responsively but still "feels" a little wonky at least in Firefox on Windows.  I would try low non-zero values, but the Docker image takes a long time to build (I'm not familiar with dev process for Wekan)
