### ISSUE TITLE
Feature Request: Everything with a date should be visible in the calendar

### ISSUE THREAD

**Issue by TomasAxelsson** [wekan/wekan#2190]
I love wekan but the calendar in the current state is not good for anything.

The original state should be that if a card have any date at all set (start, end, due, recieved) it shows up in the calender and then if you want to you could filter....
I have googled around and I don't find any clear descirptions on what and why things show up in the calendar....

**Comment by xet7** [comment]
@TomasAxelsson

Thanks for adding feature request. I'm happy to help new Wekan contributors to get started in coding, answering any questions here at GitHub issues.

Currently Wekan is in use around the world in thousands of servers, as can be seen at https://snapcraft.io/wekan . That is only for snap version of Wekan, without Docker etc other platforms.

If some Wekan contributor has some free time to look at this, it's welcome. Otherwise I will look at this later when I'm implementing Wekan calendar sync to Friend calendar.

**Comment by xet7** [comment]
Moved to #2562
