### ISSUE TITLE
Default setting / deadlines notification

### ISSUE THREAD

**Issue by Naelpuissant** [wekan/wekan#2216]
Hi,
First, thanks for your work, I realy enjoy Wekan !
But is there a way to :  
- Set default user settings (e.g. hide system message by default or set watch to tracking by default... ) ?
- Get a mail notification about deadlines ?

**Comment by xet7** [comment]
@Naelpuissant 

1) At Wekan board right click `[<]` button to show right sidebar, then click user avatar, and change user role to `No Comments`. Alternatively, automate creating many users by [loggin in to REST API with code](https://github.com/wekan/wekan/wiki/REST-API#example-call---as-form-data) and create user with Wekan REST API and [change role](https://github.com/wekan/wekan/wiki/REST-API-Role). This makes users to not see any activities and comments. This `No Comments` feauture is originally designed for customer user that should not see comments of expert team providing the service. But, there is not default user setting for this yet.

There is not yet setting for default set watch to tracking.

2) Not yet, because Wekan does not have time scheduler yet. It will be added later.

I have added these to Teams milestone, and look at implementing these during that.

**Comment by Naelpuissant** [comment]
Thank you !

**Comment by xet7** [comment]
Moved to #2567
