### ISSUE TITLE
[Bug] Cards are not show in swimlane view, but in list view

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2238]
## Issue
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* Wekan version: 2.42
* Operating System: Ubuntu with snap

**Problem description**:
- We have a board since one month (v2.18). since 2.40 (this week) i see an problem, that in the swimlane view are some cards missing. But when im in the list-View, i can see there. What i found, on exporting the board, the missing cards have the _archived:"true"_ flag. But, we dont moved this card to the archive.
- i tried to reproduced this, but the card are in the archived after reimporting.
- there is no exception in the log

**Comment by therampagerado** [comment]
I saw that bug also but didn't push further to investigate what is causing the issue. Simply some of the cards are not there but they should be.

**Comment by andresmanelli** [comment]
Can you try moving to other list in lists view and see if after that they
show up?

Le ven. 8 mars 2019 à 12:23, therampagerado <notifications@github.com> a
écrit :

**Comment by sfahrenholz** [comment]
Hey @andresmanelli 
the moving helps for me, now the card is also in the swimlane view.

Can you explane why this happend?

**Comment by andresmanelli** [comment]
There was a bug were the boardId was placed in the swimlaneId (cf issue
"Database tampered [...]")

That was corrected, but some cards have yet the boardId in their
swimlaneId. The swimlaneId isn't verified in swimlane view that's why they
show up in lists view.

When you move the card once in lists view,  their swimlaneId is reset to
the default. I think thats why this works

Le ven. 8 mars 2019 à 16:33, sfahrenholz <notifications@github.com> a
écrit :

**Comment by sfahrenholz** [comment]
Thank you for the information.
@therampagerado did this helps for you too?

**Comment by sfahrenholz** [comment]
Closed. The "workaround" helps.

**Comment by juanluisbaptiste** [comment]
Althought the workaround works shouldn't the issue remain opened until fixed ? or is this an expected behavior ?
