### ISSUE TITLE
Wekan board cards disappear

### ISSUE THREAD

**Issue by xxpqxx** [wekan/wekan#2249]
**Server Setup Information**:

* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 2.45.0

* Operating System: Ubuntu 18.04.2 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx
* Node Version: 8.15.1
* MongoDB Version: 
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl):

**Problem description**:
- While loading the page, some wekan board cards disappear after 0.5 sec. Not all only the half. I've tested this with safari and chrome browser. If i mark one of them as favorit i still see it in the top bar and i'am able to open the board. 

- *Explain steps how to reproduce*
I reload the main (index) page and can see all card's for a short moment.

2019-03-12T05:08:39Z wekan.wekan[15018]: Note: you are using a pure-JavaScript implementation of bcrypt.
2019-03-12T05:08:39Z wekan.wekan[15018]: While this implementation will work correctly, it is known to be
2019-03-12T05:08:39Z wekan.wekan[15018]: approximately three times slower than the native implementation.
2019-03-12T05:08:39Z wekan.wekan[15018]: In order to use the native implementation instead, run
2019-03-12T05:08:39Z wekan.wekan[15018]:   meteor npm install --save bcrypt
2019-03-12T05:08:39Z wekan.wekan[15018]: in the root directory of your application.
2019-03-12T05:08:40Z wekan.wekan[15018]: Presence started serverId=jG9KhtKq5iB9y8SNm
2019-03-12T05:08:41Z wekan.wekan[15018]: > Starting fix-circular-reference_ migration.
2019-03-12T05:08:41Z wekan.wekan[15018]: > Finishing fix-circular-reference_ migration.
2019-03-12T05:08:41Z wekan.wekan[15018]: Kadira: completed instrumenting the app

**Comment by rjevnikar** [comment]
are these subtask boards by any chance?

**Comment by xxpqxx** [comment]
@rjevnikar Hi, all board who disappeared contains subtasks.

I can reproduce the problem if i create a new board and set up the current board as subtask boards.

**Comment by rjevnikar** [comment]
same/similar to #2247.

**Comment by bilalsavas** [comment]
Hi, I am also having a similar issue, but not with cards, with boards.

I am using wekan on ubuntu server set up with snap.

when I enter the main page, board list appears and disappears after .5 seconds. If I can catch to click, I can enter the board without any issue.

**Comment by fvalka** [comment]
I also have this issue. When loading the home page/board overview one specific board is shown for about half a second and then disappears. 
Board can be opened via direct link, clicked while it is visible and also in the favorites bar.

**Comment by xet7** [comment]
In [Wekan v2.43](https://github.com/wekan/wekan/blob/devel/CHANGELOG.md#v243-2019-03-08-wekan-release) is new feature [Hide Subtask boards from All Boards](https://github.com/wekan/wekan/issues/1990).

I did get that feature request from Wekan users. After implementing it, I did get this bug report that Subtask boards are hidden. Nice. Well, how it should work?

**Comment by xxpqxx** [comment]
How about a switch to turn this feature on / off for each (Subtask-)board in admin menue?

And add a Quick Link near Archiv and Template (see screenshot):

![Bildschirmfoto 2019-03-12 um 22 22 32](https://user-images.githubusercontent.com/40173874/54237447-44f4c600-4516-11e9-89b1-b85e0b818729.jpg)

**Comment by bilalsavas** [comment]
if a subtask board is the one you create by adding some subtask to a board, I also think they should be hidden. But this board disappearing problem happens on my main board.

**Comment by xet7** [comment]
@bilalsavas 

Well, that's the point. Editing subtasks is possible in cards, and currently Subtasks are added to new Subtasks boards. But Subtasks were hidden from All Boards, because some did think it is a bug to see all the clutter from all the Subtask boards.

**Comment by xet7** [comment]
Moved to #641

**Comment by fvalka** [comment]
Also had the problem that this board was not actually a subtask board. But maybe it was created as one, I can neither confirm or deny this. ;-)  

**For a Solution/Workaround:** You can fix this issue by running a query against the MongoDB database removing the subtask link.

If you are running it via snap connect to mongodb on port 27019 on the machine running the board:
`mongo localhost:27019`

Use the wekan database:
`use wekan`

And remove the subtask link:
`db.boards.updateOne({title: "Your Board Name"},{ $set: {"subtasksDefaultListId" : null}})`

The commit changing the behavior/causing this issue is:
https://github.com/wekan/wekan/commit/856872815292590e0c4eff2848ea1b857a318dc4

**Comment by bilalsavas** [comment]
thanks @fvalka ! that solved my issue

**Comment by eoshared** [comment]
Hello friends,
- One of my boards disappears from 'my boards', but I still have access from the top bar of direct access to favorite boards.
- When I refresh the browser the card is visible for a fraction of a second and then disappears. If I can click, the board allows access.
- The following video shows the problem and what happens when refreshing: https://youtu.be/5cH8vRWe6Gg.
Others:
- Board configuration: Cards can not have subtasks
- I have administrator permissions
- version of wekan 2.45 on linux
I would appreciate some advice. Regards!

**Comment by xet7** [comment]
@eoshared 

Please wait that Wekan v2.46 is available at https://snapcraft.io/wekan or https://quay.io/wekan/wekan and then upgrade. Snap is upgraded automatically or manually with `sudo snap refresh`. At Wekan v2.46 Subtask boards are visible again.

**Comment by GlenMillot** [comment]
Confirmed. Thanks!

**Comment by eoshared** [comment]
Dear @xet7
Finally, the problem on the board that disappeared after a fraction of a second was solved automatically, that is, without me doing anything in particular to solve it. Mysterious but satisfying
Best regards and thank you very much for your response.
