### ISSUE TITLE
Comments not appearing

### ISSUE THREAD

**Issue by rjevnikar** [wekan/wekan#2316]
Wekan v2.48, from Docker Compose (4 containers, each on a 2cpu8gb RHEL 7.2 VM)
Node 8.15.1
Mongo 3.2.21

Card comments do not always appear in the body of the card. They appear in the counter on the mini-card, and they are in the database, but they don't show up when you open the card. This appears to only happen on certain boards, but I haven't found any similarities.

**Comment by xet7** [comment]
You could compare at MongoDB database is there something wrong or different on those boards where it happens. I presume that fixing some info on those certain boards would make it work again. There has been some previous bugs that have been already fixed in newest Wekan, in those bugs some swimlane data was wrongly modifies, so I do also recommend upgrading to newest Wekan.
