### ISSUE TITLE
SMTP stops working after a while

### ISSUE THREAD

**Issue by TomasAxelsson** [wekan/wekan#2375]
## Issue

SMTP stops working after a while
**Server Setup Information**:
![image](https://user-images.githubusercontent.com/20025012/56581994-7e6d2680-65d6-11e9-9954-06f01539dcf2.png)

Linux Snap

**Problem description**:
I have added my own SMTP-host, username, password etc and tries it out.
It works good, for some days.
And then i stops working.
If I login, and goes to the e-mail configuration and click the test button it does not work.
BUT as soon as I click "Save", without changing anything in the configuration it starts to work again.

Very strange and inconsistant error.

See the error message I get before clicking "Save".

![image](https://user-images.githubusercontent.com/20025012/56582448-9beec000-65d7-11e9-91df-0f2223e955db.png)

**Comment by rinnaz** [comment]
You should configure SMTP via snap
https://github.com/wekan/wekan-snap/wiki/Install#6-email-and-other-settings

**Comment by D347HxD** [comment]
Cannot configure via snap, username has a @ symbol inside, which is causing errors

**Comment by xet7** [comment]
@D347HxD 

You need to urlencode special characters, see:
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail

**Comment by jdavis7718** [comment]
I actually have a similar experience but maybe slightly different
In my environment there is no username/password required to hit our internal smtp server so we leave those fields blank and configure the hostname of our smtp service over port 25.  This works fine, for about a day, then it stops working.
If I simple go back into the admin panel interface click Email then Click save, it starts functioning again.  No other changes in the configuration are done, just click save.  This is a daily occurrence.  Anyone else experience this?

**Comment by xet7** [comment]
@jdavis7718 

I currently use cron https://github.com/wekan/wekan/issues/2721#issuecomment-536107835

**Comment by jdavis7718** [comment]
I also have a cron job that runs every day to set the snaps. It has no affect, every single day I have to go to the Admin web UI and click the save button for any e-mails to start to work. All the snap settings appear correct and aren't going away in the process. It is just like something stops functioning. 
What exactly does the Save button the e-mail page do, is there a function that can be ran in a cronjob to simulate the Save button being clicked?

**Comment by maltem-za** [comment]
Make sure that your snap configuration matches what you set in the admin panel!

I ran into this issue because I followed the setup instructions [here](https://github.com/wekan/wekan-snap/wiki/Install#6-email-and-other-settings), and then later realised that I need to turn off the "Enable TLS support for SMTP server" option as my server uses STARTTLS. This meant that emails worked after clicking save in the admin panel, but would stop working whenever the snap restarted and loaded the config from the environment variables that snap sets.

In fact, it's good to be aware that saving settings in the admin panel just sets snap-local environment variables, which are obviously lost after a restart. You can see how this works from [about here](https://github.com/wekan/wekan/blob/master/models/settings.js#L104) in the code.

In my case I had to change the protocol from smtps to smtp for the mail-url and the problem was solved. I haven't had to use a cron to re-set the settings either.

**Comment by xet7** [comment]
@TomasAxelsson @rinnaz @D347HxD @jdavis7718 

Please test does now `snap set wekan mail...` settings keep working with newest Wekan.
