### ISSUE TITLE
[feature/bug] Enumeration in Cards will be wrong on higher values than one

### ISSUE THREAD

**Issue by chirrut2** [wekan/wekan#2425]
## Issue
I think there is a feature to interpret special signs or maybe more like

Interpreting  (star):
![image](https://user-images.githubusercontent.com/50633042/58131209-58ab5f80-7c1e-11e9-908c-215d9661c5c3.png)

Interpretin (dash):
![image](https://user-images.githubusercontent.com/50633042/58131189-4cbf9d80-7c1e-11e9-8858-eb52b95e4d75.png)

Correct enumeration (first number):
![image](https://user-images.githubusercontent.com/50633042/58131320-a7f19000-7c1e-11e9-89ca-4011fd5fd968.png)

**Problem**:
Wrong Enumeration if the number is higher than one:
![image](https://user-images.githubusercontent.com/50633042/58131117-1b46d200-7c1e-11e9-913c-2ba7e97aab5c.png)

**Server Setup Information**:

* Wekan version: 2.74
* Operating System: ubuntu 18
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache
* Node Version: see snap
* MongoDB Version: see snap

**Comment by xet7** [comment]
This is because of Wekan feature of viewing markdown. If you would like to get it shown correctly as plain text, please use backticks.
```
`2. bubu`
```
Wekan supports newest markdown #2334
https://github.com/wekan/wekan/wiki/Wekan-Markdown

It would be very difficult to change current behaviour, so please use above workaround.
