### ISSUE TITLE
[Feature] Notification Drawer like Trello

### ISSUE THREAD

**Issue by justinr1234** [wekan/wekan#2471]
<img src="https://blog.trello.com/hs-fs/hubfs/Trello-Home-Notifications-Crop.gif?width=1280&height=720&name=Trello-Home-Notifications-Crop.gif">

**Comment by pbenkoe** [comment]
That would be a fantastic feature that would boost productivity tremendously! Is there a plan for when the Notifications milestone will be implemented (is it possible that it used to be 2019-12-31)?
Thank you!

**Comment by xet7** [comment]
I did remove all milestone dates, because that roadmap was not up-to-date.

[My current up-to-date roadmap is here](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license). Those all at roadmap are sponsored features, done as first priority. Anyone can sponsor this feature [at my Commercial Support page](https://wekan.team/commercial-support/).

Alternatively, if some Wekan contributor is interested in implementing this and sending pull request, I can answer any questions related to this.

**Comment by jtbairdsr** [comment]
@xet7 sorry I have been out of touch this last week... I ended up getting a bit of a head cold that slowed me down a little...

I am just preparing a pull request for this feature and I had a couple of question for you...

1. there is one place in the activity feeds that we are using the wrong `activityType` so we don't display anything (when we complete or uncomplete a checklist). When I fixed it the i18n translation just has place holders... 
    ``` json
    "activity-checklist-completed": "completed checklist __checklist__ at card __card__ at list __list__ at swimlane __swimlane__ at board __board__",
    ``` 
    It was easy enough to fix in English and I tried to apply the same pattern to the other languages but I am nervous that I might break something... what is the correct process here?
2. I need to expand the publication/subscription situation in order to have the information that I need about each activity/notification from all boards, cards, lists, attachments, etc. at the global level... how fine tuned do we want to be on that? I have put the subscriptions in an `onCreated` call that happens after the menu is opened but right now I am just subscribing to all `activities cards lists attachments comments swimlanes` which I assume might be a bit heavy... perhaps I try and build a clever query that will publish only those records that are related to my current notifications?  Do you have any suggestions? (I am really just fairly new to meteor so I am still trying to figure out best practice here...)
4. are there any tests that I need to be writing (unit tests or e2e tests)? I haven't been able to find anything but I wanted to make sure I didn't miss anything.
3. Finally, what do you want to do about disposing of notifications... right now I have built it so that you can toggle read status on a notification (just like Trello and the ask in this feature) but that means that there isn't any user behavior that removes the notification... do you want to try and garbage collect read notifications that have been read for a certain amount of time? do you want to add a ui to remove read notification? what do you think?

thanks again for the awesome job you are doing with this awesome project and I look forward to your feedback?

**Comment by xet7** [comment]
@jtbairdsr 

Thanks!

1. For translation, do only pull request to `wekan/i18n/en.i18n.json`. Other translations are done at https://transifex.com/wekan/wekan
2. There is already Global Webhook at Admin Panel https://github.com/wekan/wekan/pull/2665. Maybe something similar?
3. There are no unit or e2e tests in current Wekan. I have only seen some tests in group feature code that I received from some company, but that is not yet added to current Wekan. Code is formatted with prettier, there is plugin for vscode. GitHub does alert me if there is know vulnerabilies in dependencies. There is also DeepCode bot that checks if pull request has some vulnerabilities or other errors, you can see it at closed pull requests. For UCS platform, they run their own tests to check does Wekan work properly with their other apps at UCS. For Sandstorm, ocdtrekkie checks does it work. I do only test minimally that do basic features like drag-drop etc work. If something does not work, usually after release someone adds new GitHub issue about it, so I can fix it in next release. Some have [volunteered for testing](https://github.com/wekan/wekan/wiki/Test-Edge) but in practice their time is limited, and I release directly to production. It would be nice to have some integrated tests. For releases, some platforms like Docker and Snap are built by their build service, others I do build with build scripts.
4. There are also [other cleanup scripts](https://github.com/wekan/wekan-cleanup) that have not yet been added to Wekan. It would be nice to have cleanup integrated, because some have a lot of users, and a lot of notificatitions for a lot of users could rapidly fill disk space. For example, Wekan has [synced-cron](https://github.com/wekan/wekan/pull/2555) that could also be used to sheduled cleanups.

**Comment by jtbairdsr** [comment]
@xet7 

Thanks for the Global Webhook pointer... I will look into that.  

I am thinking that I will provide the ui option to delete the read notification in this pull request. Then I can add another PR with an automated cleanup script and a configuration setting to let people hosting Wekan determine how old read notifications can get before they are garbage collected.  I am currently marking notifications read with a date so we will be able to identify how long since notifications were read and then let the garbage collector clean up anything older than the config allows...

does that sound like a workable road map to you?

**Comment by xet7** [comment]
@jtbairdsr 

Yes. Thanks!

**Comment by jtbairdsr** [comment]
@xet7 let me know what you think of my PR #2975

**Comment by xet7** [comment]
@jtbairdsr 

In those publications are you adding loading a lot more of board data to browserside? Or are you loading only visible data?

For example, some parts of current Wekan has:
- [Infinite scroll](https://github.com/wekan/wekan/pulls?q=is%3Apr+is%3Aclosed+infinite+scroll) to load only visible cards, and scroll a lot of info
- Bug that [Linked cards make load all cards of database](https://github.com/wekan/wekan/issues/2688)
- But that [Card activity shows only 20 last entries on Chrome](https://github.com/wekan/wekan/issues/2934)
- In some cases, it's better to use Meteor Methods instead of Publications.

So I'm thinking, would your changes affect Wekan performance?

I did read though your code, but could you describe in which way your code handles data?

**Comment by jtbairdsr** [comment]
@xet7 

the publications are only supposed to publish data that is directly related to the users notifications... in the event that the user had a lot of old notifications that had never been deleted, it could impact performance... I am working right now on a scheduler that will remove read notifications 3 days after they have been read which would help keep things clean.  Does that answer your question or did I miss it?

**Comment by xet7** [comment]
@jtbairdsr 

Yes that answer's it, thanks! All OK. I will test this in near future.

Currently I'm working on some other bugfixes to issues that appeared as regression when I did some security fixes to Wekan.

**Comment by jtbairdsr** [comment]
@xet7 
Awesome! Do you have any idea of a time frame on when to expect this to be released?

Also, is there anything else that I can do to help facilitate this?

**Comment by xet7** [comment]
@jtbairdsr 

I have already added review about what's missing at https://github.com/wekan/wekan/pull/2975#pullrequestreview-385157834

**Comment by xet7** [comment]
@jtbairdsr 

You can add additional commits to your pull request to fix those issues.

I will also try look would I be able to figure out why it does not work.

**Comment by xet7** [comment]
@jtbairdsr 

I also still get these errors https://github.com/wekan/wekan/pull/2975#issuecomment-606927651

**Comment by xet7** [comment]
Merged https://github.com/wekan/wekan/pull/2975
