### ISSUE TITLE
highlighting and editing text in card results in screen swipe

### ISSUE THREAD

**Issue by yipcma** [wekan/wekan#255]
when dragging a mouse-click over text to highlight, one expects it to highlight, but instead it moves the whole board.

**Comment by mquandalle** [comment]
I don't understand the issue, could you elaborate?

**Comment by yipcma** [comment]
description updated.

**Comment by zeineath** [comment]
encountered this issue as well during editing a comment (or just highlighting any string) within a card IF a horizontal scroll bar is already present for spanning multiple lists.

**Comment by jadeqwang** [comment]
@mquandalle I encountered this bug too, and it's a bit annoying (and I use arrow keys to work around). Paraphrased: Let's say I'm trying to either edit the title of a card or copy its contents. So I open it and I try to highlight some of the text. When I try to do that, instead of highlighting, my mouse drags the whole board around.

Here's a video of me attempting to highlight the title text of a card:
https://youtu.be/PJSzzLPc6t8

**Comment by mquandalle** [comment]
Fixed! @jadeqwang, I hope that didn't penalize you too much on Factorio :)
