### ISSUE TITLE
Bug: Card URL refers to localhost instead of the actual server ip

### ISSUE THREAD

**Issue by hacker-h** [wekan/wekan#2554]
## Issue

**Server Setup Information**:
- Docker version 17.09.1-ce, build e398b97
- docker-compose version 1.22.0, build f46880f

**Problem description**:
The url visited after clicking on the card is localhost/... , despite the server is not running on localhost -> connection error. You can already see it by hovering over the card.

**Steps to reproduce**:

1. `curl -OS https://raw.githubusercontent.com/wekan/wekan/master/docker-compose.yml`
2. `docker-compose up -d`
3. Create an account
4. Create a board
5. Create a card
6. Hover over the card (notice the invalid URL)
7. Click on the card (-> Connection Error)

**Comment by xet7** [comment]
```
docker-compose stop
```
Then edit docker-compose.yml to have ROOT_URL=http://192.168.x.x
See:
https://github.com/wekan/wekan/wiki/Settings
Then:
```
docker-compose start
```
Or alternatively:
```
docker-compose up -d
```

**Comment by hacker-h** [comment]
So why are some links relative and some have a hardcoded root url?

**Comment by xet7** [comment]
@hacker-h 

Because that's how Meteor https://www.meteor.com Javascript Fullstack web framework works:
https://docs.meteor.com/environment-variables.html#ROOT-URL

Wekan is coded with Meteor. Meteor is about 2 GB of Javascript code for frontend+backend, using Node.js and MongoDB. Original author mquandalle implemented Wekan using Meteor and his own meteor/node packages, and after him I have been maintaining Wekan since 2016-12. Because of all functionality of Meteor, mquandalle needed only small amount of code to implement Wekan.
