### ISSUE TITLE
Pronunciation of new name

### ISSUE THREAD

**Issue by PrestonL** [wekan/wekan#259]
How should we pronounce WeKan? (I love the new name)

Like: We - Khan
  - as in "Wrath of Khan"

or: We - Can
  - as in "We can do this!"

I am leaning towards a vote for We-Can as the word Can implies optimistic and enthusiastic cooperation.  However, I would love to see the developers take on this.

**Comment by yipcma** [comment]
"Khan", that's what Kanban is. it's Khan-Bahn, not can-ban.

**Comment by mquandalle** [comment]
Wekan dev here. As a non-native English speaker, I’m curious of what people think of this.

**Comment by ocdtrekkie** [comment]
"We can" is how I read it. I think "can-ban" in my head when I see that word too @yipcma, though I've never heard it spoken aloud by others, so I could be totally wrong.

**Comment by pcalex** [comment]
We are using We-Khan and the reason is same as @yipcma that comes from Kanban.

**Comment by PrestonL** [comment]
I discussed this in the office earlier with everyone coming to the conclusion that "Wecan" rolls off the tongue really fast, while We"Khan" requires extra stress on the last syllable in casual conversation.

We"can" can be said quickly as, "Wekin".  While the etymology of Kan can still give homage to KhanBan, I'd like to think that pronunciation of it as We"can" or more casually as We"kin" wouldn't detract from it's purpose when the words are read or seen.

**Comment by nata-goddanti** [comment]
As I mentioned earlier, to me when I pronounce we 'can'  I get  Obamas 2008 slogan
 "Yes we can"  in my head. May be it should be explicity stated in the release notes or github readme the how to pronounce  'wekan'  so that people know what is stands for ....

**Comment by thomasleveil** [comment]
_non-native English speaker here_

To me it sounds like "yes we can" from Obamas slogan, and I first thought this was to give the finger to previous legal issues this project had. 

I don't know if I'm the only one having thought of that. But if many do, it is a poor choice as it fans the flames instead of burying the hatchet

**Comment by nata-goddanti** [comment]
@thomasleveil ... I hear the same way when ever I repeat it in my head, about obamas slogan. But I see it as a good thing in that, it can be seen as a play on  words with two different meanings - 1.  it is showing middle finger to the establishment or to all the people who were complaining and railing due to the DMCA and saying that "we can" which is positive  2.  "we kin" as in "we kan"ban boards which is more literal meaning in functional sense.

Either way, I think having a good story is always good for the project and brand and gives that sense of being underdog and gives that same level playing field as Trello....

**Comment by mquandalle** [comment]
Now that we have a forum, I believe this kind of discussion should happen there and not on the bug tracker (where I try to close issues as soon as possible). Sorry for the disagreement, but let's continue this discussion at http://discuss.wekan.io/t/how-to-pronunce-wekan/13
