### ISSUE TITLE
CARD_OPENED_WEBHOOK_ENABLED=false not working

### ISSUE THREAD

**Issue by rmsmgaspar** [wekan/wekan#2666]
We are updating Wekan with the setting CARD_OPENED_WEBHOOK_ENABLED=false that cames by default but still we are receiving the webhook "CardSelected".
How can we disable this setting and not receive this notification.

Cheers,
RMSMG

**Comment by JASG94** [comment]
Same problem here.

Currently using docker image v3.35 but found same problem in older versions (since v3.18 I think). Environment variable CARD_OPENED_WEBHOOK_ENABLED set to false and sending webhook notifications when a card is clicked on it.

Also tried not to set the variable (let it by default) and same problem. Also set to true the variable, same problem. Always a notification like "User CardSelected" is sent to webhook. It's a little bit annoying everytime a user click on a card to receive this notification.

Taking a look at the code I think that the error could be in client/components/cards/cardDetails.js in line 120:
`if (Meteor.settings.public.CARD_OPENED_WEBHOOK_ENABLED)` 

I don't know why but it's like always this if statement has a true condition.

**Comment by xet7** [comment]
@jymcheong @whowillcare

Can you look at this?

Related #2780

**Comment by xet7** [comment]
Open webhook was originally added at [Wekan v3.18](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v318-2019-08-15-wekan-release) with this https://github.com/wekan/wekan/pull/2620

**Comment by jymcheong** [comment]
> @jymcheong @whowillcare
> 
> Can you look at this?
> 
> Related #2780

I commented out the block of code at line 120 of CardDetails.js, did a docker-compose down then docker-compose up -d. It is still calling outgoingWebhooks.

**Comment by jymcheong** [comment]
I used v3.49 start with it with Meteor directly without docker, no webhook event emitted when clicked.

**Comment by JASG94** [comment]
In version 3.77 running on docker the problem is present again, when CARD_OPENED_WEBHOOK_ENABLED=false the alerts of CardSelected are sent anyway
