### ISSUE TITLE
No Wekan logo shown on new docker install. Is there a way to show the logo (or maybe a custom one)

### ISSUE THREAD

**Issue by Azorimor** [wekan/wekan#2681]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**: Ubuntu Server 18.04 on newest docker version with the docker-compose.yml file from the current master branch.

* Did you test in newest Wekan?: yes (fresh install)
* For new Wekan install, did you configure root-url correctly? yes. I think so. Its just a local test installation.
* Wekan version: 3.35
* If this is about old version of Wekan, what upgrade problem you have?: none?
* Operating System: Ubuntu 18.04 (docker container) newest docker version
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker (docker-compose.yml)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): see current docker.compose.yml
* Node Version: see current docker.compose.yml
* MongoDB Version: see current docker.compose.yml
* ROOT_URL environment variable http(s)://localhost(/suburl):
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chromium + Chrome + Firefox

**Problem description**:
I am not seeing any Wekan logo right now. The only "logo" I can see on the whole install is the favicon. Nothing else. Wether on the sign-in /sign-up page or after login.
Should that be so? Need I change something to show the logos? 

- *If using Docker, what does show command `sudo docker logs wekan-app` ?*
[wekan-log.txt](https://github.com/wekan/wekan/files/3581125/wekan-log.txt)

The only thing I did in this fresh install: Importing an existing wekan Board from earlier release for testing purposes. Version 2.75, but even before I imported this board the logos were not shown. Maybe the log has some errors because of this.

**Comment by xet7** [comment]
There is no logos currently, because of whitelabeling.

There no way currently to add custom logo. Pull requests welcome.

**Comment by Azorimor** [comment]
Thanks for the answer.
Good to know that generally no logos are displayed.

**Comment by Azorimor** [comment]
I would like to add the option to select your own logo for the login area and header and later make a pull request.
Is this feature still generally wanted?
Are there certain ideas or considerations for this?

**Comment by xet7** [comment]
@Azorimor 

Yes, this is still generally wanted, if someone can contribute it. Some related code [is linked at this release](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v252-2019-03-22-wekan-release).

Logo should be hidden by default, and added when enabled at Admin Panel/Settings/Layout.

It would also be nice to somehow make sure that when logo is disabled, it does not flash for a small time still at login page.

Currently I have [a very long todo list](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license). I'm trying to find ways to encourage more new Wekan contributors, because with Wekan everyone can use all these huge amount of features with MIT license without any cost also for business use. Wekan is very competitive when compared to expensive commercial software. All new contributions are very welcome.

**Comment by xet7** [comment]
Moved to #1493
