### ISSUE TITLE
Linked cards make load all cards of database

### ISSUE THREAD

**Issue by Akuket** [wekan/wekan#2688]
**Server Setup Information**:

* Did you test in newest Wekan?: No
* Wekan version: 3.33
* Operating System: Ubuntu 18.04
* Deployment Method: Docker
* Node Version: 8.16.0
* MongoDB Version: 4.0.11
* What webbrowser version are you using?  Latest Firefox/Chrome

**Problem description**:
- If there is any linked card in one board, this will cause the loading of all the cards of the database! It's a security and performance problem.
- To reproduce: create 2 boards with one card of them linked in the other and reload the page. If you look in websockets messages (chrome), you will see all cards loaded. You can also past that line in the console : `Cards.find().count()`
![image](https://user-images.githubusercontent.com/32392661/64448228-7c1aed00-d0dd-11e9-8cfe-d52fe1bb6a22.png)

- In the file server/publications/boards.js, line 151: If you comment this `            subCards.push(impCardId);` the bug does not still occur anymore. I don't know if the problem came from the module used for that (https://github.com/lfades/cottz-publish-relations) or wekan?

 Regards

**Comment by hever** [comment]
@Akuket problem that you describe really exists and must by fixed. But the way you fixed it is wrong i my opinion.

Problem is elsewhere on line https://github.com/wekan/wekan/blob/a56988c487745b2879cebe1943e7a987016e8bef/server/publications/boards.js#L141

When you stop pushing data into subCards, you stop this function. Pushing is ok, function is bad.

There must be something like this:
`
subCards.selector = _ids => ({_id: _ids, archived: isArchived });
`

I don't know this language well, but there must not be query like `SELECT * FROM cards WHERE archived = true` but something like `SELECT * FROM cards WHERE id = _ids AND archived = true`

**Comment by justinr1234** [comment]
@hever I think you're right, I put in a PR: https://github.com/wekan/wekan/pull/2697

**Comment by Akuket** [comment]
I just point the last line which cause the bug. I tried to use id in that query but i didn't know the functionnal impact that it could have

**Comment by hever** [comment]
@Akuket Once again thanks for finding this malfunction. Boards is now faster. Wekan need speed up and this was important issue.

**Comment by Akuket** [comment]
Thanks for the patch :)

**Comment by hever** [comment]
> @hever I think you're right, I put in a PR: #2697

There is another problem. When card is linking archived card then board freezes and can't load. So the line

`subCards.selector = _ids => ({_id: _ids, archived: isArchived });`

would be

`subCards.selector = _ids => ({_id: _ids });`

and when reading library info (https://github.com/lfades/cottz-publish-relations#thisjoin-collection-options-name) it looks like the line may not be here because it's a default.

I don't run developer sandpit (but slowly working on it) - @justinr1234 can you prove it and PR?

**Comment by hever** [comment]
Until it's been repaired this MongoDB command show you problematics card which are the cause of unworked (not loaded) boards

```
db.cards.aggregate([{ $lookup: { from: "cards", localField: "linkedId", foreignField: "_id", as: "linked" }}, {$match: {"linked.archived": true}}])
```

**Comment by hever** [comment]
Another different problem is here - when linked card just doesn't exists. Because it was in another board and user deleted the card. Board freezes at loading. Board might show some "unknown" word rather than freezed up while loading and don't show anything at all.

MongoDB command to find card where is the problem to resolve it by editing in database directy:
`
db.cards.aggregate([{ $lookup: { from: "cards", localField: "linkedId", foreignField: "_id", as: "linked" }}, {$match: { "linked._id": {$exists:false}, "linkedId": {$gt:""} }}])
`

**Comment by Akuket** [comment]
I made a pr to add the ability to enable or not the linked cards feature by setting a new env var.
Pr #2834

**Comment by Akuket** [comment]
Any news ?

**Comment by xet7** [comment]
@Akuket 

I will look at this after I try to get Node v12 upgrades #2881 working.
