### ISSUE TITLE
Wekan works with a quite lower performance in Win10 Docker desktop

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#2692]
My wekan board was installed in Docker base on win10 and I found it is getting slower in past weeks. 
and found the free memory was less than 100MB, does it show any problem?

![1](https://user-images.githubusercontent.com/46272743/64507742-1e211c00-d30e-11e9-865e-6946ece9e5e1.png)

**Comment by xet7** [comment]
You have very little free RAM, that's why your Win10 gets slower. For even Win10 to run on that computer 3 GB is very little. And Wekan usually takes about 1 GB or 2 GB at least. Maybe you also have also some webbrowser running too? Can you add more RAM?

It's also possible to run Wekan without Docker, with just Node+NPM+MongoDB, there is info at:
https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing

**Comment by xet7** [comment]
Running Wekan without Docker takes less RAM. You can also try running Firefox or Brave webbrowser, they take less RAM than Chrome.

**Comment by javen9881** [comment]
my computer have 8 GB memory and I configure Docker as the followings
![2](https://user-images.githubusercontent.com/46272743/64582388-128e2d80-d3c0-11e9-9271-7c446f3d68b9.png)

**Comment by javen9881** [comment]
![2](https://user-images.githubusercontent.com/46272743/64582472-2d60a200-d3c0-11e9-88a3-7c9358447d81.png)

**Comment by xet7** [comment]
You can try without Docker, and uninstall Docker:
https://github.com/wekan/wekan/wiki/Windows
