### ISSUE TITLE
Future plans for Markdown support (was: Checklist + card title with starting number and point)

### ISSUE THREAD

**Issue by KnudH** [wekan/wekan#2696]
If you want to add a list or card with the title "3. Example" wekan will show "1.Example" after saving instead. 

Newest Version and so on...

**Comment by rjevnikar** [comment]
This is a result of Wekan markdown #2334

@xet7  has stated (#2685) that there is no plan to make any changes to this since the benefits outweigh the drawbacks.

**Comment by xet7** [comment]
Yes, your title does show correctly when you add backticks around it:
```
`3. Example`
```
See inline code etc at:
https://guides.github.com/features/mastering-markdown/

**Comment by xet7** [comment]
Oops it gives wrong number. It's a bug.

**Comment by mpice-mn** [comment]
Is it intentional that this committ [41b1c55](https://github.com/wekan/wekan/commit/41b1c55988a9a65005ac0b9e1ddcc0596c047a49) completely disables all markdown lists (not just numbering issues / checkboxes)? Or is this a temporary workaround?

I used list formatting a lot in my card titles and/or descriptions (mostly unnumbered) and would love to have that feature back. Without it, lists look quite a bit more ugly.

Maybe it can be made configurable?

**Comment by xet7** [comment]
@mpice-mn 

That was only a quick fix for numbering issues and checkboxes. I did not yet have time to figure out how to keep unordered lists formatted.

Sure you can provide some quick fix as pull request for unordered lists if you like.

The actual plan is to sometime figure out how to change from [marked](https://github.com/markedjs/marked) to for example:

a) https://github.com/mermaid-js/mermaid that has diagrams, charts and graphs (preferred)

b) https://github.com/markdown-it/markdown-it that also has emoji plugin

**Comment by xet7** [comment]
Sure if someone has time to figure out how to change to mermaid, and send pull request, that would be cool :smile:

**Comment by matrixes** [comment]
I may grossly be misunderstanding this issue, so just a question for clarification.

* https://github.com/markedjs/marked seem to do basic Markdown formatting; Bold, Italic, Numbered lists, etc.
* https://github.com/mermaid-js/mermaid does "Markdown-inspired text definitions and a renderer to create and modify complex diagrams"

From my initial look on mermaid I can't tell/verify if they do any of the basic Markdown text formatting that this issue seems to be about. Maybe I missed something in their docs and you could point me in the right direction?

**Comment by xet7** [comment]
@matrixes 

Yes, I did not get mermaid working, because it did not work as function, like marked and markdown-it.

I did get markdown-it working, although it seems that markdown-it does not convert linebreaks in edit window to `<BR>` tags. I did also get markdown-it emojis working. Some other markdown-it plugins worked, some did not. There is also mermaid plugin but I did not get it working yet.

Problem is, I don't know is it useful to change to use markdown-it, because it's possible that it could break some existing marked code, because markdown-it is different. Also current marked already works with XSS sanitizing etc.

In newest Wekan I did make some changed to marked, like make checkbox lists look nicer with Unicode.

**Comment by matrixes** [comment]
> Problem is, I don't know is it useful to change to use markdown-it, because it's possible that it could break some existing marked code, because markdown-it is different. Also current marked already works with XSS sanitizing etc.

Personally, it depends; If there are features in another library that have been requested/needed from both clients and developers and/or if another library is more future proof than the current implementation, switching could be worth it.

Switching from one library to another can certainly become painful for clients depending on how much they have already invested in the existing one. However, they may be more positive if the change provide additional benefits or if there's a justified reason for doing a switch.

But this is only taken from my experience, from my perspective. You certainly know better what would be a justified reason enough for a switch than I do. :)

**Comment by xet7** [comment]
@matrixes 

The reason to switch was security. GitHub notified about some security issues in marked, recommended to switch to some better-maintained dependency, and then there came complex automated pull requests from GitHub that would have needed manual work. So I did feel it's easier to switch to markdown-it.

My priorities are:
1. Security
2. Paid features and fixes
3. Others

It seems markdown-it and markdown-it-emoji work fine. Nobody has yet reported that something does not work.

**Comment by gerroon** [comment]
The bullet and the numbered lists do not work in the comment boxes. Is this a related issue?

**Comment by xet7** [comment]
@gerroon 

Bullet and numbered lists do work, when not using wysiwyg editor:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L257

```
sudo snap set wekan richer-card-comment-editor='false'
```

**Comment by gerroon** [comment]
Sorry I did not make it clear, I meant in wysiwyg. Is this a bug then?

**Comment by xet7** [comment]
@gerroon 

No, wysiwyg editor Summernote converts to HTML. Summernote is a lot of complex code, and many alreaady use it, so it's not like it could be changed without breaking something.

**Comment by xet7** [comment]
@gerroon 

Anyway, you are commenting on closed issue. If there is some bug, search is there existing issue and comment there, or add new issue, with screenshots etc.
