### ISSUE TITLE
Cannot drag cards anymore except on unintuitive icon that obstructs view

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#2704]
## Issue

Add these issues to elsewhere:
- Snap: https://github.com/wekan/wekan-snap/issues

Other Wekan issues can be added here.

**Server Setup Information**:
![grafik](https://user-images.githubusercontent.com/53299502/64848017-9b9ba380-d610-11e9-82cb-dacabf6efb48.png)

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: yes, v
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.40.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: docker on ubuntu 18.04 LTS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): iis
* Node Version: 8.16.1
* MongoDB Version:
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome/Firefox desktop

**Problem description**:
The Problem should be explained already by the following screenshot. You can only drag cards via the icon on the right. Just before v3.40.0 dragging anywhere on the card worked perfectly fine. If this was an intentional change this should be reviewed because it impacts user experience greatly

![grafik](https://user-images.githubusercontent.com/53299502/64848165-eddcc480-d610-11e9-9571-b71894ad34ee.png)

**Comment by xet7** [comment]
My customer has paid me to implement these drag handles.

If someone would like to have feature of turning off desktop drag handles, someone can pay for that Quick amount of Feature https://wekan.team/commercial-support/ , so I will then implement it.

Or, someone can send pull request.

**Comment by derbolle** [comment]
This is very unfortunate. We are in the process of implementing wekan. If the evaluation should turn out to be successful we can consider to pay for commercial support. The problem is that this reduce the acceptance in our userbase considerably and we can only lead the wekan implementation to a success, if my users accept it over trello.

Isn't there any way to restore the proper behaviour?

**Comment by justinr1234** [comment]
@xet7 I think there is confusion between features:

1) We want to be able to disable drag and drop on mobile. When on mobile you can hardly scroll the page without accidentally drag and dropping random elements. This shouldn’t be drag handles, but completely disabled on mobile.
2) Drag handles should be an optional feature, controllable by a environment variable for instance.

Like it or not, Wekan will be constantly compared to Trello. There will be people who prefer minimalist style and can’t stand anything else (no drag handles). Others hate minimalism and prefer obvious markers (drag handles).

Coming from Trello, which will be an overwhelming majority of the user base for Wekan, the default should be no drag handles.

**Comment by derbolle** [comment]
Thanks @justinr1234 . You got the point I was trying to make through far better than I 
Maybe I should specify that I opened this issue for Desktop view. On mobile view drag handles are a highly desirable optional feature

**Comment by xet7** [comment]
As maintainer of Wekan, I need to select something that makes sense.

If I completely disable drag on mobile, then I will get complaints that drag does not work at all. That's why drag handles are very useful on mobile.

Drag handles for desktop were added, because there was already feedback that drag handles for mobile was very welcome feature.

Question is, does anyone else think that drag handles for desktop is a good idea? Because if it's not a good idea, it's much easier for me for remove drag handles from desktop, than add yet another configuration option.

I do know that for some features that I implement, some think that:
- It's a bug that now there is a new feature
- New feature should be optional
- New feature should be removed

I will keep desktop handles until I get some more feedback to this issue, and have time to think what makes most sense.

**Comment by justinr1234** [comment]
I say make it an admin global config to enable or disable on the admin panel, not env variable.

Mobile drag handles is fine with me

**Comment by xet7** [comment]
Config can not be global, then it's just arguing between users who want's it on or off.

So it would be per user option, I think.

But the question is, does someone think that desktop mode handles are useful at all ?

**Comment by xet7** [comment]
Because if there is not some that think desktop handles are useful, I just keep mobile handles, and disable desktop handles, and don't add any config options.

**Comment by justinr1234** [comment]
I think desktop handles are useful

**Comment by Keelan** [comment]
This update caught me by surprise today.

I use wekan on a touchscreen monitor on desktop (no mouse or keyboard). This has become very annoying to move a card now (with fat fingers). Plus it overlaps on the labels

![image](https://user-images.githubusercontent.com/1158997/64894693-690d9d00-d648-11e9-9fd7-272c8459336a.png)

Personally i'd like the see the option to disable handles for the desktop but if thats too much work then straight out disable them for desktop. Mobile obviously it makes sense.

**Comment by xet7** [comment]
@Keelan 

Yes, Wekan development full of suprises for me too, I get about daily new features and fixes to Wekan as pull requests, without any pre-warning. For my own development, roadmap milestones are not up-to-date, I should make new roadmap sometime. My own development depends also when I get something working, do features take less or more time.

Thanks for testing on touchscreen monitor!

Based on feedback, my plans for near future are:
- At mobile, drag handles always enabled
- At desktop, drag handles disabled by default. Per user option to enable drag handles.
- Try to make handles to not overlap.

**Comment by gerroon** [comment]
Hi

Can this be a custom preferences?  I understand that the addition is a paid feature which is great, I am glad xet7 got paid for it, but this is a total step back in user experience.

My opinion on this is that, while it sounds like a good idea for mobile, it is not much of a good idea for the desktop where the mouse interaction is the majority.

**Comment by xet7** [comment]
@gerroon 

Yes that's correct, in above issue comment my plans list that drag handes on desktop will be disabled by default, and can be added by per user preference.

**Comment by Keelan** [comment]
@xet7 is there plans to disable the desktop handles temporarily until the user options are implemented or continue as is until this can be implemented. 

If the latter, do you have a suggestion for locally patching this for now. (Even if it disables mobile handles also). Presumably roll back?

**Comment by xet7** [comment]
@Keelan 

Well, now that you ask for it, I think it makes most sense, that I now start to build Wekan release that reverts those drag handle changes. If snap build service is not busy, release takes about one hour, but if it is busy, it takes many hours.

In general, I don't know my plans beforehand. I look at these GitHub issues, my email, etc, to figure out what I should do, what should be default option on Wekan, etc.

Sure it's possible to use any previous version of Wekan with docker-compose.yml from https://github.com/wekan/wekan with version image tag, or build from source from that release tag, if it's so urgent.

**Comment by xet7** [comment]
Wekan v3.42 includes this change. Snap versions update automatically soon or at scheduled time at night.

To update manually immediately, type at server:
```
sudo snap refresh
```

**Comment by saschafoerster** [comment]
In the mobile app of Trello they solve it by leaving some time: 
- Short touch (and movement) -> scrolling
- Long touch on a card (without big movements) -> card gets highlighted and can be dragged anywhere. 

I think what was a problem beforehand, was that scrolling made move cards instantly, so it was not controllable, if you scroll or move cards. This would be my preference in usability.

**Comment by xet7** [comment]
@saschafoerster 

I tried Trello on mobile Chrome and mobile Firefox, long touch drag did not work. Is there any code example how it can be made to work on mobile webbrowser?

When I look various posts about long press, like this, it seems that it is not recommended:
https://www.cssscript.com/handle-long-press-tap-event-in-javascript-long-press-js/

Problems are:
- Some mobile browsers have long press that shows browser's own menu
- There is no visible place how to hold and drag, it's dependent on timing, you can't start dragging right away
- I already have drag handles working, and feedback that they work well

**Comment by gerroon** [comment]
I can confirm that  v3.42 of the Docker version reverted to the old behavior.

**Comment by Keelan** [comment]
Same here. Thank you

**Comment by saschafoerster** [comment]
@xet7 You are right. I tested it in the Trello-app. The web interface of Trello is a nightmare. :) So probably on mobile screens, dragging handles, if they work, are well. I tested them on Wekan demo, there it seemed like it doesn’t work as I expect. The handles didn’t move anything.

**Comment by chrisregnier** [comment]
What about requiring a double click/tap before you allow dragging? On mobile a single tap and drag will scroll, but double tap the same card and start to drag and it will drag the card instead. 
I don't think you'd really need to do this on desktop, but you could if you wanted to be consistent. And at least it wouldn't have the drag handles on desktop.

As for the long press idea, I think you could still use a longer press, but not the actual 'long press' that usually gets triggered after 3-5 seconds. Typically when you drag the screen the finger instantly slides from press point to the release point, but when you pick something to drag the finger will usually delay just slightly at that point before the drag starts to happen. That means you can set a timer for about 0.5secs when a click starts. At the end if the touch point is within a small radius (based on size of screen) then you start to drag the card, otherwise you scroll the screen. The downside here is that you have a min time before the scroll will start to happen which usually gets perceived as lag.

Another idea is to only allow card dragging if it's already selected. And a card is only selected if both click down and up happen on the same element. This way you can quickly scroll across a screen and it won't grab and drag a card (unless it happens to be selected). Again this probably isn't needed on desktop, but I think it would still be a reasonable workflow. 

Can't wait to see the improvements to mobile. Thx!
The gestures when you drag the screen vs drag
For example if you set a 0.5sec timer when you click

**Comment by xet7** [comment]
@chrisregnier 

Please re-read https://github.com/wekan/wekan/issues/2704#issuecomment-531506038

Moved to #2081

**Comment by gerroon** [comment]
Hi

I thought that this was settled around the fact that the handle only dragging should be a mobile thing. 

I just did a Docker pull, and I can't seem to be able to drag cards on Linux Firefox and Epiphany :( 


Is this an bug or again another design desicion?

**Comment by xet7** [comment]
@gerroon 

It's bug at #2081 , and will be fixed in near future.

Please use Docker release tag v3.49 until it's fixed and released in v3.50.

**Comment by gerroon** [comment]
Awesome! Sorry for the noise.
