### ISSUE TITLE
Delete API wiki page

### ISSUE THREAD

**Issue by cimm** [wekan/wekan#2709]
I found the API documentation on https://wekan.github.io/api. There is another [page](https://github.com/wekan/wekan/wiki/REST-API) in the github wiki of this repository that also mentions the API. I think the one in the repository wiki is older than the https://wekan.github.io/api one (not sure though).

Shouldn't the one in the repository wiki be removed since we have the https://wekan.github.io/api API documentation now?

**Comment by xet7** [comment]
https://wekan.github.io/api is [automatically generated from source code](https://github.com/wekan/wekan/pull/1965).

I do also often link to wiki, because it has examples that are not in automatically generated documentation.

There are some in-progress documentation efforts also at:
- https://github.com/wekan/wekanhow
- https://github.com/wekan/wekan-doc

Combining all of them depends, are there volunteers that have time to combine all these someway.

I had to disable editing wiki by any GitHub user, because I did get new wiki test pages and issues from some newbies wondering why wiki can be edited.
