### ISSUE TITLE
Change Wekan Appearance / Functionality

### ISSUE THREAD

**Issue by matthoweonline1977** [wekan/wekan#2721]
Hello, I am new to Wekan. I have worked with Meteor for quite a long time and understand it decently… I have been successful in installing and setting up Wekan on an Ubuntu Server via Snap, VERY COOL!

My question is this. Shall I want to change some of the things within meteor example (Want the cards to work in a different manner, instead of limiting my card length I would like it to take up more screen real-estate and be longer) or maybe (I want to add a hamburger icon to the starred board list so that I can have as many as I want starred and they all show, like google bookmarks bar works when no more screen real-estate). Maybe I want to combine the Board Bar at top and the Starred Boards Bar Very Top and manipulate the look / feel entirely. How is this accomplished? Is there a version that can be hacked / that can be spun up and worked on directly within Meteor? I would assume in this case you would want to have a dev environment and production environment… Please let me know if this is even possible.

**Comment by xet7** [comment]
Developer Docs:
https://github.com/wekan/wekan/wiki/Directory-Structure
https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm
https://github.com/wekan/wekan/wiki/Developer-Documentation

Themes
https://github.com/wekan/wekan/wiki/Custom-CSS-themes

**Comment by xet7** [comment]
https://github.com/wekan/wekan/issues/2686

**Comment by matthoweonline1977** [comment]
What do you mean "you do not have time for"?   Make time for...

* If you sign up for a free trial via "Scalingo" you will see exactly as
they have somehow implemented it. Please sign up yourself for a free trial
via Scalingo. Generate a new list / card. Input a great deal of text into
the card. You will see the card is full screen with all this text then
wraps, not statically set at say 1/4 of the screen non adjustable. Trello
limits this and does not let you adjust it... This is why I chose Wekan in
the first place is b/c I saw that Scalingo has accomplished this. But when
I install via ubuntu / snap latest version on my own server this maybe is
not the default behavior of Wekan? Just trying to setup my own server and
host myself with same functionality. If it is custom, would like to know
how they implemented. Sorry if you think you don't have time. Thanks again.

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
If not understood, tomorrow I can setup another free trial under Scalingo
and provide a screenshot of exact. Thanks again.

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
I will send you an email with screenshots shortly to best show you what I
am requesting.

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
Here is the updated screenshots. Thank you.

I would like to get it to look / feel like this with full screen width for
cards. Thank you.

*Matthew Howe*
720-989-1773

**Comment by matthoweonline1977** [comment]
I cannot replicate this any longer on Scalingo or Sandstorm... It must be
the new version of Wekan... Please let me know on this as it was very
useful to have full screen width card. Like full screen sortable list. It
was great.

*Matthew Howe*
720-989-1773

**Comment by xet7** [comment]
My customer paid to limit card width to fixed size at [Wekan v3.25](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v325-2019-08-23-wekan-release), because before that card cards did take too much space.

You can use older version v3.24 with docker tag with docker-compose.yml from https://github.com/wekan/wekan

Or alternatively, you can develop option to have that change back.

About time, there is currently about 500 open issues. I can not code all of them at once, I don't have time for that. Wekan is combined work of 136 Open Source contributors from around the world. Anyone can code feature or fix and send pull request, I highly encourage and help with that gladly, giving links to docs etc.

I do have [a long todo list](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) for features my customers are paying. I do provide [paid Commercial Support](https://wekan.team/commercial-support/). I need to do those first, because I need to pay my bills, rent etc.

I do some critical fixes to Wekan for free.

**Comment by xet7** [comment]
But please don't use that old Wekan v3.24 on open Internet, it has old versions of software, that could be vulnerable. Only use newest Wekan exposed at Internet. That old version should be used only local on laptop or at local LAN.

**Comment by matthoweonline1977** [comment]
I got it running on Ubuntu / Oracle Box. I would like to find out more
about the platform, how it works and how to contribute. You are talking
about paid commercial support. Let me ask you...

1) Am I able to re-brand / Place my own logo on login / have you "or myself
if possible" develop changes that pertain to my now own interests

2) in order for me to develop these changes or obviously "have you" develop
these changes what exactly are the requirements? Is there source that I
just clone to a folder and can spin up in Meteor and WaLa?

* What is your hourly rate?
* Do we both have access to the source files?
* Who owns what at that point/"Proprietary Now?
* How does this all work / How can I help?

I am familiar enough with meteor to get a project going regular Blaze or
Angular. I am able to publish from there to any platform or even setup
internal hardware for all of this effectively "Hosting" our own servers.
(My full time daily is IT, I am an MSP). I am comfortable enough with the
varying file/folder structures and language structures of the languages.

I am limited in my time as well, and limited in my ability currently to
interject and take advantage of the various libraries and "put together"
the code to make it all work. I have worked through a few meteor tutorials
"todos" etc and published them to Galaxy & Others.




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xet7** [comment]
1) Wekan did sometime have Wekan logo at login screen and at top of board, but those are currently removed, because of [whitelabeling](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v252-2019-03-22-wekan-release). I did sometime try to add custom logo feature, but it had problem that when logo is hidden, it still flashes on login screen. So that's why it's currently hidden. In many platforms Wekan is in iframe or window, not full screen, so each platforms own logo is at top left corner. For iframe, there is browser-policy-enabled and trusted-url snap settings. I don't know how important for you is it to have your logo on Wekan itself. Currently I'm working on improving Wekan usage on mobile and desktop, Teams/Organizations etc major features.

2) Wekan source code is here https://github.com/wekan/wekan . It has MIT license, you are free to modify it and use commercially, without any cost. But, if you make your own modifications to it, downside is that when you want to upgrade, you need to merge all your changes to source code to newest Wekan. Because I [release new versions versions very often](https://github.com/wekan/wekan/blob/master/CHANGELOG.md), maintaining your own fork becomes very time consuming. That is why I recommend [contributing your changes upstream](https://blog.wekan.team/2018/02/benefits-of-contributing-your-features-to-upstream-wekan/index.html), so you don't need to merge all the time.

Wekan is Open Source. That means, Wekan does progress fastest when many developers participate, send features and fixes with pull requests. There is about 500 issues open. As can be seen from [release new versions versions very often](https://github.com/wekan/wekan/blob/master/CHANGELOG.md), many Wekan contributors (companies and individuals) often send pull requests to Wekan. If Wekan work would be limited to only my work, Wekan would not progress this fast. There has been 136 contributors to Wekan. That is why there is so many features in Wekan.

I do know there are countless of forks of Wekan, inside various companies, integrated to those companies own systems in many ways. Wekan is used at hospitals and factories, where data privacy is very important. Some use Wekan because of GDPR. Some do combinations of Wekan and other software to be used inside internal networks that are not connected to Internet. Some days ago I helped someone to upgrade from Wekan v0.10.0 from year 2015 to newest Wekan.

My hourly price is 50 euro/h.

**Comment by xet7** [comment]
About propietary. Wekan has MIT license. That does mean, there is no requirement to contribute back, like there is with GPL. You don't need to publish source code of your changes publicly. It's your choise.

**Comment by xet7** [comment]
About source code:

https://github.com/wekan/wekan/wiki/Directory-Structure
https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm
https://github.com/wekan/wekan/wiki/Developer-Documentation

I do build Wekan on fast bare metal server that has Ubuntu 19.04. That is where it builds fastest.

Building Wekan works only on 64bit Linux or Mac, or Windows Subsystem for Linux, or Linux VM.

Building Wekan does not work directly on Windows, but built bundle does work directly on Windows with Windows native Node.js and MongoDB:
https://github.com/wekan/wekan/wiki/Windows

**Comment by xet7** [comment]
And in general, Wekan bundle does work on any CPU and OS where Node.js and MongoDB is available:
https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing

Wekan repo has `rebuild-wekan.sh` that 1) installs dependencies 2) builds bundle to `wekan/.build/bundle` by combining javascript to one file, css to one file, builds binary node modules, etc.

**Comment by matthoweonline1977** [comment]
Am I able to spin up this Source directly in meteor?

**Comment by xet7** [comment]
```
git clone https://github.com/wekan/wekan
cd wekan
./rebuild-wekan.sh
```
select 1 and enter, then
```
./rebuild-wekan.sh
```
select 2 and enter, then:
```
WITH_API=true meteor --port 4000
```
Then go to http://localhost:4000

When you change some source file, wait when Meteor detects your file changes, rebuilds Wekan, reloads browser, and shows your changes.

**Comment by xet7** [comment]
After that, usually this is enough to start meteor:
```
WITH_API=true meteor --port 4000
```
But sometimes there is still need to `rebuild-wekan.sh` if you don't see your changes there.

**Comment by xet7** [comment]
Well, in theory, just running only command `meteor` does start meteor on `https://localhost:2000` but I have not tested does it get all dependencies then.

**Comment by matthoweonline1977** [comment]
I am going to try to get it up and running in meteor on the latest version
of Ubuntu. Then make some extremely minor edits as I'm just getting my feet
wet.

**Comment by xet7** [comment]
Thanks! Major features have been added to Wekan by newbies:
https://blog.wekan.team/2018/05/wekan-v1-00-released/index.html

**Comment by matthoweonline1977** [comment]
I have decided to do a few things... I am going to move forward with latest
wekan version. I am going to change the server ports and make it available
online via my domain. I will have some feature requests for Wekan, but if
it will be faster for me to fork and have you do custom work I will
probably decide to do this. My setup is as such. I have a Windows System
running 2VM's One called prodserver one called devserver. (Because I
believe someday "I" may be able to do some of this). I assume if you do
custom work you will not need my devserver / you will do and we will store
files in Git? Obviously I will need you to update my prodserver afterward
or something to this effect...

First I will get my server with wekan going on the web and my front site
going as well... I will put together an exact detail, I do not want to
waste your time. I appreciate your knowledge and expertise. I will be in
touch, Matt.








<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xet7** [comment]
For work I do, I store changes in Git, and publish new feature in newest Wekan version.

I do maintain only one version of Wekan for all Wekan platforms, in master branch of https://github.com/wekan/wekan . I did delete many other branches, because merging between branches takes a lot of time.

**Comment by matthoweonline1977** [comment]
I have it up and running online... I really want the old functionality for
the cards back. Because I am the only one that will be using it (At this
point) is there an easy way for me to install the 3.24 version somehow via
Snap?

**Comment by xet7** [comment]
Not snap.

Docker:
```
image: quay.io/wekan/wekan:v3.24
```
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118

Or source:
```
cd wekan
git checkout tags/v3.24
./rebuild-wekan.sh
```

**Comment by matthoweonline1977** [comment]
Ok, that seems a task... But I am willing to try.

**Comment by matthoweonline1977** [comment]
Also, this leads me to the first either feature request to current stable
Wekan, or how much would it cost to have you do this just for my build?
I've attached a mockup. Thanks

**Comment by xet7** [comment]
Mockup missing? Or you should add it at web to https://github.com/wekan/wekan/issues/2721

**Comment by matthoweonline1977** [comment]
https://f002.backblazeb2.com/file/wekanissuemockups/cardwidth-toggle.jpg

**Comment by matthoweonline1977** [comment]
https://f002.backblazeb2.com/file/wekanissuemockups/cardwidth-toggle.jpg

**Comment by matthoweonline1977** [comment]
Just added mockup via url. Not sure why it did not attach

**Comment by matthoweonline1977** [comment]
Here is an image taken from my mobile. Android 4.3" screen

https://f002.backblazeb2.com/file/wekanissuemockups/wekanonmobile.jpg

The HTML base base is actually just fine... It could use some adjustment
though. I think some hamburger icon containing everything else could make
it look great. Anyway, just testing things out.

**Comment by xet7** [comment]
I can add that cardwidth toggle to Wekan with 100 euro, it's on payment dropdown "Small" size of feature:
https://wekan.team/commercial-support/

After you have paid, I will develop it and add it to Wekan and it will be available as automatic update to Snap, and also available to other Wekan platforms.

Visually it will look something like this:
```
Unlimited card width [_]
```

**Comment by matthoweonline1977** [comment]
I think that is fair. This would allow me to start using Wekan the way I
want it right away and on the latest version. I'll reach out this week and
most likely have you go ahead.

**Comment by matthoweonline1977** [comment]
After much thought I am certainly going to want to fork and begin my own
"distro". I have many ideas and it is possible that your mainstream Wekan
user's who have a very established base may not adopt or appreciate my
feature requests as production updates to the Wekan platform. I have a few
questions...

To many questions / feature requests... As I said I will generate a
complete detail of my requested changes / updates as well provide mock ups.

* I will let you know once I have my site up and running. Hopefully It will
generate users. Ultimately I would like to open it up to the public as a
free to paid service. Some subscription platform with "Paid" services or
features, including (Storage, Features, Custom Development / ETC).

* I am also interested in contributing to the completely open Wekan project
to the extent that I can.



As I have my server up and running and accessible publicly, when you
implement the update for the card width will it effect the data I have in
my current Wekan? (I want to begin using it / entering in information)...

**Comment by xet7** [comment]
All feature requests are always welcome, and are always appreciated. Because Wekan is translated to about 50 languages, and used in [most countries of the world](https://snapcraft.io/wekan), I can not make any generalizations what each Wekan user prefers. I do rely on all feedback at Wekan GitHub issues for direction Wekan should go, because I can not imagine all use cases. I try to select from opinions the one that makes most sense. Wekan is community driven Open Source project.

That `Unlimited card width [_]` feature will add code and database migrations, because that setting needs to be saved for each list. If I did understand it correctly, each list can then have different setting. So when implementing it, it requires many changes to Wekan code and database.  With automatic Wekan update, all database migrations happen automatically when updating, and migrations run only once.

Other alternative would be to have per board setting, where `Unlimited card width [_]` would affect all lists in board. Then only one setting per board would be required.

**Comment by xet7** [comment]
When I check pull requests, for example [like here](https://github.com/wekan/wekan/pull/1470) and discuss features with Wekan community, many times features can be improved and generalized in many ways that hugely improves the end result. That's why having Wekan community feedback is essential.

**Comment by matthoweonline1977** [comment]
I like the /card implementation. That gives the user the choice at the
creation of the card.

**Comment by matthoweonline1977** [comment]
Both Sandstorm & Scalingo seem a bit difficult to navigate / get Wekan up
and running. I assume that is b/c they are hosting a lot of different apps.
I am aiming to be the easiest / quickest way when it comes to getting going
with the wekan system. That could be "Free" I think and I would just
continue to follow the direct implementation available via Snap. The "Paid"
version I wish to create and its variations are something we can discuss at
a later time.  I will defenity want the Card width option asap as I intent
to start utilizing Wekan myself very soon. I will most likely be
implementing Wekan for many organizations / individuals alike.

**Comment by xet7** [comment]
@matthoweonline1977 

Please do not count on "Free".
- Because Sandstorm [failed Enterprise sales](https://sandstorm.io/news/2017-02-06-sandstorm-returning-to-community-roots), they had to find other jobs.
- Free plan [had to be discontinued to break even](https://sandstorm.io/news/2018-10-28-results-of-ending-free-plan).
- Now [Oasis is shutting down](https://sandstorm.io/news/2019-09-15-shutting-down-oasis), so Sandstorm is going self-hosted.

The only reason why Wekan demo server at https://boards.wekan.team is "Free" is because it is running on Wekan development server that is [sponsored by CNCF/Linux Foundation](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf/index.html) for Wekan development. There was not any agreement to agree when registering, there was just username, email address and password. Because I did have self-registration disabled, I happened to notice some other users had registered there. I do not even know most of those who has registered there. That "Free" service could go away anytime. It's only a demo. Anyone can setup their own Wekan server to any computer that has Node and MongoDB available.

Developing Wekan is not easy. Some feature takes some days. Other feature takes 6 months. It depends on feature.

I just hope that you take care of your costs, so you don't lose too much money.

**Comment by xet7** [comment]
It was like once, there was fixed price for feature. It did take 6 months to implement it, because of the complexity. Then customer's customer did not like Wekan, but changed to some other Kanban software. So I did not get paid at all for that feature.

**Comment by matthoweonline1977** [comment]
I fully understand. I've been in this atmosphere for a very long time 😀. I
know I can accommodate for the most part. It will be interesting to see how
many users I can gain by opening it up free/public. I will always pay you
up front for any feature implementation. I will pay you this evening for
the card width toggle. I'm looking forward to working with you / wekan and
becoming part of the community. Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matthoweonline1977** [comment]
I'll let you know my domain name / site for this once it is completed. I do
have everything running currently / My front site is done in Joomla b/c I
have used it for a very long time and can produce front end sites quickly
and they look very nice.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matthoweonline1977** [comment]
Is there any way that I can private message you or chat with you directly?
Without reflection to the forums? I would like to address you directly

**Comment by xet7** [comment]
Yes, email support@wekan.team , it's mentioned at https://wekan.team/commercial-support/

**Comment by matthoweonline1977** [comment]
I have a total of 3 requests... I would like them to be that of your
highest priority. I will detail them and send them to you in an email

**Comment by matthoweonline1977** [comment]
So I have everything setup and have began to use wekan on my own server...
I've input all my email information in the admin portion etc. When user
signs up it gives internal error / but lets user sign in afterward anyway.
Is there some fix for this so that the entire system works / passwords
reset as well etc? Thanks

**Comment by xet7** [comment]
Email needs to be set with snap, for example I use AWS SES this way:
```
sudo snap set wekan mail-url="smtps://username:password@email-smtp.eu-west-1.amazonaws.com:587"
sudo snap set wekan mail-from="Wekan Team Boards <info@example.com>"
```
I do also have cron job running these every morning, just in case.

**Comment by matthoweonline1977** [comment]
I will try to implement this with my own email servers

**Comment by matthoweonline1977** [comment]
I will try to get it going...

**Comment by matthoweonline1977** [comment]
Is there any way to email into the wekan system... For example, email to a
board and the content of the email creates a card?

**Comment by xet7** [comment]
@matthoweonline1977 

#2414

**Comment by matthoweonline1977** [comment]
I think this could work in a much better way... For example, the cards
already have a unique string ID that you can share with others... I see
that there is a placeholder for a unique ID to a board. This would be
implemented in that every board gets a unique string ID. When emailing into
that board it should generate a card for that board based on (Subject /
Body / Attachments).

**Comment by matthoweonline1977** [comment]
I see you can make a board "public" which generates a unique board ID. But
I don't probably want to make all my boards public

**Comment by xet7** [comment]
@matthoweonline1977 

That Pretty ID is coming sometime #2450 , it's not ready yet.

**Comment by TomasAxelsson** [comment]
Hi, we still have the same problem with the email....
I set the email information, host, port, username, password. I press save and then do a test, it works.
But only for a minute or two.... Then it stops.
As a programmer working with web programming since 2002 I can't really understand why it's so hard to solve? It's 5 parameters. and sending e-mails aren't an new invention.

I am very grateful for the great work you are doing with wekan board, you're all heroes doing this!
I hope in future that I will have the time to help out! Until then I can only be happy that you continue your great work.

**Comment by xet7** [comment]
@TomasAxelsson 

Yes, the problem is, does someone have time to help. If there were more contributors, Wekan would progress much faster.

**Comment by xet7** [comment]
Moved to #1266
