### ISSUE TITLE
Backup script for docker is broken

### ISSUE THREAD

**Issue by webafrancois** [wekan/wekan#2726]
The backup script written here for docker is wrong : 
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

the tar command doesn't work : 
` tar -zc -f backups/$DATE.tgz -C $SCRIPTPATH/backups/$DATE wekan`
After the dump, the script return : 
tar: wekan : stat impossible: No-one file or directory of this type
tar: Stop with error code because previous errors

It would be : 
` tar -zc -f backups/$DATE.tgz -C $SCRIPTPATH/backups/$DATE dump/wekan`

And the restore was (I don't try) : 
`docker cp $SCRIPTPATH/backups/$DATE-restore/wekan wekan-db:/restore`
but it should be : 
`docker cp $SCRIPTPATH/backups/$DATE-restore/dump/wekan wekan-db:/restore`

Can anyone confirm it ?

**Comment by Marabon** [comment]
I can confirm that the initial command throws the error as described.
I can also confirm that the modified command correctly creates the backup .tgz
`tar -zc -f backups/$DATE.tgz -C $SCRIPTPATH/backups/$DATE dump/wekan`

The modified restore command is also working:
`docker cp $SCRIPTPATH/backups/$DATE-restore/dump/wekan wekan-db:/restore`

In addition to the above changes, as stated on the page linked: "You need to stop Wekan before importing MongoDB database with command"

I added 
`docker stop wekan-app`
on a new line just before 
`mkdir -p $SCRIPTPATH/backups/$DATE-restore`
and then 
`docker start wekan-app`
just before the first 
`fi`

**Comment by Marabon** [comment]
I also made this change to make it more clear which backup was actually restored.
`#DATE=$(date +%Y-%m-%d_%H-%M)`
`DATE=$(basename $1 .tgz)`

The original line takes the CURRENT date and time when creating the $DATE-restore directory, while the modified line uses the chosen backups filename when creating the $DATE-restore directory.

This is just my personal preference though, but it makes more sense to me to use the filename instead of the current datetime.

**Comment by xet7** [comment]
@webafrancois @Marabon 

Can any of you make pull request to fix this?

**Comment by KEClaytor** [comment]
@xet7 I wasn't able to make a pull request to fix this, as it's a wiki page, and [github apparently doesn't support pr's on wikis](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) (but there are some [bonkers workarounds](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html)).

Anyway, I cloned your wiki (https://github.com/KEClaytor/wekan-wiki) and made edits. You can add it as a remote and cherry-pick the commit: https://github.com/KEClaytor/wekan-wiki/commit/76db4eb3ad5c5053e7c0d0677805e22e90d63919
Based this workflow off of [this gist on merging wiki edits](https://gist.github.com/larrybotha/10650410).

It's slightly different than what's listed above.
Instead of @webafrancois suggestion;

```
tar -zc -f backups/$DATE.tgz -C $SCRIPTPATH/backups/$DATE dump/wekan
```

I used;
```
tar -zc -f backups/$DATE.tgz -C $SCRIPTPATH/backups/$DATE/dump wekan
```

which doesn't require a change to the restore script.

I also agreed with the changes suggested by @Marabon and included them.

### NOTE:
The `/dump` directory seems to contain two folders; `/wekan` and `/admin`. This script only backs-up the `/wekan` directory - is it also necessary to backup the `/admin` directory? Or is that directory only used by mongodb and not wekan-app?

**Comment by xet7** [comment]
@KEClaytor 

All Wekan data is at Wekan database at `/wekan`. That `/admin` is not needed.

**Comment by xet7** [comment]
@KEClaytor 

Thanks a lot ! I added your changes to wiki https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data#backup-and-restore-scripts
