### ISSUE TITLE
Where to ask questions about how to deploy Wekan?

### ISSUE THREAD

**Issue by ePirat** [wekan/wekan#273]
I am stumbling across a lot of questions about how to deploy Wekan (mostly raw deployment without Docker or Sandstorm) here in the bug section.
I am not sure if this really is the best place to discuss such things, as usually Github issues are only meant for bug tracking and not as a question/answer forum like discussion about issues installing it (unless it's caused by a bug in the software).
Ideally we would have a forum or such for this kind of questions, like many other projects have. 

@mquandalle: What do you think about that? Do you prefer those questions here in the Github issue section or somewhere separated?

**Comment by mquandalle** [comment]
I think they will have their place in the discourse forum I plan to open for the final v0.9 version (hopefully next week) and for easier questions in the new gitter chat https://gitter.im/wekan/wekan.

Thank for your documentation initiative by the way! I guess now that I have released a release candidate, the recommended raw install should download the built app from https://github.com/wekan/wekan/releases instead of downloading meteor and source code and building the app yourself. What do you think @ePirat?

**Comment by ePirat** [comment]
Indeed, I will update the wiki instructions later today. I like the idea with the discourse forum and gitter seems to be awesome, given that I can use it via my irc client as well :+1:
I consider this answered, but if you don't think so, feel free to reopen.

**Comment by mquandalle** [comment]
Yep, I'm also an IRC user, but gitter is definitely more user friendly and with the IRC bridge, it provides the best of both worlds.

**Comment by xiaohelong** [comment]
hello, there, I do really like wekan ,but deploy and install is a big headache, We Have private server with no internet, I do really need the simplest way to install, The bitnami or vmware is really a good choice, may you will say docker image,yes it's a good choice, but no internet,if have internet , we are behind GFW. it's a joke....

**Comment by mquandalle** [comment]
Distribution of server software is a hard problem with the current infrastructure, and adding the additional restriction of not relying on an internet connexion is making the problem even harder.

@xiaohelong Do you have any technical solution to propose? Whatever method we use, we should not only support installation, but also easy upgrades.

**Comment by xiaohelong** [comment]
I don't know now why there is so complicated to install, if it has war like php like ,it will be deploy so easy. 
otherwise alternative, bitnami or turkey linux is a good choice for this, vmware/virtualbox images is alternative, and I would like that. 
I tried hard with so much times with internet ,but in china it's also  failed , may be the internet is a problem.
I suggest that included all needed file in one package like war or exe,deb likethings, give a detail installation choice. I don't know what tech you write with ,But in china alibaba's dingding talk is really easy to install, whatever, it's using nw.js ,but it packaged all things in exe.
If somethings wrong ,please forgive me! thanks a lot.
