### ISSUE TITLE
Fix boards that do not open because of deleted linked cards (was: Deleting linked card makes board not load)

### ISSUE THREAD

**Issue by superlou** [wekan/wekan#2785]
## Issue

**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings? Existing install
* Wekan version: 3.49.0
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Nginx (reverse proxy only)
* Node Version: 8.16.1
* MongoDB Version: 3.2.22
* Browser: Firefox 70.0.1

**Problem description**:
Steps to reproduce:

1. In board B, create a card.
2. In board A, link to that card.
3. In board B, delete that card (not archive).
4. Board A fails to load. All other boards appear to behave normally.

I'm unable to create a GIF currently, since I don't have a development system setup yet. I also am unable to VM into the machine right now, but will update the following as soon as I have the info. I apologize for the premature ticket, but this behavior appears to be breaking.

- *REQUIRED: Add recorded animated gif about how it works currently, and screenshot mockups how it should work. Use peek to record animgif in Linux https://github.com/phw/peek*
- *In webbrowser, what does show Right Click / Inspect / Console ? Chrome shows more detailed info than Firefox.*
- *If using Snap, what does show command `sudo snap logs wekan.wekan` ? Please anonymize logs.* 
- *If using Docker, what does show command `sudo docker logs wekan-app` ? Please anonymize logs.*
- *If logs are very long, attach them in .zip file*

I'm not familiar with Meteor, but it looks like the delete card button triggers the following, and `Cards.remove(this._id);` does the deletion.

https://github.com/wekan/wekan/blob/ebdb3a0cc3b10e804b30635b5a19dcfbf4a3eadc/client/components/cards/cardDetails.js#L814-L818

This eventually calls the `cardRemover`:

https://github.com/wekan/wekan/blob/865c8305cbcd14d99b6ae6696a89a7261387c0e3/models/cards.js#L1672-L1688

This function appears to do a lot of clean-up, but I don't see any reference to removing linked cards based on the card to be deleted.

**Comment by xet7** [comment]
That's so cool, you seem to have SuperPowers, you are very far in process of fixing a bug.

Next you can:
1. [Fork and build Wekan](https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm#3-fork-wekan-and-clone-your-fork)
2. Add some code for removing reference to linked card.
3. Test does it work.
4. `git add --all`, `git commit`, `git push`, and at GitHub webpage of your forked repo click `Create Pull Request`
5. That will get your GitHub username to Wekan [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md) for global recognition of fame and glory for rescuing the world. You can add that to your CV too.

**Comment by superlou** [comment]
I confirmed it's definitely a problem with orphaned linked cards. If someone else finds themselves like this, they can quickly get their board working again by editing the offending linked card's document, changing the `type` field to `cardType-card`. Then the board should load and the orphan card can be deleted from the Wekan GUI.

Mostly for my own notes, then, I have to decide if the correct behavior is to convert the orphaned card from a `cardType-linkedCard` to a `cardType-card` or simply delete the orphans. I could add a warning to the delete dialog during deletion that any linked cards would also be deleted. Ideally, the user would have the option during deletion to convert or delete linked cards.

**Comment by xet7** [comment]
Yes, options would be nice.

Maybe also show on what other boards/swimlanes/lists linked card is. Perhaps some linked card details somewhere?

Maybe think what would make most sense, or simplest thing that could possibly work, and not break Wekan.

**Comment by fpaillot** [comment]
Hi,
Is @superlou still working on this bug ?

@hever describe a way to fix it in #2688.

**Comment by superlou** [comment]
@fpaillot, not actively, sorry. For the bug I found, the problem was that the card was deleted, not archived, but I'm probably misunderstanding #2688. When I had a reference to an ID that no longer existed, the board would crash.

**Comment by LizVie** [comment]
I have the same problem. Even archiving, not deleting, the origin card causes that the board containing the link, does not open anymore. Is there any timeline for fixing the bug? Because as you can imagine, in the daily work it is not always possible to sync up with the colleagues for archiving linked cards. We use version 3.97.

**Comment by marc1006** [comment]
It's pretty easy to workaround it... (add null/undefined checks) but then the database would be still in a non-consistent state. So the key question is what is the expected behaviour? 

1. Decline the remove of a card as long as there is a link to it?

**Comment by xet7** [comment]
@marc1006 

2 or 3. There could be popup that asks what do about it, and on where at same or other boards that card or linked card also is.

**Comment by xet7** [comment]
Or alternatively 1, if there can be a popup that details how to really delete it. But I think navigating to other boards to remove it would be worse UX.

About removing in general, sometime later there should be thinking about plans for these features:
- Option fo all permanent deleting forbidden, only archive/unarchive possible, to prevent data loss
- Unlimited undo/redo
- Some stats/graphs

**Comment by marc1006** [comment]
> Or alternatively 1, if there can be a popup that details how to really delete it. But I think navigating to other boards to remove it would be worse UX.

I think this is the easiest solution for now and the best decision if we want to change the behaviour later.

> 
> About removing in general, sometime later there should be thinking about plans for these features:
> 
>     * Option fo all permanent deleting forbidden, only archive/unarchive possible, to prevent data loss

Yes, I think that's a good idea. Especially since it's then easier to implement undo/redo.

> 
>     * Unlimited undo/redo
> 

See comment above.

>     * Some stats/graphs

**Comment by xet7** [comment]
@marc1006 

Yes, you can try that easiest solution with popup first.

**Comment by LizVie** [comment]
I think option 3 would be the best, but I see that option 1 with the popup is the easiest way and would at least be a little improvement for our daily work. But I recognized the problem not only with deleting but also with archiving the cards.

**Comment by nikolay-martynov** [comment]
What about boards that already cannot be loaded? Will they load after the fix or we need to somehow to clean the data? Any script you can share for the latter?

**Comment by xet7** [comment]
@marc1006

Do you have ideas what is wrong in database if boards does not load? Could there be added a migration to `wekan/server/migrations.js` that fixes that database? Or should those linked cards at other boards be changed somehow?

**Comment by marc1006** [comment]
@xet7 So first of all it's pretty easy to make the boards code more robust so a board can be loaded even if the database is "corrupted" (maybe with a warning logged with `console.log(...)`). 

How should an automatic migration look like? Remove all "dangling link cards"? I assume a shell script is good enough, especially as the user then knows that there was a problem.

**Comment by xet7** [comment]
@marc1006

Migrations [like this](https://github.com/wekan/wekan/blob/master/server/migrations.js#L1037-L1043) are not a good idea, because migrations run only once.

It would be better to make boards code more robust for errors, so if there is something detected, and board does not load, there could be visible "fix" button. Or is there some even more friendly way?

It's too much to expect some Wekan user run some script from commandline. At Sandstorm there is not direct access to command line at all, it would need a lot of steps to access database and run script on external system.

For the current popup I added, it shows [these messages](https://github.com/wekan/wekan/blob/master/i18n/en.i18n.json#L808-L809) and [linkedId of card and link to this issue](https://github.com/wekan/wekan/commit/ea74a34d72fb0f33909858a640dbcd3a5fda5b7f#diff-1b884f5d7834f9bb60e403bb1185a5d9R252). It could be more user friendly to show at what other boards/swimlanes/lists linked card exists, and option to delete them all. This way there would be no need to try to find where those linked cards exists.

(Well, remembering that sometime there could be no-delete-possible-mode).

Ideas welcome what would be better and more user friendly way.

**Comment by xet7** [comment]
@marc1006 

When trying to delete card,  or list that has linked cards, there could be popup:
```
There are connected linked cards. Select what to keep.
You can not delete main card if there is linked cards pointing to it.
You can change what card is main or linked.
+-------+----------+-------+-------+-----------+-------------+
| Board | Swimlane | List  | Card  | Main Card | Linked Card |
+-------+----------+-------+-------+-----------+-------------+
| Pro1  | Team 1   | TODO  | Task1 | [X|       | [_]         |
| Pro2  | Team 2   | DOING | Task1 | [_|       | [X]         |
| Pro1  | Team 1   | TODO  | Task3 | [X|       | [_]         |
| Pro2  | Team 2   | DOING | Task3 | [_|       | [X]         |
+-------+----------+-------+-------+-----------+-------------+
```
What do you think?

**Comment by marc1006** [comment]
@xet7 I'm not sure if this will buy us much more besides more complexity. Before we could implement this we must first fix the problem with the card labels (see https://github.com/wekan/wekan/issues/2970).

https://github.com/marc1006/wekan/tree/dangling_link is a quick prototype for marking a card as a dangling link... I intentionally took an old version of master so that you can easily recreate the problem.

**Comment by xet7** [comment]
@marc1006 

Yes, most likely that is too complex idea. Nevermind. We'll look at other fixes instead.

**Comment by marc1006** [comment]
@xet7 @superlou  Can you please take a quick look at what I did? (see my comment above) I suppose only "cosmetic" changes missing. If you or somebody else wants to work on it, you're welcome to do so (even mockups of how it should look would be helpful) :) Unfortunately, at the moment I do not have that much time.

**Comment by marc1006** [comment]
> What about boards that already cannot be loaded? Will they load after the fix or we need to somehow to clean the data? Any script you can share for the latter?

@nikolay-martynov If you want you can take my changes (https://github.com/marc1006/wekan/commit/766d66b0445e0c23f2c4dd3b0ab390eea4c7ab21), improve the UI/code, and create pull request. The new behaviour is to detect a orphaned/dangling link card and display a link to delete this card. This allows the user to fix/clean up the board.

**Comment by xet7** [comment]
Moved to here from #2492 

From @xet7 

When opening board, one board (of all boards) does not open. It keeps loading.

Workaround:
1) Login to Wekan.
2) At All Boards page, reduce destop webbrowser (Firefox/Chrome/Chromium) width smaller so that Wekan goes to mobile mode, where top buttons don't have text.
3) Click board that did not open previously. Then board loard loads in Wekan mobile mode.
4) Maximize browser size, so you see full board in desktop Wekan mode.

Most likely this is related to other Wekan issues, where some boards do not load at full desktop Wekan width.

Errors on webbrowser:
```Exception from Tracker recompute function: undefined
d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:1 TypeError: Cannot read property 'archived' of undefined
    at e.getArchived (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:323:593417)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:33294
    at Object.p.call (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:123:1928)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:323:197396
    at f.View.<anonymous> (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:27982)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:19015
    at Function.e._withTemplateInstanceFunc (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:37698)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:18967
    at Object.f._withCurrentView (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:23097)
    at n (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:18916) undefined

d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:1 Exception from Tracker recompute function: undefined

d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:1 Error: Must be attached
    at f._DOMRange.t.firstNode (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:5163)
    at f.View.a.templateInstance (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:35308)
    at x (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:231:3032)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:231:4236
    at Object.e.nonreactive (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:21:4414)
    at Object.r._getTemplateHelper (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:231:4206)
    at f.View.lookup (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:32778)
    at HTML.H2.class (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:323:278200)
    at f.View.<anonymous> (http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:27982)
    at http://we/d989e0b356249a263e2e75d805326a5504ce0b60.js?meteor_js_resource=true:59:19015 undefined
```

From @Gateswong 

https://github.com/wekan/wekan/blob/2bf004120d5a43cd3c3c060fc7c0c30d1b01f220/models/cards.js#L1027-L1037

When the board is loading, it looks into every single card inside the board. If this board contains linked cards (from other boards), these code will be triggered.

When a linked card's target card (original one) is deleted from the other board, `card` in above snippet will be `undefined`, which causes this error.

I was able to reproduce this in version 3.83 (https://hub.docker.com/r/wekanteam/wekan/)

**Comment by xet7** [comment]
Please try with newest Wekan.
