### ISSUE TITLE
Opening a card goes to wrong host (localhost)

### ISSUE THREAD

**Issue by abhijitnandy** [wekan/wekan#2789]
**Server Setup Information**:
Nginx ver 1.14.0
Ubuntu 18.04 LTS

Latest version installed today.

Nginx configuration taken from here -
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config

Ran the following commands to install wekan -
```
apt install snapd
snap install wekan
snap set wekan root-url="http://localhost" port="5000"
```

There's no SSL so the nginx configuration looks like this -

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;

    server_name wekan.****.com;
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
    }
}
```

**Problem description**:
Everything works fine until I open a card. Then it just tries to open localhost.

So, the board URL looks like this -
```
http://wekan.******.com/b/Kzu4BoHpzDBPW9ybT/asdf
```

But the card URL looks like this -
```
http://localhost/b/Kzu4BoHpzDBPW9ybT/asdf/Lpgz****
```

**Comment by lhorace** [comment]
Hello there,

You'll need to update ROOT_URL env to point to your real URL.

Cheers

**Comment by abhijitnandy** [comment]
Isn't that what this line is doing?
```
snap set wekan root-url="http://localhost" port="5000"
```

**Comment by rjevnikar** [comment]
@abhijitnandy  yes, setting the ROOT URL is what that line is doing, however, in your example, you are setting the root URL to localhost.
Instead of root-url="http://localhost", you should have root-url="http://wekan.******.com"

**Comment by xet7** [comment]
```
sudo apt-get install snapd
```
After installing snapd, you should reboot.

Then:
```
sudo snap install wekan
sudo snap set wekan caddy-enabled='false'
snap set wekan root-url='http://wekan.******.com'
sudo snap set wekan port='5000'
```
Nginx config
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;

    server_name wekan.****.com;
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
    }
}
```
Is there some reason you don't setup SSL ? It's possible with Wekan included Caddy or alternatively Nginx, and Let's Encrypt or CloudFlare for free.

**Comment by canadar** [comment]
I've run into a similar problem, but not exactly for the same reason.

To preface, I'm using Traefik as my proxy to Wekan hosted inside of a docker container. This infrastructure is located on my local network (using a 192.168.x.x address for this example).

Here is an example compose file:

`version: '3.3'

networks:
  web-proxy:
    driver: bridge

  wekan-net:
    driver: bridge

services:
  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - "web-proxy"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  wekan-mongo:
    image: "mongo:4.2.2"
    container_name: "wekan-db"
    networks:
      - "wekan-net"
    expose:
      - 27017
    volumes:
      - "/example/docker/wekan/wekan-db:/data/db"
      - "/example/docker/wekan/wekan-db/dump:/dump"
  wekan:
    depends_on:
      - "wekan-mongo"
    image: "wekanteam/wekan:latest"
    container_name: "wekan"
    networks:
      - "web-proxy"
      - "wekan-net"
    environment:
      - "ROOT_URL=http://wekan/wekan"
      - "MONGO_URL=mongodb://wekan-mongo:27017/wekan"
      - "WITH_API=true"
      - "RICHER_CARD_COMMENT_EDITOR=true"
      - "CARD_OPENED_WEBHOOK_ENABLED=false"
      - "BROWSER_POLICY_ENABLED=true"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wekan-rtr.rule=PathPrefix(`/wekan`)"
      - "traefik.http.routers.wekan-rtr.entrypoints=web"
`
Using this setup, Wekan works very well within the docker network! Traefik will route `192.168.x.x/wekan` to the appropriate places. Where I run into issue is the url on the card itself. Every link (except for the card) does not use the root url at the bottom level. So for example, when viewing my boards, the link to a board will end up as `http://192.168.x.x/wekan/b/BgmJee3FmQQcBqQbd/to-do-list` navigating to the appropriate place.

However, the card itself replaces the 192.168.x.x with the original root url, ex. `http://wekan/wekan/b/BgmJee3FmQQcBqQbd/to-do-list/mtmGfXQfPfj64zw6M` which of course other machines on my network won't find. If I manually replace `http://wekan/` with `http://192.168.x.x/` , the problem resolves... But this is slightly annoying to do for each card.

Is there any configuration that I can do to remove the root url from the Card links? Or is this expected behavior?

**Comment by DaXiongAhey** [comment]
I have a similar question. I set the "Root_url=192.168.3.104:port". So if I open the URL in my home-network environment, it works well. But if out of the environment, actually, I make DDNS with a domain. So I can use "http://domain:port" to open it. Well, though I open the website, I cannot click any card, because of the address jumping to "192.168.3.104: port". 
Should I set "Root_url = domain:port" ?

**Comment by xet7** [comment]
@DaXiongAhey 

Yes. See https://github.com/wekan/wekan/wiki/Settings

For example, set root-url https://github.com/wekan/wekan-snap/wiki/Install#3-install-wekan-set-url-like-subdomainexamplecomsuburl

And setup Caddy to proxy to your port https://github.com/wekan/wekan-snap/wiki/Install#optional-install-caddy---every-site-on-https

**Comment by gustavengstrom** [comment]
I was struggling with this as well. I had a standalone installation on Ubuntu 20.04. Installed using steps 2-5  https://github.com/wekan/wekan-maintainer/wiki/Developing-Wekan-for-Sandstorm and running behind a NGINX proxy server. 

For others having the same issue: 
before launching app using e.g. meteor -p 4000 
you need to set the environmental variable as follows:  

export ROOT_URL=https://my.url.org/wekan 

instead of:

export ROOT_URL=https://192.168.x.x:XXXX/wekan 

which causes the above card editing failure:
