### ISSUE TITLE
Test Wekan Edge v3.56

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2823]
@saschafoerster @cafeoh @maedoc @fmeehan and anyone else

Please [Test Edge](https://github.com/wekan/wekan/wiki/Test-Edge) and add comments to this issue about are those [at ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v356-2019-11-21-wekan-release) fixed, and is something else fixed or broken compared to previous Wekan version.

This is so that I could know can I release Wekan v3.56 to stable Snap channel.

Thanks!

**Comment by cafeoh** [comment]
We updated, and the scrolling is now *much* better, thanks! 😃

We haven't had any issue yet, will update if we come across any, but it's looking good for now 👍

**Comment by xet7** [comment]
Ok, seems like improvement, I'll release it to stable.

**Comment by saschafoerster** [comment]
I needed some more time to test, but I looks to me, like it is an overall improvement. I like the new overview-button for calendar/lists/swimlines. I still have problems with scrolling vs. drag and drop on mobile devices, when there is a long list of cards. I see there is the new drag-button on the right side, but when I try to scroll in the middle or left from the middle, then suddenly cards start moving instead of scrolling. Only when I go to the very left side, I can scroll on mobile.

**Comment by xet7** [comment]
@saschafoerster 

Thanks for testing ! Your issue moved to https://github.com/wekan/wekan/issues/2081#issuecomment-557888190
