### ISSUE TITLE
snap + centos 7 workaround available ?

### ISSUE THREAD

**Issue by spacecabbie** [wekan/wekan#2888]
Any alternative install method then snap?
Also any documentation on the bug/error zo i can see if i'll take the risk ?

Thanks !

**Comment by xet7** [comment]
@spacecabbie 

You can use Docker with docker-compose.yml at https://github.com/wekan/wekan

Snap bug could be because of some libssl and libcurl .so files are not added to path when starting MongoDB. I did add them to path with changes that are in git already, but it remains to be seen does this fix Snap on CentOS 7.

If you like to try Snap, please make daily backups with cron script to somewhere safe:
https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
Docker does not have automatic updates. Snap does have automatic updates.

Sure there is [DockerBunker](https://github.com/chaosbunker/dockerbunker) and [other Docker management systems](https://github.com/wekan/wekan/wiki/Docker) if you like to use those.

**Comment by spacecabbie** [comment]
docker is not really a work around i am not  a fan of layer upon layer.

I was more looking along the line is there snap version that still works then id just compile and install that one.

**Comment by xet7** [comment]
@spacecabbie 

In that case, you can use just [node 12.14.1 and mongodb 4.x](https://github.com/wekan/wekan/wiki/Platforms#not-exposed-to-internet-bundle-for-raspi-3-arm64-windows-and-any-nodemongo-cpu-architectures-no-automatic-updates-no-sandboxing) with [update bash script](https://github.com/wekan/wekan-bash-install-autoupgrade).
