### ISSUE TITLE
Pasting text into a card is adding a line before and after (and multiplies by pasting more)

### ISSUE THREAD

**Issue by msbt** [wekan/wekan#2890]
## Issue

As the title suggests (and I'm pretty sure this wasn't always the case): When pasting text in a card, it adds a newline before and after the pasted word. It is not preformatted text, just plain, so that shouldn't be the issue. Even worse, when pasting something else, it's adding even more empty lines before (and after?), which is rather annoying to remove them again. 

This happens in all major browsers and on self-hosted or sandstorm wekan.

**Problem description**: 
The issue should explain that, but in short, if you paste stuff, it adds a bunch of new lines before/between the pasted content. Also tried changing the language to english (as you can see, the german translation below the cards doesn't fit and/or opens on click, but that's a seperate issue)

Demo:
![wekan](https://user-images.githubusercontent.com/8767096/72715738-50227480-3b71-11ea-8a81-7f47b5ece2ed.gif)

Reproduce: paste any text in any card

Best regards

**Comment by xet7** [comment]
That's a bug in WYSIWYG editor. @whowillcare Can you fix it ?

You can turn off WYSIWYG editor this way, then it's just text and markdown:
```
sudo snap set wekan richer-card-comment-editor='false'
```

For docker-compose.yml at https://github.com/wekan/wekan , that setting is [here](https://github.com/wekan/wekan/blob/master/docker-compose.yml#L241)
```
- RICHER_CARD_COMMENT_EDITOR=true
```
For Sandstorm, it's not yet possible to turn off WYSIWYG editor. I could change it to off, but I don't think it's a good idea, because @ocdtrekkie seems to like that feature.

Maybe it would be better, that there would be both markdown+WYSIWYG ways to comment, for example at first visible tab markdown, and at 2nd tab WYSIWYG editor. That way it would not need to be a Wekan-wide setting.  @justinr1234 what do you think?

**Comment by juliensl** [comment]
Hi ! 

It was working on the version 3.00 and it brokes at the version 3.01 ;)

See you

**Comment by msbt** [comment]
any updates on this? how is anyone else handling this other than changing the editor? the platform i'm using doesn't allow changing the editor...

**Comment by xet7** [comment]
@msbt 

What platform?

**Comment by msbt** [comment]
@xet7 [cloudron](https://cloudron.io/)

**Comment by xet7** [comment]
@msbt 

Yes sure. I can disable WYSIWYG editor permanently, so everyone is forced to use markdown/plain text editor.

Currently nobody has volunteered to fix WYSIWYG editor related bugs.

**Comment by msbt** [comment]
well I do like the WYSIWYG editor, but it's annoying to use atm, am I the only one facing that issue or is everybody on markdown?

**Comment by xet7** [comment]
In general, most production users use markdown, that works better with Outgoing Webhooks etc.

**Comment by FuXXz** [comment]
Cool, there is a WYSIWYG editor :)
Can this also be activated for the description field?

**Comment by xet7** [comment]
@FuXXz 

AFAIK when enabled, it's also enabled on description field in newest Wekan.
