### ISSUE TITLE
Unable to change Root URL

### ISSUE THREAD

**Issue by TheDrEmil** [wekan/wekan#2896]
Hi, 
I am using Wekan inside a VirtualBox Ubuntu 18.04 Installation and when I set the desired url using "sudo snap set wekan root-url='http://myurl.com'" in my browser this url is not found.
Only when I set the root url to the ip adress of my virtual machine it loads wekan in the browser. 
Is this a known issue? Or am i doing something wrong?

Thanks

**Comment by xet7** [comment]
That is how Internet works.

When you type text web address to webbrowser, computer checks what IP address that text means from nameserver:
1. Is at your own computer `/etc/hosts` (at Linux desktop, Windows/Mac/other OS can have hostsfiöe elsewhere) for example `192.168.0.100 wekanserver` so then you can browse to http://wekanserver
2. If your local network has dhcp server that tells also ip address of nameserver to each computer.
3. If you are connected to Internet, then your modem (like ADSL, cable, lightcable, mobile phone hotspot etc) is usually tells address of nameserver to each computer.

When you buy a domain from for example Namecheap, AWS, Google Domains, etc, then you can point each web addess of your domain or subdomain to your IP address.

For example, if you have rented a server that has public ip address, you can add it to nameserver settings.

If your server is at home, you can use modem settings to configure dynamic DNS to use you for example Namecheap FreeDNS,  DynDns or other similar service so that if your IP address changes, new IP address can be updated to your nameserver.

If your modem does not have dynamic dns, you can also use somr script or dynamic dns client software to update your ip address.

To be able to access your Wekan throuh Internet, you would need to be able to open some port to Internet. Ask your Internet provider how to do it on your modem, or google search for manual of your modem.

For example, if you can open ports 80 and 443, you can setup Caddy to provide SSL to your (sub)domain. See Wekan GitHub wiki pages OAuth2/Caddy/Nginx/Apache for more info.

On your computer internet settings, or Linux command `ip address` , you can see address of your modem as nameserver address if you use dhcp. For example, modem address can be http://192.168.0.1 or 192.168.1.1 . There you can login for example usually admin/admin and change virtual server settings to point outside ports like 80 and 443 to your VirtualBox VM IP address. Sure you can use any other port too, if your Internet provider does not allow some ports to be open. Some have public IP address as separate paid service, for some it's already to open port without extra payment.

Also see:
https://github.com/wekan/wekan/wiki/Settings
https://github.com/wekan/wekan/wiki/virtual-appliance
