### ISSUE TITLE
newui.libreboard.com is gone

### ISSUE THREAD

**Issue by singpolyma** [wekan/wekan#294]
I had a (pretty important to me) board I was using on there.  It seems everything is transitioning to try.wekan.io, but that is not working yet -- will the database be transferred?  I would really like not to lose the work on that board.

**Comment by mquandalle** [comment]
I've re-enabled access to newui.libreboard.com. This instance was only deployed for testing purpose, not for production use. Since you have some data in it, I will keep it active until we have a way to export and re-import some board data (hopefully in v0.10). The data of libreboard.com was transferred to wekan.io.

**Comment by singpolyma** [comment]
Thank you so much! If it becomes too much pain to leave it enabled, we can maybe export the data by hand, but of course a real export feature would be nicer :)

**Comment by singpolyma** [comment]
This seems to be gone again.

**Comment by singpolyma** [comment]
Nevermind, was a problem on my end

**Comment by singpolyma** [comment]
Ok, this is still resolving -- but all the data seems to be gone?  Did the database get reset or something?  :question:

**Comment by singpolyma** [comment]
hmm, now the board shows up, but won't load.  some kind of hiccup maybe.  will wait and see if you don't know of anything that might be up
