### ISSUE TITLE
Scrolling in lists on mobile no longer possible 

### ISSUE THREAD

**Issue by derbolle** [wekan/wekan#2947]
## Issue

Other Wekan issues can be added here.

**Server Setup Information**:

* Did you test in newest Wekan?: yes, 3.80

* Wekan version: 3.80
* Operating System: Linux
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Traefik
* Node Version: 12.16.1
* MongoDB Version: 4.2.3

* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Current Chrome/Firefox on Android and Safari on iOS

**Problem description**:

Scrolling on mobile browsers does not work at all anymore. If you try to scroll with your finger you instead move or open cards. This basically makes wekan unusable on mobile 

Probably an easy fix would be drag handles only on mobile and enabling scrolling in every other area on a list

I enclosed a gif. This is from chrome mobile view but is representative for what happens if you tap to scroll on mobile. 
This is reproducable on every mobile browser I tried

![wekanmobilescrolling](https://user-images.githubusercontent.com/53299502/75544049-74e8f200-5a23-11ea-8151-156ab0e718a0.gif)

**Comment by xet7** [comment]
This is currently waiting for funding:
https://community.vanila.io/?t=1fc61593-d2d4-42f0-a292-c6c53815b188

**Comment by sh2515** [comment]
I have this issue also. Maybe a slide on the left or right of the screen, or have the movement icon on the cards so any scrolling wouldn't affect the card unless you touched and moved the crossed arrows. What is the cost of funding this fix?

**Comment by xet7** [comment]
1000 euro to Wekan Team (xet7) https://wekan.team/commercial-support/

At that community page someone said that they would pay, but I still have not received it.

Currently I have funding for only those that are marked Urgent/TOP PRIORITY at [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license). I don't have any funding for bugfixes, speed improvements etc. That's why I'm thinking should I spend less time maintaining Wekan.
