### ISSUE TITLE
Update docker package to v4.00 (latest)

### ISSUE THREAD

**Issue by bandresen** [wekan/wekan#3053]
## Issue

Docker image lags behind at this point in time by 3 releases:
https://hub.docker.com/r/wekanteam/wekan/tags

**Comment by xet7** [comment]
Docker builds have failed for both Docker Hub and quay.io/wekan/wekan. I'll try to fix it.

**Comment by xet7** [comment]
This image now is built, this gets latest tag:
```
image: quay.io/wekan/wekan
```
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L118

Docker Hub has not finished building yet.

There is no version tag for this yet, because fix was this
was added after v4.00 . Next tag will be v4.01 when next
Wekan version will be released.
