### ISSUE TITLE
wekan-db: high Block I/O in docker stats

### ISSUE THREAD

**Issue by DanBenHa** [wekan/wekan#3059]
**Server Setup Information**:

* Did you test in newest Wekan?: no
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ? yes
* Wekan version: 3.97.0
* Operating System: Armbian Ubuntu 18.04 (RockPro64)
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker-compose (latest mongodb, wekan-app image built from source)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): HAproxy
* Node Version: 12.16.1
* MongoDB Version: 4.2.5
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Firefox

**Problem description**:
Using the docker-compose.yml file I get a very high output count for the wekan-db container that has been running for 2 days:
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
6a0e14cc7938        wekan-app           6.25%               173.2MiB / 3.777GiB   4.48%               679MB / 494MB       4.1kB / 0B          36
797ac31c2f5a        wekan-db            2.23%               74.91MiB / 3.777GiB   1.94%               493MB / 678MB       31.1MB / 24.1GB     40
```
Maybe I'm wrong, but to me this sounds like the database wrote 24 GB to disk. Seems strange because currently I'm the only user and I don't use wekan that extensively. I don't have any performance issues but would like to keep disk writes to a minimum.

Thanks for the great app and your help!

**Comment by xet7** [comment]
You should not use Wekan on disk that has limited writes. Please add USB harddisk and move your /var directory to it.

Wekan is 13 years of programming work of about 180 contributors. Wekan does a lot of real time stuff. I don't yet know how to limit those writes.

**Comment by xet7** [comment]
How does that I/O go in those stats? Is that 24.1GB reads or writes?

**Comment by DanBenHa** [comment]
> How does that I/O go in those stats? Is that 24.1GB reads or writes?

I think `I` is reads and `O` is writes: https://forums.docker.com/t/what-docker-stats-net-and-block-means/37357

**Comment by DanBenHa** [comment]
> You should not use Wekan on disk that has limited writes. Please add USB harddisk and move your /var directory to it.

Just another thought that occurred to me: I interpret `BLOCK I/O` as disk read/write from/to mounted docker volumes. For me that's `/data/db` and `/dump`. Moving `/var` to a volume wouldn't change the high disk write to the former two directories.
When I look at the directory for `/data/db` there _is_ a lot of writing going on, even when I'm not actively using wekan (as I said, as of now I'm the only user, so I'm pretty sure there's no other access).

**Comment by derbolle** [comment]
we had the very same problem. Please make sure your Oplog config is correct and your replicaset is "active" even if you have only one db instance. I will post our docker config (for swarm although) as soon as I have time during the next days

**Comment by DanBenHa** [comment]
@derbolle Thanks for your suggestion! Yes, properly configuring the oplog was on my list but I didn't make the connection. Will try to sort the oplog config and report back.

**Comment by derbolle** [comment]
a hint for you: To initialize the oplog you have to go docker  exec -it into your container and call the mongo command from there to properly init the replicaset. we have a proper initialization in the docker-compose I will post in the course of the next days but this should give you a start

**Comment by xet7** [comment]
Also Snap does not yet have replicaset. Creating it should sometime be added to here, pull requests welcome:
https://github.com/wekan/wekan/blob/master/snap-src/bin/mongodb-control#L69

**Comment by DanBenHa** [comment]
I set up the replica set and oplog, but to no avail. The `Block I/O` accumulated high values in the `O`.

I'm not sure what exactly the `O` means, though. In the meantime I played a bit with a simple Alpine Linux container, simply reading from and writing to a mounted volume. In both cases **only `I` values** were increased.

Back to the wekan-db container, I found that there's a high turnover of the WiredTiger journal files. It's rewriting 100 MB several times a minute.
In addition to disabling replica set and oplog, I disabled journalling and set syncdelay to 15 minutes. This seems to do the trick.
I'm not an expert in databases but disabling journalling doesn't feel right. Any ideas on why there's so much journalling in the first place, even though there's no user activity?

**Comment by Tampa** [comment]
That is odd, I install wekan native since I use cloud machines for them and even on the larger boards I don't see such high cycling. The constant DB hits could hint at other issues of wekan trying to talk to the DB and failing to do so, though I doubt that is the cause it might be worth checking, especially if you have upgraded a few times already.

Generally with databases if you want to reduce the writing pushes so it stops overloading your disk you increase caching sizes and memory allocations along with the commit sizes so it commits bigger chunks of data at once rather than tons of small ones. There is a golden ratio here that generally depends on the disk speed, actual query time under optimal conditions and the available memory and filesystem even.

Now most databases tend to run routines for cleanup, compression and such tasks over time and if those fail they retry them, depending on journal size this may happen immediately because it does not have to space to leave this for later. I don't know if mongo has a debug mode, but I suspect you can make it quite verbose. I would suggest gathering some logs of what it is actually trying to commit.

Some general advice I can give. In recent years a lot of applications have become more io-hungry and spinning storage struggles to keep up. I have switched a lot of databases to solid storage. IO issues can compound very quickly so with faster storage whatever ends up hogging that to death ends up either a bug or someone trying to denial of service something e.g. debugging is a lot easier if you are dealing with just one issue and not unrelated ones as well.

If needed I can run some artificial stats on wekan performance as I have a bunch of different systems with different storage speeds lying around, though I still have some doubts that these could be made clean enough to get any relatable data out of those.

**Comment by DanBenHa** [comment]
Thanks for your tips.

I set mongod to the first verbosity level and constantly see messages when the wekan-app container is running, even though noone is using it. When I stop wekan-app there are no more messages in the log of mongod. So it probably hints at some problem of wekan-app talking to the DB... BTW, I get this even with the x86 version and newest commit.

Unfortunately, I don't know much about databases, so I can't debug this myself. Since my use-case is 5 users max, I will probably switch to another Kanban software like Kanboard.
