### ISSUE TITLE
Ldap sync issue

### ISSUE THREAD

**Issue by y0d4a** [wekan/wekan#3063]
hi, i have installed wekan with snap.
have problem with AD sync.
I was change AD account and now he cannot connect, said creds. wrong, but creds. are fine.
also i get this error:

> 'E11000 duplicate key error collection: wekan.cronHistory index: intendedAt_1_name_1 dup key: { : new Date(1588108080000), : "LDAP_Sync" }',

> 

how to delete that key?

**Comment by xet7** [comment]
@y0d4a 

With nosqlbooster GUI connect to server port localhost 27019 (optionally through SSH) and remove it from wekan database cronHistory collection/table.

**Comment by y0d4a** [comment]
to remove collections "cronHistory" ?

**Comment by xet7** [comment]
Do not remove collection, only delete all contents of it.
```
db.cronHistory.deleteMany({})
```

**Comment by y0d4a** [comment]
i saw now, when i list content :)
sorry, did not work on mongo until now... :)
But after that this error is missing, but still dont work, said that is invalid creds. but creds. 100% correct

[ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v2580

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/LDAP

https://github.com/wekan/wekan/issues?q=is%3Aissue+52e+is%3Aclosed

**Comment by y0d4a** [comment]
yep, exactly that i followed...

**Comment by y0d4a** [comment]
also see that more they have same issue, unsolved:
https://github.com/wekan/wekan-ldap/issues/52

**Comment by xet7** [comment]
Well, you maybe need to unset and set ldap sync settings again.
```
sudo snap unset wekan ldap...
sudo snap set wekan ldap...
```

**Comment by xet7** [comment]
That's because you did delete that data from database.

**Comment by y0d4a** [comment]
still unable to set....
is it possible to drop all ldap collection and recreate?

**Comment by xet7** [comment]
@y0d4a 

[Backup](https://github.com/wekan/wekan/wiki/Backup) first.

It would be better to test on other install of Wekan first, how to get LDAP working, and then apply those changes to your original install.

You can try to drop ldap collection, but do not drop users collection, because those user IDs are connected to board IDs who is where.

And it's very easy to get Wekan messed up by directly editing database.

In theory, you could export all boards to Wekan JSON, and import to Wekan from previous export, but it's possible that not all board data is exported/imported in that process, there could be some open issues about that.

**Comment by y0d4a** [comment]
i am sorry, it was my fault, i did not enter full CN, was missing one character :(
all is fine, thank you for time!
