### ISSUE TITLE
{request} dragdrop mobile cards like trello. 

### ISSUE THREAD

**Issue by Mrian07** [wekan/wekan#3186]
{request} dragdrop mobile cards like trello. I see in the mobile card version, you can slide it to the right like Trello, it looks like if the card is made to slide right and left like Trello it's very good. if you are too busy to develop other features. can you give a reference to change the layout of a dragdrop card car like a trello?
![5850A029-B836-4852-978C-C74D0B796DD1](https://user-images.githubusercontent.com/45984394/85162963-53d73600-b28c-11ea-984b-b90538e82fb2.jpeg)

**Comment by xet7** [comment]
At mobile phone using Android webbrowser menu, you can request desktop website where you can pinch zoom board, and drag cards from drag handles.

At iPhone Safari that request desktop website does not work, it only shows mobile web version.

When dragging outside of drag handles, it's possible to move around board.

Compared to Trello, if you login to Trello with mobile webbrowser, it's not possible to move cards by dragging cards, I just tested it today.

With drag handles, it's possible to start dragging immediately, it's not like in Trello mobile app where there is delay before it starts dragging - that delay drag is some mobile app feature, I don't know is there such feature for webbrowser.

Also, it's possible to create PWA app icon that launches Wekan fullscreen, so that Wekan works then like a mobile app, more details at https://github.com/wekan/wekan/wiki/PWA .

There are no plans to change how drag drop works, it already works very well.

**Comment by mpodshivalin** [comment]
Just to be clear - how do we move a card to another list from a PWA/Mobile view? It seems like I can only drag a card within a list. It seems like it is a simple drag&drop action on a PC, but on a mobile I have to open a card, select Move card, select a list, click done, and then I have to manually navigate to that list, or am I missing something?

**Comment by xet7** [comment]
@mpodshivalin 

Yes, that's how it works in mobile web view.

**Comment by xet7** [comment]
How could it be improved?

**Comment by mfilser** [comment]
I also thought about this in a while too.
Using the Menu at mobile view is "ok" to move the card to another list, but if the card is moved this way, it's not clear for me where Wekan orders the moved card. For me it would be great if the moved card is always at the top, for other maybe at the bottom.
Is it possible to add an option for this ?

![grafik](https://user-images.githubusercontent.com/13166201/85222471-90ee1600-b3bb-11ea-81d9-354e51ebe95b.png)

**Comment by mpodshivalin** [comment]
> How could it be improved?

@xet7 I see two options

# Option 1 (Trello-style)

![trello-style](https://user-images.githubusercontent.com/16121630/85223538-930ca080-b3cc-11ea-80f8-e0bafb86c92a.gif)

It fixes two important problems:
* We can navigate through large number of lists using swipes
* We can move an item to another list in a very convenient manner

It's great. But I imagine that it's very hard to do this reliably :)

# Option 2

In this example we have 4 lists
![Screenshot from 2020-06-21 14-42-54](https://user-images.githubusercontent.com/16121630/85223714-8ccaf400-b3cd-11ea-9564-58012d51c7da.png)

Let's see how it looks on mobile:

![image](https://user-images.githubusercontent.com/16121630/85224438-15985e80-b3d3-11ea-88d7-f35b8ec1ed66.png)


There are two issues here:
* Because 4 lists don't fit on a top bar, we can't switch from current list 3 to list 4 with a click, we have to go back to the list menu and look in a plain list for it. This seems like not a big deal, but you frequently have to go no the previous/next list, and if you have 10 lists, this is very inconvenient
* To move a card to another list, we have to open a card, select Move card, select a list, click done, and then manually navigate to that list, and that's not all, the card isn't even there, you have to scroll a list to find it

So right now it seems like it's easier to open a laptop than reliably do it on phone :)

I propose a not ideal, but hopefully easier to implement solution to both of these problems - let's fix the top bar and add arrows to move things:
![image](https://user-images.githubusercontent.com/16121630/85224593-11207580-b3d4-11ea-824b-305abdd5950c.png)


* **Top bar:** If there is not enough space on the top bar, show only current, previous and next list (instead of showing only the first batch). Show indication ("...") that there are more lists (but it shouldn't be interactive). That way it would be possible to navigate from the first to the last list without switching to list selection.
* There are now left and right arrows on a list item. If we click on a left arrow, the following should be done:
  * The list item should be moved **to the top** of the next list to the left
  * The current view should switch to that list

That way, if a user decides to move item to another list which, for example, is two times left, he would just tap two times on an arrow.

**Comment by rianseven** [comment]
I was thinking about how the Wekan style mobile version like Trello, I was developing for it @ xet7 can you give a reference about this? maybe the time of the mobile version board is made like trello / dnd react?

**Comment by xet7** [comment]
@Mrian07 

1) If I understand all of the above correctly, I think you are just asking that desktop view of Wekan, with drag handles, should be the default also on mobile display. And that mobile web display seems to be to hard to use for moving cards to different lists.

2) About mobile apps and dnd react: I have not used react.

**Comment by xet7** [comment]
I tried to do some changes, but I did not get it working in a way that it would improve anything.

Some suggestions above mention double click. AFAIK there is no double click in webbrowser.

I and other Wekan contributors have spent a lot of time to get current mobile web view working this well.

I would think moving with left right arrows would require some confirmation popup, so that it would not move cards by accident. I don't yet know would those arrows be a good idea.

Pull requests welcome if someone finds a way to improve this.

**Comment by Mrian07** [comment]
in cellular mode I managed to drag it horizontally like trello, please see https://www.loom.com/share/8c37fd1799104d9f9627769f381758e8

I don't know if this makes wekan users happier, I hope you enter my code in the next release

**Comment by xet7** [comment]
@Mrian07 

You can send pull request, so that I can test it.

**Comment by xet7** [comment]
I did not receive any code as pull request.
