### ISSUE TITLE
error in the latest windows wekan problem

### ISSUE THREAD

**Issue by rianseven** [wekan/wekan#3187]
hi I try to install wekan on windows 10. I have followed the instructions in https://github.com/wekan/wekan/wiki/Windows {I use the https://github.com/wekan/wekan/wiki/Windows method .

there is a problem when run ./start-wekan.sh. following the problem I experienced

**/mnt/c/repos/wekan$ ./start-wekan.sh
./start-wekan.sh: line 5: cd: .build/bundle: No such file or directory
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/mnt/c/repos/wekan/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}**

**Comment by rianseven** [comment]
I've also run ./rebuild-wekan.sh (but still ./start-wekan.sh doesn't work)

**Comment by xet7** [comment]
Prebuilt bundle is at https://releases.wekan.team , wekan-VERSIONNUMBER.zip .

If you use Windows version of Node 12.x and MongoDB 4.x, you need to edit start-wekan.bat to have correct path for changing to bundle directory, like `cd bundle`, `node main.js`, and then run it in cmd.exe command prompt. You can optionally edit ROOT_URL and PORT.

It takes more time to install WSL and use rebuild-wekan.sh option 1 to install dependencies, and option 2 to build wekan to directory `wekan/.build/bundle`, with WSL you need to edit start-wekan.sh so that it does `cd .build/bundle` to correct directory and then `node main.js`

**Comment by xet7** [comment]
Building from source does not currently work with Windows version of node

**Comment by rianseven** [comment]
so basically I want to fix a style that is not good on mobile, I try to run the meteor on localhost that also doesn't work. can you tell me what system i should install on my PC? how can i change the style of wekan?

**Comment by xet7** [comment]
@rianseven 

What style is not good? Screenshot?

Or is it some other existing issue? If that is the case, please close this issue and add comment to original issue.

**Comment by rianseven** [comment]
Hi xet7 the current problem, I just want to run with the repo version on my computer. and style it further. can you tell what version of time you can devoloper on windows ?. or does it allow me to install ubuntu ?. and what version of Ubuntu is it so that I can run wekan on localhost and do template editing?

**Comment by xet7** [comment]
I use Ubuntu 20.04 64bit. Ubuntu dual boot works faster, Ubuntu on VirtualBox is  slower.

**Comment by rianseven** [comment]
thank you @xet7 I will try installing ubuntu and run wekan on my local_host
