### ISSUE TITLE
[not an issue] Add Helm chart to install options in the Wiki

### ISSUE THREAD

**Issue by Gabisonfire** [wekan/wekan#3226]
I wrote an Helm chart to deploy to Kubernetes if you want to add it to the Wiki install section.

https://github.com/Gabisonfire/charts/tree/master/wekan

**Comment by xet7** [comment]
@Gabisonfire 

I don't understand how that works. Can you add pull requests to for example these repos, so that it would use them for installing Helm chart? And also add pull requests to fix paths so they work so that all code is at Wekan repos?
- Wekan website https://github.com/wekan/wekan.github.io
- Fork of your charts repo https://github.com/wekan/charts
- Wekan repo https://github.com/wekan/wekan

Thanks!

**Comment by Gabisonfire** [comment]
Hi @xet7 !

The fork you made is of my helm repo as a whole, for now there is only Wekan but there will be other applications at some point. I will maintain this chart myself, I thought you could only add some instructions to the wiki on how to do so. Browsing the code, I noticed you already have one (which i did not see mentionned in the documentation) here: https://github.com/wekan/wekan/tree/master/helm/wekan although this one lacks a lot of options. Mine is more complete (has all environment variables) but does not offer the option to deploy mongodb.

**Comment by varac** [comment]
@Gabisonfire I created #3923 and started a summary of the different helm charts I found. Maybe you could extend it since you seem to know best the differences between them ?

**Comment by xet7** [comment]
Moved to #3923
