### ISSUE TITLE
Display Authentication Method option prevents authentication

### ISSUE THREAD

**Issue by Aversiste** [wekan/wekan#3261]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Not yet.
* Wekan version: 4.22
* Operating System: Debian 10
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): custom (ansible)
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 12.18.3
* MongoDB Version: 4.2.9

**Problem description**:

My wekan install only allows LDAP authentication so the environment is properly configured with all the `LDAP_*` variables. It works in production without trouble but the authentication method selector is always displayed:
![1](https://user-images.githubusercontent.com/426692/92622322-34690b80-f2c5-11ea-8ecc-0445bd90747c.png)

To prevent any confusion I decided to remove this choice and toggled the option “Display Authentication Method” in the Admin Pannel and then saved the configuration:

![disable](https://user-images.githubusercontent.com/426692/92622607-8578ff80-f2c5-11ea-8ae3-21133cfdddc0.png)

I then disconnected to check the login screen:

![2](https://user-images.githubusercontent.com/426692/92622775-beb16f80-f2c5-11ea-8cf6-b9d24dce4ae2.png)

It looks exactly as it should but... when I try to login back the page refresh and nothing happens. There are also no new event in the logs as if wekan doesn't try to contact the LDAP server. Regarding log configuration I have these variables defined: `INTERNAL_LOG_LEVEL=info`, `LDAP_INTERNAL_LOG_LEVEL=info`, `LDAP_LOG_ENABLED=true`.

To fix this problem I directly modified wekan settings in mongodb using the following commands:

```
use wekan
db.settings.updateOne({'displayAuthenticationMethod': false}, { $set: { 'displayAuthenticationMethod':  true}})
```

**Comment by xet7** [comment]
@Aversiste 

You seem to have some also some OIDC/OAUTH2 settings also configured? That's why you have button `Sign In with Oidc` still visible. I think OIDC/OAuth2 is not related to LDAP in any way.

For start-wekan.sh and docker-compose.yml, you should comment those settings like this:
```
# export OAUTH2_ENABLED=true
# export OAUTH2_.......  (etc all this kind of settings)
```
For Wekan Snap version, you should first look what settings you have:
```
sudo snap get wekan
``` 
And then unset all all those oauth2 Snap settings, this way:
```
sudo snap unset wekan oauth2-enabled
sudo snap unset wekan oauth2-..... (etc)
```

For OIDC/OAuth2 login, settings are like these:
- https://github.com/wekan/wekan/wiki/Azure
- https://github.com/wekan/wekan/wiki/Google-login

For LDAP, settings are like these:
- https://github.com/wekan/wekan/wiki/LDAP

When you have removed OIDC/OAuth2 settings, after that you can set LDAP as default login. Sometimes it could be also required that in Admin Panel / People you edit users and change users from Password login to LDAP login.

That way you should only have `Sign In` button visible. Not that OIDC button anymore.

**Comment by Aversiste** [comment]
There are no OIDC configuration and I was never successful at disabling this feature. I just deployed again with `OAUTH2_ENABLED=false` and the login screen still displays “Sign In with Oidc”:

![2020-09-10-145734_340x527_scrot](https://user-images.githubusercontent.com/426692/92731994-17404580-f376-11ea-9b77-135da95b89d4.png)

LDAP authentication is still fully functional.

**Comment by xet7** [comment]
If you still have any setting text that has text `OAUTH2`, you should remove all of that setting text lines like `OAUTH2_ENABLED=false` completely, so it's not set to anything.

**Comment by xet7** [comment]
Please try with newest Wekan.

**Comment by Aversiste** [comment]
> Please try with newest Wekan.

Tested with wekan v4.39: disabling “Display Authentication Method” now works as expected in my setup.
I still have the “Sign In with Oidc” button even if I have no `OAUTH2_*` options defined thought.

Thank you :)
