### ISSUE TITLE
How to update LibreBoard/wekan?

### ISSUE THREAD

**Issue by dialogik** [wekan/wekan#327]
Is there any documentation about how to update (in our case from LibreBoard to wekan)?

**Comment by kant1** [comment]
+1

2015-09-24 11:00 GMT+02:00 dialogik <notifications@github.com>:

**Comment by PrestonL** [comment]
I believe you just need to copy the contents of .meteor/local/db into the new install.

Let me know if this helps.

user$ ls
wekan
user$ mv wekan wekan-old
user$ git clone https://github.com/wekan/wekan.git
Cloning into 'wekan'...
done
user$ mkdir -p wekan/.meteor/local/db
user$ cp -R wekan-old/.meteor/local/db/* wekan/.meteor/local/db

**Comment by dialogik** [comment]
Can someone (preferably developer/contributor) confirm this?

**Comment by mauzao9** [comment]
Well after stop the node.js server, i just do a git pull from master again to merge all the changes with the install i have, after that, you just follow the installation steps again from the step that is building the meteor app again to the end, start the node.js server and that's it. Been working flawlessly with me till now.

**Comment by mquandalle** [comment]
Hi @dialogik,

Wekan will automatically migrate your data on first launch. The way to upgrade depends on the installation method you have initially chosen:

* if you use docker, you'll have one docker container for the database and one container for the application. You'll need to stop the old application container, replace it by the new one and start it again;
* if you used “raw-installation”, you need to stop the nodejs server, download the wekan application and start again the nodejs server

@PrestonL explanations work in the case you used the `meteor` tool to launch the application, ie (`git pull https://github.com/wekan/wekan.git && meteor`). In this case the database is located in the `wekan/.meteor/local/db` subdirectory and as Preston said you'll need to copy it to your new application folder. This installation way is not recommended for production use because you won’t get some of the production optimization you normally get with the other methods (code minification, gzip compression, etc.)

The entire state of the application is persisted in the mongo database (we don't touch any file for instance).

What installation method did you use @dialogik?

**Comment by dialogik** [comment]
We chose the sandstorm installation routine.

**Comment by mquandalle** [comment]
So Sandstorm upgrades work automatically. You need to go the the [sandstom app market](https://apps.sandstorm.io/) and click on the `install` button of Wekan. Then Sandstorm will tell you that this application is already installed on your server and ask you if you want to upgrade it. I imagine Sandstorm team plan to improve the UX here, so feel free to talk to them if you find this upgrade process confusing (cc @kentonv).

**Comment by dialogik** [comment]
Thanks for the heads up!

I dared to [add the three update routines (docker, sandstorm, manual) into the wiki](https://github.com/wekan/wekan/wiki/Install-und-Update). Feel free to revert or to extend my contribution.

**Comment by kentonv** [comment]
@jparyani is working on automatic updates in Sandstorm as we speak! (Not quite automatic, but rather you'll get a notification that an update is available.) But yes, for now you need to go back to the market and click "install" again.
