### ISSUE TITLE
Can I install Wekan on Github Pages? How?

### ISSUE THREAD

**Issue by koncztomi** [wekan/wekan#3324]

**Comment by xet7** [comment]
No, because GitHub Pages can have only static HTML pages, it does not have any database.

Wekan Snap, as described at Download part of page https://wekan.github.io , is recommended to install to newest Ubuntu (20.04 or 20.10) 64bit server that has at least 2 GB RAM, although 4 GB RAM would be better. For example, Hetzner, DigitalOcean, AWS, Azure, UpCloud.

**Comment by xet7** [comment]
For your own use, you can install Wekan to own computer, like Windows/Linux/Mac/RasPi4 etc, details at https://wekan.github.io
