### ISSUE TITLE
Markdown is not working in comments and description

### ISSUE THREAD

**Issue by yelloff** [wekan/wekan#3343]
**Server Setup Information**:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?:
* Did you test in newest Wekan?: yes
* For new Wekan install, did you configure root-url correctly so Wekan cards open correctly https://github.com/wekan/wekan/wiki/Settings ?
* Wekan version: 4.49.0
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Linux
* Deployment Method: docker
* Http frontend if any: nginx
* Node Version: 12.19.0
* MongoDB Version: 4.0.12
* Browser: Firefox

Markdown is not working in comments and description. Is this behaviour intended? 
EDIT: I did a bit more testing. And it turns out that if I use MD in the first row the word is displayed as expected.

 
![grafik](https://user-images.githubusercontent.com/10900427/98801240-d87c4980-2411-11eb-9a82-7f39441a5697.png)

**Comment by xet7** [comment]
This is because you have set this true in docker-compose.yml:
```
- RICHER_CARD_COMMENT_EDITOR=true
```
This uses buggy rich text editor, that only shows markdown when there is no other formatting.

Rich text editor was enabled also for description [in Wekan v4.48](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v448-2020-11-02-wekan-release).

If you would like markdown to work better, you can disable rich text editor:
```
- RICHER_CARD_COMMENT_EDITOR=true
```
Currently I'm trying to find a replacement for current rich text editor, that would be less buggy and have working emoji selector. I did not yet get working any MIT license compatible emoji selector for current Summernote rich text editor.

Current rich text editor Summernote was added by some Wekan contributor that did not stay around fixining related bugs, that's why rich text editor is disabled by default.

Newest Wekan is v4.50, you could upgrade.
