### ISSUE TITLE
css isnt copyrighted

### ISSUE THREAD

**Issue by makethingsbetter** [wekan/wekan#3353]
css isnt copyrighted
and fonts arent copyrighted if open source

can understand images

see https://github.com/wekan/wekan/wiki/FAQ#why-does-wekan-look-so-different-now-compared-to--v09

good ux/ui is most important thing https://github.com/wekan/wekan/issues/2939

**Comment by xet7** [comment]
@makethingsbetter 

If something like code/css/fonts/images etc does not have permissive Open Source license (MIT, BSD, etc) I can not add it to Wekan. Wekan is Open Source, free also for commercial use.

UI/UX does change all the time in both Wekan and Trello, when features are added, UI/UX is improved, etc. Both Wekan and Trello have been in development for many years. Trello is propietary, only Atlassian has all the code, only browserside HTML/CSS/JS is visible to Trello users, only Atlassian sees serverside code. AFAIK Wekan does not have any Trello code, and Trello does not have any Wekan code.

Some of Wekan UI/UX is better than Trello, and vice versa.

Anyone can send pull request to Wekan to improve UI/UX.

**Comment by makethingsbetter** [comment]
are you saying if something is 'open source' then it can only use things that has to have 'open source licnese'? that's how open source works?

**Comment by xet7** [comment]
@makethingsbetter 

Yes.

If Open Source permissive MIT/BSD/Apache licensed code like Wekan would include GPL code, that Wekan version becomes GPL licensed, like here https://github.com/wekan/wekan/issues/2870#issuecomment-695041746 https://github.com/wekan/wekan-gantt-gpl

If Wekan would include code from some propietary software that has license that does not allow redistributing that code, then Wekan would be violating that propietary license.

Open Source licenses have been created so that modifying and redistributing code would be allowed, legal and possible.

Trello does use many open source components in their product. It's possible to use those same components in Wekan, if they are available with Open Source license elsewhere, like GitHub, GitLab, etc with permissive licence. But Trello code itself is not Open Source.

APIs are different thing. At EU, implementing other products compatible APIs is legal. At USA, currently in court case Oracle vs Google, Oracle argues that APIs are copyrightable, while at the same time [Oracle has implemented AWS S3 API](https://docs.cloud.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm).

**Comment by xet7** [comment]
If some code at some repo does not have any license, that code is propietary, and it can not be used in Wekan. For Wekan, permissive license is required.
