### ISSUE TITLE
Question: Docker image builds

### ISSUE THREAD

**Issue by bkraul** [wekan/wekan#3380]
Quick question. Are the docker hub image builds at [wekanteam/wekan](https://hub.docker.com/r/wekanteam/wekan) going to continue? There has not been a new tag in 15 days, eventhough there have been multiple version releases.

**Comment by xet7** [comment]
@bkraul 

Currently Docker Hub can not build Wekan Docker Container, it has this error ENOMEM:
```
 at Object.bundle (/tools/isobuild/bundler.js:3244:16)
at buildCommand (/tools/cli/commands.js:1087:30)
at /tools/cli/commands.js:951:25
at Function.run (/home/wekan/.meteor/packages/meteor-tool/.2.0.0-beta.4.5f0ahh.tiou6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
at /tools/cli/commands.js:949:18
at /home/wekan/.meteor/packages/meteor-tool/.2.0.0-beta.4.5f0ahh.tiou6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Promise.await (/home/wekan/.meteor/packages/meteor-tool/.2.0.0-beta.4.5f0ahh.tiou6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
at /tools/cli/main.js:1529:7 {
errno: 'ENOMEM',
code: 'ENOMEM',
syscall: 'spawn'
}
```
Also [Quay](https://quay.io/wekan/wekan) can not build Wekan, because Docker Hub has rate limits for base images and MongoDB, that are downloaded in Wekan Dockerfile from Docker Hub:
```
Could not pull base image: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Related info here:
https://www.openshift.com/blog/mitigate-impact-of-docker-hub-pull-request-limits

So probably I would need to sometime mirror those base image and MongoDB Docker Hub containers to Quay, to get any Docker container builds working.

Sure if someone could find out is there existing Quay mirrors for those base image and mongodb image, and add pull request to https://github.com/wekan/wekan/pulls , that would help to get Docker builds working, if someone still uses Docker.

**Comment by bkraul** [comment]
I was able to manually build on my local env (using the provided Dockerfile) and push to my docker hub repo [bkraul/wekan](https://hub.docker.com/repository/docker/bkraul/wekan) without issues. I guess that works for the time being.

**Comment by xet7** [comment]
@bkraul 

Yes, manually building works on your computer, because you have not exceeded Docker Hub pull rate limit on your computer IP address.

I will add fixes to Wekan Dockerfile and docker-compose.yml so that Quay builds start working again, possibly copying some containers from Docker Hub to Quay.

**Comment by xet7** [comment]
I fixed Quay builds by copying base image containers from Docker Hub to Quay. https://github.com/wekan/wekan/commit/152a0b50f2662fd71c0f744ac20731198c701c65

**Comment by xet7** [comment]
Oops, some problem with starting docker-compose.yml, just a moment, fixing...

**Comment by xet7** [comment]
Hmm, it seems working anyway, I just needed to reboot.

I added additional info here, also at wiki is link to this page:
https://github.com/wekan/wekan/wiki/Repair-Docker

**Comment by xet7** [comment]
@gerroon 

Thanks a lot for your :heart: emoji, it really means a lot to me that someone appreciates all this work.
