### ISSUE TITLE
deleta attachement is missing

### ISSUE THREAD

**Issue by lzieba** [wekan/wekan#3397]
* Wekan version: 4.62

Normal user cannot remove an attachment from the card and cannot move several cards to the archive at the same time

**Comment by xet7** [comment]
Yes, see #3377 

@compumatter @Samunosuke  @pgh2357 What do you think?

**Comment by compumatter** [comment]
In the end I think there will always be "one more thing" when it comes to User Roles until such time an ability to for the Wekan installation owner to modify via checkboxes what permissions each User Role authorizes.  This of course is a very complex and so unlikely animal to implement anytime soon...

Wordpress does exactly that.  They start with 6 Roles https://wordpress.org/support/article/roles-and-capabilities/#roles .  Expanding the number of roles to 6 (or more) of course allows for more division and nuances.  So this is worth thinking about. 

I would recommend simply assigning each role a "Level" instead of using names like 'no comment' or 'comment' for instance Level One, Level Two and so on and then being very clear in documentation what each Level can do over and above the lower one.  

For instance Level 6 can only view everything.  
Level 5 can do everything Level 6 can do PLUS move comment.   
Level 4 can do what Level 4 can do what  Level 5 can do PLUS and so on until you get to Level 1 - which can do everything

A central place of documentation showing what each role can do will then be important for the Wekan user base to know and therefor minimize questions about what is possible with each.  

That said you will ALWAYS have new Wekan installers wanting a different overlapping of rights / capabilities than the above defaults so the ability to control that on a system wide installation level is the only long term solution to 'please everyone'.

Back to the original question - Should a 'Normal' user be able to delete an attachment.  For my uses that answer would be NO.  Then again my definition of 'Normal' is not the same as my girlfriends :-) so I once again suggest using Level X to remove arbitrary prejudices by your user base.

**Comment by xet7** [comment]
Well, depends when there is funding for granular permissions #3022 .

**Comment by Samunosuke** [comment]
@xet7 
From my perspective I would allow a "normal" user to delete an attachment if it was uploaded created by him/herself, but I would not want that he/she can delete "my" or any other attachments. 
Just think of the following examples: 
1. The "normal" user has uploaded an attachment, but is still in a planning phase and reworked it later on. 
2. The wrong attachment was uploaded (by a "normal" user) or the attachment contains an error
In both of the situations the normal user would need to ask the admin to delete the attachment. I guess this would result into an annoying situation for both (the admin and the "normal" user).

For the option to move multiple cards at once to the archive, I would clearly say: NO.
That's a thing for the owner of the board. We usually create list with the name "completed", when the feature or bugfix or whatever has been tested we move the task to "completed". Why should a "normal" user archive all tasks of a list? If I would another user to allow this, I can still lift up the the rights to "admin". If I create my own board I can still do whatever I want with this board, so I don't think that it is neccessary to give a "normal" user by default the rights to mess up my board.

**Comment by xet7** [comment]
@Samunosuke 

Restricting permissions has caused trouble for some, because normal users can not reorder swimlanes etc
https://community.vanila.io/?t=7b77e753-86bd-4ebc-814e-20904b16342e

So it has resulted some needing to give normal users BoardAdmin permissions or their own account username/password so that users really could edit board. It makes it harder for users to figure out how to use Wekan.

Easiest for me would just revert all permission restrictions, and wait for someone fund https://github.com/wekan/wekan/issues/3022 . Maybe I was just too kind to add restrictions, and that way making other Wekan BoardAdmin lives harder.

**Comment by Samunosuke** [comment]
@xet7 
I can understand that some users do not understand why they need to change the permissions for users of their board if they still want work the same way. For me it it was a bug right from the start. If you revert it, you will just postpone it. I think you have to go through it sooner or later.

**Comment by xet7** [comment]
Well, with those restrictions I already made you all @compumatter @Samunosuke @pgh2357 feel this is better and fixed now. I don't yet have enough reasons to revert or change this.

**Comment by Samunosuke** [comment]
@xet7
If you wanna really keep it how it was, I would recommend you to create an option with the default user level for a board.
When "admin" was set up as default level, it will be same as before, because there was no difference between admin and normal user.

**Comment by xet7** [comment]
For having normal user to delete attachment that user just added, but not delete other attachments, I don't yet how to do it with current Wekan permission system, that could be complicated.

**Comment by Samunosuke** [comment]
@xet7 
I can understand that these things can sometimes get really complicated. I am a developer by myself. If I would better understand how to debug wekan, I would help you out. Web development is kind of a stranger to me :-I

**Comment by xet7** [comment]
@Samunosuke 

Yes, Wekan is made with www.meteor.com full stack web framework. It makes hard things like realtime updates easy, and for some small amount of easy things it can make hard. With Meteor and relatively small amount of code it's possible to create features that would take much more code in other programming languages and web frameworks.

Web development is always changing moving target. For example:
- Some new Chrome update made Wekan feature broken #1404 so it did take a lot of time for some Wekan contributor to figure out how to fix it.
- Also, I have problem with Wekan Snap still using Caddy v1, and new Caddy v2 has incompatible config format https://caddy.community/t/caddyfile-v1-adapter/9129/2
- There are new security fixes to Node.js and other dependencies often.
- Some dependencies get deprecated, and sometimes to use new dependency, it requires small or big code changes.

**Comment by xet7** [comment]
Moved to #3022
