### ISSUE TITLE
Wekan shows nothin

### ISSUE THREAD

**Issue by rahanozturk** [wekan/wekan#3448]
I'm a windows user (shame on me) and discovered better 'to do' programs about two months ago. I was using every day then one day after i double clicked wekan, it showed nothing. Like 'wekan' written on the top left and white windows the rest. The worse thing is that i moved all of my 'text' notes into wekan and now its all gone. What can i do? If i reinstall wekan (i think wekan updated), shall i get back my old admin panel?

**Comment by xet7** [comment]
@rahanozturk 

Please add as attachment to comment to this issue anonymized screenshot of your desktop when there is Wekan and something white, so I can see what is the problem. Thanks!

**Comment by xet7** [comment]
@rahanozturk 

Many use Wekan on Windows, it's OK.

**Comment by rahanozturk** [comment]
![wekan_white](https://user-images.githubusercontent.com/53366283/105181521-f3b7b380-5b3c-11eb-80d5-5dba1448675a.png)

**Comment by xet7** [comment]
@rahanozturk 

It seems to be some compatibility problem with Wekan Windows app. Thanks for info! I will try to fix it.

Meanwhile, before I have fixed it, you can login to Wekan with Chrome/Firefox/MS Chromum browser at address https://boards.wekan.team/sign-in

**Comment by rahanozturk** [comment]
what a relief, thank you!

**Comment by xet7** [comment]
I submitted a new Wekan Windows app to MS Store. I will wait when they verify app, and do they accept new version to MS Store and when.

In new app, difference is that as rendering engine, instead of old MS Legacy Edge webbrowser, new Wekan version uses new MS Chromium Edge webbrowser.

I did recently add new feature to Wekan, of export to Excel. I presume white screen error is because that Excel Javascript code is not compatible with old MS Legacy Edge webbrowser. So I hope that by changing to MS Chromium Edge webbrowser, it will start working, without any other changes required.

Wekan Windows app has been created with https://www.pwabuilder.com , that converts PWA compatible website to app for app stores, like MS Store and Android Play Store. When creating new version of Wekan Windows app, I was happy it now supported changing to more compatible newest MS Chromium Edge webbrowser.

**Comment by xet7** [comment]
From Microsoft Partner Center I do see that for some users, Wekan has crashed. So I hope this new submitted version fixes that.

**Comment by rahanozturk** [comment]
I'm happy to see that you are so kind and quick. As an improvement, maybe there is an add button for interested features. Since I use alone, I'm not using many of them which could be essential in team works. It was pretty good but maybe that would help the response rate of Wekan. Just an opinion.

**Comment by xet7** [comment]
@rahanozturk 

There is now new version of Wekan at MS Store of Win10 desktop. Before installing Wekan, I recommend installing newest MS Chromium Edge browser, so that then newest Wekan will work.
