### ISSUE TITLE
Sandstorm: grains upgraded from LibreBoard prompt for username/password

### ISSUE THREAD

**Issue by kentonv** [wekan/wekan#346]
A user reports that old grains upgraded from LibreBoard to Wekan cannot be shared: upon visiting the share link, recipients are prompted for a username and password, which of course they don't have on Sandstorm.

Presumably some bit in the database is making Wekan think it is in username/password mode rather than Sandstorm mode, but this bit was only ever set by old LibreBoard.

**Comment by radomici** [comment]
This is another issue with recently created Wekan documents: When I create sharing link with edit
rights, the document opens read only via the link, no option for editing or adding member in any way.

**Comment by kentonv** [comment]
@radomici - The recipient needs to sign in (and choose to reveal their identity) in order to get edit access. This is arguably a bug in Wekan, but it's unclear how Wekan should record an audit trail for an anonymous user.

**Comment by mquandalle** [comment]
@radomici You are right, this was reported in #349, let’s keep the issues separate.

**Comment by mquandalle** [comment]
@kentonv I was able to share a Wekan grain upgraded from LibreBoard using the share link (without edit mode as you realized). Do you have any further indication to help me reproduce this bug?

By the way there isn’t really a “username/password mode”, the page is still there we just don’t display it. I guess it’s possible to see this form if the grain URL is changed to home `/`, but I don’t know how this would happen.

**Comment by kentonv** [comment]
@radomici do you have a grain backup zip that demonstrates the issue which you'd be willing to share with @mquandalle?

**Comment by dwrensha** [comment]
> I guess it’s possible to see this form if the grain URL is changed to home /, but I don’t know how this would happen.

Presumably the app already has some kind of redirect from / to /boards/sandstorm/libreboard or whatever. Why wouldn't that continue to apply in this case?

**Comment by mquandalle** [comment]
The redirection is done on the server side ([here](https://github.com/wekan/wekan/blob/c804813e5f5fdffb8a7deca72737b65f052ea28a/sandstorm.js#L65-L68)). This HTTP redirection isn’t enforced if the client modifies the URL to `/` (which shouldn’t be possible from the UI).

**Comment by radomici** [comment]
Restored my Wekan doc zip backup (created on Sept 24) that was created in Libreboard and upgraded to Wekan. Created shared link. Opening that shared link results in "Board not Found. This page may be private. You may be able to view it by logging in" message.
But I noticed that when I deleted this Wekan grain, the page with "Board not found......" page dissappeared immediatelly from the browser window on my other computer. The message "Invalid authorization token [403]" appeared instead. So, it seems it actually found the board but did not allow to view it.
Restored the Wekan grain from zip file. Had to create sharing again, it was not preserved. Tried to open the shared link on my other computer and got same "Board not found......" page.
I have a backup zip file of the grain ready but this board did not allow me to upload it as ZIP, no extension, TXT, PDF. How do you want me to deliver it to you?

**Comment by mquandalle** [comment]
You can upload it [here](https://alpha.sandstorm.io/shared/xmWOF-JsgCwv3zcNBwGOZ2hjJMh0fi_9G0cM1no088b), or send me an e-mail if you prefer something else.

**Comment by radomici** [comment]
File has been uploaded.

**Comment by mquandalle** [comment]
Thanks, I was able to reproduce the issue with it.

**Comment by mquandalle** [comment]
The iframe URL is of the form `https://alpha-xxx.sandstorm.io/_sandstorm-init?sessionid=xxx&path=/`. That URM seems to come from the Sandstom shell, do you know if that suppose to redirect @kentonv?

**Comment by mquandalle** [comment]
Well actually that seems to be expected.

**Comment by mquandalle** [comment]
Ok, I got it, it was an easy one.

LibreBoard v0.8 didn’t implement the Sandstorm sharing model (which didn’t exist at the release time) and instead kept the visibility setting (“public” or “private”) in the UI as does the main Meteor application. On Wekan v0.9 access is now handled by Sandstorm itself so [the board is created “public”](https://github.com/wekan/wekan/blob/a78debc461944f55de246db15a1dd29353dec4ae/sandstorm.js#L18-L21) and the button to change that visibility setting has been removed from the UI. It turns out that if you changed the visibility to “private” on LibreBoard v0.8, it will stay private in Wekan v0.9 because I forgot to include a migration to change it. I’ll include such a migration in the next release of Wekan. Meanwhile @radomici, if you need to share by link a “private” Wekan board, you can:

1. open the Wekan grain with the owner account that has access to it
2. open the console in the debuggers tool and select the appropriate grain frame (something like `https://domain.com/b/sansdstorm/libreboard`)
3. run
  
  ```js
  Boards.update('sandstorm', {$set: {permission: 'public'}})
  ```
4. You should now be able to share this grain with the Sandstorm sharing link
