### ISSUE TITLE
Show no. of cards in lists on mobile

### ISSUE THREAD

**Issue by Nevarro** [wekan/wekan#3465]
I've got a feature request:

It would be great to be able to see the number of cards in a list in the compact view on mobile devices (smartphones).

**Comment by mfilser** [comment]
I think this option should help:
![grafik](https://user-images.githubusercontent.com/13166201/106859804-d8fc4780-66c3-11eb-890e-077148bbc35f.png)

But i also saw that at mobile view you can't change the number because the spinner is not visible (at my mobile).
So for now if you don't see the spinner too you have to change it at desktop browser.
In the future i will fix this too, it's already on my todo list since last week

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3545
