### ISSUE TITLE
Wekan in Docker on Raspberry

### ISSUE THREAD

**Issue by harrykl** [wekan/wekan#3477]
## Issue
On my Raspberry i have Docker running and the build crashes with **standard_init_linux.go:211: exec user process caused "exec format error"**

I have tried the dockerfile.arm64v8 but it also chrashes.

Do you have any Ideas?

**Comment by xet7** [comment]
@harrykl 

What OS version you have? Check with `uname -a` and `cat /etc/issue`:
- If you have [Raspberry Pi OS 32](https://www.raspberrypi.org/software/operating-systems/#raspberry-pi-os-32-bit), that does not work.
- If you have [Raspberry Pi OS 64bit](https://www.raspberrypi.org/forums/viewtopic.php?t=275370), it could maybe work.
- If you have [Ubuntu Desktop 20.10 64bit](https://ubuntu.com/download/raspberry-pi), it could maybe work.

For 64bit arm64, like 64bit Linux on RasPi3/4 and arm64 bare metal Linux servers like [Equinix Metal](https://www.packet.com), there is [Wekan bundle](https://github.com/wekan/wekan/wiki/Raspberry-Pi).

I have not tested does building Docker image for arm64 work yet. That "exec format error" could mean that you are trying to use Docker on 32bit ARM.

**Comment by Shahin-rmz** [comment]
Hello,
A Kanboard user here. 
Although I am fascinated about Kanboard as FOSS project and I like the brain behind it, found Wekan and want to migrate to Wekan.
Wekan is also FOSS, and respects privacy and it is full featured. It is  also well maintained, and has good Documentation.
Simply awesome.

Just want to know if there are any docker-compose files which I can use, to install Wekan on my Raspberry pi4 that works as my "self hosted " server?

Could't find any good documentations. All I see was bare metal installation.
Thanks

OS: Ubuntu Server 20.10 64bit

The problem is mainly with Mongodb as far as I see in the logs.
Here is the logs when I make the docker.

```
Recreating wekan-app ... done                                                                                                                                 
Attaching to wekan-db, wekan-app                                                                                                                              
wekan-app  | exec /usr/bin/bash: exec format error                                                                                                            
wekan-app exited with code 0                                                                                                                                  
wekan-app  | exec /usr/bin/bash: exec format error                                                                                                            
wekan-app  | exec /usr/bin/bash: exec format error                                                                                                            
wekan-app  | exec /usr/bin/bash: exec format error                                                                                                            
wekan-app exited with code 1                       ```

**Comment by xet7** [comment]
@Shahin-rmz 

There is not yet Docker version for RasPi. I'll try to sometime add Docker and Snap also for arm64. I'm also In Progress of releasing new WeKan v6.29 soon.

For RasPi, I recommed that you edit /etc/mongodb/mongodb.conf or /etc/mongodb.conf to store raw database files of /var/lib/mongodb instead to USB3 SSD drive. microSD cards can only handle limited amount of writes.

RasPi info is here:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

Current versions required are listed at https://wekan.github.io Download section:
- Ubuntu 20.04 arm64 (or Raspberry Pi OS 64bit maybe), MongoDB is only compatible with this
- WeKan zip file https://releases.wekan.team/raspi3/wekan-latest-arm64.zip
- Node.js 14.x for Linux arm64 https://nodejs.org/dist/latest-v14.x/
- MongoDB 5.x. for Ubuntu 20.04 arm64 https://www.mongodb.com/try/download/community

You could use that systemd service stuff at that wiki page,
or edit start-wekan.sh from https://github.com/wekan/wekan so that it has settings and this kind of code:
```
cd bundle
node main.js
```
Other settings, see your raspi ip address:
```
ip address
```
And change here your IP address:
```
export ROOT_URL=http://192.168.0.200:2000
export PORT=2000
 ```
More info about ROOT_URL at https://github.com/wekan/wekan/wiki/Settings

About adding users:
https://github.com/wekan/wekan/wiki/Adding-users

I'm also trying to add support for more databases, like SQLite etc.

**Comment by Shahin-rmz** [comment]
@xet7 thanks so much for fast and complete reply.
I will answer you tomorrow, and update this comment about the progress of installing.
Best.

**Comment by xet7** [comment]
@Shahin-rmz 

I wrote more info to https://github.com/wekan/wekan/wiki/Raspberry-Pi

If you use that Snap version of MongoDB, it's possible that using newest Ubuntu arm64 or Raspberry Pi OS arm64 also works.
