### ISSUE TITLE
for a Better experience

### ISSUE THREAD

**Issue by javen9881** [wekan/wekan#3517]
Suggestion and feedback on bugs.
1. [Pop-up card]show card content as a pop-up window when click on card;
2. [Update mark]show a mark(i.g. red point) on the card which my name in the member list when any update I didn't read.

bugs I found in Wekan V4.91 on Win10.
1. Export to excel doesn't have the pictures;
2. Customize field don't have a right sequence.
3. Activities didn't show the recent days/months.

**Comment by mfilser** [comment]
> Customize field don't have a right sequence.
What do you mean with it exactly, can you send a screenshot?

**Comment by javen9881** [comment]
![image](https://user-images.githubusercontent.com/46272743/106578995-21f4b480-657b-11eb-8b1a-1ec40ce58532.png)
Customize field don't have a right sequence.

**Comment by mfilser** [comment]
The custom fields are now sorted alphabetically (since v4.82). Before it, the custom fields were displayed in the order they were added to the card, so at 1 card the order was different to another card.
The best would be indeed the custom fields are ordered as at "Edit custom fields". Also there could be the option to reorder by drag drop the custom fields.
I just wonder at the moment that the fields are not ordered alphabetically in the screenshot. At which version did you create the screenshots?

**Comment by javen9881** [comment]
> The custom fields are now sorted alphabetically (since v4.82). Before it, the custom fields were displayed in the order they were added to the card, so at 1 card the order was different to another card.
> The best would be indeed the custom fields are ordered as at "Edit custom fields". Also there could be the option to reorder by drag drop the custom fields.
> I just wonder at the moment that the fields are not ordered alphabetically in the screenshot. At which version did you create the screenshots?

v4.91，I found it also on v4.87

**Comment by mfilser** [comment]
For custom fields i will have look

**Comment by javen9881** [comment]
> For custom fields i will have look

great thanks
