### ISSUE TITLE
Stable tag for latest release

### ISSUE THREAD

**Issue by nimasamii** [wekan/wekan#3541]
For automatic updates of containerized deployments used in production, it would be very helpful to have a "stable" tag referencing the latest release of Wekan in the registries docker.io and quay.io. At the moment there is only latest which is bleeding edge and updates too often for a production deployment. Periodically checking the registry places an (avoidable) burden on operators wishing to track the latest stable release.

**Comment by xet7** [comment]
@nimasamii 

You see current Wekan release version here:
- [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md)
- [RSS feed](https://github.com/wekan/wekan/releases.atom)
- [Wekan website Download section](https://wekan.github.io)

So according to those, current Wekan release version is v4.93.

There are already release tags at [Docker Hub](https://hub.docker.com/r/wekanteam/wekan/tags?page=1&ordering=last_updated) and [Quay](https://quay.io/repository/wekan/wekan?tag=latest&tab=tags)

There tags `latest` and `master` do mean git repo latest no-release tag.

Anyone deploying Docker version of Wekan should only deploy Docker release tags.

Alternatively, you could grep ["version" at package.json file](https://github.com/wekan/wekan/blob/master/package.json#L3).

Does this answer your question? Please give more details. Thanks!

**Comment by xet7** [comment]
For my own server, I do run [Wekan Snap version](https://github.com/wekan/wekan-snap/wiki/Install) that does run Wekan automatically. I also have automated daily backups.

For Docker, there are various [update management systems](https://github.com/wekan/wekan/wiki/Docker#dockerbunker-easy-docker-management), if you like to use Docker.

Anyway, in your server management, I would recommend to automate as many manual steps as possible, to make it faster to deploy and rollback, if required.

**Comment by nimasamii** [comment]
@xet7 Thank you for your quick reply.

Basically what my request boils down to would be after a release to tag the built container as "stable" in addition to its version, e.g.
podman tag quay.io/wekan/wekan:vX.Y.Z quay.io/wekan/wekan:stable
just as you do with master & latest.

Unfortunately Snap is not an option for us. I'm running wekan in production on Openshift using the images from the quay.io registry. Openshift has ImageStreams that allow tracking of remote registries. They can automatically synchronize image tags with an upstream registry and trigger a re-deployment when a new version is available.

I can track latest/master just fine, but not the stable releases. I have to manually check if there is a new release and update the ImageStream by hand. A simple shared tag from the latest released version to "stable" would let me automatically update the production deployment without manual intervention.

As an example how that works, the nextcloud Project does this:
https://hub.docker.com/_/nextcloud?tab=description
20.0.6-fpm and stable-fpm are the same image. When 20.0.7 is released the stable-fpm tag is moved to the new release and anyone tracking the "stable-fpm" tag will be notified of the new release.

**Comment by xet7** [comment]
Unfortunately, adding `stable` tag did not work. It caused some Wekan platforms version numbers to be `table` instead of actual version numbers. It also added too much delay and additional complexity to release process. So I had to remove `stable` tag, and revert `docker-compose.yml` files back to `latest` tags.

The reasons why some features break in Wekan are:
- Very often some dependencies get deprecated, changed, etc
- There are often security issues, so it's still necessary to run latest with newest security fixes
- There are often added new features and fixes to Wekan, that sometimes break something, but those are usually fixed fast
- There are often changes to webbrowsers like Chrome/Firefox/Safari etc that cause some Wekan feature get broken that worked with previous browser version

Wekan is still going in direction of fixing all bugs.

So I don't currently have a way to provide stable version, there are too many moving parts. I can only try to fix what I can.
