### ISSUE TITLE
wekan stores user password in clear text. Unacceptable!

### ISSUE THREAD

**Issue by atlantsecurity** [wekan/wekan#3598]
Are the user passwords are stored in clear text?
The admin is able to view a user, and the password behind the asterisks can be seen via "Inspect" in any browser. 

Upon further inspection I found that every time you inspect a user password, it always shows the same 'template' password. 

I am kindly asking the project maintainers to obtain a CVE for this vulnerability and quote me in it. 
https://docs.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories

If this is a false positive, which is possible, accept my apologies :)

**Comment by xet7** [comment]
@atlantsecurity 

What version of Wekan are you running?

**Comment by atlantsecurity** [comment]
4.96.0

**Comment by xet7** [comment]
@atlantsecurity 

Please send screenshot of that to support@wekan.team , and continue to discuss there.

**Comment by xet7** [comment]
Anyway:
- Wekan stores passwords as bcrypt hashed etc, as is default in Meteor auth package
- I did not yet find with where password would be visible with browser inspect, that's why I need more details to support@wekan.team
- Unfortunately Wekan issues GitHub template does not yet have link at top to https://github.com/wekan/wekan/blob/master/SECURITY.md , I will add this soon, sorry about you losing some points by adding public GitHub issue.

**Comment by xet7** [comment]
Discussion will be continued in email.
