### ISSUE TITLE
Operation problems in offline environment

### ISSUE THREAD

**Issue by xuguotong** [wekan/wekan#3623]
When npm install is executed in an offline environment, an error occurs. Can l  delete the npm install command in the script?In other words, you have better suggestions to complete the build operation of offline environment？

**Comment by xet7** [comment]
@xuguotong 

For offline install, usually `npm install` is not required:
https://github.com/wekan/wekan/wiki/Offline

What are you trying to install with `npm install` ?

**Comment by xet7** [comment]
Newest compatible nodejs is here https://nodejs.org/dist/v12.21.0/

**Comment by xet7** [comment]
@xuguotong 

For running Wekan offline, those steps are not needed. All required files are inside [wekan-5.02.zip](https://releases.wekan.team/wekan-5.02.zip) already.

So after unzipping that file, you have `bundle` directory

[start-wekan.bat](https://raw.githubusercontent.com/wekan/wekan/master/start-wekan.bat) or [start-wekan.sh](https://raw.githubusercontent.com/wekan/wekan/master/start-wekan.sh) sets some settings, and then does:
```
cd bundle
node main.js
```

**Comment by xet7** [comment]
Usually when using Wekan, it's not required to change any source code:
- All required settings can be set at `start-wekan` scripts and Admin Panel
- at `All Boards` page boards can be bookmarked by moving mouse over icon and clicking star
- At Admin Panel / Settings / Layout you can set Custom Logo and Custom Product name

But if you have modified your code, and really need to build bundle offline, unfortunately that would require some mirroring software that would cache those packages to local harddrive from https://atmospherejs.com and https://npmjs.com when building software while being connected to Internet. I prefer to add more settings to Wekan if any are missing, so that building offline would not be necessary at all.
