### ISSUE TITLE
Unable to connect to Wekan snap DB

### ISSUE THREAD

**Issue by ChrisFredriksson** [wekan/wekan#3645]
Following the information from xet7 in this thread;
https://github.com/wekan/wekan/issues/2935

Trying to log into the MongoDB database to clear out the activity.

Trying command;
`/snap/wekan/current/bin/mongo --port 27019`

And I get the following error;
`/snap/wekan/current/bin/mongo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

Command "locate libssl" gives;

/snap/core/10859/lib/x86_64-linux-gnu/libssl.so.1.0.0
/snap/core/10859/usr/share/doc/libssl1.0.0
/snap/core/10859/usr/share/doc/libssl1.0.0/changelog.Debian.gz
/snap/core/10859/usr/share/doc/libssl1.0.0/copyright.gz
/snap/wekan/1402/lib/x86_64-linux-gnu/libssl.so.1.0.0
/snap/wekan/1402/usr/share/doc/libssl1.0.0
/snap/wekan/1402/usr/share/doc/libssl1.0.0/changelog.Debian.gz
/snap/wekan/1402/usr/share/doc/libssl1.0.0/copyright
/snap/wekan/1407/lib/x86_64-linux-gnu/libssl.so.1.0.0
/snap/wekan/1407/usr/share/doc/libssl1.0.0
/snap/wekan/1407/usr/share/doc/libssl1.0.0/changelog.Debian.gz
/snap/wekan/1407/usr/share/doc/libssl1.0.0/copyright
/usr/lib/dovecot/modules/libssl_iostream_openssl.so
/usr/lib/x86_64-linux-gnu/libssl.a
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
/usr/share/doc/libssl-dev
/usr/share/doc/libssl-dev/changelog.Debian.gz
/usr/share/doc/libssl-dev/changelog.gz
/usr/share/doc/libssl-dev/copyright
/usr/share/doc/libssl1.1
/usr/share/doc/libssl1.1/NEWS.Debian.gz
/usr/share/doc/libssl1.1/changelog.Debian.gz
/usr/share/doc/libssl1.1/changelog.gz
/usr/share/doc/libssl1.1/copyright
/var/cache/apt/archives/libssl-dev_1.1.1d-0+deb10u5_amd64.deb
/var/lib/dpkg/info/libssl-dev:amd64.list
/var/lib/dpkg/info/libssl-dev:amd64.md5sums
/var/lib/dpkg/info/libssl1.1:amd64.list
/var/lib/dpkg/info/libssl1.1:amd64.md5sums
/var/lib/dpkg/info/libssl1.1:amd64.postinst
/var/lib/dpkg/info/libssl1.1:amd64.postrm
/var/lib/dpkg/info/libssl1.1:amd64.shlibs
/var/lib/dpkg/info/libssl1.1:amd64.symbols
/var/lib/dpkg/info/libssl1.1:amd64.templates
/var/lib/dpkg/info/libssl1.1:amd64.triggers

Edit..
I also tried opening up port 27017 and 27019 in the router to the server to try and connect with MongoDB Compass - which I don't know is the correct software to connect to a MongoDB server.. as I've never used this database software before.. But I'm unable, the DB server isn't responding - I don't have UFW installed on the Debian server either, so should be completely "open" on the local LAN inside the router.

I can't find any username/password for the MongoDB either, so I don't know if that is needed.

I'm anyhow very much unable to get into the DB to clear activity on the board.

I installed Wekan via snap just a few days ago, I don't know the version I'm currently running on Wekan.

**Comment by ChrisFredriksson** [comment]
So, I guess this either isn't possible or Wekan isn't under development anymore?

**Comment by xet7** [comment]
Oops, sorry I forgot to answer this earlier.

You see your snap version with:
```
sudo snap list
```
Version should be same like here https://snapcraft.io/wekan

You should not delete your activity history, because it also contains card comments, you would lose important data.

For that recent speed improvement, that is done to database automatically, you don't need to manually edit database.

For that mongoshell, see:
https://github.com/wekan/wekan/wiki/Backup#mongodb-shell-on-wekan-snap
That LD_LIBRARY_PATH setting is important, so mongo commands do know paths to .so files (they are similar like .dll at Windows).

Another way to edit database is with nosqlbooster:
https://github.com/wekan/wekan/wiki/Backup

About is Wekan being still developed, I have released new version of Wekan about every 3rd days since 2016-12:
https://github.com/wekan/wekan/blob/master/CHANGELOG.md

Also at OpenHub:
https://www.openhub.net/p/wekan
when clicking `Stable Y-O-Y development activity` you get description:
> Over the last twelve months, Wekan has not seen any change in activity. This may be a good sign, and an indication that development is continuing at the same pace and not dropping off.
