### ISSUE TITLE
Can't remoove filter "Sort Cards"

### ISSUE THREAD

**Issue by Kairiefr** [wekan/wekan#3647]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: Yes
* Wekan version: 5.05
* Operating System: CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): apache
* Wekan only works on newest desktop Firefox/Chromium/Chrome/Edge/Chromium Edge and mobile Chrome. What webbrowser version are you using? Chrome 89.0.4389.82, Firefox 78.8.0esr, Opera

**Problem description**:

After sorting the cards in a board using the "Sort Cards" option, I can not more rearrange cards as I want, I just can change them from one column to another.
It becomes impossible to move the cards up or down. It's like I can't remove the "Sort Cards" filter
In addition, the option "Sort cards" applies to all board. So we have the same problem of inability to move the cards with all the boards

The only solution I have found is to delete my cookies from the browser

I don't know if this is the desired use of this new feature (added in version 4.98) or a "bug".

Is it possible to remove this filter "Sort Cards" to have the "real" board (not sorted) and to be able to move the cards again without having to delete the cookies of the browser?
Not like delete the option,but juste choosing activate it or not.

Hoping to have been as clear as possible.

**Comment by xet7** [comment]
@ednamaeG 

Do you have time to fix this?

**Comment by xet7** [comment]
In general, is something a bug or feature, depends does it work well enough, and is someone so interested in some feature that someone keeps fixing it so it mostly works. Those features that do not work usually get removed.

**Comment by ClaudiaK21** [comment]
I noted this issue here too: https://github.com/wekan/wekan/discussions/3607#discussioncomment-409409

When using a sorting in the board area, you can not move a card in this view - only in the standard/default view (which is correct).
But to get back to the standard default, **you need to refresh** the board page, switching to another board and coming back does not reset the set sorting, so it might be helpfull to add a "Standard" or Default option to the sorting options and maybe a highlighting so you can see which sorting is active.

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3662

**Comment by ClaudiaK21** [comment]
@ednamaeG
thanks for the adjustment. The  "Added a button to clear/reset sort" is nice and highlighted
![grafik](https://user-images.githubusercontent.com/79307821/111973138-7db0d800-8afe-11eb-9968-1f2dac50f6ab.png)

But when I **switch boards** the sorting has not been reset.
I mean, the highlighted active sorting button is good to recognize now. If you all think a reset when switching board should work automatically then you might check the code, because this doesn't work at the moment.

**Comment by urmel1960** [comment]
Hi there 

I just also tested this issue.

When I set a filter on one board - I do get the button/label reminding me that a filter is set. 
When I then switch to another board - the filter automatically disappears and is cleared.

For me that is fine  - thanks for the fix.

**Comment by ClaudiaK21** [comment]
That is weird. 
I tested it with Firefox 86.01, Edge 88.0.705.63 and Chrome 89.0.4389.90 
and also my colleague who has a default firefox with no addons - the sorting is not reset when switching a board.

**Comment by urmel1960** [comment]
Hmm 

Setting a filter means that only certain entries in a board are not displayed - so that only the entries I want to have filtered out are displayed.
In the previous posts "sorting" and "filter" are sometimes and somehow mixed and used together. This is not the right term from my point of view. Sorting is not a filter but the instruction in which order certain entries are displayed on the board. 

And yes, you are right - sorting is not reset when changing the boad. The filters is reset to default when switching boards

From my point of view this is ok - but it is only my point of view .... :-)

**Comment by ClaudiaK21** [comment]
ah, well yes the new sorting button is meant not the filter options. I'm glad, that not reset when switching is not working for you too ;-) but I would like it, because not all users will check this, and it would reduce steps like first delete active sorting and then choose a new one.

**Comment by xet7** [comment]
From https://github.com/wekan/wekan/pull/3662#issuecomment-803951430 @ClaudiaK21 

> I noted an issue here https://github.com/wekan/wekan/issues/3647#issuecomment-803942354
> "Sorting is reset to default when switching to other boards" does not work correctly.

@ednamaeG Can you look at this?

**Comment by ednamaeG** [comment]
@ClaudiaK21 thanks for the info. I'm not sure why it doesn't work on yours. I just tested it and when i switched to other board, the sorting is reset where I can move the cards up/down which is the default sorting of wekan I think.

**Comment by Kairiefr** [comment]
Hello,
I was able to test the fix yesterday, and for me everything is good!
Thanks for it

Should I close the issue ? I don't know if everyone got an answer.. ?

**Comment by ClaudiaK21** [comment]
Sorry to say, but the "sorting" reset when switching board is still not working for us, Firefox, Chrome, Edge. 
I have asked our IT now, it is weird that it works for some users here.

**Comment by ClaudiaK21** [comment]
OK - we have found out something. 
the reset works when switching the board via **Home** "all boards", but
we allways and **only switch via** Starred Favorite Board - the Quicklink list. With 10 boards this saves time
AND using these quicklinks to **starred boards: the reset does not work.**

**Comment by bbyszio** [comment]
> OK - we have found out something.
> the reset works when switching the board via **Home** "all boards", but
> we allways and **only switch via** Starred Favorite Board - the Quicklink list. With 10 boards this saves time,
> using these quicklinks to **a starred board: the reset does not work.**
> 
> When using the filter options on the right the reset works also for the starred board links.

I can confirm that on our side.

**Comment by xet7** [comment]
@ednamaeG 

If there is some existing reset, could you change it to go to "all boards" page? Or alternatively, try some other way to fix?

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/3686
