### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by kevr** [wekan/wekan#3660]
Hello Wekan.

Apologies for the simple question -- after cloning wekan, I'm trying to build the project to host via nginx. I have been unable to locate any documentation for build steps, and so I just looked around the root directory to try and figure it out off the top. I ran `rebuild-wekan.sh`, which succeeded, but... where exactly are the files for the web root located after that, or if that's not how it's hosted, how do I proceed afterward?

Anyway, I'm just trying to figure out if there's any stable documentation for the build steps. Any help would be greatly appreciated, and thank all of you for making this!

**Comment by xet7** [comment]
@kevr 

I usually install Wekan Snap version with included Caddy webserver that provides Let's Encrypt SSL or CloudFlare SSL:
https://wekan.github.io has Download / Snap x64 automatic updates:
https://github.com/wekan/wekan-snap/wiki/Install
I usually use CloudFlare SSL with Caddy:
https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config

If you really would like to use Nginx instead of Caddy, there is info here:
https://github.com/wekan/wekan/wiki/Nginx-Webserver-Config
But good luck trying to get it working, some have not got Nginx working well enough in front of Wekan.

For normal users, it's not required to build from source code, Wekan has web based UI, Admin Panel etc.

**Comment by kevr** [comment]
Gotcha, @xet7. Thank you for the information. I'm personally a bit conflicted with both `snap` and `apt` managing packages on my systems, but I suppose I could go that route.

I very much appreciate your time and information. Sorry to bother!

**Comment by xet7** [comment]
@kevr 

It's OK to ask, you did not bother.

About packaging:
- Snap is currently best packaging system, because it is sandboxed (similar to Docker/Sandstorm Grain etc), and it automatically upgrades to newest version of Wekan. For Internet connected servers, it's a huge advantage, because when I release new Wekan version that has security fixes (like new version of Node.js) it updates to all Snap servers wordwide very soon. Also when update comes, there is very little downtime, it updates to newest version fast.
- Docker has problem that all those layers take a lot of space, updating usually takes much more time
- deb/rpm packages usually are not sandboxed, and updating usually takes much more time. I have not yet fixed Wekan deb and rpm package builds.
- Sandstorm version of Wekan currently is most secure, but does not have all user management features etc that other Wekan versions have, because security and permissions work differently at Sandstorm
- Wekan itself requires only node+mongodb, like described at https://github.com/wekan/wekan/wiki/Offline
- For only node+mongodb, there are Wekan for x64/arm64/s390x/ppc64le at https://github.com/wekan/wekan/wiki/Raspberry-Pi

**Comment by xet7** [comment]
@kevr 

I saw your message at IRC. If you don't need isolation like snap and automatic updates, then use x64 bundle, like at:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

**Comment by kevr** [comment]
Aha, okay! Thank you very much :)
