### ISSUE TITLE
Time-Format / Date-Format in German Translation wrong since update from 5.17.0 to 5.20.0

### ISSUE THREAD

**Issue by mks-85** [wekan/wekan#3718]
Hi there,

OS: ubuntu 20.04
Wekan 5.20.0 installed by snap

Since updated from 5.17.0 to 5.20.0 the time format in german translation is 12 hours with am and pm instand of 24h format and date format is now MM/DD/JJJJ instead of DD/MM/JJJJ.

![wekan2](https://user-images.githubusercontent.com/74009667/114716264-2f28df00-9d34-11eb-8708-fd97b02aa652.jpg)

**Comment by urmel1960** [comment]
I do see the same behaviour here as well. Had the same already in the past after upgrading - but it was then gone somewhen shortly after it occured. This time it is persistent so far. 

Tried with different browser and already double checked language settings and clearing caches but no positive result. 

Any advise to solve this issue is highly appreciated

**Comment by urmel1960** [comment]
just checked traffic woth developer tools in Firefox and I see the folliwng message:

`Laden fehlgeschlagen für das <script> mit der Quelle "http://localhost:3001/packages/mquandalle_moment/locale/de.js?_=1618469932828".`

Maybe that is the reason - but I do not know how to solve this ...

**Comment by lzieba** [comment]
Hi,

Same with me. After upgrading from v5.17 to v5.20, the date format in English (UK) or Polish is MM / DD / YYYY instead of DD / MM / YYYY

**Comment by StefanNeubert** [comment]
Same here from 5.19 to 5.20

**Comment by pnrm** [comment]
Hi there,

OS: ubuntu server 20.04.2 LTS
Wekan 5.22.0 installed by snap

In version 5.22.0 the time format in french translation is 12 hours with am and pm instand of 24h format and date format is MM/DD/JJJJ instead of DD/MM/JJJJ.
![image](https://user-images.githubusercontent.com/18323883/115702349-1ab69900-a369-11eb-8af6-e29e3f5afa13.png)
