### ISSUE TITLE
Generating REST API Docs: highligh.js deprecated?

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#3757]
@bentiss 

When I install REST API docs dependencies with https://github.com/wekan/wekan/blob/master/releases/rebuild-docs.sh , when `~/python` directory does not exist yet, it shows these:
```
npm WARN deprecated mkdirp-promise@1.1.0: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated highlightjs@9.16.2: Use the 'highlight.js' package instead https://npm.im/highlight.js
```
Then when it is generating REST API docs, it outputs `658` times this same text (I did count 658 repeating lines with `cat log.txt | grep highlight.js | wc -l`):
```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```
Can you fix https://github.com/wekan/wekan/blob/master/releases/rebuild-docs.sh to show less errors while generating docs?

**Comment by bentiss** [comment]
> Can you fix https://github.com/wekan/wekan/blob/master/releases/rebuild-docs.sh to show less errors while generating docs?

unfortunately, these errors are related to `api2html`, and I am not sure I can do anything to fix them.

I spend some time finding an alternate, and https://mrin9.github.io/RapiDoc/index.html seems interesting: we don't generate the html page as it is generated on the client side with the provided js script.

I can see 2 downsides however:
- we lose the ability to have a single static file (we need a server or modern browsers will refuse to load the js and the yaml file)
- we lose the snippets in various languages.

On the plus side:
- no more generation of the html (we just embed the .js which is MIT licensed and we provide a single html file)
- we should be able to try on live the API calls, because AFAICT wekan is serving the `public` repo from its webserver, so it might be working.

FWIW, the "static" html would ressemble:
```html
<!DOCTYPE html>
<!-- Important: must specify -->
<html>
  <head>
    <meta charset="utf-8" />
    <!-- Important: rapi-doc uses utf8 charecters -->
    <script
      type="module"
      src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"
    ></script>
  </head>
  <body>
    <rapi-doc
      spec-url="wekan.yml"
      theme = "dark"
    show-header = "false"
    primary-color = "#f54c47"
    bg-color = "#2e3746"
    text-color = "#bacdee"
    render-style="read"
    show-components="false"
    allow-authentication="true"
    allow-try="true"
    allow-server-selection="true"
    >
    <img
    slot="nav-logo"
    src="../logo-header.png"
  />
    </rapi-doc>
  </body>
</html>
```

(or with a copy of `rapidoc-min.js` put in the `public/api` directory)

Note: for the page to work properly, #3762 needs to be merged first

**Comment by xet7** [comment]
> - we lose the snippets in various languages.

This would be very big downside.

My current feeling is, if something is not maintained, I need to fork it and maintain it myself.
