### ISSUE TITLE
Wiki - Contributed to Backup and Apache pages

### ISSUE THREAD

**Issue by pitastrudl** [wekan/wekan#3811]
Hi,

I "fixed" a statement for the docker-compose down command and added some lines for the Apache configuration. Relating to my centos 8 install, it does differ, but as stated in the wiki, it depends on the distribution. 

Repo: https://github.com/pitastrudl/wekanwiki 

Edit: I was not sure how exactly to contribute to a wiki, so I cloned it and opened an issue, if there's a better way, please let me know. 

Regards,
pitastrudl

**Comment by xet7** [comment]
@pitastrudl 

Thanks! I added your changes here:
- https://github.com/wekan/wekan/wiki/Apache
- https://github.com/wekan/wekan/wiki/Backup

There is currently no better way to edit wiki, you did it OK. Previously wiki was editable by any logged in GitHub user, but because some newbies did add some test pages to wiki wondering why they have write access (they did not understand what wiki is), I had to limit wiki edit access.
