### ISSUE TITLE
admin panel access?

### ISSUE THREAD

**Issue by LievreAI** [wekan/wekan#3905]
hey ya guys i using windows store Wekan version , how i can access admin control panel?

**Comment by xet7** [comment]
@LievreAI 

Teams/Organizations feature https://github.com/wekan/wekan/issues/802#issuecomment-870738124 of those apps at [Win10 Microsoft Store, Android Play Store and Ubuntu Touch OpenStore](https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix) is still In Progress, it's not fully finished yet, so it's not possible to create suborganizations for each user currently, or to have subadmin accounts. Although, you could already have some other people also register at Windows Store app, and add them to your board with their email address.

Because you are asking, maybe it would be useful? But yes, I think this could be improved, it's not yet like click-click-buy-instant-admin-panel-access experience. Also, having separate instances of Wekan be installed for separate is kind of more work, that having everything in same Wekan instance, although actual data could maybe be in separate databases in future maybe? Does somebody have more ideas about it?

There are some other alternative options:

a) Buy hosting, so I'll make available server that has admin access https://wekan.team/commercial-support/

b) Setup your own Wekan Server:
- https://github.com/wekan/wekan/wiki/Offline
- Installing as app: https://github.com/wekan/wekan/wiki/PWA
- OAuth2: https://github.com/wekan/wekan/wiki/OAuth2
- LDAP: https://github.com/wekan/wekan/wiki/LDAP

**Comment by xet7** [comment]
BTW, those Android Play Store users of app often leave low rating like 1 or 2 stars, and give reason that mobile app does not yet have feature to add your own Wekan server, and after all, does everybody just want to use their own server anyway to store their data? I had some ideas about that here https://github.com/wekan/wekan/issues/480#issuecomment-753973488 and some more ideas here https://github.com/wekan/wekan/issues/480#issuecomment-881011242 but I don't yet know what would be be best solution.

Apple has been actively removing PWA style apps from their App Stores, so I don't yet know how much effort it would require to and iOS or Mac app at App Stores. I'm thinking about it anyway https://github.com/wekan/wekan/wiki/Mac .

**Comment by xet7** [comment]
Those apps at various desktop and mobile stores are currently more like a demo and to host roadmap. Usually when some Windows user asks about Wekan, after those offline install links usually I don't get any other feedback from them.
