### ISSUE TITLE
Using the HTML5 Drag and Drop API

### ISSUE THREAD

**Issue by mquandalle** [wekan/wekan#391]
@Kentonv and other users suggested that we should use the HTML5 Drag and Drop API to move cards across boards (which would be one implementation of #240).

The argument for using it is that it would theoretically works across browser windows (whether or not they are Sandstorm grains). Unfortunately the last time I tried it (when I was refactoring LibreBoard into Wekan) it was very difficult to have a good user experience with it (for instance it is impossible to customize the drag preview). For those interested I fully agree with [this critic of the HTML5 Drag and Drop API](https://medium.com/@dan_abramov/the-future-of-drag-and-drop-apis-249dfea7a15f#340d).

Still, being able to drag cards across window would be great, so I’m opening this discussion with the hope that we will be able to find some sort of hybrid solution (using both the HTML5 drag API and the pure-DOM simulation) that would combine the advantages of both methods. I’ll also keep a close look at what React-Dnd is doing in this area — because Wekan is obviously not the only web application experiencing this issue.

**Comment by gwillen** [comment]
I think I might have been one of the users who prompted Kenton to mention this (he or someone else in #sandstorm suggested this approach when I asked about moving cards between boards.)

Because I'm using Wekan on Sandstorm, I think I can't be helped by plugin solutions that involve enumerating boards, since boards on Sandstorm are not expected to be able to see each other. So HTML5 drag-n-drop seems like the only simple method for accomplishing this (without having to create new Sandstorm capabilities for boards to communicate.)

One stopgap I thought of was a two-or-three-step process: Use jquery D&D (or a menu on the card) to move the card to a holding area (perhaps represented as a small icon somewhere in the UI); then use HTML5 D&D to drag the card from the holding area on one board and drop it into the other board (perhaps via another holding area). This is annoying UX-wise, but would minimize required changes to the app (which is why it was the most tempting approach if I was going to try to implement it myself.) It would mean not using HTML5 D&D for most card movement, which would preserve your existing UX for most purposes.
