### ISSUE TITLE
Wekan.team free to use?

### ISSUE THREAD

**Issue by Poolitzer** [wekan/wekan#3929]
Hi,

I am sorry that I don't understand the FAQ entry. I stumbled over https://boards.wekan.team/ and was able to sign up as well as create a board there. https://wekan.team/ calls itself Official Commercial Support for Wekan. But I do not see a paying option for using weekan.team, rather for features, bug fixes etc. as bounties, or for other support.

So my question is, can I use https://boards.wekan.team/ for my personal projects, or is it an error that I can just sign up there and I will be kicked out at some point? :D

Sorry for having to deal with my confusion.

**Comment by xet7** [comment]
@Poolitzer 

Currently it is free. In Wekan software itself, there is no feature of being able to pay something, in Wekan itself. If someone would like to support development of Wekan Open Source kanban, it's possible to optionally support Wekan development by paying some amount you like at https://wekan.team/commercial-support/ . That same https://boards.wekan.team also has apps at various appstores, listed at https://github.com/wekan/wekan/wiki/Browser-compatibility-matrix . That server where https://boards.wekan.team is, is donated to Wekan Team by [CNCF that is big part of Linux Foundation](https://blog.wekan.team/2019/06/wekan-on-raspi3-and-arm64-server-now-works-and-whats-next-with-cncf). Unrelated to Wekan, Linux Foundation also pays salary of Linus Torvalds. Many big companies belong to Linux Foundation to fund Open Source development.

How long it will be free? Hmm. I have maintained Wekan since [2016-12](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v0110-2016-12-16-wekan-fork-first-release), releasing new Wekan version about every 3rd day. I still don't see into future, I don't know what will happen tomorrow, or will earth still exist after about 20 years.

You can also export your boards to Wekan JSON, install Wekan Server from Download section of https://wekan.github.io to your own server or own computer, and then import those Wekan JSON files with `Add Board` => `Import from previous export`. On your own installed Wekan Server, boards are saved to that server, and you also have access to Admin Panel. All Wekan source code is here https://github.com/wekan/wekan . Info how to build wekan source code is at https://github.com/wekan/wekan/wiki/Emoji . For your own Wekan Server, also please make [daily backups](https://github.com/wekan/wekan/Backup).
