### ISSUE TITLE
Registration still visible after Disable "Self Registration" in Admin Panel

### ISSUE THREAD

**Issue by kameleon1er** [wekan/wekan#3971]
## Issue
`Deian 10 / Snap edition / NginX / Firefox or Chrome (Mac Os)` 

Hello, as stated in the title, the ability to create a new account is still present in the front-end while I checked the box "disable registration" in the back-office.

I also tested it by opening a "new private page" in FFox and Google Chrome.

Thanks.

**Comment by devrobinkroeker** [comment]
Hi, I face the exact same error.

I'm running wekan with snap and this is my environment:

- Debian 9
- snap/snapd 2.51.7
- wekan 5.65

Is this a confirmed bug or is there maybe a misconfiguration on my side? Please let me know if you need more information.

**Comment by devrobinkroeker** [comment]
Unfortunately after digging into the code I realized nobody will be able to create an account by himself cause the invitation link is required to create an account. The invitation link field is what gets toggled when using the setting `Disable Self-Registration` in the back-office.

I just had to read carefully \:. This issue is no longer urgent to me.
