### ISSUE TITLE
Board with 865 cards got slow

### ISSUE THREAD

**Issue by solunix** [wekan/wekan#4061]
## Issue with large Boards

**Server Setup Information**:
* Did you test in newest Wekan?: YES
* Wekan version: v5.65
* Operating System: Debian Linux
* Deployment Method: docker
* Http frontend if any: Apache
* Node Version: 12.22.7
* MongoDB Version: 3.2.21
* What webbrowser version are you using? FF 91.2.0esr and Chrome 94.0.4606.81

**Problem description**:
- Broswers (latest FF oder Chrome) got really slow with such a huge board. All Cards have Checklists (copied from a template card)
An export JSON is 60MB, including an orphan pdf attachement. I sedded the attachments out (sed -e 's/"file":".*=="//g') and got an 22MB JSON.
Importing this in an empty localhost Docker wekan works, but still got seconds of Click-Delays. Importing in the Production Server wont work. Chrome is not able to parse the JSON after pasting it and Firefox offered the User-Mapping screen but stops working after clicking on Finish.
- The Board has Rules to move Cards to the next Collumn when a Checkbox is checked.
- Browsers RAM Usage is over 4GB when entering the Board.
- It's hanging only with Admin Users.
- Can send you the JSON Export to reproduce
- In webbrowser Consoles says nothing
- No Docker Logs

**Comment by solunix** [comment]
I tested a bit with different scenarios, standalone and offline and with those NODE_OPTIONS. Nothing helped. Also I run wekan-cleanup and db.activities.deleteMany({}). We have 270 boards an 5500 Cards, and this extremly slow board has now 100 Cards after cleanup. So I think it is not with the size of this board itself.
Currently I saw some "too much recursion" errors in /wekan/1b...0e.js?meteor_js_resource=true:534:19196. This is the place where the Dot is in
`return p.inArray(e,t)>-1!==n}`
I guess that nothing helps to find the Error :)
Do you see another way?

**Comment by xet7** [comment]
@solunix 

I will fix this in some WeKan update at this or next year anyway. After that fix, only visible cards are loaded to browserside.

**Comment by solunix** [comment]
Happy new Year xet7 :)

I just updated to 5.88, but your mentioned Issue changed nothing with this Problem. Because of this Bug, there was no way to export Boards, but it was possible to do a mongodump. Would it be helpfull if I send it to your support-Mail?

**Comment by xet7** [comment]
@solunix 

No. WeKan v5.88 does not have any fixes for this yet, I have not written those fixes yet. Please wait for some later version of WeKan and then test. You will see something about speed improvements sometimes at [ChangeLog](https://github.com/wekan/wekan/blob/master/CHANGELOG.md).

**Comment by xet7** [comment]
@mfilser asked:

> I saw some days ago a comment of you (https://github.com/wekan/wekan/discussions/4282#discussioncomment-1950136)
> You told you are planning to make Wekan with optional Javascript. I am interested of a bit more information, what you are going to do that Wekan works without Javascript. At the moment (i think) most features are only available with Javascript...
>
> I also realized that there is more Javascript code than necessary, many things are written more than 5 times the same, too many database queries and so on...

It's related to these speed improvements. It depends does other WeKan community help, and do I have enough funding to do this. Here are some random notes about what could maybe be done:

- Change jade stylus to html css
- Minimal or no css
- Javascript include file that runs if browser js enabled
- At login or at top menu, possibility to changes layout of HTML4, HTML5+CSS, Accessible, custom layout template, etc
- Javascript replaces parts of page with in-place update code, drag drop, etc
- Calendar will be like html table. Optional per-date/month/year settings, allowing leap seconds, any kind of custom calendar, etc
- Have all HTML/CSS/JS also editable, making possible full customization of card/list etc layouts. Those templates could have keywords that are replaced with actual text content.
- Language translations done serverside, like this [language detection](https://github.com/wekan/php/blob/main/public/index.php#L42-L164) and using translate() function. Not like currently all translations loaded to browserside js.
- No build step of bundle. All public js at public folder, without minimize uglify. all serverside outside of public folder. Serverside code installed with npm, and mostly already existing current serverside code. Remove not-in use extra code. Check that Javascript code works with newest Node.js, Miniflare and Friend APIs. At each webpage, only load those js files that are needed, like only current database using code, only required cards, only required optional js, looking at environment variables what platform etc WeKan is currently running on. I don't know yet is there any time or possibility to try to use any other programming language than Javascript, because some platforms are Javascript only (with optional generated Javascript), and it would maybe be harder to debug generated Javascript code.
- For boards, board like html table, where only those visible cards from top left of board
- Navigation arrows to change view area, like right left up down
- Buttons to hide or show swimlanes, lists etc
- Without js does full page reload
- With js does in-place changes
- Scroll cards of list with scroll looking buttons, that will show how much cards is below. for example, if half of cards not visible, upper button of visible area 50% with active color, and below button 50% that would change non-visible area to be visible
- Hover menus for moving cards with css only, no js
- Only show image thumbnails. For each image and video, create thumbnail and smaller video file when file is uploaded
- Separate mongodb queries to folder `wekan/db/mongo/*.js` , also have queries for SQLite and PostgreSQL
- If possible, use SQLite that has no cost to several thousand queries, see https://www.sqlite.org/np1queryprob.html and https://news.ycombinator.com/item?id=29902345 , it's better than any other database. I don't know would additionally using some compiled programming language help.
- Each action at board, like copy card, copy board etc is written to actions todo list at serverside. at serverside, each action is done at small steps, saving result about does that step successfully work, and time when it was tried to do. If server has been restarted, or some time has been passed without progress, some server process or cron job tries to do it again, but only limited amount of tries, to prevent DDoS. So not like currently doing copying etc partially at serverside.
- Each action also automatically updates all downloads, like downloading board JSON, Excel, SQLite etc versions of exports for newest changes, and saves those changed files with date at filename. This way, when downloading those export files, it starts to download immediately.
- Optional deduplication. Generate hashes of each file, card, board, etc. Only store that data once, with time when it was created. When for example, when board is copied, it only copies that board hash, not content, making copies happen immediately. If there are changes to some board, only changed new non-existing data is saved, with new hash.
- Optional encryption. Save each attachment with different encryption key. Save all encryption keys to [databunker](https://databunker.org/) database. Save per-user data etc text data encrypted to databunker. If storing files to S3, use S3 per-file access keys to download encrypted file to browserside, and decrypt with Javascript at browseside with streaming. Searching using encryted keyword index databunker provides. When negotiating with webserver using browserside js, generate browserside public crypto keys to save at browser localstorage, and encrypt all data in transit even on HTTP networks.

**Comment by xet7** [comment]
Oh, and then there is question, why to try to do those changes at all? Well:

- WeKan currently uses Node.js v12, with EOL 2022-04-30 https://nodejs.org/en/about/releases/ . Node.js v12 does not receive any security updates after that.
- Nobody has helped me to upgrade to newest Meteor #3881
- There are often security updates to many dependencies. So I would like to have less dependencies.
- If there were no Javascript at browserside, there would be no need to fix that Javascript every time some browser update breaks something like happened at hard to fix case #1404
- All those drawing etc extra features could also be drawn serverside to png image file, so it would show in all browsers.
- It would not need to use most powerful expensive computers to use WeKan
- When not loading so much browserside, boards would load faster, it's helpful for big amount of users
- That's why also try some alternatives to Javascript, are they any better in some way, or would there be easier syntax.

**Comment by solunix** [comment]
Little positive Update from my Installation. I could speed boards up a little bit with deleting notification. Some Users had thousends entries. `db.users.updateOne({ "username":"loremipsum"},{ $set:{ "profile.notifications" : []} })`
This helps a bit, but browsers response Time is between 10 second and a Minute.

Can Notifications be generally disabled?

**Comment by xet7** [comment]
@solunix 

Maybe. I or someone else will find out.

There is still a possibility that I'll try to figure out how to:
- Upgrade Meteor
- Switch off those features that slow down too much
- Move attachments from MongoDB to S3 or elsewhere
- While still using Meteor, also have no-JS and accessible frontends possibility

I'll see how it goes.

**Comment by xet7** [comment]
@solunix 

Some progress, try these stack related fixes: https://github.com/wekan/wekan/issues/3585#issuecomment-1021522132

**Comment by xet7** [comment]
This kind of profiling could be useful:
https://forums.meteor.com/t/solved-meteor-server-memory-leaks-profiling/58210

For PubSub at  `wekan/server/publications/`, it would be useful find out how to start subscriptions of swimlanes/lists etc that are visible, and stop subscriptions when they are not visible.

**Comment by xet7** [comment]
Currently a lot of Javascript is running at frontend. That could be changed to run at backend. When clicking something, that would continue running as background job ( similar like scheduled jobs) and after it id finished, there would be it visible at frontend after reloading (if there is no Javascript/websockets/longpolling st frontend).
