### ISSUE TITLE
Wekan upgrade from legacy version 5.17 , which is installed from source

### ISSUE THREAD

**Issue by petkodimitrov1986** [wekan/wekan#4100]
Hello,
 We are currently running WeKan version 5.17 , installed long time ago manually from source. We have the following folders in /home/wekan : 
5.00  5.01  5.02  5.03  5.04  5.05  5.06  5.07  5.09  5.13  5.14  5.15  5.17  bundle  latest-x64 .  I have downloaded the newest version 5.68 in another folder , ran npm install but nothing happened, we are still with 5.17. Do we have 2 installs on the same server then ? Anyway, I can't seem to find any documentation in your wiki how to upgrade from legacy installation from source to the newest version? There is only install with "snap" .... Please let me know how can I upgrade my old version of WeKan 5.17 , installed from source, to the newest version of WeKan 5.68 . Thank you.

**Comment by xet7** [comment]
@petkodimitrov1986 

Please, do not try to build from source on production server. You will just mess up whole server with all those dependencies, build steps, etc, making whole server not work anymore.

You did not answer my questions at https://github.com/wekan/wekan/issues/4100#issuecomment-954650917

You should only use Snap on production server. This is because when I release new WeKan version that has fix to vulnernability like new Node.js version, it soon automatically upgraded to all WeKan Snap servers wordwide, making those servers safe from vulnerabilities. Usually when security fixed versions are released, withing some hours bad guys starts mass scanning of Internet to find and exploit vulnerable servers. Everything at servers need to be automatically updated, and also possible to generate new server with Ansible/SaltStack/Bash scripts etc. Do not install anything manually to production servers. For critical services, you should limit access to server to only allowed IP addresses at your firewall settings. You need to try to explain to your management how important this is, and document to with pen and paper dates and your own steps that tried to make possible having secure enough server. Because if management does not believe you, it is management's fault that management did not allow implement security properly. Using Snap, Docker, LXD, LXC, VMs etc is great way to separate server software from each other, so code in some app does not have direct access to delete all files at server, install malware etc.

**Comment by xet7** [comment]
If installing Snap to local network, it is usually done like this:
```
sudo apt -y install snapd

sudo reboot

sudo apt install wekan

sudo snap set wekan root-url='http://192.168.0.200'

sudo snap set wekan port='80'
```
You can see on which port MongoDB is running with:
```
sudo apt -y install net-tools

sudo netstat -plant | grep mongo | less
```
Usually Snap has MongoDB running at port 27019.

For your previous MongoDB database, I presume you did backup it this way:
```
mongodump --port 27017
```
For seeing what database name is correct, you see it in `start-wekan.sh` or similar, where is MONGO_URL. At database, you see it this way, using MongoDB shell:
```
mongo             <=== this uses 27017. Alternatively, try: mongo --port 27019
show dbs         <=== this shows what databases are available, for example wekan
use wekan       <=== this changes to use wekan database
show collections  <==== this shows what tables database has
db.users.find()     <==== this shows some users
db.users.count()    <==== this counts users
exit        <==== this exists MongoDB shell
```
If it is old source install,  could also be that is has different database name than wekan. In that case, you can use mongodump to dump that database only, and restore database with different name.

**Comment by xet7** [comment]
It is important to find correct database name to backup, and restore to new snap. If port or database name is not correct, it does not work.

**Comment by xet7** [comment]
For having SSL/TLS for WeKan, usually some webserver like Caddy/Nginx/Apache is used. Config examples are at https://github.com/wekan/wekan/wiki for those webserver.

Because there was already manual source install, most likely some of those webservers is already proxying to Wekan nodejs port. You see those config files usually at `/etc/nginx/...` or `/etc/apache2/...` . Also, that port number is on your server at `start-wekan.sh` or some service file like at `/etc/systemd/system/wekan.service` or `/etc/init.d/wekan`.

For example, if Nginx is at port 80 that redirects to port 443 TLS, then Nginx proxies TLS of https://wekan.example.com to local Wekan nodejs port, for example 4000. In that case, settings are:

```
sudo snap set wekan root-url='https://wekan.example.com'
sudo snap set wekan port='4000'
```
With this command, you see what Snap packages are installed:
```
$ sudo snap list

Name    Version    Rev    Tracking       Publisher     Notes
✓    snapd
wekan   5.71       1792   latest/stable  xet7          -
```
You see is Wekan running with this command:
```
$ sudo snap services

Service        Startup   Current     Notes
wekan.caddy    disabled  inactive    -
wekan.mongodb  enabled   active  -
wekan.wekan    enabled   active  -`
```
So both wekan.wekan (nodejs+wekan code) and wekan.mongodb (database) needs to be running. Snap also includes Caddy, it is possible to enable it and use it for TLS, or use some other webserver.

**Comment by xet7** [comment]
Difference between Snap and start-wekan.sh services is:

1) start-wekan.sh settings are uppercase underline, like `ROOT_URL='https://wekan.example.com`

2) Snap settings are lowercase minus, like `snap set wekan root-url='https://wekan.example.com`

It is important to get case etc correct.

**Comment by xet7** [comment]
Also, you should have at least automated daily backups https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
For prebuilt bundle on x64 server, it's possible to use it like this:
```
wget https://releases.wekan.team/wekan-latest-x64.zip

unzip wekan*.zip       # <==== this has directory "bundle"

start-wekan.sh
```
This requires, that in `start-wekan.bat` is correct path. For example, if bundle files are in directory bundle, then there should be in `start-wekan.sh`:
```
cd bundle
node main.js
cd ..
```

**Comment by xet7** [comment]
If you really would like to mess up your production server by building from source, it's possible this way.

You should clone Wekan source to new directory, so it has newest source code, newest build scripts etc. Build scripts do change when some dependency version changes.

```
git clone https://github.com/wekan/wekan

cd wekan

./rebuild-wekan.sh
```
There select 1 to install dependencies. Then:
```
./rebuild-wekan.sh
```
There select 2 to build Wekan. That generates files to `wekan/.build/bundle`. To run that, `start-wekan.sh` should have those ROOT_URL etc settings, and:
```
cd .build/bundle
node main
cd ../..
```

When installing Meteor, that .meteor directory with take something between 2 to 6 GB of disk space.

Installing dependencies installs many development packages, like compilers etc, that usually are not needed at production servers. Installing these can conflict with other versions installed at server already, messing up other software that is already installed to server.

Building Wekan downloads a lot of Javascript dependencies from atmospherejs.com and npmjs.com .  Building uses 100% CPU time for at least 10 minutes. This can slow down usage of production server a lot, if there are some users using that server at the same time. This is because final bundle has about 48000 files of HTML/CSS/Javascript etc.

**Comment by xet7** [comment]
Well, you could build from source on you laptop, and only transfer files of node.js, mongodb, bundle directory, and start-wekan.sh to your server. That way you would not need to install all development packages to production server.

**Comment by xet7** [comment]
I will close this issue, but please do not take it personally. You can still add comment to some closed issue, it's OK. I usually close issue where I have added so much information that someone probably can already figure it out. There are about 600 open issues. I'm just trying to help, in friendly way. And I need more people to ask more questions, so it's possible for me to help make something work.

**Comment by xet7** [comment]
Also, anyone can install Wekan in any way they like. While I like Snap, anyone can install bundle, install from source, Docker, etc in any way. YMMV.

**Comment by petkodimitrov1986** [comment]
Hello ,
I managed to install wekan with snap. Wekan was using the old (default) DB even after I restored using `mongorestore --maintainInsertionOrder -h 127.0.0.1 --port 27019 -d wekan /bin/dump/wekan`

Then I connected using the mongo command, and found my restored DB, wekan:

> show dbs
local  0.000GB
wekan  0.004GB

Then I attempted to set the right DB used using the command: 

snap set wekan mongo-url='mongodb://127.0.0.1:27019/wekan'

Then I restarted the mongo service, and it failed. 

```
mongo --port 27019
MongoDB shell version: 3.2.22
connecting to: 127.0.0.1:27019/test
2021-11-03T12:53:48.014+0200 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27019, in(checking socket for error after poll), reason: errno:111 Connection refused
2021-11-03T12:53:48.014+0200 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27019, connection attempt failed :
connect@src/mongo/shell/mongo.js:231:14
@(connect):1:6

exception: connect failed
```

Please let me know what should I do next to resolve this? Thank you.
