### ISSUE TITLE
Why did not have notifications center?

### ISSUE THREAD

**Issue by Graybobo** [wekan/wekan#415]
If someone @[me] or the card have an new comment, I did not received a notification message.

**Comment by mauzao9** [comment]
It's a feature not implemented yet, really hoping to see notifications going on to keep track of everything on the same board.

**Comment by NickGodspeed** [comment]
:+1:

**Comment by jseadragon** [comment]
Agreed, this would be great.

**Comment by floatinghotpot** [comment]
I'd like to have a try to implement this feature. 

I describe the detailed requirement as following:
1. A member can subscribe/unsubscribe a card, a list, or, a board. (technically, they will be added to a queue of notification watchers)
2. When the card is changed (assigned/unassigned, moved, deleted, or commented), the subscriber will see the activity in his/her notification center (technically, the activity id is added to the notification queue), user can clear the notifications (technically, remove the ids from queue).
3. The subscribe will also receive an email, with the message exactly same as the activity text. (if SMTP_URL is configured)

Is it the expected behavior?

**Comment by floatinghotpot** [comment]
After studying how github notification works, I've implemented a notification feature in this PR: #454

**Comment by xet7** [comment]
This is already merged to Wekan.
