### ISSUE TITLE
Adopt a release schema

### ISSUE THREAD

**Issue by andynd** [wekan/wekan#4387]
Stop doing **multiple** releases per hour, this is mind mind boggling insane.
Come up with any actual release plan like "once per month" or even better actual feature milestones with release candidates and testing.

Right now this makes wekan close to unuseable because every single release has to be checked if it fixes security issues.
This burns resources for no benefit.
There is no reason to create a release for every single commit or as you did right now, two releases in the same minute.

This is unprofessional at best.

PS: an actuall versioning scheme like [SemVer](https://semver.org/) would make this process a lot better as well.

**Comment by xet7** [comment]
@andynd 

But but... in WeKan 6.10 Snap did not build at all, because of new sudden requirement that included files need to be at "safe URLs" like GitHub, MongoDB website, etc. Download link to my build server did not work at all.

Yes, there are updates to dependencies very ofte, some of them are security updates, like for Node.js, some other dependencies, etc.

The reason is, whole world is very busy fixing entire supply chain of software from various attacks. During these corona and war times, everybody is at home and work (yes, paid criminal attack corporations) trying to break into everything.

When some new security fix is released, like for example by Microsoft, Drupal, etc, very soon after security fix release some criminals figure it out, and try to mass scan Internet and exploit everything.

If your WeKan is at Internet, you should use Snap version, that updates automatically immediately, and also setup at least daily backups https://github.com/wekan/wekan/wiki/Backup . Snap automatic updates are the best thing available.

I'm just trying to keep up, so that WeKan servers would stay safe. It's very important, please try to understand. This is the world we live in.

**Comment by ocdtrekkie** [comment]
@andynd Broken builds causing multiple releases is not uncommon for software. If you want to pick and choose Wekan releases, maybe wait until they have been out a day or so without a new release, as that is likely to be relatively stable. I never install Windows updates on day one either. ;)

**Comment by xet7** [comment]
Yes. WeKan development happens in waves or change storms. During those there are many new updates, features, changes, etc.

For example, WeKan v6.05 2022-02-07 was for many days. Then came WeKan v6.06 2022-02-26.

[WeKan v6.10](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v610-2022-03-02-wekan--release) is [Switch from CollectionFS to Meteor-Files](https://github.com/wekan/wekan/pull/4336). It is a very big change, affecting changes to all those different platforms that have different writeable file paths. It takes some releases to fix all corner cases.

**Comment by xet7** [comment]
Something being can happen for many reasons:
- Some build servers maybe do not work
- Some new requirement, like recent requirement for safe URLs only
- New release of Chrome, Firefox etc, where some browser feature has been removed, so some feature in WeKan does not work anymore
- Some dependency getting deprecated, so I need to find some replacement, try to get it working
- Some build server suddenly going offline, does not boot anymore, I need to reinstall it
- Etc, anything. There are very many moving pieces, and WeKan has many interdependent parts.

So we just keep fixing, until everything works with all supported webbrowsers, WeKan platforms like Snap/Docker/Source/Sandstorm/UCS, etc.

**Comment by andynd** [comment]
Thank you for confirming you do absolutly no testing before doing a release :/

**Comment by xet7** [comment]
Hmm, I'll think is there some way to improve this.

**Comment by xet7** [comment]
Hmm, I have an idea.

What if I say to everyone, that tries to hurry me up to develop some feature/fix/release, that it is unprofessional to hurry up? Would that be OK ?

**Comment by mfilser** [comment]
@andynd
I don't see any problems here. This is an open source project. Everyone is contributing for free, and especially the developers are investing a lot if time. For me, i did code for some month with many new features, and now i just hear complaining and that Wekan contributors are unprofessionell from you.

You are using a software for free, have a full featured Kanban Board with most or more features than other big software Kanban board solutions and are requesting for services you have to pay a lot of money every month.

@xet7 is doing more than his best, everything fine!

**Comment by urmel1960** [comment]
I am personally very happy about the extremely committed work of @xet7 and the other colleagues and I have had only a few problems so far - with e.g. commercial software and their "release cycles" there has always been considerably more effort and the developers there are usually not so responsive. 

@andynd 
No one is forced to always use the latest version. So if you don't feel comfortable with automatic updates, you can deactivate the automatic update via e.g. snap and stay on the desired version. This way it is possible to control your release jumps and also to do advanced tests on your own before you start using a release.

**Comment by xet7** [comment]
If there is something that does not work, I usually fix it same or following day.

Some days ago I looked Jira, how hard it is to update. It seems very complex and time consuming.

**Comment by jeroenstoker** [comment]
I look forward to every email of a new release. Also I don’t mind the updates because I’m using snap. Keep up the good work @xet7 💪🔥
