### ISSUE TITLE
Feature Request: A dummy Howto Installation with docker/portainer

### ISSUE THREAD

**Issue by corincorvus** [wekan/wekan#4391]
Hi,

i try to find a easy installation howto for Wekan. At the Moment i use Univention Wekan, but it crashes often in last time. I want to realize it with Portainer and Docker, but i dont know how.

I only need a ldap connection to my userdb.

Best Regards

**Comment by xet7** [comment]
@corincorvus

I don't know how Portainer would help? Can it import all settings from docker-compose.yml ?

There is docker-compose.yml at https://github.com/wekan/wekan . It needs ROOT_URL setup like mentioned at https://github.com/wekan/wekan/wiki/Settings

LDAP info is at https://github.com/wekan/wekan/wiki/LDAP

You can backup your WeKan like https://github.com/wekan/wekan/wiki/Backup or https://github.com/wekan/wekan/wiki/Repair-MongoDB

Info about various webservers like Nginx/Caddy/Apache is at https://github.com/wekan/wekan/wiki right menu.

I don't know how you can ask for both "LDAP" and "easy" at the same time. I don't know much about LDAP, it's not easy for me.

For my own servers, I prefer Snap Automatic Updates, link is at Download section of https://wekan.github.io , it is easier for me, because it installs updates automatically. But some other people prefer to test some specific WeKan docker tag version before deploying. Or some like to install without containers, like at https://github.com/wekan/wekan/wiki/Offline . Depends what you like.

**Comment by xet7** [comment]
If WeKan is crashing, does your UCS VM have enough RAM allocated to that VM ? Is it swapping? See with:

```
free -h
```

If it is swapping, please increase amount of RAM in VM.

**Comment by xet7** [comment]
Are you using UCS 4.4 or UCS 5 ? I would like to test does it really crash.

**Comment by corincorvus** [comment]
> Are you using UCS 4.4 or UCS 5 ? I would like to test does it really crash.

10 gb Ram, 8gb free,
UCS 5+

**Comment by corincorvus** [comment]
> @corincorvus
> 
> I don't know how Portainer would help? Can it import all settings from docker-compose.yml ?
> 
> There is docker-compose.yml at https://github.com/wekan/wekan . It needs ROOT_URL setup like mentioned at https://github.com/wekan/wekan/wiki/Settings
> 
> LDAP info is at https://github.com/wekan/wekan/wiki/LDAP
> 
> You can backup your WeKan like https://github.com/wekan/wekan/wiki/Backup or https://github.com/wekan/wekan/wiki/Repair-MongoDB
> 
> Info about various webservers like Nginx/Caddy/Apache is at https://github.com/wekan/wekan/wiki right menu.
> 
> I don't know how you can ask for both "LDAP" and "easy" at the same time. I don't know much about LDAP, it's not easy for me.
> 
> For my own servers, I prefer Snap Automatic Updates, link is at Download section of https://wekan.github.io , it is easier for me, because it installs updates automatically. But some other people prefer to test some specific WeKan docker tag version before deploying. Or some like to install without containers, like at https://github.com/wekan/wekan/wiki/Offline . Depends what you like.

I never work with a docker compose. Its completely new for me. Thank you for the Links. i will try today.

**Comment by luistiktok** [comment]
I have docker installation and also have portainer. To install wekan using portainer use the wekan docker compose located[ here](https://github.com/wekan/wekan/blob/master/docker-compose.yml).
If you have portainer installed and running. 
1- Log in into your portainer account.
2- Click the running docker container (local).
3- On the menu in the left click on "Stacks".
4- Click on "Add stack".
5- Put any name (ex. wekan).
6- Under "Web editor" paste the wekan docker compose text from the url above.

Hope it helps

Saludos!

**Comment by corincorvus** [comment]
> 

Hi,

i get an error, while paste the Docker compose Template:
     command: mongod --logpath /dev/null --oplogSize 128 --quiet

![grafik](https://user-images.githubusercontent.com/21257329/167398742-093b4c5b-0745-4ff3-8c9d-7bc659b84f30.png)
