### ISSUE TITLE
Snap didn't update to 6.12 automatically

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#4423]
Hi
When I check info for wekan snap I see:

channels:
  latest/stable:    6.09 2022-03-11 (1998) 167MB -
  latest/candidate: 6.09 2022-03-11 (1998) 167MB -
  latest/beta:      6.09 2022-03-11 (1998) 167MB -
  latest/edge:      6.12 2022-03-17 (2014) 178MB -
installed:          6.09            (1998) 167MB -

Snap do not update automatically because 6.12 is not a stable version?

Thanks!

**Comment by xet7** [comment]
Yes. Snap 6.12 causes restart loop on some installs, so I changed 6.09 to be newest stable.

**Comment by xet7** [comment]
Reason for restart loop could be snap-specific writable-path attachment setting that does not work properly yet. This happens only on some Snap systems that have existing data, not all.

**Comment by saschafoerster** [comment]
My snap installation is also hanging at 6.09. Can I do something about it?

**Comment by xet7** [comment]
@saschafoerster 

Snap WeKan Stable channel is at 6.09, because currently it kind of works.

You can test does some newer version work well enough:

https://github.com/wekan/wekan-snap/wiki/Testing-new-WeKan-Snap-versions

Current newest Snap and some other builds fail.

There is PR about some fix https://github.com/wekan/wekan/pull/4486 , to be included in some newer release.

**Comment by saschafoerster** [comment]
Alright, I am happy to hear, that you kept the stable version for snap users! I will test the other newer version on a different system then and sent you a report.

**Comment by xet7** [comment]
@Meeques 

Snap builds are still broken, I'm trying to figure it out. I will release newest Snap when I have fixed build error.

**Comment by Meeques** [comment]
@xet7 Thank you!

**Comment by ClaudiaK21** [comment]
> @Meeques
> 
> Snap builds are still broken, I'm trying to figure it out. I will release newest Snap when I have fixed build error.

Hi all, we are also still on Wekan 6.09 - auto updates fail, because Snap is still on 6.09.

How can we update Wekan to 6.30?

**Comment by xet7** [comment]
@ClaudiaK21 

But upgrade experience is not so great yet. I helped someone upgrade at paid support, that made me wish I had not helped, it did take so long time (4 hours per 400 GB backup or restore try, that 3 times)

And after upgrade, they complained:
- Attachments are not visible anymore
- Users can not be added to board
- API does not work
- Some migration process could also save temporarily all attachments to filesystem, taking more space, or running to risk of disk full (and that could cause MongoDB corruption)
- Etc, more info at https://github.com/wekan/wekan/issues/4578

Some upgrade info is here, if someone is brave enough to spend a lot of time:
https://github.com/wekan/wekan/issues/4505#issuecomment-1158380746

Yes sure, newest WeKan has newer Node.js etc security fixes.

I would like to improve that upgrade experience, so that there would be kind of in-place upgrade for any MongoDB version, by:

a) reading raw database files with MongoDB code directly or

b) using any MongoDB (or other database) version directly with WeKan (currently newest WeKan works only with MongoDB 5.x)

c) Testing some more about these ways to migrate.

Meanwhile:
- When we have not figured out how to get everybody to MongoDB 5.x, MongoDB released MongoDB 6.x with some additional features like searching encryped database - that feature may or may not be in Open Source MongoDB version.
- WeKan is using Node.js 14.x, and Meteor is trying to figure out how to upgrade to 16.x and remove fibers, when Node.js newest is actually 18.x
- And I'm not actually trying to migrate to newest MongoDB, I'm writing migrations to SQLite etc.
- Some customers would like WeKan to not use Websockets that are denied in their network, so that would mean not using some browserside Meteor code.
- For drag-drop WeKan currently uses JQuery Draggable/Droppable/UI, but that does not work well on Ubuntu Touch Morph browser (that is based on Qt/Chromium), so probably I would use SortableJS that seems to work better, or something else

**Comment by ClaudiaK21** [comment]
@xet7 thanks for this detailed answer and explanation, It is sad there are so many problems _(I don't really understand all the thechnical stuff of it)_ and I hope it will be solved in the near future and thanks for your huge efford. 

We'll be patient :)

**Comment by xet7** [comment]
@ClaudiaK21 

Thanks! I will release automatic etc updates when the upgrading experience is fast and easy and everything works well enough.

**Comment by xet7** [comment]
If someone would like to test newest changes directly from source, it's possible by:

1. Doing backup with mongodump https://github.com/wekan/wekan/wiki/Backup 
2. Cloning wekan repo:
```
git clone https://github.com/wekan/wekan
cd wekan
```
3. Uncommenting these lines https://github.com/wekan/wekan/blob/master/docker-compose.yml#L142-L144 (removing hashtag from start of those)
4. Changing ROOT_URL=http://192.168.0.100 (change your server ip address here)
5. Build and start wekan:
```
docker-compose up -d --build
```
6. Restoring backup with mongodump https://github.com/wekan/wekan/wiki/Backup

**Comment by xet7** [comment]
Well, today another upgrade experience, that could be improved in future:

1. Someone had hurry to get export of big board to JSON, for one problematic big board. He was using current stable Snap WeKan.
2. I noticed exporting big board works in candidate Snap WeKan, so I sent info how to upgrade to candidate. He only needed WeKan JSON export without attachments of that one big board. Currently candidate WeKan does not export attachments with JSON.
3. He upgraded to candidate, and was able to export big board JSON.
4. But it seems candidate started spamming candidate users via email about old cards content, missing attachments, etc, about 300 emails per user, via O365 email sending. Well, it seems email sending via O365 works, but it's kind of too much, there could be some email bug.
5. And some users noticed that there are missing attachments. Maybe attachments migrations did not have time to run yet, or something.
6. So he liked to go back to stable. So I informed, that stop wekan, delete all others but not Caddyfile from /var/snap/wekan/common/ , change to stable, mongorestore, start wekan.

What could be learned here, to improve upgrading experience? Maybe:

a) Go back to old WeKan stable code, where all attachments are visible, try to stay there without any database migrations, add some of newest changes there

b) With candidate, disable all email sending, and code those Notifications Settings

c) With candidate, Fix any bugs so that attachments are immediately visible

d) Some rewrite, because removing most code could also remove most bugs

e) Something else?

**Comment by DamianGuth** [comment]
Are there any updates on this? Wekan-Snap is like 40 versions behind :/

**Comment by xet7** [comment]
@DamianGuth 

Hmm, actually that's a good point. I'll get some coffee and think.

**Comment by ClaudiaK21** [comment]
> Are there any updates on this? Wekan-Snap is like 40 versions behind :/

Our IT currently has changed to Docker and now we are using the current version. 
Maybe only temporarily, until it works via Snap/meteor again.

**Comment by xet7** [comment]
Snap Candidate has newest WeKan, but it is missing more code and testing how to migrate Snap 6.09 to newest, trying to make it work well enough, so that I would not mess up about 10 000 WeKan Snap servers worldwide.

**Comment by mohammadZahedian** [comment]
> > Are there any updates on this? Wekan-Snap is like 40 versions behind :/
> 
> Our IT currently has changed to Docker, also because of security reasons and now we are using the current version of wekan finally. Maybe only temporarily, until it works via Snap/meteor again.

did you migrate to docker ?
how?

**Comment by ClaudiaK21** [comment]
> did you migrate to docker ?
> how?

I am sorry, but I don't know how our IT does it.

**Comment by DamianGuth** [comment]
> > > Are there any updates on this? Wekan-Snap is like 40 versions behind :/
> > 
> > 
> > Our IT currently has changed to Docker, also because of security reasons and now we are using the current version of wekan finally. Maybe only temporarily, until it works via Snap/meteor again.
> 
> did you migrate to docker ? how?

So i have not upgraded yet but i have moved wekan a few times so i think it will be pretty much the same.
This is what i have done in the past and what i will be trying when moving to docker soon: log into current mongo-db instance and backup the entire wekan table.

After that install wekan via docker, log into that mongo-db and restore the backup we created. Database should be good at this point. After that i will just move my current favicon to the new docker instance.

That was all i needed to do in the past. It moved all our users and everything we had in wekan.

Note: I have not tested it for moving from wekan snap 6.09 to the latest version.

**Comment by Sneeuwgors** [comment]
Thanks for the great work for the snap package of Wekan.
Is there any update as to when snap will update Wekan above version 6.09.0 ? Any ETA would be appreciated.

**Comment by xet7** [comment]
@Sneeuwgors 

I presume sometime this year.

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/4780
