### ISSUE TITLE
Bug: Custom logo and attachments broken

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#4468]
The [URL](https://enscim.com/.static/enscim-logo-square.svg) we used to specify the logo in the admin panel works thought.

![image](https://user-images.githubusercontent.com/2115696/162259695-6fc235cd-8bd3-48b7-bc5e-bd790d208599.png)

![image](https://user-images.githubusercontent.com/2115696/162259984-50b09d6c-926b-48c3-97ab-82fd10f35f1d.png)

**Comment by xet7** [comment]
@AuspeXeu 

Yes, at [WeKan v6.16](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v616-2022-04-06-wekan--release) was added [Fix Can't add attachments because of Content-Security-Policy](https://github.com/wekan/wekan/commit/0d9c37b0067d46669b7258bfff5dfc16d590e1d9), but that seems to be allowing only local content. That policy is defined here https://github.com/wekan/wekan/blob/master/server/policy.js#L6-L9 . There could be workaround, by adding that logo to public board, and linking to that logo at public board.

Another way would be to make more permissible policy. That policy package is here:
https://atmospherejs.com/meteor/browser-policy-content

That browser policy code is here, it has some available functions that can be used to define policy:
https://github.com/meteor/meteor/blob/master/packages/browser-policy-content/browser-policy-content.js

Not allowing remote content would maybe be too strict for someone. Some have wished to add some iframe to card, to combine to dashboard various sources, or even embed YouTube video. Cunrretly embedding YouTube video does not work, because WeKan uses dompurify https://github.com/wekan/wekan/blob/master/package.json#L32 that is at https://www.npmjs.com/package/dompurify to sanitize HTML/MathML/SVG to [prevent fieldbleed kind of security issues](https://wekan.github.io/hall-of-fame/fieldbleed/), so that Javascript saved to input fields does not run.

Alternatively, there could be settings about what origins to allow, per origin. Or, allow all origins.

Also Sandstorm has some features for content policy, for various restrictions for grains etc.

Additionally, at Firefox there https://github.com/wekan/wekan/issues/4461#issuecomment-1090685005

#3817 

ocdtrekkie what do you think?

**Comment by xet7** [comment]
These policy changes are not related to attachment changes.

**Comment by xet7** [comment]
Allowing embedding YouTube videos could maybe be scary. YouTube video pages usually have very many tracking scripts.

**Comment by xet7** [comment]
Hmm, I think having this strict policy could maybe cause various image, attachment etc stuff to be broken. I'll think how to fix this.

**Comment by ocdtrekkie** [comment]
So the URL is on a different domain or subdomain from where you host Wekan, I presume?

**Comment by xet7** [comment]
@ocdtrekkie 

Yes.

**Comment by AuspeXeu** [comment]
My board is running under projects.enscim.com while the logo is hosted on enscim.com in case this helps.

**Comment by Takalele** [comment]
@AuspeXeu 
i did hit the same issue as you, as workaround just host the logos local like described here https://github.com/wekan/wekan/wiki/Custom-Logo

BR
Takalele

**Comment by xet7** [comment]
Moved to here from #4467 

From @AuspeXeu

I am on version 6.17 - somehow this also broke our custom logo.
![image](https://user-images.githubusercontent.com/2115696/162259465-9730e170-aca3-454f-9c3b-1368ba9903e1.png)

**Comment by AuspeXeu** [comment]
@Takalele sounds more like a workaround than a solution 🙈
