### ISSUE TITLE
[Bug] Problems with attachments

### ISSUE THREAD

**Issue by AuspeXeu** [wekan/wekan#4474]
Is there a way to figure out what's wrong with these attachments? It seems that recently there was a change to the way files are handled and I wonder whether this is related. I see the following in my network panel of the firefox debugger.

![image](https://user-images.githubusercontent.com/2115696/162908146-e729fdc9-4994-48be-99a5-bf4ec602cc4f.png)

**Comment by mfilser** [comment]
Which version of Wekan are you running?

**Comment by xet7** [comment]
@AuspeXeu 

Are those same visible with Chromium/Chrome?

Is that Public or Private board?

What WeKan platform (Snap/Docker/Sandstorm/SourceBundle/UCS) ?

**Comment by xet7** [comment]
@AuspeXeu 

Did you use newest docker-compose.yml at https://github.com/wekan/wekan ? It has important changes for WRITABLE_PATH etc.

**Comment by AuspeXeu** [comment]
I have not set the `WRITABLE_PATH` variable. So I guess it should be whatever the default is.

**Comment by xet7** [comment]
@AuspeXeu 

Yes, you should add exactly like this::
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L149

And this:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L678

And this:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L730-L731

And have enough disk space, because all attachments files are written to that volume while migrating MongoDB => filesystem => MongoDB

**Comment by mfilser** [comment]
https://github.com/wekan/wekan/issues/4416#issuecomment-1094870824

https://github.com/wekan/wekan/issues/4393#issuecomment-1086800688

https://github.com/wekan/wekan/issues/4393#issuecomment-1086828359

**Comment by AuspeXeu** [comment]
I executed `ls` in the mentioned data folders and they're all empty. What now?

**Comment by gerroon** [comment]
@AuspeXeu Were you able to figure out what the problem was? I have the same issue, Wekan tries to load covers from some cdn stuff from the root of my domain , I serve it under a subfolder
