### ISSUE TITLE
Take a lot time to enter the board

### ISSUE THREAD

**Issue by Arbor0000** [wekan/wekan#4480]
Hello!
I used wekan in my project. It works well.
But while there are about 300 cards in one board, 3 labels in each card, 4 custom fields showed on miniCard, I met some problems that it takes a lot time to enter the board.(about 5~10 seconds), which is not friendly to users.
I have made some optimizations, but the results are not satisfactory.
Here is what i have made.
    1. Calculate custom fields showed on miniCard in server.
    2. Calculate labels showed on miniCard in server.
    3. No longer publish some fields I don't need on cards.
    4. Remove some templates I dont' need on client

Could you give me some advice? Thank you!

**Comment by helioguardabaxo** [comment]
Hi @Arbor0000 
Could you tried use http/2 on server. This protocol version have a prioritization schema (HTML, CSS and JS) and multiplex TCP connection. I don't use http/2 on Wekan server, but I am using in some sites and had good results.

@xet always recommend to use SSD or NVME:
https://github.com/wekan/wekan/wiki/Scaling

**Comment by helioguardabaxo** [comment]
Have you used the Lighthouse in Chrome devtools?
Lighthouse show some tips to improve performance.

**Comment by xet7** [comment]
@hatl 

I'm working on WeKan Multiverse version, that does not have that 5 MB of Javascript at frontend. It will have only small amount of HTML/CSS of currently visible small area of board. That is what some of my customers require, they have about 22 000 users using WeKan. It will be compatible with all modern and legacy browsers that support HTML4, like also Netsurf, Amiga AWeb, FreeDOS Dillo, Links, Elinks, w3m, etc.

Development of current Meteor WeKan will also continue, it already has all that drag drop etc fancy stuff.

**Comment by helioguardabaxo** [comment]
@xet7 @hatl 
And if drag and drop function could be toggleable for each board?
In this case, user would move a card in dropdown "List" in card details.
Will this improve performance?

**Comment by helioguardabaxo** [comment]
And if a view table as default for a big boards without badges and with pagination/filter?

**Comment by mfilser** [comment]
I think there is "some" to optimize while loading all minicards.
Drag / Drop is after the board is loaded, so this shouldn't be a performance killer.
Some day i will have a look at all the "loading code stuff", maybe there's a chance to get loading faster...

**Comment by xet7** [comment]
For Multiverse WeKan, it's for HTML4 webbrowsers that don't have any Javascript support at all, or very minimal Javascript support. AFAIK there is usually no drag drop possible. Those HTML4 webbrowsers can not view current Meteor WeKan at all, it's just too much CSS/JS. Multiverse WeKan is mostly going to additional platforms where Meteor/Node.js/MongoDB is not available.

For Multiverse WeKan:
1. Minimize everything, so that all webpages are minimal HTML/CSS/images
2. Have pagination. Browsing big board is similar like changing to view different cell at spreadsheet, left/right/up/down, or like in text adventure north/south/east/west. Showing screenful of data at a time.
3. Serverside will run also on platforms where Meteor/Node.js/MongoDB is not available
4. Add all current and paid In Progress features
5. (Maybe add optional Javascript drag drop extras)

For Meteor WeKan:
1. Try to fix Snap builds etc
2. Try to upgrade to newest Meteor
3. Try to modify PubSub to only load visible cards browserside, and that database queries would be done mostly serverside.

**Comment by Arbor0000** [comment]
I developed Wekan on the Intranet, so it was difficult to update the environment of wekan.
I have tried the following optimizations.
    1.PubSub only  subscribe 4 cards in each labels, the left cards subscribe after that
    2.Publish the cards linked in other board while I clicked the miniCard.
    3.Publish the count of the cards in each label together with label.
It worked, but I ran into some other problems 
    1.The swimlaneHeader and listHeader was rendered after the miniCard, which looks like loading not smoothly, and I find it was caused by list.count(), so I did the operation 3 above. But it didn't quite solve the problem, sometimes it rendered right sometimes it not. Maybe there some ohter reasons but I haven't found,,,

**Comment by xet7** [comment]
@Arbor0000 

Yes. Currently in Meteor WeKan:
- All about 105 translations are in browserside Javascript file
- It takes some seconds until all Javascript has run, and language changes to selected language
- All cards are loaded browserside, for big boards this is too much, browser crashes
- When there are realtime update operations for larger amount of users, there is very much traffic between browser and server, so it is too much also for serverside CPU usage, and browserside too much data
- Having so much of features Javascript-only makes boards not visible in those browsers that don't support Javascript, or have Javascript disabled for security reasons, like for example preventing rowhammer Javascript exploits etc. Many browsers have increased protections but I have not checked are those enough.
- There could be some ways to move translations to serverside, like is maybe done at upgrade-meteor branch
- There are also ways to move some code to serverside and lazy load it, like was made with exceljs code
- It could be maybe possible to check which swimlanes, lists etc are visible, and start their subscriptions, and stop subscriptions of non-visible ones
- It could maybe be possible to change so that not all Javascript, CSS etc is loaded at every page, but instead they would be in page- or theme specific files. Currently build process combiles all browserside Javascript to one file, and CSS to one file.
- Anyway, there will be new versions of Meteor WeKan, because it is currently existing full-featured version of WeKan.

In Jira and Kanboard:
- There is also too much loaded to browserside, and too big part of board shown at once

In Multiverse WeKan:
- There is minimal HTML/CSS. Although, it takes some time to get up-to-speed with amount of features etc.
- I'm trying various backends, like some parts of current Meteor WeKan backend, and some other backends, to see which one would work best.
