### ISSUE TITLE
Calendar view logic

### ISSUE THREAD

**Issue by edkedk99** [wekan/wekan#4511]
I am using the calendar view to manage my cards date and time. Whatever date I input, it shows always the end date plus 1 hour. Is this 1 hour time lapse hard coded on Wekan, so I can not modify it, or there is somewhere I can set this default value?

Is there a reason wekan to be configured to be used only with 1 hour time lapse. I would expect the time lapse showed in calendar to be from start to end date (and time).

**Comment by helioguardabaxo** [comment]
Hi, @xet7 and @edkedk99 !

I create a example to clarify this bug.
![image](https://github.com/wekan/wekan/assets/24301085/561935b3-c53a-4fdc-9ee2-a35a1fc6bbfe)

Current version of Calendar view looks like this:
![image](https://github.com/wekan/wekan/assets/24301085/63c71125-e81a-4e15-b277-6a7e6aaebe5e)
Just due date are considered and displayed.

The correct visualization should this:
![image](https://github.com/wekan/wekan/assets/24301085/9e10904e-a427-443d-867e-e274fab1eda6)

Is my reasoning correct?

**Comment by xet7** [comment]
@helioguardabaxo 

How it should work, is that maybe for example:
- all those 4 different dates should be visible at card
- it would be possible to edit dates at calendar, maybe by click edit popup or drag drop
- it would be possible to undo or redo changes
- or set permissions can Normal user edit date or not. BoardAdmin can I presume.

There could be other WeKan issues about calendar.

There could also be some CalDav scripts in PHP and Python related to syncing board events with some calendar, that kind of feature option should be added directly to WeKan.

Also look at how works:
- FullCalendar various examples
- Calendar in other software, like Kanboard, Nextcloud, Google Calendar, Outlook Calendar etc, can they they show something similar, is it possible to sync or sync+edit ?

Anyway, if you like to add or fix something in WeKan Calendar, try to add something that kind of makes sense.

Some forks of FullCalendar also have MIT licensed Gantt Chart, I don't know are those forks maintained or up-to-date enough, or is it just best to use MIT-licenced Gantt component mentioned in newest comments of Gantt issue.

**Comment by xet7** [comment]
If someone changes date at calendar, that change should be saved to card notifications history, and related triggers for webhooks lauched.

Undo/redo of date could list previous/next dates at card history.

Also to card history save, who modified card, was modification at card or at calendar.

**Comment by helioguardabaxo** [comment]
Would it be opportune to update fullcalendar to the most current version?

**Comment by xet7** [comment]
@helioguardabaxo 

Yes, it would be very nice to have newest fullcalendar. I have also updated many other dependencies.

**Comment by helioguardabaxo** [comment]
@xet7 
Currently fullcalendar is a deprecated meteor package.
Which better way to update this dependency?
Try to update this meteor package or install npm package?

**Comment by xet7** [comment]
@helioguardabaxo 

Maybe copy meteor package to wekan/packages , change name in package.js like wekan-calendar , meteor add wekan-calendar , and update files

**Comment by DimDz** [comment]
After latest updates, creating card via calendar view is not possible. Will try to see what changed and maybe fix it.

**Comment by helioguardabaxo** [comment]
@DimDz 
Would be not about bootstrap dependency?
https://stackoverflow.com/questions/25757968/bootstrap-modal-is-not-a-function

**Comment by xet7** [comment]
@helioguardabaxo @DimDz 

Bootstrap is the problem. Best would be, if that create card popup were changed to not use bootstrap.

There was bootstrap 3 in WeKan, used by WYSIWYG editor summernote #5012 that uses atmospherejs.com package `easylogic:summernote` . But boostrap 3 required older vulnerable jQuery. I updated to newest jquery (in newest, it is spelled `jquery`, not the old `jQuery`) and removed old boostrap 3 and old summernote. There is newest summernote at https://github.com/summernote/summernote that can use bootstrap 4 (or maybe even boostrap 5? or maybe even without boostrap?) but I did not find is that bug of using newest jquery now fixed.

I don't know is this vulnerability yet fixed in summernote https://github.com/summernote/summernote/pull/3782 . I'm looking for some editor that does not have vulnerabilities.

For preview PDF, @VidVidex fixed PDF preview in [WeKan v6.99.7](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v6997-2023-07-11-wekan--release) so that is does not require bootstrap.

Currently in WeKan repo `npm audit` does not show any vulnerabilities, because jquery was updated etc. I would like it to stay that way, to not add vulnerabilities.

**Comment by xet7** [comment]
Also, removing summernote and bootstrap 3 fixed #4994

**Comment by helioguardabaxo** [comment]
@xet7 
Thanks to clarify this point.
I tried to update fullcalendar from 3.8.0 to 3.10.5. It's works fine.
Is not the latest version, but have some fixes and added Bootstrap 4 support.
Is it useful to send as PR?

**Comment by xet7** [comment]
@helioguardabaxo 

Wait that I have checked at merged https://github.com/wekan/wekan/pull/5014 that changes a lot in WeKan, and released WeKan v7.00 , then add your changes with code style of that https://github.com/wekan/wekan/pull/5014 and send your PR. Thanks!

**Comment by DimDz** [comment]
Now we have to update fullcalendar so it can show once again the cards at calendar view.

**Comment by helioguardabaxo** [comment]
@DimDz 
Are due date days appear in calendar view to you after 7.0.0 update?
