### ISSUE TITLE
Trying add existing user to a board - no result show 

### ISSUE THREAD

**Issue by alsace68347** [wekan/wekan#4530]
* Did you test in newest Wekan?: yes 
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? :yes 
* Operating System: linux 
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker 
Wekan version : since 6.23 =>  6.26. works with 6.22 and previous

Hello, 
since wekan 6.23 when i try to add existing user to board nothing appears. In wekan 6.22 it's works. 
docker container logs same error  after each key pressed for search user (by name, id ....)

 ```

Exception from sub users/easySearch id qgMCEGCikhMf5b9ox MongoInvalidArgumentError: Argument "options" must not be function
    at Collection.aggregate (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:371:19)
    at packages/meteor.js:311:21
    at Collection.Mongo.Collection.aggregate (packages/meteorhacks_aggregate.js:39:46)
    at Object.search (packages/matteodem_easy-search.js:549:37)
    at Subscription.<anonymous> (packages/matteodem_easy-search.js:123:39)
    at packages/matb33:collection-hooks/server.js:33:71
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
    at packages/check/match.js:118:15
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1882:18)
    at packages/ddp-server/livedata_server.js:1107:9
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Subscription._runHandler (packages/ddp-server/livedata_server.js:1106:60)
    at Session._startSubscription (packages/ddp-server/livedata_server.js:917:9)
    at Session.sub (packages/ddp-server/livedata_server.js:673:12)
    at packages/ddp-server/livedata_server.js:603:43


```

**Comment by xet7** [comment]
Thanks! I'll check what happens here.

**Comment by lukasjelonek** [comment]
For me the bug is a show stopper, so I looked into it.

I checked the code base. It seems that this might be a problem with easysearch. There is only a single usage of `initEasySearch` in the whole codebase, and thats in users, so nothing else should be affected.

Unfortunately I am not familiar with meteor and easysearch, so at the moment, just looking at the wekan code, I don't see the rationale why it broke (yet). But I will investigate it further.

**Comment by lukasjelonek** [comment]
What works is to enter the username or the email-address in the text field and then to click on the invite by mail button.

So the add member to board feature does work, but the search/list and select feature for users does not work.

**Comment by freggel2401** [comment]
I do have in fact the same issue. I use Wekan for quite some time now without any issues. In fact I tried creating teams and organizations right before figuring out this issue. Not sure if this is relted to the bug or if it really just started by the update. So in case it is not reproducable just try to start by an empty installation and create a team and an organiziation. In case it helps to find the problem here the stack trace:

wekan-app  | Exception from sub users/easySearch id "ID REMOVED BY ME" MongoInvalidArgumentError: Argument "options" must not be function
wekan-app  |     at Collection.aggregate (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:371:19)
wekan-app  |     at packages/meteor.js:311:21
wekan-app  |     at Collection.Mongo.Collection.aggregate (packages/meteorhacks_aggregate.js:39:46)
wekan-app  |     at Object.search (packages/matteodem_easy-search.js:549:37)
wekan-app  |     at Subscription.<anonymous> (packages/matteodem_easy-search.js:123:39)
wekan-app  |     at packages/matb33:collection-hooks/server.js:33:71
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
wekan-app  |     at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
wekan-app  |     at packages/check/match.js:118:15
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
wekan-app  |     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
wekan-app  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1882:18)
wekan-app  |     at packages/ddp-server/livedata_server.js:1107:9
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
wekan-app  |     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1106:60)
wekan-app  |     at Session._startSubscription (packages/ddp-server/livedata_server.js:917:9)
wekan-app  |     at Session.sub (packages/ddp-server/livedata_server.js:673:12)
wekan-app  |     at packages/ddp-server/livedata_server.js:603:43

**Comment by adolfombarros** [comment]
I have the same issue with v6.27 and v6.25

**Comment by mconsoir** [comment]
I have the same issue with v6.28

**Comment by xet7** [comment]
@alsace68347 

About this, and others, I'm trying to figure it out https://github.com/wekan/wekan/issues/3796#issuecomment-1173874036

Also any help with figuring these out is very welcome. It's just reading code, trying is it bug in WeKan code, or some new bug in some webbrowser, adding some `console.log(variable);` statements, building WeKan like at https://github.com/wekan/wekan/wiki/Emoji  (preferably on Linux, because building on macOS results to more bugs).

**Comment by mconsoir** [comment]
Still the same problem...
WeKan ® Version | 6.29.0
-- | --
Meteor version | 2.7.3
Node version | 14.20.0
MongoDB version | 5.0.9

**Comment by xet7** [comment]
@mconsoir 

Yes, this issue is still open, this is not fixed yet. I try to figure this out. 

From previous WeKan release is one month, and there has been other fixes, that's why this release:
https://github.com/wekan/wekan/releases/tag/v6.29

**Comment by DoktorScience** [comment]
I'm also encountering this issue. I don't know how to go about writing the code for this one, but here's a few suggestions.

It seems the following bit is causing the error, try commenting it out: https://github.com/wekan/wekan/blob/master/models/users.js#L532-L536

I would have expected the user search to be implemented similarly as `searchBoards` or `searchSwimlanes` from https://github.com/wekan/wekan/blob/master/models/boards.js.
That is, relying on the [Mongo.Collection find](https://docs.meteor.com/api/collections.html#Mongo-Collection-find) method.

**Comment by GuiGuiSoft** [comment]
Hello, same issue here with version 6.30

**Comment by xet7** [comment]
Hmm, it looks like this. I'll try.

https://github.com/meteor/meteor/discussions/11749#discussioncomment-2031425

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/4623
