### ISSUE TITLE
Wekan fails to get MongoDB server version

### ISSUE THREAD

**Issue by simon816** [wekan/wekan#4596]
### Server Setup Information

* Did you test in newest Wekan?: Yes (6.30.0)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? Yes
* Operating System: Ubuntu 18.04.6 LTS
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache
* Node.js Version: v14.18.3
* MongoDB Version: 3.6.3
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Firefox

#### Reproduction Steps

1. Configure wekan to use mongodb without access to the "serverStatus" command
2. Open the /information page as an admin user
3. Observe "MongoDB version" as "unknown"

#### Logs

The exceptions are suppressed, so I edited it to add `console.error(e)` here: https://github.com/wekan/wekan/blob/v6.30/server/statistics.js#L76

As expected, we fail on the first attempt due to permission error:
```
 MongoServerError: not authorized on wekan to execute command { serverStatus: 1, lsid: { id: UUID("1bb8fb42-a34a-4b67-b2cc-4391c8656f7b") }, $db: "wekan" }
```

However, on the fallback method, the `mongo` variable is missing
```
ReferenceError: mongo is not defined
    at MethodInvocation.getStatistics (server/statistics.js:90:15)
```

**Comment by mfilser** [comment]
As far as i know Wekan requires MongoDB 5.
MongoDB <= 4 will not work.

**Comment by simon816** [comment]
Well it's been working for my use-case for the past 3 years at least :stuck_out_tongue:

**Comment by xet7** [comment]
Well, that's just because we spent one year trying to upgrade WeKan dependencies like Meteor etc to newest. Currently Docker WeKan works only with MongoDB 5.x, using docker-compose.yml from https://github.com/wekan/wekan . If I sometime figure out how to support also older MongoDB versions, well, it depends do I get it working or not.

**Comment by mfilser** [comment]
I thought Meteor requires MongoDB 5, or?

**Comment by xet7** [comment]
@mfilser 

Yes, newest Meteor only works with MongoDB 5, because all MongoDB queries in both Meteor and WeKan have been changed to use MongoDB 5 syntax.

**Comment by xet7** [comment]
But problem is, that some WeKan users may not have enough disk space for migrating to newer MongoDB version, like for doing automatic mongodump/mongorestore, so there is risk of losing data. If MongoDB runs out of free disk space, it will corrupt database. That's why I'm looking at various ways to use any version of MongoDB (or other databases).

**Comment by simon816** [comment]
Looks like the missing variable is not fixed yet

**Comment by simon816** [comment]
Sorry for being a bother, the above commit does not appear to fix it.
To fix you just need to put `const { mongo } = MongoInternals.defaultRemoteCollectionDriver();` on line 89, which will bring the variable into scope.

**Comment by xet7** [comment]
@simon816 

Thanks a lot !

Point with any bug is, keep trying, until it is fixed. Usually features and fixes takes many tries to get right, it's normal.
