### ISSUE TITLE
Hard to drag cards into very long columns and rows

### ISSUE THREAD

**Issue by kentonv** [wekan/wekan#476]
When dragging a card into a column from some other column, it seems the target column will only accept the card if it is being placed high enough in the column that it would be visible when the column is scrolled to the top -- that is, it is being placed within the first "page" of the column. If the column is very long and has been scrolled down by more than a full "page", it is not possible to drag cards into it from other columns. The cards within the column can be reordered, though, and so it is possible to move a card into the top of the column first then drag it down, but this is tedious.

**Comment by mquandalle** [comment]
Yes, this is the vertical counterpart of the horizontal #443.

**Comment by kentonv** [comment]
Hmm, this seems a little bit different from #443. I'm not asking for the columns to scroll while I'm dragging. I'm just trying to move a card from one column into the currently-visible area of another column, but it simply doesn't work if that other column's currently scroll position is beyond its first page.

**Comment by mquandalle** [comment]
Ah ok, thank you very much for clarifying. I’ll see how I can debug that (generally speaking DOM mutating sortable or Dnd libraries are very difficult to tweak correctly).

**Comment by jods4** [comment]
:+1: This bug is annoying me like crazy. 
If you have a long column and it is scrolled down enough (past the fold/screen height) it does not work as a drop target anymore.
Repro in Chrome and Firefox.

**Comment by AlexanderZobkov** [comment]
We are experincing issue when dragging/reordering  cards within a very long column (list).  It does not scroll vertically (up and down) if we want move a card within the same column to a possition that is "off-screen".  

This issue tells about a bit diffrent use-case, Does it makes sence to create a new issue?

**Comment by xet7** [comment]
@AlexanderZobkov 

No, don't create new issue. I did change issue name to have both rows and columns mentioned.

**Comment by dpoznyak** [comment]
Done some investigation for columns:
 * caused by `.js-minicards` height driven by screen height, not content height; hence when it scrolls out of the view, dropping becomes impossible (it's a target of sortable's `connectWith`)
 * which in turn is caused by `.list-body` being flex

Just removing flex from `.list-body` fixes the issue; looks like there's no real need for it to be flex?
```css
.list-body {
    overflow-y: auto;
    padding: 5px 11px;
}
```

Happy to PR if this looks right.
<details><summary>Repro:</summary>
1. Add cards to the list so that scrolling appears (e.g. if 10 cards are usually visible, add 20)
1. Scroll 
1. Try to drag a card to the section of the list not originally visible

Expected: drops normally
Actual: 
* unable to drop (placeholder not appearing)
* Debug: `.js-minicards` scrolls out of the view
</details>

**Comment by xet7** [comment]
@dpoznyak 

If you find good fix, please add pull request to Wekan devel branch. Thanks!

**Comment by xet7** [comment]
Dragging small distances works.

Dragging longer distances is easier, if you zoom out board, so destination is visible.

To get more precise moving or card, click card hamburger menu, and move card.
