### ISSUE TITLE
API /users/register does not work in docker container - HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by WassimDhib** [wekan/wekan#4774]
Hi

I just installed the wekan v6.60 ( docker compose method)

The API /users/register does not work (it was perfectly working in previous v6.20)

Documentation says that this operation does not require authentication.

```
curl -X POST -H 'Content-Type: application/json' -H 'Accept: */*' http://localhost:80/users/register -d '{"username":"testuser", "password":"testpassword", "email":"testuser@domain.com"}'


< HTTP/1.1 403 Forbidden
< Cache-Control: no-store
< Pragma: no-cache
< Date: Tue, 13 Dec 2022 10:33:15 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
<
* STATE: PERFORM => DONE handle 0x203d0738; line 1980 (connection #0)
* multi_done
* Connection #0 to host localhost left intact
* Expire cleared
```

**Comment by gustavengstrom** [comment]
@xet7 the fix is not working for me. The API /users/register works fine in v6.20 but not in the latest v6.67. Hence problem as described by @WassimDhib above remains.

**Comment by xet7** [comment]
@gustavengstrom 

Did you try api.py at https://github.com/wekan/wekan ?

**Comment by xet7** [comment]
@gustavengstrom 

https://github.com/wekan/wekan/blob/master/api.py#L43

**Comment by bastianwenske** [comment]
This issue seems still present, even in the current versions of WeKan.
I was able to verify that everything was functioning properly in v6.22, so it is possible that this bug was introduced in v6.23.

I've tested with the latest version v7.44 (`quay.io/wekan/wekan:v7.44`)
See what I've tried to reproduce, the registration is not working via the API. 
```
curl --verbose -H "Content-type:application/json" \
      http://localhost:8080/users/register \
      -d '{ "username": "myusername", "password": "mypassword", "email": "my@email.com" }'
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> POST /users/register HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: */*
> Content-type:application/json
> Content-Length: 79
> 
< HTTP/1.1 403 Forbidden
< Cache-Control: no-store
< Pragma: no-cache
< Date: Sat, 04 May 2024 20:55:47 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
```

**Comment by xet7** [comment]
@bastianwenske 

Does api.py newuser not work?

https://github.com/wekan/wekan/blob/main/api.py

**Comment by bastianwenske** [comment]
@xet7 the [newuser function](https://github.com/wekan/wekan/blob/main/api.py#L351) within the api.py script is using the [user create]( https://github.com/wekan/wekan/wiki/REST-API-User#user-register) endpoint (/api/users) callable by a Wekan admin, whereby this issue is referring to the [registration endpoint](https://github.com/wekan/wekan/wiki/REST-API-User#user-register) (/users/register) any user can call according to the sign-up page (/sign-up) available in Wekan Web UI.

The registration endpoint worked until version v6.22. So it seems that v6.23 introduced a bug, as reported in this issue.

**Comment by jsbrain** [comment]
I'm facing the same problem in v7.94. How is this still an issue?

**Comment by xet7** [comment]
@jsbrain 

This is still an issue, because nobody has been interested to send pull request to fix this.

**Comment by xet7** [comment]
This already works.

**Comment by AhmedLukman** [comment]
This still reproduces on current `main` at the time of testing (`feda5fc72`): `POST /users/register` returns HTTP 403 even when Wekan's `disableRegistration` setting is false because the route checks `Accounts._options.forbidClientAccountCreation`, which the useraccounts package keeps enabled for its browser sign-up flow.

I opened #6598 with the verified fix: https://github.com/wekan/wekan/pull/6598
