### ISSUE TITLE
ldap login not working - wrong binding

### ISSUE THREAD

**Issue by q16marvin** [wekan/wekan#4827]
## Issue
Auth again LDAP is not working

### Server Setup Information
* Did you test in newest Wekan?: yes (6.72.0)
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? sure
* Operating System: Linux (5.10.0-20-amd64)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node.js Version: 14.21.2
* MongoDB Version: 5.0.14
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? actual firefox

### Problem description

user: CN=erik.test,OU=lpg2,OU=agents,DC=gut,DC=contact

binding from logs: sAMAccountName=erik.test,dc=gut,dc=contact

correct would be: sAMAccountName=erik.test,OU=lpg2,OU=agents,dc=gut,dc=contact

###Logs:

> [INFO] Init LDAP login "erik.test"
[WARN] Lookup for unset variable: INTERNAL_LOG_LEVEL
[WARN] Lookup for unset variable: LDAP_USER_ATTRIBUTES
[INFO] Init setup
[INFO] Connecting "ldap://192.168.62.30:389"
[DEBUG] connectionOptions{
  url: 'ldap://192.168.62.30:389',
  timeout: 10000,
  connectTimeout: 10000,
  idleTimeout: 10000,
  reconnect: true,
  log: Logger {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _level: 30,
    streams: [ [Object] ],
    serializers: null,
    src: false,
    fields: {
      name: 'ldapjs',
      component: 'client',
      hostname: '0c54a0acb35e',
      pid: 1
    },
    [Symbol(kCapture)]: false
  }
}
[INFO] LDAP connected
[INFO] Binding with User "sAMAccountName=erik.test,dc=gut,dc=contact"
[ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
[INFO] Fallback to default account system:  {
  "username": "erik.test"
}
[DEBUG] Fallback options:  {
  "user": {
    "username": "erik.test"
  },
  "password": {
    "digest": "3bb18864abf5ea83930cc9a174747d88ba595d90e92936bcdc11e4567f6164b8",
    "algorithm": "sha-256"
  }
}

**Comment by ManZosh** [comment]
I came here to wekan/issues to post exactly this!!!

Ever since updating from WeKan **_6.62_** to **_6.74_**, we keep receiving the following:
`wekan.wekan[12153]: [ERROR] InvalidCredentialsError: 80090308: LdapErr: DSID-0C090434, comment: AcceptSecurityContext error, data 52e, v4f7c`

The rest of our config is as follows:
**Meteor** v2.10.0
**Node** v14.21.2
**MongoDB** v6.0.4

Nothing else changed in our environment, so something in one of the recent releases is what's now breaking LDAP. Our WeKan's LDAP is configured to a Windows Server 2022 AD as well.

**Comment by xet7** [comment]
@ManZosh @q16marvin 

Is this related?
- https://github.com/wekan/wekan/issues/4754
- https://github.com/wekan/wekan/pull/4760

I don't have my own LDAP server. I depend on other WeKan contributors that can test WeKan LDAP code with their LDAP server, and [send PRs](https://github.com/wekan/wekan/wiki/Emoji) for changes.

**Comment by ManZosh** [comment]
Hi @xet7 

For #4754 is this specific to Docker deployments? I should've mentioned that our specific deployment is via Snap on Ubuntu Server v20 LTS.

We run many other applications and services all with their authentication leveraging LDAP, so we're pretty familiar with all the paths and syntax. We also use _ldp.exe_ on Windows and _ldap-utils_ Red Hat Linux so definitely lemme know if we can help test something or verify any LDAP search syntax.

**Comment by xet7** [comment]
@ManZosh 

It is specific to:
- WeKan v6.74 at Docker
- WeKan v6.74 at Snap Candidate (MongoDB 6) and Snap Beta (MongoDB 5)

That #4754 is related to logging in with LDAP, are usernames, email addresses etc escaped properly, having DEBUG=true in docker-compose.yml

There are also many other open LDAP issues at:
- https://github.com/wekan/wekan/issues
- https://github.com/wekan/ldap/issues
- Also PR at https://github.com/wekan/ldap/pulls

For each of those, they would need:
- Info is there some bug, and PR to fix it to https://github.com/wekan/wekan/pulls
- If there is no bug anymore, info about that issue can be closed
- Check new LDAP sync code that does cleanup properly https://github.com/wekan/wekan/blob/master/ldap-sync/ldap-sync.py , maybe do related changes to Javascript code at https://github.com/wekan/wekan/tree/master/packages so that [WeKan LDAP users sync](https://github.com/wekan/wekan/pulls?q=is%3Apr+ldap+sync+is%3Aclosed) would work properly.

Thanks for any help anyone can provide.

**Comment by ManZosh** [comment]
Hello @xet7, hope you've been well!

Just curious, is it possible to cleanly downgrade from WeKan **v6.74** back to **v6.62**?

We have internal employees + 3rd party consultants all collaborating on an ERP implementation & migration and this LDAP issue is proving to be pretty inconvenient right now.

However when I run `sudo snap list wekan --all` it doesn't seem like prior ones are available. Or maybe I'm misunderstanding this Snap function?
```
Name   Version  Rev   Tracking          Publisher  Notes
wekan  6.75     2368  latest/candidate  xet7       disabled
wekan  6.76     2375  latest/candidate  xet7       -
```

**Comment by xet7** [comment]
@nebulade

Do you have LDAP login working? Do you have any idea what is bug here?

**Comment by xet7** [comment]
@ManZosh 

If you really would like to spend time downgrading to old more buggy and more vulnerable version, you could backup Snap and restore to Docker. But it would be more helpful that LDAP users would help to fix this bug.

- https://github.com/wekan/wekan/wiki/Backup
- https://github.com/wekan/wekan/blob/master/docker-compose.yml#L125

**Comment by xet7** [comment]
@ManZosh 

Downgrading has not been tested, I don't know does it work at all.

**Comment by nebulade** [comment]
To be honest we at Cloudron haven't noticed any regression on the LDAP side in wekan. We are updating it with every version and such an LDAP error would have been noticed and caught by the integration tests. So I suspect this is a misconfiguration mostly then. LDAP is sometimes non-trivial to configure.

@ManZosh and @q16marvin maybe you can share your LDAP env variables to compare?

**Comment by ManZosh** [comment]
@nebulade We now run a freshly promoted WinServer2022 DC and we'll soon be demoting a pre-existing WinServ2012R2 DC that previously ran much of our WinDomain. WeKan was previously LDAP'd to the 2012R2 DC. Since updating to v6.74 we haven't been able to get WeKan to work on _any_ of our DCs which host an AD catalog.

Attached is a long bash command that gets all the available Snap WeKan LDAP config options. Below is the result:
[getSnap-LDAP-Config.txt](https://github.com/wekan/wekan/files/10840601/getSnap-LDAP-Config.txt)
```
ldap-enable: true
wekan-default-authentication-method: ldap
ldap-port: 389
ldap-host: 2012dc.blockhouse.com
ldap-basedn: OU=Users,DC=Blockhouse,DC=blockhouse,DC=com
ldap-login-fallback: false
ldap-reconnect: true
ldap-timeout: 10000
ldap-idle-timeout: 10000
ldap-connect-timeout: 10000
ldap-authentication: true
ldap-authentication-userdn: CN=lookupUser,OU=Services,OU=Users,DC=Blockhouse,DC=blockhouse,DC=com
ldap-authentication-password: censored!
ldap-log-enabled: true
ldap-background-sync: true
ldap-background-sync-interval: every 1 hour
ldap-background-sync-keep-existant-users-updated: true
ldap-background-sync-import-new-users: true
ldap-encryption: false
ldap-user-search-field: sAMAccountName
ldap-username-field: sAMAccountName
ldap-fullname-field: cn
```
We've already spent a ton of hours troubleshooting this and have these same LDAP options already configured and working on other FOSS apps like SnipeIT, osTicket, & EspoCRM. So that's kinda why we started pointing at the WeKan update as the potential issue.

Anything stick out to you or any ideas we can look into? We were planning to begin packet tracing this week.

**Comment by ManZosh** [comment]
Ok.... Atleast for my situation, we're all-good. Our probably was we accidentally used a third additional **_DC=_** in our UserDN... It should only be DC=tld,DC=com!
Big apologies for the commotion!

**Comment by nebulade** [comment]
ah nice, glad it worked out in the end! These settings are often quite hard to get right with little info pointing to those misconfigured items.

**Comment by karokarov** [comment]
When connecting to AD via LDAP usually it helps to use email format of connecting user rather than DN format.
Use: "**ldap-authentication-userdn: lookupUser@domain.com**"

If anybody can comment why it works like this, it would be much appreciated. :)
