### ISSUE TITLE
Mermaid js

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4841]
There seems to mermaid included 2 times somehow. It could be mermaid bug, or something else.
I try can I find a way to remove duplicate included mermaid, or some other way to get Meteor WeKan building.
Probably by going back to older working git commit of WeKan, and adding some newer additions back.
Or making some more minor or major changes to code.

Sure someone could help, if they have time, although I probably will figure this out in near future.

**Comment by xet7** [comment]
I fixed it, now building Meteor WeKan works.

**Comment by sharky98** [comment]
Hello, I was going over the features documentation and found out that Wekan supported [Mermaid](https://github.com/wekan/wekan/wiki/Mermaid-Diagram) at some point, but dropped support after Mermaid hit `v10.0.0` due to bugs created in Wekan.

By searching for Mermaid issues in this repository, I ended up in this issue. I suspect that the commit https://github.com/wekan/wekan/commit/67500abcd4d034ebed2d13f5156123d5f70bd014, which remove Mermaid altogether, kinda closed this issue and was released in [v6.76](https://github.com/wekan/wekan/releases/tag/v6.76).

So, all this intro to say, as a user of another project ([Docusaurus](https://github.com/facebook/docusaurus)), I was looking at using the experimental [`mindmap`](https://mermaid.js.org/syntax/mindmap.html) graph of Mermaid. It wasn't working well with the Mermaid version used by Docusaurus, so I forced an upgrade to `v10.2.3`. From then, all Mermaid graph were broken!

It is then I found out that the mindmap was using [lazy loading & async rendering](https://mermaid.js.org/syntax/mindmap.html#integrating-with-your-library-website) since `v9.4.0`, which Docusaurus didn't supported. After some digging, it turns out that a major breaking changes was made in `v10.0.0`[^1]. Mainly, [`mermaid.render` and `mermaid.parse` were made async](https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md#1000) (returning `promise`).

So, I did a local patch (with pnpm) to Docusaurus (see https://github.com/facebook/docusaurus/issues/9032#issuecomment-1588093686) and it was working perfectly afterwards.

I am commenting here, in the off-chance that the issue you had with Mermaid v10.0.0 might have been related to this change of `mermaid.render` returning a promise instead. If the issue was deeper (maybe the ESM-only breaking change?); well, feel free to ignore 😆.

[^1]: It's a major change, so it does fit! 😅

**Comment by sharky98** [comment]
Ok, this is just my brain wondering if... So I'll write here some notes of a potential fix to Mermaid and see if I can get time to test it for real (that might prove difficult😅 but at least my mind process would be documented if someone wants to tackle it).

Original code
https://github.com/wekan/markdown-it-mermaid/blob/2f46e22015ca4fd7ccf1bd48cc33ca32fe0bbaf8/src/index.js#L18-L28

Untested potential fix. This would not work as is. I put an await to the call to Mermaid.render but did not change parent to async function. I'll need more than my tiny cellphone to check a proper way of doing it (and time).
```js
const MermaidChart = (code) => {
  try {
    var needsUniqueId = "render" + Murmur(code, 42).toString();
    const svgResult = await Mermaid.render(needsUniqueId, code); // This line is async. Need to cascade up the promise or find a wait to sync the call here.
    return `<div class="mermaid">${svgResult}</div>`;
  } catch (err) {
    return `<pre>${htmlEntities(err.name)}: ${htmlEntities(err.message)}</pre>`;
  }
};
```

The other thing would be to validate the impact of having Mermaid as ESM only.

**Comment by helioguardabaxo** [comment]
Hi, @xet!

Would these alternatives replace Summernote and Mermaid respectively?
Toast UI editor: https://github.com/nhn/tui.editor#-why-toast-ui-editor
Toast UI chart: https://github.com/nhn/tui.chart

**Comment by xet7** [comment]
@helioguardabaxo 

No. Those are not maintained properly.
