### ISSUE TITLE
mail configuration

### ISSUE THREAD

**Issue by MeriemBH** [wekan/wekan#4887]
Hello,

after installing wekan on ubunto, the email notifications and sending invitations don't work.

thanks to clarify

**Comment by khazaddum** [comment]
I am trying to configure this through the ProtonMail Bridge, following the [wiki](https://github.com/wekan/wekan/wiki/Troubleshooting-Mail) and unfortunately the documentation is very unclear.

Per the configuration of the bridge that I use elsewhere, I am using this

```
sudo snap set wekan mail-url='smtp://EMAILUSER:EMAILPWD@127.0.0.1:1025'
```

When sending the test e-mail, I get a self-signed certificate error. This is expected because the bridge is local, is there a way to override the certificate check?

cc: @xet7

**Comment by khazaddum** [comment]
Answering my own question, to configure e-mail through ProtonMail Bridge in split-address mode:

```
sudo snap set wekan mail-url='smtp://USER%40DOMAIN:PASSWORD@127.0.0.1:1025?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'
```

**Comment by xet7** [comment]
Thanks! I added it to https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
