### ISSUE TITLE
Minicard cover image is not set via card

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#5005]
@VidVidex 

Do you know how to fix set and unset minicard cover image?

I'll get more coffee, try to wake up, and try to understand code in your previous PR.

**Comment by VidVidex** [comment]
Its a bit of a mess, I used a `data-attachment-link` attribute to save link to the attachment in HTML. 
Then on mouseover event of `.js-open-attachment-menu` I save that link in a global variable.
I wanted it to be click event but for some reason this doesn't work (popup does not open):
```js
 'click .js-open-attachment-menu'(): {
    Popup.open('attachmentActions')
    attachmentActionsLink = event.currentTarget.getAttribute("data-attachment-link");
  },
```
At the end I just pass this new url to the existing `setBackgroundImage` code.

If you know of a better way to pass data from HTML to JS please let me know because I seem to use it all over the place.

**Comment by xet7** [comment]
@VidVidex 

Do you mean Jquery?

https://github.com/wekan/wekan/blob/master/client/lib/utils.js#L5

**Comment by xet7** [comment]
@VidVidex 

> I wanted it to be click event but for some reason this doesn't work (popup does not open):

Browsers block self-clicking code.

**Comment by VidVidex** [comment]
Hey, sorry for the delay. As far as I can tell cover images on minicards work (running wekan 6.99.5).

![image](https://github.com/wekan/wekan/assets/18378617/fb729f33-d60c-4b1a-b12b-0a1a50b55ff1)

For anyone reading this in the future: check if you have minicard cover images enabled, they are disabled by default.
(Board settings > Minicard settings > Cover image on minicard)

![image](https://github.com/wekan/wekan/assets/18378617/3a953ec0-ec39-438c-a496-863741390e6b)

**Comment by LsYueh** [comment]
Wekan 7.01.0, after minicard cover images enabled.
![螢幕擷取畫面 2023-08-01 134350](https://github.com/wekan/wekan/assets/6870865/f2c8e33a-e76d-486c-a7f1-2d992619190e)
