### ISSUE TITLE
No login mask after snap refresh to 7.02

### ISSUE THREAD

**Issue by mgdbbrt** [wekan/wekan#5048]
### Server Setup Information
Installed wekan snap package tracking latest/candidate.

### Problem description
After a snap refresh from 7.01 to 7.02 the login mask is no longer shown and it is not possible to login to wekan. A snap revert to 7.01 fixes the problem.

![image](https://github.com/wekan/wekan/assets/113188948/721679e9-641b-4b47-a3ff-19b9f036f7f1)

Expected:

![image](https://github.com/wekan/wekan/assets/113188948/a79625f8-873e-4c02-ac0a-1b2cf2841bbe)

**Comment by nebulade** [comment]
Most likely a side-effect of https://github.com/wekan/wekan/pull/5041 
What are your environment variables related to the login methods?

**Comment by nebulade** [comment]
I think I found a potential root cause. Is it possible that `displayAuthenticationMethod` in the settings db is set to `false`?
Looks like some of the code cleanups now make the UI adhere to this setting, which brings up the question what this setting is useful for in the first place, if it locks users out. Does anyone know what it is supposed to do?

To fix an instance for the moment, change the setting to true via mongo-cli:

```
mongosh <your connection details> --eval "db.settings.update({}, { \$set: { displayAuthenticationMethod: true }}, { upsert: true })"
```
