### ISSUE TITLE
Error while try to install wekan on windows

### ISSUE THREAD

**Issue by Danny-Graf** [wekan/wekan#5084]
Hello,

if I try to install wekan on windows server 2022, I receive the error, that the node module fibers is missing.

E:\wekan-latest-amd64-windows\bundle\programs\server\node_modules\fibers\bin\win32-x64-108\fibers.node` is missing.

What can I do to solve this problem?

Best regards,
Danny

**Comment by xet7** [comment]
@Danny-Graf 

Are you using WeKan from wekan-7.07-amd64-windows.zip ?

**Comment by Danny-Graf** [comment]
@xet7 

I've download wekan from https://releases.wekan.team/windows/ 

I downloaded the file with the "latest" value instead of the "version" value. (wekan-latest-amd64-windows.zip)

**Comment by xet7** [comment]
@Danny-Graf 

When did you download it?

latest and version numbered files are same. But if you downloaded it some days ago, that is old. I released 7.07 yesterday.

**Comment by Danny-Graf** [comment]
@xet7 

I use the newest version of wekan, I downloaded the file today.

**Comment by xet7** [comment]
@Danny-Graf 

I don't understand what your problem is. It works for me at Windows 2022 server.

https://github.com/wekan/wekan/wiki/Offline

- WeKan from wekan-7.07-amd64-windows.zip
- I did set ROOT_URL to IP address and port to 80
- Using newest Node.js 14.21.4
- Using MongoDB 6.x .msi
- Using newest start-wekan.bat
- At bundle directory, files: node.exe, start-wekan.bat, main.js . There run: start-wekan.bat.

Maybe you have some old files?

<img width="1037" alt="win2022server" src="https://github.com/wekan/wekan/assets/15545/5000f539-e54f-44cd-be73-0b78154a7a25">
