### ISSUE TITLE
Wekan roadmap returns 503

### ISSUE THREAD

**Issue by Chaostheorie** [wekan/wekan#5104]
## Issue

The Wekan roadmap, as linked by the main website, is responding with a 503 error.

## Reproduction Steps

Visit [the roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) (last fetched 19:21 CEST, 24.08.23). This url originates from the [wekan.github.io](https://wekan.github.io/) (visit the public, read-only roadmap).

#### Logs
![Screenshot 2023-08-24 at 19-22-21 zCloud - Internal server error](https://github.com/wekan/wekan/assets/42151227/38ab4a26-75c2-4197-9e32-43eade448a3c)

**Comment by xet7** [comment]
@Chaostheorie 

Yes, because I'm moving WeKan demo zCloud, their Meteor developers will help me fix memory leak in WeKan, so that WeKan will keep running, and not need restart once a week when it freezes. That fix will then be added to upcoming WeKan release, and will benefit all WeKan users.

That WeKan demo is at webbrowser and also apps at Android Play Store, Windows MS Store, and Ubuntu Touch OpenStore.

We are setting it up now, so it should start working soon.

**Comment by xet7** [comment]
zCloud server location is at Finland.

**Comment by filipenevola** [comment]
Hey, Filipe Névola here from zCloud.

We are going to help @xet7 with this migration & tests but we are still in the process of configuring it so the DNS is now again correctly pointing to the old provider. 

Thanks!

**Comment by xet7** [comment]
Currently WeKan demo and roadmap is using old server, and it works.

I will open this issue later when we try again to move to zCloud.

**Comment by xet7** [comment]
I'm trying to move to zCloud again. So there will be small downtime.

**Comment by xet7** [comment]
Ok we are now running at zCloud.
