### ISSUE TITLE
Font Awesome Update

### ISSUE THREAD

**Issue by helioguardabaxo** [wekan/wekan#5124]
Hi, @xet7 !

I'm looking to Font Awesome dependency update.
Current package uses 4.7.0 version from 2016.

On Font Awesome Readme there this topic:
"In the Font Awesome Free download, the MIT license applies to all non-font and non-icon files."
Is this a problem for use a newer version on Wekan?

**Comment by xet7** [comment]
@helioguardabaxo 

There are also some alternatives to Font Awesome https://lineicons.com/blog/font-awesome-alternatives/

Using newer Font Awesome would require to check that:
- have any icon names changed, check that icons works
- check that all of new Font Awesome is included, so that it works offline, does not load anything from Internet

Sure, you can send PR. Thanks!

**Comment by xet7** [comment]
Updated at https://github.com/wekan/wekan/pull/5125 . Thanks to @helioguardabaxo !
