### ISSUE TITLE
Notifications are identical until one is marked read

### ISSUE THREAD

**Issue by kschimpanski** [wekan/wekan#5153]
### Server Setup Information

* Did you test in newest Wekan?: Yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
* Operating System: Ubuntu
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): None
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.10
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Edge, Chrome, Firefox

### Problem description
Since about two months the notifications are kind of buggy in our wekan instance. After logging in to wekan and clicking on the red bell, all the notifications are identical. If you mark one of the notifications as read, the remaining notifications appear to be updated and show the correct info. Logging out and in again or refreshing the browser window will then again change the notifications back to the identical ones. Sometimes keeping the notification window open while browsing through boards/cards will initiate an update of the notifications.
The (identical) notifications vary for each user, however all users appear to be affected.
If all notifications are marked as 'read' new notifications will still be identical but with a new information.

I already tried the clean-up tool on a backup in a seperate instance but with no effect on the notifications..

I had to conceal parts of the gif, I hope it is still comprehensible: 
![wekan-notifications-bug](https://github.com/wekan/wekan/assets/117566832/7e99c69a-cf2a-452d-8bfc-d0b23e1a6ee1)

#### Logs
[wekan-log.txt](https://github.com/wekan/wekan/files/12819429/wekan-log.txt)

**Comment by kschimpanski** [comment]
I took a deeper look into this issue:
It occurs first with the release of Version 7.00, maybe due to the changes of the reactive cache (and activities)?

It can be reproduced by setting up a new (docker) instance:
Create 2 users which can access the same board, make them follow the board - second user needs to join the board before the following steps.
When both users have access to the board, use one user to create a card, set the second user as member. Make several comments and a checklist with a couple of entries.
Log out and login with the second user. - At this point it is sometimes necessary to reload the webpage (F5). Afterwards click on the bell and you will see identical activities.

Hope this helps,
best regards

**Comment by kschimpanski** [comment]
I took a deeper look into this issue:
It occurs first with the release of Version 7.00, maybe due to the changes of the reactive cache (and activities)?

It can be reproduced by setting up a new (docker) instance:
Create 2 users which can access the same board, make them follow the board - second user needs to join the board before the following steps.
When both users have access to the board, use one user to create a card, set the second user as member. Make several comments and a checklist with a couple of entries.
Log out and login with the second user. - At this point it is sometimes necessary to reload the webpage (F5). Afterwards click on the bell and you will see identical activities.

Hope this helps,
best regards

Unfortunately I clicked on "close with comment" and therefore had to reopen this issue. Sorry for that..

**Comment by JohnnyTravulta** [comment]
This bug makes WEKAN notifications completely useless. I get hundreds of identical comments the same way as @kschimpanski. The only way to get to actual notifications is to set one of identical comments as read. This way you have to check out notifications every single minute, because you have no idea when an actual and important notification may come in and you don't want to lose any info so you waste time on perusing through an extra long list. It makes managing a team a nightmare.

**My config is:**
Did you test in newest Wekan?: Yes
Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)? yes
 Operating System: Windows
Deployment Method (Snap/Docker/Sandstorm/bundle/source): bat file bundle
Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): None
Node.js Version: 14.21.4
MongoDB Version: 6.0.10
What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)? Edge, Chrome, Firefox

**Comment by mfilser** [comment]
I think there is another similar issue which I am looking
