### ISSUE TITLE
v7.09 arm64v8 mongodb exec format error

### ISSUE THREAD

**Issue by Flattermann78** [wekan/wekan#5167]
## Issue
The mongodb-arbiter-0 is not strting on a kubernetes setup on RPi4 providing an "exec format error".

### Server Setup Information

Version v7.09
MongoDB is 13.6.X where bitnami seems to have some issues providing an arm64 version.

### Problem description
The helm chart for v7.09 armv8 uses a MongoDB version of bitnami which is not multi-universe it seems (https://github.com/bitnami/charts/issues/3635)

#### Logs
pi@kube1:~/.cache/helm/repository $ kubectl logs wekan2-mongodb-arbiter-0
exec /opt/bitnami/scripts/mongodb/entrypoint.sh: exec format error

**Comment by xet7** [comment]
@Flattermann78 

1. Please add PR to https://github.com/wekan/charts . I do not know how to make multi-universe Chart.

2. I do not know how to make multi-universe Docker image in same Dockerfile, so that same Docker image works at multi CPU. Please look at https://github.com/wekan/wekan for various Dockerfile and docker-compose.yml files and send PR or advice how to make it possible.

Thanks!
