### ISSUE TITLE
Wekan sometimes does not work.

### ISSUE THREAD

**Issue by duongdang1992** [wekan/wekan#5209]
I have this issue that I need your support with. I apologize for my limited English writing skills and appreciate your understanding. I am installing Wekan version 7 on a computer running the Windows Server 2019 operating system (Offline) with the configuration of a core i3 10100, 8GB RAM, and 1TB HDD storage, for a trial with 12 users (planned to deploy for 60 actual users). However, sometimes the Wekan application becomes unresponsive, and I have to restart the start-wekan.bat file to get the application working again. Could you please guide me on how to resolve this issue? Additionally, can you provide instructions on how to back up, restore, extract logs, and upgrade the Wekan application? I sincerely thank you for your assistance!

**Comment by xet7** [comment]
@duongdang1992 

> However, sometimes the Wekan application becomes unresponsive, and I have to restart the start-wekan.bat file to get the application working again. Could you please guide me on how to resolve this issue? 

That is a bug https://github.com/wekan/wekan/issues/5140

I have asked for help to fix that bug at https://forums.meteor.com/t/meteor-application-works-very-slowly-after-1-2-weeks-of-operation/60834/4

It could be, that bug will be fixed in sometime in the future, in some upcoming WeKan release, with a fix, upgrade or rewrite.

> Additionally, can you provide instructions on how to back up, restore, extract logs, and upgrade the Wekan application?

https://github.com/wekan/wekan/wiki/Backup

For logs, at `start-wekan.bat` , `start-wekan.sh` or `docker-compose.yml` , set `DEBUG=true` to get more logs.

For Docker, `docker logs wekan-app` or `docker logs wekan-mongodb`  or `docker-compose logs`

For snap, at server type `wekan.help | syslog` to see options where to save logs, like syslog, etc

If using Windows, newest WeKan works with Docker and docker-compose.yml from https://github.com/wekan/wekan

Moved to #5140
