### ISSUE TITLE
Problem with language in Wekan Docker Containter

### ISSUE THREAD

**Issue by 32Dexter** [wekan/wekan#5228]
Hi, I'm trying to use Wekan. I use Docker and download images from Docker Hub. I'm trying to use version 7.21.
I have a problem with the language setting (in my case Italian) but it doesn't seem to work. I select any language but nothing seems to change.
So I tried to install version 6.22 and there seems to be some problems with this version (I noticed the change in the Meteor version, I don't know if it could be influential). Previous versions seem to work fine.
I would like to use the latest versions.
I wanted to try to change or install new versions directly from the container's bash but unfortunately I don't know the wekan/admin user password.

**Comment by 32Dexter** [comment]
My Operating System of host machine is Windows 10 v.22H2 - 19045.3693

**Comment by xet7** [comment]
@32Dexter 

Sometimes these help:

1. At `docker-compose.yml`, where `export ROOT_URL=http://YOUR-IP-ADDRESS` you change there your Windows IP address like 192.168.0.200
2. At right top your username / Language, change language

But there are still some bugs, that in some cases some translations do not show translated text. I'm trying to find a way to always show translations correctly.

**Comment by Julianoe** [comment]
I use with Wekan with DOcker too. It does not fail at showing the propper translation, but the mail notifications are not translated anymore

**Comment by MayhemBill** [comment]
I'm having a similar issue, it seems that certain things are being shown in the langs that shouldn't? I'm using English language, but I see `-title` on a lot of the items.

**Comment by captainstarfish** [comment]
I'm having a similar issue to MayhemBill.

Everything spools up fine with a docker install (either compose or directly with a docker run for mongo and for the wekan app). When I open the URL, though, all the field labels are displayed with their tags (eg quick-access-description, my-boards, board-view-swimlanes) rather than the translations. 

Unsure if related but, when I go to my user menu and select "changeLanguagePopup-title", English is selected - but it won't let me change to any of the other English variants.

**Comment by xet7** [comment]
@captainstarfish 

If you can't change language, that is usually because docker-compose.yml setting ROOT_URL is not something like subdomain https://boards.example.com with some webserver (Caddy, Nginx, Apache like at right menu of https://github.com/wekan/wekan/wiki ) proxying it to localhost port were is docker-compose.yml setting like PORT=8080 or similar.

Or alternatively, at local network, ROOT_URL could be like http://IP-ADDRESS, like http://192.168.0.200 , and PORT=80 . 

Also, to have correct language, at browser settings should be only one language that you would like to use WeKan with.

There are still bugs, where in some cases, it takes time for all those about 10 MB of Javascript to run, so later translations comes visible. If someone does not give enough time for all Javascript to run, and even does browser page reload often, that is not so helpful.

I'm working on some prototypes where translations are done serverside, but those are not ready yet.

**Comment by captainstarfish** [comment]
Thanks, xet7

I came back to find the post and update after I found this answer elsewhere - it absolutely was ROOT_URL not pointing to the same port as the one mapped by docker.

Fixed! :)

**Comment by xet7** [comment]
@captainstarfish 

Kind of. That setting is only, if there is only one user of WeKan at same laptop where Docker is running.

If there are other users of same WeKan at same local network, it should have IP address of Docker server, like this:
```
ROOT_URL=http://192.168.0.200:9001
```
