### ISSUE TITLE
export command from command line ?

### ISSUE THREAD

**Issue by mzemb** [wekan/wekan#523]
Hi.

I'm using wekan since a few days and I love it !
Is there a way to pass the export command to wekan from command line ?
(My goal is as you can imagine to a line in my crontab to do a daily backup to another machine).

Thanks.

**Comment by gonter** [comment]
That export alone might not make you happy, should you need to actually restore the machine.  Instead, as mentioned in #494, the MongoDB needs to be backed-up.

Since I had to do it anyway sooner or later, here is my very simple and non-self-cleaning script which premiered on my instance a few minutes ago:

https://gist.github.com/gonter/b0383d7785bddc8e5809

YMMV, GG

**Comment by mzemb** [comment]
Thank you, I'll test this soon.

**Comment by scoubidoo** [comment]
hi i use a script to make a dump 
```
#!/bin/sh
DIR=`date +%m%d%y`
DEST=../Mongo_Sauv/$DIR
mkdir $DEST
mongodump -h 127.0.0.1 -d DBNAME  -o $DEST
```
