### ISSUE TITLE
Activities Filter

### ISSUE THREAD

**Issue by andionita** [wekan/wekan#5297]
## Issue
We just set up a webhook from our board to a webex channel, which worked directly and grealty improves our productivity. We were wondering whether any filtering of the activities is supported? Either on the list of protocolled activites on the board (in the hamburger menu) or when forwarded by the webhook. Thanks in advance.

**Comment by xet7** [comment]
@andionita 

There at wiki there is right menu Webhooks https://github.com/wekan/wekan/wiki

There is limiting Webhook data https://github.com/wekan/wekan/issues/2830

There is also old, not merged, PR about integrating webed, I don't know what it does, would it be useful https://github.com/wekan/wekan/pull/758

**Comment by andionita** [comment]
Thank you for your reply and the helpful links.

So the changes need to be made globally. The option to change them per board would have been even better.

I am not sure what some attributes mean: listId?, oldListId? Are there any descriptions that I could find?

The webex integration works pretty straigtforward. Set up an Endpoint in [webex webhooks](https://apphub.webex.com/applications/incoming-webhooks-cisco-systems-38054-23307-75252) to a webex channel and entered the resulting URL in the wekan webhooks. Boom! We are very happy with it, except that it is somewhat verbose. But now things are more clear.

**Comment by xet7** [comment]
@andionita 

Attributes are listed at translations https://github.com/wekan/wekan/blob/main/imports/i18n/data/en.i18n.json

For example, there is webhook message, that card has been moved from old list (oldListId) to new list (listId).

Those limitations to webhook data are global. But webhooks itself can be per-board, or global. per-board webhook URL is defined at right sidebar / board settings.

Global webhooks are defined at Admin Panel, and send all changes of all boards, so that can slow down WeKan.

**Comment by xet7** [comment]
@andionita 

Also, webhook messages should receive message 200 OK immediately. If some webhook does not work, it can slow down wekan.

**Comment by andionita** [comment]
Great, thank you for the explanation and valuable information!
