### ISSUE TITLE
WeKan Upgrades coming soon

### ISSUE THREAD

**Issue by mqu** [wekan/wekan#5475]
## Issue

* Did you test in newest Wekan?: yes: 7.51
* Operating System: debian/bookworm + docker
* Deployment Method (Snap/Docker/Sandstorm/bundle/source): docker
* Node.js Version: 7.51

### Problem description

may be Nodejs version end of life ...
```
$ docker-compose exec wekan nodejs -v
v14.21.4
```

best regards.

**Comment by xet7** [comment]
@mqu 

Node.js 14.21.3 is EOL by original Node.js developers.

Node.js 14.21.4 is maintained by Meteor developers:
- https://github.com/wekan/node-v14-esm/releases/tag/v14.21.4
- https://github.com/meteor/node-v14-esm

WeKan currently uses Meteor 2.14. that was released 2023-12-12:
- https://github.com/wekan/wekan/blob/main/.meteor/release

Upgrading WeKan to newer Meteor was tried at 2024-07-15 https://www.youtube.com/watch?v=Zjb3m9JsAD0 , but currently upgrading breaks creating new board. That and other WeKan related videos are listed at https://github.com/wekan/wekan/wiki/Meteor

Meteor 3 https://www.meteor.com
- was released 2 weeks ago
-  uses newest Node.js 20
-  Online event about Meteor 3, In Progress:
  - https://www.meteor.com/the-renaissance-of-meteorjs
  - Past and upcoming live streams: https://www.youtube.com/@meteorsoftware/streams  
- There is new Meteor 3 docs
- Meteor is adding more examples, videos, docs, etc, helping to upgrade.

Some other non-WeKan Meteor based apps have already upgraded to Meteor 3. In general, many Meteor-based apps are in progress of upgrading to Meteor 3. Meteor 3 is brand new, it did require 3 years of development to migrate from fibers to Async/Await, etc, huge amount of changes.

There is in progress trying to upgrade WeKan to Meteor 3. At the same time, I'm also making some other non-Meteor based WeKan prototypes more feature complete, so that they could replace Meteor-based WeKan.

For any current WeKan user, upcoming WeKan versions are automatic upgrades at Snap Stable channel. Other WeKan platforms usually need manual upgrade, or clicking something to upgrade. Improving upgrade experience is in progress.

**Comment by mqu** [comment]
thanks.

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan-snap/issues/170#issuecomment-2270426407

From @paul1278

> @xet7 do you know when the update will be available?

It depends, when I have created WeKan version, that can use any version of MongoDB between 3.x - 7.x, not needing any database migration.

Problem with any kind of database migration is:
- Out of disk space, with possibility of database corruption
- It takes too much time to run migrations at https://github.com/wekan/wekan/blob/main/server/migrations.js to change schema, that can take from many hours to days, when schema changes to thousands of cards

Any kind of migration causes a downtime, that is not acceptable.

WeKan needs to be able automatically detect and use:
- Any MongoDB version of 3.x - 7.x
- Any database schema of any WeKan version, from oldest to newest
- Do queries with existing data

There are MongoDB databases with huge sizes, like 800 GB etc. For those:
- WeKan needs to start immediately, without any migrations
- WeKan needs to be able to migrate any attachments from MongoDB GridFS to any other storage (like filesystem, minio, S3, etc) at background, without too much CPU usage (so that WeKan does not become unresponsive or crash)

All this needs to be carefully tested, so that upgrading works immediately with only couple seconds of downtime. Otherwise there will be wordwide downtime of about 10 000 WeKan Snap servers.

If someone is worried about security of old version of WeKan, then just run WeKan offline, or via VPN, not directly exposed to Internet.

If someone needs more reasons, why updates should be tested properly before releasing, please look at some commentary videos at YouTube, about recently happened CrowdStrike update. So, please do not hurry up, let me develop properly working successfull update, that updates immediately, with only couple of seconds of downtime.

**Comment by xet7** [comment]
Currently these MongoDB versions are in use:

Using Meteor 2:
- MongoDB 3.0: Sandstorm
- MongoDB 3.2.22: Snap Stable
- MongoDB 4.x, 5,x, 6.x: Some WeKan Docker and Bundle versions
- MongoDB 6.x: Snap Candidate

Using Meteor 3:
- MongoDB 7.x: Meteor 3 based WeKan prototype https://github.com/wekan/wekan-meteor3

If possible sometime, maybe also try to support:

- FerretDB/SQLite and FerretDB/PostgreSQL
  - WeKan Node.js/Bun/Deno prototype at https://github.com/wekan/wekan-node20
  - https://forums.meteor.com/t/ferretdb-1-18-now-has-oplog-support-trying-replace-mongodb-6-x-with-ferretdb-postgresql-or-ferretdb-sqlite/61092
- Amazon DocumentDB
  - https://www.mongodb.com/docs/drivers/documentdb-support/#std-label-documentdb-compat
  - https://github.com/wekan/wekan/issues/2852
- Azure CosmosDB https://www.mongodb.com/docs/drivers/cosmosdb-support/#std-label-cosmosdb-compat
  - https://www.mongodb.com/docs/drivers/documentdb-support/#std-label-documentdb-compat
  - https://github.com/wekan/wekan/issues/2852

**Comment by xet7** [comment]
Related https://github.com/wekan/wekan-snap/issues/103

**Comment by xet7** [comment]
About migrating attachments #5515

**Comment by xet7** [comment]
Snap Stable will be upgraded to newest WeKan sometime during this month 2024-08, for those where it's possible to upgrade. If there is some problem, like lack of free disk space, there will be info about it at some visible place.

**Comment by xet7** [comment]
First will be upgrade to newest Meteor 2 WeKan. After that, automatic upgrades to newer versions of WeKan.

**Comment by Ilav1** [comment]
Is it possible to trigger the update manually?

`sudo snap refresh` doesn't find any wekan updates

**Comment by xet7** [comment]
@Ilav1 

Not yet, because I have not released it yet. I first need to write some code and test that upgrading will work. Only after that I will release it to Snap Stable.

**Comment by xet7** [comment]
I'm still working on this. I promised to help someone to upgrade at next week. For general Snap Stable upgrade, I will release it when I get it working well enough.

**Comment by xet7** [comment]
But, open question for general upgrade is, that MongoDB 6.x works only on hardware where CPU supports AVX. Some old hardware has CPU that does not support AVT. I'll try is there some workaround.

Related:
- https://github.com/wekan/wekan/issues/4321
- https://github.com/wekan/wekan/issues/5532

**Comment by xet7** [comment]
Moved to #5562
