### ISSUE TITLE
MongoDB restore from Wekan 6.09.0 to 7.55.0 is missing images!

### ISSUE THREAD

**Issue by drhugobr** [wekan/wekan#5515]
## Issue

Please report these issues elsewhere:

* Did you test in newest Wekan?
* yes
* Did you configure root-url correctly so Wekan cards open correctly (see https://github.com/wekan/wekan/wiki/Settings)?
* yes
* Operating System:
* windows\linux (same issue in both)
* Deployment Method (Snap/Docker/Sandstorm/bundle/source):
* bundle
* Node.js Version:
* 12.22.10 to 14.21.3
* MongoDB Version:
* 3.2.22 to 6.0.16
* What webbrowser version are you using (Wekan should work on all modern browsers that support Javascript)?
brave\firefox\edge

### Problem description

migrating from one server to another, executing a mongodump on the old machine, and using mongorestore on the new machine, everything works perfectly, accounts, boards, and etc. but the attachment images dont load, nor the avatar images, but the "standard images" from wekan works normaly.

Old version:
![image](https://github.com/user-attachments/assets/8b8e4071-70c7-4b85-9773-a7a4c4fc1130)
New version:
![image](https://github.com/user-attachments/assets/de2cca0d-a3a5-420d-baf4-a9f8dc437c7f)
![image](https://github.com/user-attachments/assets/1ac4a899-308a-4e4d-b281-47db818d7081)

#### Reproduction Steps

make a mongodump from version 6.09, and try restoring the db in to 7.55.

**Comment by xet7** [comment]
@drhugobr 

Yes, that is because attachments in new WeKan version are using different database structure, table names, and field names.

Attachments are stored at database using GridFS. Old WeKan uses CollectionFS, new WeKan uses Meteor-Files, those have different database structure.

MongoDB data can be seen using GUI like like DBGate or nosqlbooster. Nosqlbooster can also show list of attachments and save those files. https://github.com/wekan/wekan/wiki/Backup#dbgate-open-source-mongodb-gui

Migrations of attachments are not currently enabled, because that process has bugs, it easily loses files, because of problems with non-usual characters in filenames, so usually it would be better to save files with filenames like sha256 strings, that would also deduplicate to have only one of each file. Commented out migration code is buggy:

https://github.com/wekan/wekan/blob/main/server/migrations.js#L1250-L1410

It is possible to export MongoDB JSON text and attachments to SQLite and files at disk, but that process is being improved, trying to use some sha256 like has for filenames, because there usually are many files that have same name (like image.png) , but different content.

https://github.com/wekan/minio-metadata

That SQLite database is used in some future WeKan prototypes (like WeKan Studio https://github.com/wekan/wekanstudio and WeKan-PHP https://github.com/wekan/php ), but those do not have even working login yet, only some minimal test webpages, that are designed to be visible at all browsers, including retro and legacy browsers. Current Meteor 2 WeKan only works at modern brosers, not all browsers.

It is also possible to save all MongoDB content to JSON files, where attachments are base64 encoded inside JSON files:

https://github.com/wekan/wekan/wiki/Export-from-Wekan-Sandstorm-grain-.zip-file#11b-dump-database-to-json-text-files

There is some not working commented out migration code in Snap Candidate, but it has not been tested, does it work at all:

https://github.com/wekan/wekan/blob/main/snap-src/bin/mongodb-control#L21-L77

WeKan v6.09 database structure is here:

https://github.com/wekan/wekan/tree/v6.09/models

WeKan v7.55 database structure is here:

https://github.com/wekan/wekan/tree/v7.55/models

The best way to upgrade would be to make attachment related changes in-place, by renaming attachments related gridfs tables, modifying text descriptions of files to be in structure of new database table and field names, and keeping actual 
files chunks at database (not exporting and importing those). Attachments actual files are divided to one or more chunks.

I have been thinking of trying to support many different versions of MongoDB:

https://github.com/wekan/wekan/issues/5475#issuecomment-2271611017

But newest Meteor 3 web framework only supports newest MongoDB 6 database query syntax, and Meteor 3 is thinking about upgrading to MongoDB 8 syntax, from OpLog (used for real time updates) to Change Streams, etc. I mentioned about it at Meteor Forums, when I was trying does using FerretDB work (I have not got FerretDB working yet with WeKan), because FerretDB added OpLog support, but I don't know does FerretDB plan to add support Change Streams:

https://forums.meteor.com/t/ferretdb-1-18-now-has-oplog-support-trying-replace-mongodb-6-x-with-ferretdb-postgresql-or-ferretdb-sqlite/61092/5?u=xet7

**Comment by xet7** [comment]
Changing to different database (or supporting many other databases) is related to MongoDB currently using non-free SSPL license:

https://en.wikipedia.org/wiki/MongoDB

Using free database is what is recommended for Standard for Public Code to get more points. For that current status of standard compliance audit is here:

https://wekan.github.io/standard-for-public-code/

Meteor has some existing packages at https://atmospherejs.com for supporting MySQL and PostgreSQL. Creator of MySQL package just asked somewhere at some Meteor chat or forum about versions for supporting both Meteor 2 and Meteor 3, how their version numbers and package names could be, because creator of MySQL package is in progress of updating MySQL package for both Meteor 2 and Meteor 3.

There are also other alternatives for databases, but it depends what I get working well enough.

**Comment by xet7** [comment]
Another possibility is, that URL to attachments is wrong: https://github.com/wekan/wekan/issues/5366

**Comment by drhugobr** [comment]
Hello @xet7 ! thanks for the very quick reply!

I`ll try to restructure the MongoDB to the new standard as I`ve seen in another issue, theres an explanation renaming the Dbs and also to convert them, as for the URL, I had that issue before but it was fixed with the correct ROOT_URL. I`ve checked the link to the missing avatars images and they seem to point to the correct URL, but they are not working.

**Comment by xet7** [comment]
@drhugobr 

Yes, if ROOT_URL is not correct, attachments etc do not work properly.

**Comment by xet7** [comment]
For database structure changes, point is to look at MongoDB database query docs, how to rename and modify those tables to work corrently. If someone figures it out, please add those MongoDB queries to comment of this issue, so I'll then try to make database attachments migrations working. Sure, I'll try also look at it, when possible.

**Comment by drhugobr** [comment]
Been trying the conversion and DB rename, but I think I`ve hit my tecnical limit, it still doesn't work, I was just reading about a manual "one by one" type o conversion, but my attachments are over 1K images with about 2.7Gb database file.
![image](https://github.com/user-attachments/assets/d575b508-ca46-443d-8475-87b6ffdbe8fa)

to my knowledge this would be virtually impossible.
unless I'm missing something.

**Comment by xet7** [comment]
Currently Meteor 2 WeKan can only show attachments from MongoDB GridFS.

This code converts most text based MongoDB data to SQLite:

This code in loop reads list of files from SQLite database, and saves attachments to separate files. When I used it previously, I modified it to use OBJECTID as filename, because actual filenames have strange characters and duplicate filenames:

https://github.com/wekan/minio-metadata/blob/main/transfer.sh#L27

Meteor 2 WeKan has feature of export board as HTML zip file. There was some request to make it working better. Maybe export of each board could be some .zip file, that has JSON and attachments as normal files.

Export of boards could be also organized to directory structure, that can be used like local static website.

With .zip files, there is question, should files used directly from .zip file without extracting, or is there some safe way to extract files at serverside directory, or stream from .zip file each attachment to some file storage server, validating content of file, etc.

**Comment by xet7** [comment]
MongoDB database size of 2.7 GB is still very small. Some have database size of 800 GB, and wish to have a way to migrate attachments to separate file server, like S3 or minio. But minio is not free for commercial use.

**Comment by xet7** [comment]
With a lot of attachments, one way would be to add all of them to one .zip file, and use them directly from that .zip file. That is possible with

a) Redbean https://redbean.dev at WeKan Studio prototype https://github.com/wekan/wekanstudio

b) Using Caddy Server https://caddyserver.com that can serve files from databases, archives etc, I presume, I have not tried yet.

If files are at local filesystem, then for that to work, those files need to be organized correctly to subdirectories, for filesystem to be able to handle it:

https://github.com/rclone/rclone/wiki/Big-syncs-with-millions-of-files

**Comment by xet7** [comment]
Anyway, saving many attachments from big MongoDB database to separate file, creating file checksums, uploading to file storages, that could take many days, or maybe weeks, and need possibilities to verify, retry, and continue interrupted transfers.

**Comment by xet7** [comment]
The point in also supporting old versions of MongoDB is, that if I release newest WeKan to Snap Stable, it would be able to login and use that existing MongoDB data. And not be hours/days/weeks of downtime, when showing nothing. It could be possible, if loading both new and old MongoDB drivers, like in my Node.js/Bun/Deno prototype.

For Node.js and Bun:

https://github.com/wekan/wekan-node20/blob/main/package.json#L22-L23

https://github.com/wekan/wekan-node20/blob/main/main.js#L8-L9

For Deno:

https://github.com/wekan/wekan-node20/blob/main/deno.json#L16-L17

https://github.com/wekan/wekan-node20/blob/main/main-deno.js#L3-L4

For some migrations I have tried, those have taken too many hours, there was not enough disk space at current disk to make migration, so external USB harddrive had to be added, etc. Any kind of manual upgrade is a lot of trial and error, with trying to write correct syntax without typos, etc.

**Comment by xet7** [comment]
I will make changes, that when starting some upcoming version of WeKan, it will make images visible automatically.

**Comment by ChristianAlfredsson** [comment]
I had success in test enviroment with this. Can you test @xet7?

BACKUP
`# Stop Wekan
sudo snap stop wekan

# Create backup directory
cd /var/snap/wekan/common
sudo mkdir -p backup

# Run MongoDB backup
sudo snap run --shell wekan.mongodb
cd /var/snap/wekan/common/backup
/snap/wekan/current/bin/mongodump --port 27019 --out=./wekan_backup_$(date +%Y%m%d)
exit`

UPGRADE WEKAN
`# Remove old files (after backup)
sudo rm -rf /var/snap/wekan/common/*

# Upgrade to latest version
sudo snap refresh wekan --channel=latest/stable

# Stop all services for clean start
sudo snap stop wekan`

RESTORE DATA
`# Start MongoDB
sudo snap start wekan.mongodb
sleep 15

# Restore database
sudo snap run --shell wekan.mongodb
cd /var/snap/wekan/common/backup
/snap/wekan/current/bin/mongorestore --port 27019 --drop ./wekan_backup_YYYYMMDD/wekan/
exit`

MIGRATE ATTACHMENTS
`sudo bash -c 'cat > /var/snap/wekan/common/migrate_attachments.sh' << 'EOL'
#!/bin/bash

echo "1. Starting migration process..."
/snap/wekan/current/bin/mongoexport --port 27019 --host 127.0.0.1 \
    --db wekan --collection cfs.attachments.filerecord > old_files.json

while IFS= read -r line; do
    # Extract key from copies.attachments
    key=$(echo "$line" | grep -o '"key"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
    
    if [ ! -z "$key" ]; then
        echo "Processing file with key: $key"
        
        # Extract all metadata
        name=$(echo "$line" | grep -o '"original"[[:space:]]*:[[:space:]]*{[^}]*}' | grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        type=$(echo "$line" | grep -o '"original"[[:space:]]*:[[:space:]]*{[^}]*}' | grep -o '"type"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        size=$(echo "$line" | grep -o '"size"[[:space:]]*:[[:space:]]*[0-9]*' | cut -d':' -f2 | tr -d ' ' | head -1)
        boardId=$(echo "$line" | grep -o '"boardId"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        cardId=$(echo "$line" | grep -o '"cardId"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        userId=$(echo "$line" | grep -o '"userId"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        swimlaneId=$(echo "$line" | grep -o '"swimlaneId"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        listId=$(echo "$line" | grep -o '"listId"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
        
        # Determine file extension
        ext=$(echo "$name" | awk -F. '{print $NF}' | tr '[:upper:]' '[:lower:]')
        
        # Determine file type
        isPDF=$(echo "$type" | grep -q "pdf" && echo "true" || echo "false")
        isImage=$(echo "$type" | grep -q "image" && echo "true" || echo "false")
        
        echo "Creating new format for: $name"
        
        # Create new record in new format
        echo "{
            \"_id\": \"$key\",
            \"size\": $size,
            \"type\": \"$type\",
            \"name\": \"$name\",
            \"meta\": {
                \"boardId\": \"$boardId\",
                \"swimlaneId\": \"$swimlaneId\",
                \"listId\": \"$listId\",
                \"cardId\": \"$cardId\"
            },
            \"ext\": \"$ext\",
            \"extension\": \"$ext\",
            \"extensionWithDot\": \".$ext\",
            \"mime\": \"$type\",
            \"mime-type\": \"$type\",
            \"userId\": \"$userId\",
            \"path\": \"/var/snap/wekan/common/files/attachments/$key.$ext\",
            \"versions\": {
                \"original\": {
                    \"path\": \"/var/snap/wekan/common/files/attachments/$key-original-$name\",
                    \"size\": $size,
                    \"type\": \"$type\",
                    \"extension\": \"$ext\",
                    \"storage\": \"gridfs\",
                    \"meta\": {
                        \"gridFsFileId\": \"$key\"
                    }
                }
            },
            \"_downloadRoute\": \"/cdn/storage\",
            \"_collectionName\": \"attachments\",
            \"isVideo\": false,
            \"isAudio\": false,
            \"isImage\": $isImage,
            \"isText\": false,
            \"isJSON\": false,
            \"isPDF\": $isPDF,
            \"_storagePath\": \"/var/snap/wekan/common/files/attachments\",
            \"public\": false
        }" > "new_$key.json"
        
        echo "Importing to new format..."
        /snap/wekan/current/bin/mongoimport --port 27019 --host 127.0.0.1 \
            --db wekan --collection attachments \
            --file="new_$key.json"
            
        rm -f "new_$key.json"
        echo "Completed migration for: $name"
        echo "--------------------------"
    fi
done < old_files.json

echo "Migration completed"
EOL

sudo chmod +x migrate_attachments.sh`

RUN MIGRATION
`# Run migration script
sudo snap run --shell wekan.mongodb
./migrate_attachments.sh
exit`

START AND VERIFY
`# Create attachments directory
sudo mkdir -p /var/snap/wekan/common/files/attachments

# Start Wekan
sudo snap start wekan

# Check status
sudo snap services wekan`

CLEAR CACHE AND TEST

**Comment by ChristianAlfredsson** [comment]
Updating previews is not in this script.

**Comment by xet7** [comment]
Moved to #5562
