### ISSUE TITLE
Wekan Windows 64bit version On-Premise

### ISSUE THREAD

**Issue by sunilnc** [wekan/wekan#5591]
## Issue

Hello,

I have followed the instructions as per the guidance on this page to deploy Wekan Windows 64bit version On-Premise:
https://github.com/wekan/wekan/blob/main/docs/Platforms/Propietary/Windows/Offline.md

However, the service isn't working for me.

I have tried the default ports 80 and 2000, but nothing is loading when I go to those pages from another machine on the same network.

Do you have any ideas on what I'm doing wrong?

**Comment by xet7** [comment]
@sunilnc 

For example, when `start-wekan.bat` is inside `bundle` directory, if your IP address is 192.168.0.100:

```
SET ROOT_URL=http://192.168.0.100

SET PORT=80

node.exe main.js
```
At other computer, webbrowser to address http://192.168.0.100/sign-in

**Comment by xet7** [comment]
Just check, that URL is not https . It should be http .

**Comment by sunilnc** [comment]
Hi,
URL is http and not https.

The host machine IP is 192.168.0.54 according to IPCONFIG.

This is what my start-wekan.bat file contains:

```
SET WRITABLE_PATH=..
SET MONGO_URL=mongodb://127.0.0.1:27017/wekan
SET ROOT_URL=http://192.168.0.54:2000
SET PORT=2000
node.exe main.js
```

**Comment by xet7** [comment]
@sunilnc 

Is there any errors?

What is webbrowser name and version?

**Comment by sunilnc** [comment]
> h

I right clicked start-wekan.bat file and ran it as administrator. How do I check for errors?

I'm using Edge on the other machine. I have also tried Safari but both are timing out.

Even trying to reach the URL on the host machine is timing out too, which makes me think the service is not running probably.

**Comment by xet7** [comment]
@sunilnc 

Does start-wekan.bat produce any text output?

**Comment by sunilnc** [comment]
@xet7 
Nope, a black box pops open and then quickly closes.

**Comment by xet7** [comment]
@sunilnc 

1. Run cmd.exe as Administrator
2. Change to directory where files are. For example:

```
dir

cd \Users\USERNAME\Downloads\bundle

start-wekan.bat
```
3. Then from all that text, copy the end of it, text at visible part of terminal window, to comment of this issue.

Did you install MongoDB ?

**Comment by xet7** [comment]
@sunilnc 

In that bundle directory should be:
- node.exe
- start-wekan.bat
- main.js

**Comment by sunilnc** [comment]
@xet7 
Yes, that is what I see in the directory. Attached is a screenshot of what's there.
![Screenshot 2024-11-27 110358](https://github.com/user-attachments/assets/78811722-2156-4d3e-9086-07654d3a4451)

I ran in cmd andf this is what it says:

> Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
> 
> PS C:\Users\sunil\OneDrive\Documents - Sunil Chauhan\Desktop\wekan\bundle> start-wekan.bat
> start-wekan.bat : The term 'start-wekan.bat' is not recognized as the name of a cmdlet, function, script file, or
> operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
> again.
> At line:1 char:1
> + start-wekan.bat
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (start-wekan.bat:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> 
> Suggestion [3,General]: The command start-wekan.bat was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\start-wekan.bat". See "get-help about_Command_Precedence" for more details.
> PS C:\Users\sunil\OneDrive\Documents - Sunil Chauhan\Desktop\wekan\bundle>

**Comment by xet7** [comment]
@sunilnc 

In that directory, try this, what does it show?
```
.\start-wekan.bat
```

**Comment by xet7** [comment]
@sunilnc 

For backup, download MongoDB tools from https://www.mongodb.com/try/download/database-tools

Make backup of database with this command:

```
mongodump
```
If you sometime need to restore, when start-wekan.bat is not running, run this command:
```
mongorestore --drop
```
MongoDB database is running at default port 27017. If it were some other port, that would have to be defined, like `mongodump --port 27019` , like with WeKan Snap version.

Then there can be attachments at previous directory, because there is writable directory setting at start-wekan.bat:
```
SET WRITABLE_PATH=..
```
So, there could be filed directory at wekan directory
```
Desktop\wekan\files\attachments

Desktop\wekan\files\attachments

Desktop\wekan\files\bundle
```

The reason why running `wekan.bat` did not work at first, is because you used PowerShell as Administrator. At PowerShell, running commands needs prefix `.\`  , like `.\wekan.bat\` . If you had started cmd.exe as Administartor , there running command `wekan.bat` would have worked OK.

**Comment by xet7** [comment]
One way to make installing at Windows easier, would be if I would make some GUI, where is button for downloading newest WeKan, input field for port, button for backup, etc.

**Comment by sunilnc** [comment]
@xet7 I agree, that would be awesome. 

If I were to move the entire folder onto another PC, change the IP in the wekan-start.bat file, wouldn't the same instance work anywhere?

**Comment by sunilnc** [comment]
@xet7 If I wanted to use my Gmail, what do I need to configure here?

REM # https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
REM SET MAIL_URL=smtps://username:password@email-smtp.eu-west-1.amazonaws.com:587/
REM SET MAIL_FROM="Wekan Boards <info@example.com>"
REM # Currently MAIL_SERVICE is not in use.
REM SET MAIL_SERVICE=Outlook365
REM SET MAIL_SERVICE_USER=firstname.lastname@hotmail.com
REM SET MAIL_SERVICE_PASSWORD=SecretPassword

**Comment by xet7** [comment]
@sunilnc

You can try, does Gmail work:

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#gmail

I use AWS SES:

https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses

**Comment by xet7** [comment]
Problem with Gmail could be rate limits, if WeKan would send too many email notifications.

**Comment by sunilnc** [comment]
> @sunilnc
> 
> You can try, does Gmail work:
> 
> https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#gmail
> 
> I use AWS SES:
> 
> https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses

Thanks. I don't plan on sending many emails. 
So if I've understood correctly, I can just replace all this:
```
REM # https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
REM SET MAIL_URL=smtps://username:[password@email-smtp.eu-west-1.amazonaws.com](mailto:password@email-smtp.eu-west-1.amazonaws.com):587/
REM SET MAIL_FROM="Wekan Boards [info@example.com](mailto:info@example.com)"
REM # Currently MAIL_SERVICE is not in use.
REM SET MAIL_SERVICE=Outlook365
REM SET MAIL_SERVICE_USER=[firstname.lastname@hotmail.com](mailto:firstname.lastname@hotmail.com)
REM SET MAIL_SERVICE_PASSWORD=SecretPassword
```

With this:
`set wekan mail-url='smtp://myemail@gmail.com:apppassword@smtp.gmail.com:587'
`

**Comment by xet7** [comment]
@sunilnc

Use this syntax:
```
SET MAIL_URL=smtp://myemail@gmail.com:apppassword@smtp.gmail.com:587
```

**Comment by xet7** [comment]
@sunilnc 

Meteor 2 based WeKan uses versions of Node.js and MongoDB that are listed at https://wekan.github.io/install/ . It is not compatible with newer versions, using those would require figuring out how to upgrade to Meteor 3, that is currently using Node.js 22, and maybe also MongoDB 8 https://docs.meteor.com/history . 

Upgraging to Meteor 3 may require many changes: https://v3-migration-docs.meteor.com

I have not tested, does Meteor-Files work with Meteor 3 yet, so that uploading files would be possible https://github.com/veliovgroup/Meteor-Files/pull/884

Alternatively, I have many prototypes of WeKan in different programming languages, it depends do they get enough progress to get full-featured, or is it possible to change one part at a time as internal changes to WeKan, while still keeping all the same features.

There are plans to change to different database, because MongoDB has SSPL license, it is not Open Source. It is related to making progress with standard for public code: 

https://wekan.github.io/standard-for-public-code/

One way would be to to replace MongoDB with FerretDB, if it sometime becomes compatible, but previously when I tried, it did not work yet:

https://forums.meteor.com/t/ferretdb-1-18-now-has-oplog-support-trying-replace-mongodb-6-x-with-ferretdb-postgresql-or-ferretdb-sqlite/61092

**Comment by sunilnc** [comment]
@xet7 
Hey, thanks for your support so far.
Do you know how I can set up multiple workspaces which contain boards? Similar to what Trello does?

**Comment by sunilnc** [comment]
> @sunilnc
> 
> For backup, download MongoDB tools from https://www.mongodb.com/try/download/database-tools
> 
> Make backup of database with this command:
> 
> ```
> mongodump
> ```
> 
> If you sometime need to restore, when start-wekan.bat is not running, run this command:
> 
> ```
> mongorestore --drop
> ```
> 
> MongoDB database is running at default port 27017. If it were some other port, that would have to be defined, like `mongodump --port 27019` , like with WeKan Snap version.
> 
> Then there can be attachments at previous directory, because there is writable directory setting at start-wekan.bat:
> 
> ```
> SET WRITABLE_PATH=..
> ```
> 
> So, there could be filed directory at wekan directory
> 
> ```
> Desktop\wekan\files\attachments
> 
> Desktop\wekan\files\attachments
> 
> Desktop\wekan\files\bundle
> ```
> 
> The reason why running `wekan.bat` did not work at first, is because you used PowerShell as Administrator. At PowerShell, running commands needs prefix `.\` , like `.\wekan.bat` . If you had started cmd.exe as Administartor , there running command `wekan.bat` would have worked OK.

So I rang mongodump but it's throwing a 'mongodump' is not recognized as an internal or external command, operable program or batch file. Any ideas?

**Comment by xet7** [comment]
@sunilnc 

## PowerShell

Requires starting command with `.\`  in directory where is mongodump.exe, for example,

Backup:
```
.\mongodump.exe
```
Restore:
```
.\mongorestore --drop
```

## cmd.exe 

Backup:
```
.\mongodump
```
Restore:
```
.\mongorestore --drop
```

**Comment by xet7** [comment]
@sunilnc

> Hey, thanks for your support so far.

Thanks! There is 2 kinds of support:

a) Free Public Open Source support here at issues. I help anyone to get WeKan installed and running. I also help Open Source contributors to get started.

b) Private Paid Commercial Support for Support/Features/Fixes/Hosting at https://wekan.team/commercial-support/ . All features and fixes are added to Open Source MIT license version, that has all Enterprise features for all platforms at this GitHub repo https://github.com/wekan/wekan . Everything is Open Source, there is nothing propietary.

> Do you know how I can set up multiple workspaces which contain boards? Similar to what Trello does?

Currently there is All Board page, there is not separate workspaces yet. I think maybe need to add workspaces sometime.

In theory, at Admin Panel / People, you could add some Organization or Team, and then at each Admin Panel / People / People add each user to some Organization or Team, and then add that Organization or Team to some boards. But, that does not work well yet, because when removing some people from Organization or Team, boards memberships do not yet yet updated correctly. And explaining all this is already too complicated.

When someone logins to WeKan, by default there is no boards visible. It's possible to invite someone to board using right sidebar, adding by email address, or clicking at user list.

I do have some prototype ( https://github.com/wekan/weror ) , where is workspaces, but it does not have enough features to be usable yet, there is no user management etc all other features.

In future, there will be many features and fixes added, something similar what exists at Trello/Jira/ClickUp etc, but simpler, because Trello/Jira/ClickUp has many duplicate menus https://github.com/wekan/wekan/wiki/Design-Principles

**Comment by sunilnc** [comment]
hi @xet7 
Thanks for your support so far. I'm using this personally, not as a business. I want to reduce my reliance on Trello and store my data locally. Before I do a full migration, I want to make sure the backup and restore features work as expected before I transition.

I have tried the mongo backup command and it worked. As in it created a directory with the backup. Hoever, I am having issues with the restore.

This is what I did:
1. Ran wekan-start.bat
2. Created a bunch of test boards and cards.
3. I ran the backup command and created a dump.
4. I then deleted a bunch of boards.
5. I then stopped the wekan-start.bat script.
6. I ran the restore script, but it did not restore the boards I deleted earlier.

What am I doing wrong?

**Comment by xet7** [comment]
@sunilnc 

What commands you used for backup and restore?

**Comment by sunilnc** [comment]
@xet7 

.\mongodump.exe
.\mongorestore.exe --drop

**Comment by xet7** [comment]
Hmm, I don't know.

Does someone have any ideas?
