### ISSUE TITLE
Manually create users in MongoDB

### ISSUE THREAD

**Issue by Bimbam360** [wekan/wekan#629]
Is there a format for manually creating users directly in MongoDB and completely omitting the need for email?

I tried db.createUser({ user: "user", pwd: "password", roles:["readWrite", "dbAdmin"] } ) on a whim but this just gives me 'Login Forbidden' at the login page.

Thanks

**Comment by mquandalle** [comment]
You can’t create users like that because the password isn’t stored in clear in the database, and so basically the passwords doesn’t match—also the document structure you provide isn’t the one we use in Wekan/Meteor. Until we have a more direct API, the easiest way to import users would be to use the `createUser` method of a DDP client that you will have to point to the running Wekan server.

**Comment by xet7** [comment]
Use REST API:
https://github.com/wekan/wekan/wiki/REST-API#example-of-all-steps-of-create-user
