### ISSUE TITLE
LibreBoard logo design

### ISSUE THREAD

**Issue by yasaricli** [wekan/wekan#64]

**Comment by iraycd** [comment]
@yasaricli I will make the logo. How do you want it to be?

**Comment by iraycd** [comment]
Variations: I thought material design would be good for this. So made it something like this.

## 1
![logo](https://cloud.githubusercontent.com/assets/1450984/5642650/2f2d02ac-9673-11e4-9817-96b2ffb10d16.png)
## 2
![logo 2](https://cloud.githubusercontent.com/assets/1450984/5642647/2f2a58b8-9673-11e4-8bb6-614857547082.png)
## 3
![logo 3](https://cloud.githubusercontent.com/assets/1450984/5642649/2f2c88b8-9673-11e4-9fe2-7296c382ec06.png)
## 4
![logo 4](https://cloud.githubusercontent.com/assets/1450984/5642648/2f2bd2d8-9673-11e4-8df7-8ff315f5b6a8.png)
## 5
![logo 5](https://cloud.githubusercontent.com/assets/1450984/5642646/2f27819c-9673-11e4-8595-6807460c38b1.png)
## 6
![logo 6](https://cloud.githubusercontent.com/assets/1450984/5642651/2f2e5af8-9673-11e4-8927-b88ce2194d7c.png)

**Comment by yasaricli** [comment]
Hello; 

a friend of mine is also working on log. Thanks.

**Comment by iraycd** [comment]
@yasaricli Okay.

**Comment by yasaricli** [comment]
Thank you my Friend [Ekrem](https://www.facebook.com/ekremates10). 

All logos

Social Avatar :+1: 

![libreboard](https://cloud.githubusercontent.com/assets/1306620/5644002/631076be-9667-11e4-8fad-b9462c3be723.png)

Site logo :+1: 
![logo](https://cloud.githubusercontent.com/assets/1306620/5644274/6c76d114-966a-11e4-9671-1f951fa90690.png)

**Comment by orges** [comment]
I think it's fancy :) i liked it

**Comment by yasaricli** [comment]
@orges :+1:

**Comment by iraycd** [comment]
@yasaricli Loved it. :+1: Cool.

**Comment by mquandalle** [comment]
I tend to uppercase the letter B to make the name easier to understander Libreboard — LibreBoard

This is also what other do:
![libreoffice-banner](https://cloud.githubusercontent.com/assets/1730702/5675061/146b741e-97b6-11e4-8ab8-8731f62e0507.png)

Let's pick a convention and stick with it!

**Comment by orges** [comment]
I think it's a good point! When i write libreboard i always feel writing it as LibreBoard is better. It emphasis on the Libre as an adjective and Board as the main functional unit..
But also if we write it like Libreboard it sounds like a board of liberty, emphasing Liberty and a place to show it...
Also i vote for LibreBoard with capital "B" but i can't imagine how it will look like...

**Comment by mquandalle** [comment]
Also, I believe there are some copyright issues — http://designshack.net/design/pigeon

**Comment by fjaguero** [comment]
What about using another font (while matching the core identity values) to add a +1 on the Trello differentiation effort?

**Comment by Narno** [comment]
@yasaricli "Pigeon, Logo for political party." https://dribbble.com/shots/746215-Pigeon

**Comment by gomex** [comment]
:+1:

**Comment by Squ34k3rZ** [comment]
![libre](https://cloud.githubusercontent.com/assets/4743518/6055014/2de73af2-acbc-11e4-94a5-6c45388e96cd.png)

**Comment by erlend-sh** [comment]
@yasaricli it appears your friend did not make that logo. Leaving aside the fact that this is dodgy practice, that logo needs to change asap before you guys get into legal troubles again.

How about a stack of cards/post-its? Here are some free examples (so you can use them as-is or modify them if you'd like).

https://openclipart.org/detail/183333/cube-notes-by-crisg-183333
![](https://openclipart.org/image/300px/svg_to_png/183333/cube-notes.png)

https://openclipart.org/detail/45841/sticky-note-green-folded-corner-by-palomaironique
![](https://openclipart.org/image/300px/svg_to_png/45841/Sticky-Note-02-Green.png)

https://openclipart.org/detail/140227/stack-of-unlined-colored-index-cards-by-snifty
![](https://openclipart.org/image/300px/svg_to_png/140227/stack-of-unlined-colored-index-cards.png)

**Comment by dalerka** [comment]
Hey guys! I'm not a designer, but I've tried to explore some ideas (the feeling/meaning of "Liberty" and a "Tool to explore & deliver" and a "Journey from point A to B" ) and came up with the following  logo design (proposal). So, if anybody likes this idea and can design a logo upon it, I'd be very happy. :) 

![image3047](https://cloud.githubusercontent.com/assets/3251602/6198570/0d0e1adc-b435-11e4-9450-e61519d56bc9.png)

**Comment by ePirat** [comment]
Quick adaption of the Cube Notes: 
![CubeNotes Adaption](https://cloud.githubusercontent.com/assets/323210/8146151/6ef36d9e-122a-11e5-9ee2-f0dbe671d4e7.png)

**Comment by erlend-sh** [comment]
:+1:

**Comment by ePirat** [comment]
I think if the current logo really is a problem, we should sort it out before the next release, as else it will just confuse more if we change the logo not at the same time as we changed the overall design.

**Comment by ocdtrekkie** [comment]
@ePirat I definitely agree.

**Comment by ocdtrekkie** [comment]
I think @neynah may be interested in this thread.

**Comment by neynah** [comment]
Thanks @ocdtrekkie 

Hi all! I am the designer at Sandstorm.io. This is a very relevant discussion to me as I also found the existing LibreBoard logo on a Dribbble user's portfolio and decided that I should not use it to represent the app on Sandstorm. Here are the variations I have come up with (sharing for the first time).

Option 1: New design altogether
![libreboard-preview1](https://cloud.githubusercontent.com/assets/855341/9509585/46214b5e-4c16-11e5-9eee-4b510a9f6091.png)

Option 2: Existing plain text logo (which I assume does not have copyright issues) with a nice gradient bg
![libreboard-preview2](https://cloud.githubusercontent.com/assets/855341/9509594/5b71e360-4c16-11e5-82c6-f8369449e9ee.png)

Option 3: I'm very much open to suggestions and am happy to volunteer my time to design something so we can get this on the new App Market ASAP. :)

**Comment by mquandalle** [comment]
I wanted to make this announcement in due form at the v0.9 release time, but I will share my idea now (2am here in France :)) in favour of saving everyone's time. Here is the thing, I would like to re-brand the project from “LibreBoard” to “Wekan”.

Yasar the originally author of this application originally named it Metrello because it was a Trello clone made in Meteor. Trello wasn't happy with that and asked us to rename the project. I first thought of "OpenBoard" (because well it's an open-source board) but because the dot com domain name was already taken, I replaced the word “Open” by “Libre” which is free as in freedom in some Latin derived languages (including French). The whole naming process took something like 10 minutes.

It turns out this name is pretty difficult to remember (when I talk to some people about this project, they always forget how it was called) and I've seen quite a few person on reddit/twitter (and also #sandstorm IRC if I recall correctly) that says we should stop naming our project "LibreSomething".

I think that my proposition, Wekan, is shorter to type and more memorable (of course if you are used to the name LibreBoard you may dislike it :)). This is a name includes both the idea of collaboration "We" on a "Kan"ban software. I also bought this logo:

![wekan colors](https://cloud.githubusercontent.com/assets/1730702/9509810/68ce5b08-4c64-11e5-864c-2ac487ba9ee3.png)

The slogan/catchphrase could be something like “Wekan — organize anything”

Any feedback about this re-branding idea? If people don't like it, I can very well change my mind. Also about the logo I'm open to alternatives, especially since I currently don't have a good “square icon”.

Of course the project will stay open-source, just because a Firefox isn't called LibreBrowser doesn't mean it is not free as in freedom :)

**Comment by mquandalle** [comment]
Also @neynah, I really like all your work, both here and on sandstorm :-) The re-branding is not a blocker, I could publish at least a beta under current LibreBoard name using either option 1 or 2.

**Comment by ePirat** [comment]
@mquandalle Wow I think that is a great idea and the proposed logo looks great and catchy!

**Comment by neynah** [comment]
@mquandalle I appreciate that. Perhaps we can wait a day or so to see what the consensus is. If you'd like to go with Wekan then I think we should publish the app under Wekan. The downside to publishing the app as LibreBoard with LibreBoard branding is that once it's updated to Wekan, it will be difficult to find/identify. Some users may think "what happened to LibreBoard?"

If you could share the source file for the logo I'd be happy to provide some square logo options based on what you have.

**Comment by mquandalle** [comment]
That's super kind to you Néna, I sent you the AI source on a sandstorm grain. And if you have a genius idea, please share, I'm completely open to changes.

**Comment by nata-goddanti** [comment]
You know, when I am repeating this "WeKan"  in my head, the image I see is Obama's 2008 campaign slogan "Yes we can". I am not sure if it only me or rest of folks in US feel the same. I am not sure if it is good or bad thing in terms of branding a open source kanban board - I mean in the right instances it might be a good thing as there is already name recognition

I got this idea of using some kind of metaphors instead that creates images of organizing, like Hive or OpenHive or kanHive or kanbanHive... There is this french word that chefs use to organize the ingredients "Mise en place" , we can appropriate that word in some fashion and kind of make as a brand. Just my 2 cents...

![image](https://cloud.githubusercontent.com/assets/203255/9511247/6cdbd5da-4c29-11e5-9731-80b8efe5af4f.png)

**Comment by neynah** [comment]
FWIW: when I and others at Sandstorm read "WeKan," Jade said "Oh, like a kanban board." I also made the same connection in my head and hadn't thought of Obama's campaign- though if it had the word "Yes" in front of it I definitely would have. Maybe this is different for others.

@mquandalle  If we go with WeKan branding, we can always improve the graphics later. The important part(in the context of Sandstorm) is to have it in the App Market by Sunday so that it will be ready for Launch. However, if we get the SPK package sooner we will have time to test it thoroughly.

For the sake of time, I created a preview of the app graphics using the source file you sent me. I'll create a pull request shortly for 2 sets of graphics so that you'll have graphics available whether you decide to go with LibreBoard branding or Wekan branding.

![wekan-preview1](https://cloud.githubusercontent.com/assets/855341/9532416/66ead72e-4cc0-11e5-9c2c-e1176875d029.png)

**Comment by fjaguero** [comment]
Looks really neat @neynah :smile:

**Comment by neynah** [comment]
Thanks @fjaguero !

I also came up with a slight improvement for LibreBoard which I think is pretty cool- but my opinion is biased.

![libreboard-preview3](https://cloud.githubusercontent.com/assets/855341/9533246/901f6e02-4cc5-11e5-84e8-0e10e093cf01.png)

**Comment by mquandalle** [comment]
This is indeed very cool @neynah :-) Would that concept work with the Wekan name?

**Comment by orges** [comment]
These are really great!!! @neynah

**Comment by guarilha** [comment]
awesome work, @neynah!
love the second concept...

**Comment by neynah** [comment]
@mquandalle

I rounded the edges of the square outlines to better match the type. My only issue with this is that "We" is not super legible due to the e being attached. But the source file has the entire type logo outlined so I won't be able to change that without some surgery. (But maybe you think it's OK as it is.)

![wekan-preview2](https://cloud.githubusercontent.com/assets/855341/9533810/5f5c4ba6-4cc9-11e5-93c5-2eccadcb4d3a.png)

**Comment by nata-goddanti** [comment]
Nice work @neynah  Looks good.  How about using 'Wk' instead, if 'e' is not legible....

**Comment by neynah** [comment]
@nata-goddanti I gave it a shot but I don't think the k flows as smoothly. (Probably because the typography wasn't originally designed for this.)

![wekan-preview3](https://cloud.githubusercontent.com/assets/855341/9534971/c0a9caf2-4cd1-11e5-9ef3-3a7e7c7e2e3e.png)
)

**Comment by nata-goddanti** [comment]
oh ok...I see what you are saying. I confess  the word it is kind of growing on me :-)

**Comment by fjaguero** [comment]
+1 for the "We" since the logo has more whitespace as @neynah said.

**Comment by neynah** [comment]
Thanks for all the feedback everyone. I'm in a rush so I went ahead and created PR #247 with the blue tron-like graphic sets for LibreBoard and Wekan. I exported for Sandstorm purposes but they're editable so feel free to play around with them for other purposes. If you're having trouble, let me know. :)

@mquandalle we're excited to see this on the App Market soon! :D

![image](https://cloud.githubusercontent.com/assets/855341/9535493/d01f37ba-4cd6-11e5-8aaf-0be686f03f42.png)

![image](https://cloud.githubusercontent.com/assets/855341/9535504/f2e94b6e-4cd6-11e5-9b71-0c98ab30c3be.png)

**Comment by nata-goddanti** [comment]
awesome work @neynah  :+1:  :+1:

**Comment by mquandalle** [comment]
Awesome Néna, I'll merge the wekan logo as part of the upcoming re-branding (by the way I'm dubious we had the right to use the Libreboard font).

I'm also in a rush to fix remaining bugs, but that will be ready for the Sandstorm app market launch.

Thank you very much :)

**Comment by ePirat** [comment]
@mquandalle So it's official now? Can I rename Libreboard to Wekan in the Wiki?

**Comment by mquandalle** [comment]
Yes. I'll probably re-brand tomorrow.

**Comment by mquandalle** [comment]
Done.
