### ISSUE TITLE
Community governance of Wekan?

### ISSUE THREAD

**Issue by brylie** [wekan/wekan#640]
Given a recent silence from @mquandalle, specifically regarding the card Todo list feature, it may be timely that the Wekan community discuss forking the project, or at least transforming the Wekan governance structure. 
- What would be some goals and impacts of a fork?
- What type of governance structure would the community like to build?

**Comment by JoseVega** [comment]
I am interested. I´ve been following wekan very closely for the last 7 months waiting for some bugs to be fixed , but it seems to be abandoned. No significant changes in over 6 months.

**Comment by xet7** [comment]
@mquandalle 's latest comment on GitHub is just 5 hours ago:
https://github.com/oblador/react-native-vector-icons/pull/247

And  contributing to Wekan seems to require CLA like this:
https://cla-assistant.io/wekan/wekan?pullRequest=639

So while license is MIT:
https://github.com/wekan/wekan/blob/devel/LICENSE

I don't know how CLA affects license, I'm not license expert.

Then it seems that because wekan has 916 forks, lots of customization and feature additions are made all around, but they are not combined to main repo.

There's a roadmap here:
https://wekan.io/b/MeSsFJaSqeuo9M6bs/wekan-roadmap

But I don't know is that roadmap up-to-date, and what core developers priorities are right now.

**Comment by ocdtrekkie** [comment]
@mquandalle is likely busy or otherwise disposed, I assume. People get burned out doing solo management of a project like this. I don't think this was a full time gig for them. As to whether or not you should fork, I abstain.

CLAs are effectively a way to prevent a contributor from coming back and suing claiming their rights were violated or some such down the road. But the project is licensed MIT and can be forked like any other MIT licensed code.

Note that generally trademark doesn't go with code, so if you forked you would need to call it something else.

**Comment by AlexanderS** [comment]
*Wekan* is already an organization account. @mquandalle could add people to the wekan organization, so that more people can help with the management of the project. @mquandalle could still set the long term development goals, but for example simple bug fixes and release management could be handled by someone else.

**Comment by ocdtrekkie** [comment]
Sure, @AlexanderS, it depends what @mquandalle wants to do. Adding people willy-nilly has security risks, figuring out delegation is still potentially a lot of effort and time. It's really hard to suggest a path to follow without an opinion from the project's maintainer and those people who care and would put in the effort to work on this project. (At the end of the day, I _personally_ don't care what anyone does, really, because the current Sandstorm package of Wekan does everything I need.)

**Comment by JoseVega** [comment]
I agree with @ocdtrekkie , I think the current package is pretty good , I´m interested in fixing just a few bugs so I dont think a big fork is necessary. Maybe @mquandalle can streamline the process for contributions and tell us the state of the project.

I understand he might be busy or he can´t afford to spend more time on the project , so maybe we can pay him for his time to review and accept a few patches.

**Comment by mquandalle** [comment]
@xet7, as @ocdtrekkie pointed out, the CLA is by no way here to restrict user rights on the code, including the right to modify it. Wekan is released under the very liberal MIT license, which allows forks and even re-licensing.

I wouldn’t mind if there were a strong push for a community-governed fork, as the code could still go back and forth between the two “branches”. However that is a suboptimal model that would consume developers and confused users time, it would be better if people could be satisfied with the governance of this original Wekan repository.

One of the reason I failed to merge recent contributions, is because I focused on making a modular Wekan (basically what I have described [here](https://discuss.wekan.io/t/rfc-the-plugin-system/132)). A lot of different users want to write specific features and integrations, and a model where they can build and maintain these as plugins on top of a small core is appealing. I spent a lot of time trying to build that model, but I think I got lost in my will to rewrite everything. Especially when I tried to use cutting-edge tools (like GraphQL). Writing an open-source platform with a market store where people can publish an install plugins is much harder that I hoped. And @ocdtrekkie is also right that I got burnt doing solo development on Wekan for 18+ months, and I one point I stopped reading the notifications that came all day.

My long-term vision is remain pretty clear, which is to make Wekan an open platform for project management. I failed at my rewrite-everything solo plan. So I’m going back to my code-review homework, and I’ll try to associate other developers in the long-run.

**Comment by AlexanderS** [comment]
@mquandalle Is there somewhere something of your "rewrite-everything solo plan" available, so that maybe other people can help?

**Comment by brylie** [comment]
>  it would be better if people could be satisfied with the governance of this original Wekan repository.

@mquandalle what process should we follow to add people to the Wekan organization as managers?

Should we have a brief election to add, for example, two more people as community maintainers of the Wekan organiation?

**Comment by brylie** [comment]
I would like to propose a process we could initially follow:

1. members of the Wekan community nominate one or more persons other than themselves to be part of the 'Wekan governance team'
2. we cast votes for the nominated people, e.g. using Github reactions (thumbs up only)
3. the top two voted members will become part of the initial 'Wekan governance team'

**Comment by brylie** [comment]
I have opened a [thread on the Wekan discussion platform](https://discuss.wekan.io/t/wekan-community-governance-process/331).

**Comment by davidmabelle** [comment]
So appreciate the 18 months of work @mquandalle put in to Wekan.   Just for a bit of Humor - We Kan for me is We Can - We Can community seems happy to support you if you guide us.  I may also put some financial support to you if that would be useful.  Maybe even a crowd funding campaign for @mquandalle.  I would also love to see it be a team effort since so many have already forked to simply share with them the precise requirements/standards for getting their forks merged.  Feel free to call me if you want to discuss US +1 (424) 229-2363 or UK +44 (0) 7774411186.  WIth deep gratitude for your work - and the very best of regards.  David

**Comment by lkisme** [comment]
Interested with this.

**Comment by brylie** [comment]
I nominate @lkisme for membership to the 'Wekan maintainers' team.

If you agree with this nomination, please react to this comment with a 'thumbs up'.

**Comment by pierreozoux** [comment]
@brylie why not for @lkisme but a rapid look at https://github.com/wekan/wekan/graphs/contributors doesn't show any contribution?

**Comment by brylie** [comment]
I nominated @lkisme because they have an open pull request, showing active contributor status.

@pierreozoux perhaps you could nominate someone from the contributors list as well?

**Comment by ocdtrekkie** [comment]
I would suggest starting with @mquandalle's last comment here: A community-governed fork. Get everything set up and working, bring in the open PRs. Keep everything as aligned with the original repository as possible, submit PRs for changes made to the community fork to the main Wekan repository, so it is possible to sync them up at a later date if possible. Keep the differences well-documented, especially when it comes to data portability.

Who runs the official repo of course, remains up to @mquandalle, but I imagine a well-running, well-supported fork would likely demonstrate best who is adequate to assist in maintaining the official repo, if that decision gets made.

The other person I'd recommend you keep in the loop is @dwrensha from Sandstorm.io. I'm not sure how many people percentage-wise of the Wekan community uses Sandstorm to host it, but it's a core app for Sandstorm, and there's a key trust relationship in terms of what version gets published and pre-installed for Sandstorm users.

**Comment by koorg** [comment]
As a simple wekan user (promoting it to our teams), I'm really waiting for the community-driven fork.
With over a thousand forks, please explicitely state which fork will be centralizing all the efforts :smiley: thanks !!

**Comment by brylie** [comment]
@koorg thanks for your input. I think we need a shared organization for the community fork.

Does anyone have any proposals for a shared organization, or at least a name of a new organization, for the community fork?

**Comment by brylie** [comment]
> I wouldn’t mind if there were a strong push for a community-governed fork, as the code could still go back and forth between the two “branches”. However that would be a suboptimal model consuming both developers and confused users time, it would be better if people could be satisfied with the governance of this original Wekan repository.
>
> - @mquandalle 

@ocdtrekkie what I think @mquandalle was saying is that it would be preferable if we nominate community stewards for the Wekan organization/repository, as opposed to a community fork.

@mquandalle do I understand you correctly? If so, would you be willing to grant administrative rights to the Wekan organization for one or more persons nominated to be community maintainers?

**Comment by robisson** [comment]
Hello everyone,
    I found this project a few days and I was really interested in contributing, either to the current roadmap or any other. Continuity was given to this matter?

**Comment by ocdtrekkie** [comment]
@robisson There's a ton of active interest in Wekan and contributing to Wekan, so I have no doubt that this project will continue, but in the apparent absence of @mquandalle, everything is probably pending someone stepping up and creating a fork and reviewing and integrating the open PRs into it.

I have a strong interest in Wekan's continuity and success, but since I am not familiar with it's code, and am not much of a developer, I'm hoping other people move on this.

In the meantime, if you have contributions, please do open PRs on wekan/wekan here, as this is both the initial source any well-managed forks would start from, and I'd also hope that PRs continue to be opened here for if and when the official repo comes back to life.

**Comment by robisson** [comment]
I understand that the author lost a little in project management, even by the proportion that took. But the project is excellent. For me only needed a plugin system and an API. And from what is already in admin plans as described [here ](https://discuss.wekan.io/t/rfc-the-plugin-system/132)in a well structured manner. Then I let go, and I will send some PR when I think it will be good for the project

**Comment by pierreozoux** [comment]
Ok, we have a fork \o/

https://github.com/wefork/wekan

Sorry for the organisation name... I just found that.
I invited all people that made PR.
(Sorry @brylie and @lkisme I didn't see)
(If I forgot you, please do not hesitate to ping me)

All members are admin, I put it more open at the beginning, but we can restrict later.

If you have any questions, please open an issue in the new repo.
And I created a chat channel here:
https://chat.indie.host/channel/wekan (using Rocket.Chat an other great meteor project)
And you have an open wekan instance here:
https://wekan.indie.host

I'll not contribute code, but I offer hosting for it, so that's why I'm interested this project going further.
(And I can't resignate going to use kanboard php...)
I can take care of the docker image.
Hope it helps!

**Comment by soohwa** [comment]
Hi ! For those who are interested in a installation for Debian Wheezy 64 bit, this is a doc at my repository :  https://github.com/soohwa/sps/blob/master/example/docs/1/wekan.md

**Comment by tchncs** [comment]
Are there plans for the master branch and releases related to the fork?

**Comment by pierreozoux** [comment]
@tchncs Not really, but you are more than welcome to come and participate :)

**Comment by brylie** [comment]
We need to get some pull requests opened and review in the Wekan community fork. Then, we can issue a release.

**Comment by fmonthel** [comment]
Hi @pierreozoux - is it scheduled to have docker image on docker hub for wekan wefork image?
We're using docker compose so should be helpful
Thanks

**Comment by brylie** [comment]
@fmonthel would you mind opening an issue in the [Wefork/wekan repository](https://github.com/wefork/wekan)?

**Comment by fmonthel** [comment]
Done : https://github.com/wefork/wekan/issues/33

**Comment by mquandalle** [comment]
Hi, it seams that you have made some progress in the fork. @xet7 would you be interested to get admin access on this wekan/wekan repository? Or should I delegate that role to someone else?

**Comment by pierreozoux** [comment]
@mquandalle indeed, @xet7 looks the most appropriate person to get admin access here to move back the fork to the original repo.

Thanks @mquandalle to take time to tackle this issue! And all the best!

**Comment by xet7** [comment]
@mquandalle 

Yes, you can add me as admin, I will then merge all changes back. Thanks!

**Comment by xet7** [comment]
I got access to Wekan 2 days ago, and now I'll start merging.

**Comment by ocdtrekkie** [comment]
I am pretty excited to see the fork merging back into the master.

**Comment by fmonthel** [comment]
Good to know !

**Comment by soohwa** [comment]
@mquandalle @xet7 Thanks !

**Comment by manuelsongokuh** [comment]
@mquandalle @xet7 thank you but thank you also all people who wanted to continue project wekan/wefork..!!

**Comment by xet7** [comment]
@Danny4927 asked at chat: "Hi. I want to install wekan with the docker image, but the readme says it needs to be updated can i get updated instructions anywehere? This image: https://hub.docker.com/r/mquandalle/wekan/ uses wefork...can i use the official one?"

When I looked at Docker Hub, it seems that official Wekan docker image was built as trusted build when I merged Wefork to Wekan yesterday:
https://hub.docker.com/r/mquandalle/wekan/tags/
I can see it from size: latest build is 88 MB and previous build is 258 MB.

Could somebody test does it work? I'll also try myself soon.

**Comment by mquandalle** [comment]
So @xet7 is now a Wekan admin, and he has already merged back the wefork/wekan repository and started to tackle issue triage. It's so great to have an active maintainer again, warm thank you @xet7.
I wonder @xet7, are you using the Sandstorm integration or are you only self-hosting Wekan?

@kentonv If I want to authorize a trusted third-party to release new versions of the Wekan spk, is the only way to transmit my app private key or is there now an option to have multiple authorized private keys?

**Comment by ocdtrekkie** [comment]
@mquandalle AFAIK, @xet7 does not use the Sandstorm flavor.

Re: Sandstorm, @dwrensha utilized a key replacement feature of Sandstorm to allow a key controlled by him to issue releases of Wekan for Sandstorm. This feature could be used again to allow someone else's key to be officially supported for Wekan releases. Although this may not be necessary if David intends to continue publishing Wekan releases going forwards. On Wefork he had commit rights to push Sandstorm-specific code directly.

**Comment by dwrensha** [comment]
@mquandalle We've already authorized a new key so that we could release new SPKs: https://github.com/sandstorm-io/sandstorm/commit/0574fbfa0527ea09e8878c771fefc80a43510c46. (I'm not sure whether you received the email I sent you about this on 1 November 2016.)

The cleanest way to allow someone else to make releases is to transfer the app private key. Adding an entry to appid-replacements.capnp, as we've done in your case, is currently the only other option.

**Comment by xet7** [comment]
@mquandalle 

Thanks! I do have both Sandstorm server and self-hosted local Wekan installed. In contributions I have tested more at self-hosted side, mostly VirtualBox appliance at https://wekan.xet7.org .

@dwrensha has made Sandstorm fixes, releases, etc.

I have not yet looked how to create spk packages, I have issue here:
https://github.com/wefork/wekan/issues/36

**Comment by xet7** [comment]
I think that in near future it'll be the same, I'll be maintaining self-hosted side and @dwrensha Sandstorm side. I do look from pull requests etc that is something makes sense for Sandstorm then enable it there based on environment variable.

For example in future, moving card to another board does not make sense for Sandstorm, because there   is only one board in use in one grain.

**Comment by kentonv** [comment]
@xet7 Possibly OT, but FWIW I think moving cards across boards would make sense for Sandstorm, but may need to be implemented differently. You could maybe do it with HTML5 drag-and-drop, or through the Powerbox.

**Comment by kentonv** [comment]
@mquandalle Great to hear from you! I hope you don't mind that we made an edit on the Sandstorm side permitting us to sign Wekan releases with a new key. We tried to contact you first, but didn't hear anything.

We did this so that we could push some interesting new Sandstorm integration features: You can now assign people to a card even if they've never visited the board before (through the identity-picker powerbox), and Wekan's activity feed now feeds into Sandstorm and can generate notifications to users who don't have the board open.

**Comment by xet7** [comment]
@mquandalle 

Can you give me maintainer access to Wekan Transifex, so I can move newest translations from Wefork Transifex to Wekan Transifex?

**Comment by mquandalle** [comment]
@xet7 Sure, I've just done it. Sorry for not having thought of this before.

**Comment by xet7** [comment]
@mquandalle 

Would there sometime became any situation that I would need to do something at Docker Hub and have access there? It anyway seems that Wekan trusted builds are being generated automatically.

**Comment by mquandalle** [comment]
Yes, trusted builds are generated automatically, but there are some generals settings that might be changed at a latter point, so I'm sharing the access to DockerHub too. (Is your username `xet7` on DockerHub?)

**Comment by xet7** [comment]
@mquandalle 

Yes xet7 is my username at DockerHub.

**Comment by xet7** [comment]
@mquandalle 

I moved official chat to Vanila, we will get more developers from there:
https://chat.vanila.io/channel/general
New chat badge link is at:
https://github.com/wekan/wekan

Can you give me access to wekan.io domain? That new chat channel's user kinder is designing new updated website for Wekan.

**Comment by shtefcs** [comment]
Yeah, we moved the official chat to https://chat.vanila.io/channel/wekan as we already have 1600 registered members there, and they will help us push the project further.

@mquandalle  I am thinking of re-designing the homepage bit, add more content, optimize for SEO, Social etc.

**Comment by xet7** [comment]
@mquandalle 

Can you give me access to https://twitter.com/wekanApp ?

I was only able to tweet about new Wekan v1.11.1-rc1 using my own twitter account:
https://twitter.com/xet7

**Comment by xet7** [comment]
@mquandalle 

I don't yet have access to Docker Hub so I'm unable to tag releases.

**Comment by xet7** [comment]
Resolved:
- Wekan fork has been merged back to Wekan
- I have contact to @mquandalle 
- I have Twitter access
- I'm able to create Docker Hub tags to https://hub.docker.com/r/wekanteam/wekan
- @mquandalle did setup redirect of wekan.io to wekan.github.io we have access to change website
- Forum has been moved to free hosting, and Google/GitHub login works
- @dwrensha can do Wekan Sandstorm releases, that's enough for now

Closing issue.
