### ISSUE TITLE
Card pop-ups do not work - missing port in URL - wekan docker

### ISSUE THREAD

**Issue by jknaus** [wekan/wekan#679]
Hi,
I installed Wekan via Docker and it is accessible via port 8080.
All works fine so far, but whenever I click on a card or a link to a card, I get an error page.

```
Not Found
The requested URL /b/376rJEBudZNWRRvf3/welcome-board/cemsb5uBfbgYya788 was not found on this server.
```

This is because the `:8080` is missing in the URL to that card.
When I log in, I am on `http://<ipaddress>:8080/b/376rJEBudZNWRRvf3/welcome-board`.
However, clicking on a card invokes `http://<ipaddress>/b/376rJEBudZNWRRvf3/welcome-board/cemsb5uBfbgYya788` which results in the above error.
If I manually add `:8080` to the ipaddress all is fine. 

Is this a bug or have I misconfigured something?

Thanks for your help.

**Comment by mquandalle** [comment]
Absolute URLs such as the above card URL are generated from the `ROOT_URL` environment variable. Adding the following parameter to the docker CLI launcher: ` -e ROOT_URL=http://<ipaddress>:8080"` should fix your issue.

**Comment by jknaus** [comment]
Thank you! That solved it.

**Comment by C0rn3j** [comment]
For people running the snap and not the docker version - 

```
# as per wekan.help
snap set wekan root-url='http://192.168.1.68:8080'
```

Am kinda surprised I had to do this, especially since the port is already decided, but eh, gonna leave it here for those who ran into this before checking the help page.

**Comment by casperl** [comment]
I still have this issue with the latest WeKan Snap on Ubuntu 18.04.  SInce I am running Apache on the same server I am accessing Wekan with port 3001.  I did issue the snap command to set the port to 3001, and everything works barring opening the port for individual cards.  Manually inserting :3001 before the card URL does open the card, but it becomes tedious to do this for every card.  This must surely be a program bug, since lists and individual boards work perfectly with the correct port injected in their URL's.

This works: `http://wekan.local:3001/b/uC7nn8LWohAJbCDSb/krooninfo`
The individual card does not work: `http://127.0.0.1/b/uC7nn8LWohAJbCDSb/krooninfo/Zzof6XD4B6y5mSCi8`
Inserting :3001 into the URL does work: `http://127.0.0.1:3001/b/uC7nn8LWohAJbCDSb/krooninfo/Zzof6XD4B6y5mSCi8`

This has to be a bug and not a config issue.

**Comment by xet7** [comment]
@casperl 

Well, it is still a config issue.

https://github.com/wekan/wekan/wiki/Settings
