### ISSUE TITLE
Bad file name while attachment downloading

### ISSUE THREAD

**Issue by dinya** [wekan/wekan#698]
I'm attaching files to my cards with cyrillic symbols in file name. But the file name is correct in the card view, but it is wrong while download.

I use Wekan v0.10.1 under Ubuntu 14.04 and nginx (charset utf-8 in site settings)

![wekan_cyrillic_attachment](https://cloud.githubusercontent.com/assets/2182222/18900334/d4677a50-8559-11e6-92d6-211b1b5f5d14.png)

**Comment by gabrin** [comment]
Same trable

**Comment by xet7** [comment]
Could be related to this:
https://github.com/wefork/wekan/issues/87

**Comment by xet7** [comment]
Moved to #784

**Comment by Dudki01** [comment]
My issue is just the same with only difference is  that i cannot apply code fix to cfs_access-point.js because there is no such file. The structure of applications has changed since then, is there any ways to solve this promblem now?
![image](https://github.com/wekan/wekan/assets/18345675/4f37d2d9-49ab-43d1-9d43-dd3ae99918c2)
![image](https://github.com/wekan/wekan/assets/18345675/3042fd4b-32a7-4118-a18f-8d41654a8d5f)

Wekan 6.0.9 with snap. Ubuntu 22.

**Comment by ajimix** [comment]
I'm facing the same problem with spaces in filenames. `test file with spaces.pdf` becomes `test%20file%20with%20spaces.pdf`

Wekan 7.91 with snap. Ubuntu 22

**Comment by xet7** [comment]
This works at WeKan 9.04
