### ISSUE TITLE
[Feature Request] import cards from another board

### ISSUE THREAD

**Issue by Merlin90** [wekan/wekan#725]
Hello,
It would be nice to move cards from one board to another.

greetings

**Comment by soohwa** [comment]
Hi. I think you should post your feature request here at this fork : https://github.com/wefork/wekan
Regards

**Comment by ocdtrekkie** [comment]
Everyone on wefork is surely still reading here. This is probably fine. :)

**Comment by Merlin90** [comment]
Hi,
what is the difference between the original and the fork? Will the Fork have other features?

**Comment by ocdtrekkie** [comment]
@Merlin90 The maintainer of Wekan has been silent for a while, so a bunch of other Wekan users/developers are working on the fork so that new stuff can continue to be done. So yes, it should have newer features coming, whereas we cannot be sure the speed at which this project will progress. As I said though, everyone on the fork is subscribed to the original though, so your feature request should still be seen either way. But if you ever open a Pull Request, make sure to open it against the fork as well.

**Comment by Merlin90** [comment]
@ocdtrekkie Ah, ok! Is the Fork completely compatible with the original version? Can I update from the original version to the newer Fork version?

**Comment by ocdtrekkie** [comment]
@Merlin90 Yes, currently the fork is the same as the original plus a couple of relatively trivial fixes. Right now there is no major differences, but that will change over time, as the fork starts to add new features. The fork has not yet officially published a new release yet.

**Comment by mario-orlicky** [comment]
Hi, will the original repo(this) of wekan be up again or is this all abandoned? Any news?

**Comment by ocdtrekkie** [comment]
Hard to say for sure at this point.

**Comment by xet7** [comment]
Wefork has been merged back to Wekan.

Move this issue to #797 , please continue discussion there.
