### ISSUE TITLE
Wekan Member - Sandstorm - Cannot remove member

### ISSUE THREAD

**Issue by ertanalytics** [wekan/wekan#731]
Added existing Sandstorm user to board, now cannot remove him.

![accessissue](https://cloud.githubusercontent.com/assets/7130518/20316920/8fec0ba2-ab29-11e6-908d-55d1e29f97c3.JPG)

**Comment by dwrensha** [comment]
The problem here is that Sandstorm does not yet have a way to notify the grain that the user has lost access. We have an open issue about that: https://github.com/sandstorm-io/sandstorm/issues/1863. Note that the user cannot actually access the Wekan grain anymore, even if the grain doesn't know that yet.

**Comment by ertanalytics** [comment]
Thanks dwrensha!  I will make a note and keep track of that other issue.
