### ISSUE TITLE
One-click installation support for Heroku

### ISSUE THREAD

**Issue by brunoqc** [wekan/wekan#76]
It would be nice to also have one-click installation support for Heroku.

**Comment by Slava** [comment]
Isn't there a one-click support for meteor.com? `meteor deploy myapp`?

**Comment by iamale** [comment]
+1. 
Also, supporting Heroku would imply [Dokku][]/[Deis][](?) support automatically (which is fairly common deployment solution afaik).
[Dokku]: https://github.com/progrium/dokku
[Deis]: http://deis.io/

**Comment by mquandalle** [comment]
I'm in favor of “one-click” - or more generally “simple” - installation for all platforms where some users will want to run LibreBoard on. That's why we added Sandstorm support (one click installation on your own machine), and we plan to add docker signed images. I never used Heroku (or docker based open alternatives like Dokku or Deis) but IIRC we need to write a “buildpack”, is that correct? I imagine we could take advantage of using meteor here, since we really don't do anything fancy a buildpack for a standard meteor application should work for LibreBoard.

As tagged, PR encouraged!

**Comment by andreioprisan** [comment]
Creating an Amazon AMI would also be a good option here, helping companies justify a self-hosted option and drive adoption easily.

**Comment by iamale** [comment]
Quick [ducking](https://duckduckgo.com/?q=meteor+buildpack) shows that there is already [a Meteor buildpack](https://github.com/jordansissel/heroku-buildpack-meteor) so it should be only a matter of writing a few lines in README.

@andreioprisan I'm not sure about AMI, mainly because I have'nt worked with AWS that much. Could you go into some more detail? Just a bit.

**Comment by andreioprisan** [comment]
An Amazon AMI is a machine image (http://docs.aws.amazon.com/AWSToolkitVS/latest/UserGuide/tkv-create-ami-from-instance.html) that you can create and publish on Amazon, so that others can use. For instance, there are AMIs for Wordpress installs. 
Then, anyone can launch that public AMI under their private account without worrying about having the right setup and versions of packages etc. from scratch.
The AMIs would be versioned for each major release.

**Comment by krichtof** [comment]
I just made a PR for a "one click deploy" on heroku ;)
https://github.com/libreboard/libreboard/pull/188

**Comment by iamale** [comment]
@krichtof Your PR seems to [have failed CI build](https://travis-ci.org/libreboard/libreboard/builds/66443478) :(

**Comment by krichtof** [comment]
@iamale  I don't think it's due to my PR. In fact, if you have a look to https://travis-ci.org/libreboard/libreboard/builds, you'll see that there is a lot of commits that made failed CI build (since build #457, one month ago)

**Comment by AdrianoCahete** [comment]
It's working right now?

**Comment by mquandalle** [comment]
Now it is!
