### ISSUE TITLE
Add feature: Move or copy cards from one board to another.

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#797]
_From @xet7 on December 14, 2016 19:33_

Original issue: https://github.com/wekan/wekan/issues/725

Or said another way, import cards from another board.

Could be also related to https://github.com/wefork/wekan/issues/39

_Copied from original issue: wefork/wekan#47_

**Comment by xet7** [comment]
_From @soohwa on December 15, 2016 13:33_

And / or maybe the possibility to import the json just exported (from wekan) ?

**Comment by xet7** [comment]
From #388

@hsduk

Hi
FYI: I have pushed a card clone feature to https://github.com/hsduk/wekan/tree/plugin-simple-timer

**Comment by xet7** [comment]
Also related to https://github.com/wekan/wekan/pull/446

**Comment by m1L31s** [comment]
Is this still on the roadmap and work in progress?

**Comment by xet7** [comment]
@m1L31s 

Yes.
https://github.com/wekan/wekan/wiki/Roadmap

Copying cards within one board https://github.com/wekan/wekan/pull/1204 will be merged soon.

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...

**Comment by remcooverweg** [comment]
Could anyone let me know if this is still being worked on? Move/Copy card from one board to another board for the Sandstorm Wekan.

**Comment by ocdtrekkie** [comment]
@remcooverweg Nobody is working on that at present, particularly with regards to the Sandstorm version. In order to do that, we would need to use Sandstorm's powerbox feature, of which only a handful of developers (none of which currently contribute to Wekan) have used.

My hope is that the recent internationalization features of Sandstorm will lead to an uptick in Sandstorm users and contributors, which may eventually expand out into more contributors making Sandstorm features work well in other apps.

**Comment by remcooverweg** [comment]
Thanks for the quick reply. If it becomes available on Standalone Wekan i will see if i can make a switch.

**Comment by remcooverweg** [comment]
@ocdtrekkie This is possible with the stand-alone feature of Wekan right? You mentioned this earlier in the posts above. Let me know, then i will test out the standalone version, thanks!

**Comment by ocdtrekkie** [comment]
I don't follow standalone very closely, but xet7 is pretty good about closing issues that are resolved. Since this issue is still open, my guess is standalone doesn't have this feature either. I do know it would be *easier* to code this with standalone Wekan than with Wekan for Sandstorm, but that doesn't mean anyone is working on it either.

**Comment by xet7** [comment]
@remcooverweg 

There is no feature yet to move card to another board at Standalone and Sandstorm. For Standalone development is still in progress:
https://github.com/wekan/wekan/wiki/Roadmap

If this feature is important for you, in Standalone and/or Sandstorm, please add to bounty:
https://www.bountysource.com/issues/41780302-add-feature-move-or-copy-cards-from-one-board-to-another

**Comment by symphonyxrv** [comment]
hello @xet7 any update for that feature ? 
Regards.

**Comment by xet7** [comment]
@killua-eu 

Bounty to @GhassenRjab :+1:

**Comment by remcooverweg** [comment]
Thanks guys!, i will checkout the stand-alone version, since this is a very nice feature to have when you want to delegate tasks to other teams :D

**Comment by killua-eu** [comment]
@xet7 , can't login to Bountysource with my Github account. Anyone seeing the same problem?

**Comment by xet7** [comment]
@killua-eu 

Yes there's that problem, I did use other login method like forgot password or something else, with those I was able to login.

**Comment by killua-eu** [comment]
@xet7 - wow, thats such a convoluted way of getting into the account that I didn't even consider. Bountysource didn't feel like replying me, so thanks lots for the tip. Bounty released to @GhassenRjab , thanks lots!
