### ISSUE TITLE
Add Feature: Import/Export labels

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#813]
_From @whittssg on January 13, 2017 20:21_

Just putting this here before i forget about this - i will fill out the details later.

_Copied from original issue: wefork/wekan#66_

**Comment by xet7** [comment]
@whittssg 

What details?

**Comment by whittssg** [comment]
Hi, sorry completely forgot about this.. I wanted someway to import previously created labels so that we didnt have to recreate them each time.. Or someway to create labels and then save them as a set. Then when we create a new board there can be an option that says. Use labels from X set. 

I then realized that the board import PR (https://github.com/wekan/wekan/pull/446) includes labels as well so that probably covers it. But it still would be nice to be able to save sets of labels and then being able to import them to any board.

Thanks,

**Comment by lonix1** [comment]
If the board already exists, then you can't use the "export as template" trick. So this is still a good idea.

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Sync
