### ISSUE TITLE
Error: language th does not exist

### ISSUE THREAD

**Issue by prawee** [wekan/wekan#854]
On login page when choose language with "br, fi, no, sr and th" have this problem
`
Uncaught Error: language br does not exist
....
`

**Comment by xet7** [comment]
@prawee 

Yes, because login screen translations for th is missing, add your translation pull request to:
https://github.com/softwarerero/meteor-accounts-t9n/tree/master/t9n

I already translated fi, but I need to change build scripts to include newest translations of login screen.

You could probably try if logging in with English and then changing language to th works, but that's only temporary workaround.

**Comment by prawee** [comment]
@xet7 
fixed already via translate to https://github.com/softwarerero/meteor-accounts-t9n/tree/master/t9n
 too. 
after him merge and me update repo again that working for me.
thank you.
