### ISSUE TITLE
Reordering checklists has visual glitch (Already added Feature: Reorder Checklists and Checklist entries with click-and-drag, and drag from one checklist to another)

### ISSUE THREAD

**Issue by cyphar** [wekan/wekan#876]
In Trello, you can click-and-drag to move checklist entries (just like cards). While this is mostly a graphical nicety, in my team we might write a checklistlist out-of-order and then later re-order it by priority or the timeline.

**Comment by GuillaumeAmat** [comment]
By *checkpoint* you meant *checklist* right? ;)

**Comment by Nefeth** [comment]
Please this would help immensely with writing action plans which has to be done in order. Multiple times I had to play around with copy pasting multiple lines and it is annoying. Don't know much about the difficultly of this feature though. If it is too hard, then just call it ;)

**Comment by dejIO** [comment]
Any update on whether this can be done? Maybe by dragging and dropping list items?

We are in the process of migrating to Wekan in our office and some of our coworkers are having a hard time adapting their workflow, especially with checklists, to this new software.

**Comment by xet7** [comment]
@dejIO

There could be some open or closed pull request or GitHub issue that also has some drag and drop for labels (or some other drag and drop) already implemented, but somebody would need to find it and add info to this issue.

There are some drag-and-drop features in Wekan elsewhere like when dragging cards in a list.

**Comment by frmwrk123** [comment]
I managed to reorder items in a checklist. That is relatively easy for itself but the hierarchy of the DOM makes it practically impossible. The reason is that the card details and with it the checklist are below the container for the lists. But this container is already a sortable and multiple independent sortables inside a hierarchy don't seem to work with jQueryUI Sortable. For testing purposes I removed the code that makes it a sortable (inside boardBody.js) and immediately the checklist sortable worked.

If that problem is solved then it will be quite easy to implement this feature.

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/pull/1215 

Noticed by @ocdtrekkie

> Quirks:
>
> - Somehow I managed to overwrite a checklist item by dragging and lost a couple that way while rapidly playing with this.
> - You cannot drag into a checklist that has no existing items. So, if you have two lists, you can be dragging around, drag them all into one list, and before you are able to drag them back into the other list, you have to manually add an item to that list so dragging works again.

cc @frmwrk123

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/pull/1215#issuecomment-329415525

From @max-marschall

> The following I actually see (came from 0.37 to 0.38 dockerhub-image):
>
> - Extend existing checklists (before upgrade): Not possible
> - Move checklist-entries from one to another checklist (existing checklist before upgrade): Items are lost immediately
>
> = does not happen with checklists created **after** the upgrade

cc @frmwrk123

**Comment by frmwrk123** [comment]
@max-marschall Well, I suppose the issue here is that I haven't tested the conversion of existing (large) checklists. The reason for this behaviour is likely that the way in which items are added has been changed and there might be database inconsistencies when having checklists created by the old method that get new items with the new behaviour. The only easy solution I can offer is to create new checklists and then dragging the checklist items on the new checklist after a first item was added to the new checklist.

@ocdtrekkie For the first point there would need to be more details to understand what exactly occurred. The second point is true. Something that certainly contributes to this behaviour is the fact that there is only one sortable for each card. For the sortable widget all items are in ONE sortable separated by each other by non-sortable elements. Therefore if you drag an item below the lowest existing item, it will be positioned as the lowest item but not on the new checklist.
Honestly, I don't know how to change this behaviour with an easy solution. There is only one sortable to ensure that new checklists are picked up immediately and items created there can be dragged immediately without closing and reopening the card details.

@xet7 As much as I appreciate fast merges, is a pull request not exactly there to test for such problems before merging it?

**Comment by xet7** [comment]
@frmwrk123 

I did test manually with a small checklist. There is no automated testing yet, because nobody has contributed those tests yet. If pull requests look like they work, don't have lint errors, and don't crash Wekan, they go to new release soon. Then somebody finds problems, creates issue about it, problem is fixed by somebody in pull request. It's always possible to download previous version of Wekan if newest has problems.

**Comment by xet7** [comment]
@frmwrk123 

Also in Open Source project, if somebody does not have time, or does not know how to fix, then usually somebody else thinks it's important and spends the time to fix that bug. So do not take anything personally or take any pressure about this. It's just code.

**Comment by ocdtrekkie** [comment]
@frmwrk123 FWIW, I test releases submitted to the Sandstorm App Market, so my feedback will always come after a release, not a PR. Nothing I commented on here is a release-blocking issue, I'm just throwing out some feedback for possible future improvements.

**Comment by ocdtrekkie** [comment]
@max-marshall's determination explains why I had a hard time replicating the lost checklist items when testing. I only had a few checklist items I had created ahead of upgrading to test with, and I did, indeed, pretty quickly lose all of them.

**Comment by max-marschall** [comment]
Creating new checklists and moving items to these checklists works for me. Not beautiful but no crisis :)
Another hint: When moving items between two checklists information about items status is lost.

@xet7 Yes, just code :)

Thanks again to @frmwrk123 for that fantastic feature...

**Comment by nztqa** [comment]
> Extend existing checklists (before upgrade): Not possible
@frmwrk123
I hope you find [migrations](https://atmospherejs.com/idmontie/migrations) informative. 
https://github.com/wekan/wekan/blob/devel/server/migrations.js

**Comment by ocdtrekkie** [comment]
If it's possible to add a migration that prevents data loss when moving existing checklists, that'd be really worthwhile, IMHO.

**Comment by GhassenRjab** [comment]
I have encountered an issue when copying a card. My card has already a checklist created before adding sort feature, so there were no sort attribute in it. When copying the card I had an error saying sort is required. The solution would be to take into consideration old checklists that has no sort attribute and add the sort attribute on the fly, for example based on the checklist index.

**Comment by ocdtrekkie** [comment]
@GhassenRjab That would probably also fix the bug in this version of Wekan where trying to sort a checklist item which existed before the update causes it to vanish.

If it's possible for someone to fix this, I'd rather wait for that to be fixed before pushing the update to Sandstorm, so we don't have a glitch that causes data loss.

**Comment by ocdtrekkie** [comment]
Is anyone willing to tackle a fix that adds the sort attribute to checklists that don't have it? I just want to know whether or not I should continue to hold the Sandstorm version for a fix.

**Comment by xet7** [comment]
@ocdtrekkie

@GhassenRjab is working on this. Please continue to hold Sandstorm release.

**Comment by xet7** [comment]
@GhassenRjab 

Checklist items now are not lost, but:

1) When moving Checklist item, item loses it state that it is checkmarked.

2) In run-wekan.sh script when running Wekan, there's messages to console about migrations. Are they necessary, could they be removed?

```
./run-wekan.sh
> Starting add-sort-checklists migration.
> Finishing add-sort-checklists migration.
```

**Comment by GhassenRjab** [comment]
@xet7 

I'll check the first point.
As of the second, those messages will appear only one time when the migration occurs and they will be gone if you restart or stop/start Wekan.

**Comment by xet7** [comment]
Related fix: [Keep state of checklist items when moved cross checklists](https://github.com/wekan/wekan/pull/1242)

@ocdtrekkie 

Please test new Wekan version v0.40 and it's fixes, in my tests it did not lose data. If v0.40 works for you too, you can release it to official Sandstorm App Market.

**Comment by ocdtrekkie** [comment]
Reviewing 0.41 is now on my todo list.
