### ISSUE TITLE
Can't scroll left/right on mobile

### ISSUE THREAD

**Issue by mmikeww** [wekan/wekan#882]
I've tried using wekan on mobile, both through the sandstorm demo, and also on the wekan roadmap at indie.host, and I can't scroll left/right by dragging the screen. Chrome on Android

**Comment by xet7** [comment]
@mmikeww 

Wekan roadmap is read-only and not editable for non-loggedin users. Please install Docker version locally and test on local WLAN.

There has been some other reports that Wekan works on Android browser. I have not tested yet.

**Comment by mmikeww** [comment]
I also tried on the sandstorm demo. Initially when adding new columns, the dragging works. But after that I am stuck with no horizontal dragging

> Wekan roadmap is read-only and not editable for non-loggedin users.

This might be a separate bug then, because when trying to drag on mobile, sometimes it re-orders the columns. I tested on desktop too, and I am able to drag to re-order the columns. I think "read-only" should disallow that, no?

**Comment by GuillaumeAmat** [comment]
In fact, you can scroll up/down and left/right but the drag event handlers seem to have the priority.
So, to succeed your scroll, you have to find the exact scroll spot in the screen :P 

For the up/down scroll I use the thin space between the right side of the card and the vertical separator of columns.
For the left/right scroll it's... The same actually...

It would be better to put some delay before the drag handlers win the deal. In order to let the user scroll quickly or move a thing by keeping pressed on the thing he wants to move.
The Trello Android app has a great handling of those cases, in my opinion it can be used as good inspiration source.

**Comment by xet7** [comment]
Moved to #953
