### ISSUE TITLE
Documentation on setting this up on our computer

### ISSUE THREAD

**Issue by blessenm** [wekan/wekan#90]
Is there any documentation on how to get this setup on our own machine. I couldn't find anything.

**Comment by mountwe** [comment]
Same here. I downloaded the zip file and extracted it. The site talks about one-click installer for Sandbox (Sandstorm?) and Docker image. I don't see installers.

**Comment by ocdtrekkie** [comment]
@mountwe Sandstorm is a new cloud platform you can find out more about at https://www.sandstorm.io

It can either be run on a hosted server or any Linux machine. I suggest trying out the Sandstorm demo, where you can install LibreBoard quickly and try it out on their servers to see how it works. ;) Sandstorm is relatively easy to install (one command, basically), if you have a compatible Linux server with a high enough kernel version.

**Comment by ocdtrekkie** [comment]
Also, as a Meteor application, it should be able to be installed or deployed in the same way as any other Meteor application, I believe. So you can look to any information on the Internet as to how to run and/or deploy Meteor applications.

**Comment by blessenm** [comment]
I am considering Libreboard as my company doesn't make it easy to use software which doesn't run on their own servers. We use windows machines over here. It would be really great if there was some steps mentioned in the README on how to get this setup.

Most users may not be familiar with Meteor or Sandstorm. Telling them to go figure out Meteor and its deployment steps is not great. Im just looking for some steps like, download this, use the following commands and go to this url in the browser. This is just my opinion.

But that said, I'll check out Meteor app deployment and see if I can get things working.

**Comment by ocdtrekkie** [comment]
Ah, @blessenm you might hit a snag there. Pretty much everything relating to Meteor (or Sandstorm or Docker) is done on Linux. Someone did port Meteor to Windows, but it is not updated to the latest version, and I am guessing there's not a lot of people that would be able to step you through a Windows deployment of Meteor or a Meteor app.

If you're hoping to host it on something not running Linux, you'd probably not fall within the confines of a readme as it is.

**Comment by blessenm** [comment]
Oh that's unfortunate. I do see Meteor preview releases for windows. Will try that out sometime.

**Comment by ocdtrekkie** [comment]
Someone just told me that one of the core Meteor devs is working on a more official Windows version of Meteor now.

**Comment by mquandalle** [comment]
@blessenm LibreBoard is a web application using the classical client-server architecture. What do you want to do? Install the LibreBoard server on a windows machine? Wrap the client application into a `exe` file? Or something else?

This project is very young (version number 0.7), and we are totally aware of lack of good documentation (and lack of tests, and lack of certain features, and performances...), we'll improve that over time.

**Comment by blessenm** [comment]
@mquandalle  I was hoping to deploy the application in my machine and share my machines ip to my team members so that they can access the board via their browser. So my machine would just act as the server for everyone else to use.

Btw all our work stations are windows based computers.

If this was a php application, I would just put the app in a folder in XAMPP and just share a url like 10:243.222.22/libreboard to my team mates.

**Comment by neandrake** [comment]
I just got this up and running on a local machine and here's what I did.

**Note** I don't know much about meteor, and haven't used much in the way of heavy-npm-library-dependent projects. I'm also not properly schooled on server administration, so check with your IT, etc.

### System
CentOS 7 (Minimal Install) - The main project I install/run at `/var/www/libreboard/`.
1. Create libreboard user
`sudo useradd -r -m -d /var/www/libreboard libreboard`
2. Delete the files created in /var/www/libreboard from useradd (there might be a param to avoid this step). The git clone won't work unless libreboard is empty.
3. `[neandrake@machine /var/www] $ sudo -u libreboard git clone https://github.com/libreboard/libreboard.git`
I used the HTTPS url as I did not want to bother setting up ssh accounts to access github.
4. Note - The minimal install of CentOS 7 has SELinux running under 'Enforcing' mode which means only certain ports allowed to be bound by a process. I previously set the mode for SELinux to 'Permissive' while testing out other services that needed other random ports opened. This involved modifying selinux config file and running a command to actively change the mode. I would expect the service to not properly start with an error about not being able to bind to address/port if this wasn't the case.

### Dependencies
1. Install Mongo - follow instructions on mongo's [website](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux/) - add repo info for mongo then something like:
`$ sudo yum install -y mongo-org`
No additional mongo configuration was necessary at this moment.
2. Install node + npm. I had done this previously on the machine, but should have been something simple like
`$ sudo yum install -y nodejs`
3. Install Meteor - follow instructions from the [website](https://www.meteor.com/install)
`$ sudo curl https://install.meteor.com/ | sh`
4. Install Forever
`$ sudo npm install forever -g`

### Build Libreboard
1. Run Meteor - I first tried running the `build` script in the repo but that did not work (likely something I'm missing with this setup) as it complains something like `'/var/www/libreboard/.meteor' exists, but '/var/www/libreboard/.meteor/meteor' is not executable.`
Instead I run meteor as root, then chown the new directory stuff back to libreboard. I assume when upgrading this step will be required again until this problem is resolved.
```
$ cd /var/www/libreboard
$ sudo meteor build .build --directory
$ sudo chown -R libreboard:libreboard /var/www/libreboard
```
2. Run build script
`[neandrake@machine /var/www/libreboard] $ sudo -u libreboard ./build`
3. Open firewall for the port used by the build script
```
$ sudo firewall-cmd --zone=public --add-port=5000/tcp --permanent
$ sudo firewall-cmd --reload
```

### Completed!
At this point the service is running and I could use it by navigating to the server on port 5000.

**Comment by mquandalle** [comment]
@neandrake Thank you very much for this great tutorial! Even for a completely manual installation like the one who did there are some things we could improve, for instance you shouldn't need to download meteor because we provide the builded nodejs application (for the last version). I imagine we should also update the `build` script.

It would be very cool if you mind copy your post in a new [wiki page](https://github.com/libreboard/libreboard/wiki).

PS: I've seen all the issues you posted, thank you the very detailed explanations. As you can see on the commit I already fixed some of them :-)

**Comment by blessenm** [comment]
@neandrake great stuff. This is a step forward. But like @mquandalle  it would be great if things were a lot more simpler. Should I close this issue or keep this open?

**Comment by mountwe** [comment]
I was going to reply to blessenm's question about but I see that neandrake has done an excellent job.

As for my original post, I have now tried out sandstorm.io. I understand a lot better. You can apparently run your own sandstorm. I tried it on a Linux image I'm running on Oracle VirtualBox. It did not have a new enough kernel to run sandstorm. So I will build another Linux when I have time.

**Comment by neandrake** [comment]
OK So Meteor shouldn't be required to run the service, but it's used to build. I agree with @mquandalle that we could update the repository so that meteor is run, and then a commit is made with the resulting content. We should create a configuration file used by the build script which is not part of the repository (maybe have a sample/default config file which is, and can be used as reference). That way modifications to the build script are system-agnostic and can be tracked in commits, but when configured for specific systems the config file can be modified and not interfere with the git repo.

I will create a Wiki with the information from my previous post. I think I might fork and play around with the build script, resulting in a pull request - before creating the wiki.

**Comment by andreioprisan** [comment]
#76 deals with remote installations on Heroku/Amazon.
Meteor is the framework, it's not required to run but it is required to build it. All you need is nodejs and mnogodb for running.

**Comment by BenoitPel** [comment]
Hi, i search to install Libreboard on debian wheezy without Standstorm and Docker ...

I see 1 comment with intall on CentOs but i need help too adapt this ...

Where are wiki to repertory installation experience ?

thanks

**Comment by Aekschen** [comment]
Thank you neandrake for your guideline!

Here some lines to get it working on a Debian 7 installation with root rights (Turnkey Core VM)

useradd -r -m -d /var/www/libreboard libreboard
cd /var/www/
git clone http://git.libreboard.com/libreboard/libreboard.git
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list

apt-get update
apt-get install -y mongodb-org
curl -sL https://deb.nodesource.com/setup | bash -
apt-get install -y nodejs
curl https://install.meteor.com/ | sh
npm install forever --global
cd /var/www/libreboard
meteor build .build --directory
chown -R libreboard:libreboard /var/www/libreboard
./build
firewall-cmd --zone=public --add-port=5000/tcp --permanent
firewall-cmd --reload

**Comment by BenoitPel** [comment]
Aekschen , i followed your somes lines and few remarks : 
- curl -L its better to see if your command line work instead than curl -sL (silently)
- then add user libreboard and create home directory you need to delete .bashrc, etc to make git clone worked.

I have a problem in build moment, someone have an idea ?


```
root@xx:/xxx/libreboard$ ./build
                                              
WARNING: The output directory is under your source tree.
                                              
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
/
> fibers@1.0.1 install /xxx/libreboard/.build/bundle/programs/server/node_modules/fibers
> node ./build.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/xxx/libreboard/.build/bundle/programs/server/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

npm ERR! fibers@1.0.1 install: `node ./build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the fibers@1.0.1 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /xxx/libreboard/.build/bundle/programs/server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
error:   Forever cannot find process with id: /xxx/libreboard/.build/bundle/main.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: /xxx/libreboard/.build/bundle/main.js
```

**Comment by neandrake** [comment]
@BenoitPel - Does the ".build" directory exist? Make sure you ran meteor:
```
$ meteor build .build --directory
```

**Comment by BenoitPel** [comment]
sorry yes .build directory exist and i run meteor build .build --directory (bad paste sorry) and doesnt work ...

**Comment by neandrake** [comment]
I'm not sure then - looks like the `fibers` package may not exist. You could try running `npm install` somewhere within that directory to try and get npm dependencies to install.

**Comment by BenoitPel** [comment]
```
ls -a /root/.npm/fibers/
.  ..  1.0.1  1.0.5
```

**Comment by neandrake** [comment]
That's installed globally though, right? The output you listed earlier shows that it can't find some fibers file inside:
```
Error: Cannot find module '/xxx/libreboard/.build/bundle/programs/server/node_modules/fibers/build.js'
```

The project is probably sandboxed - defines its own dependencies rather than relying on globally installed dependencies.

**Comment by Aekschen** [comment]
I'm actually experiencing some problems as well. With CentOs as well as with Debian I get this result:

'''
[root@localhost libreboard]# ./build

WARNING: The output directory is under your source tree.

npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.1 install /var/www/libreboard/.build/bundle/programs/server/node_mo                      dules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

fibers@1.0.1 node_modules/fibers

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1
error:   Forever cannot find process with id: /var/www/libreboard/.build/bundle/                      main.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up f                      or at least 1000ms
info:    Forever processing file: /var/www/libreboard/.build/bundle/main.js
'''
I can access the libreboard without any problems and everything looks good on the first sight. Then problems with the user management appear. I can't search for users and add them to the board. The search will just continue without any result. Also I can't perform any actions within the settings section. All Links are not responding. Otherwise all looks functional.

'''
[root@localhost libreboard]# sudo npm install forever -g
/usr/bin/forever -> /usr/lib/node_modules/forever/bin/forever
forever@0.14.1 /usr/lib/node_modules/forever
├── colors@0.6.2
├── timespan@2.3.0
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── utile@0.2.1 (deep-equal@1.0.0, rimraf@2.2.8, ncp@0.4.2, async@0.2.10, i@0.3.2, mkdirp@0.5.0)
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.1, async@0.2.10, pkginfo@0.3.0)
├── nconf@0.6.9 (ini@1.3.3, async@0.2.9, optimist@0.6.0)
├── forever-monitor@1.5.2 (watch@0.13.0, minimatch@1.0.0, ps-tree@0.0.3, broadway@0.3.6)
└── flatiron@0.4.3 (optimist@0.6.0, director@1.2.7, broadway@0.3.6, prompt@0.2.14)
[root@localhost libreboard]#
'''
The forever installation doesn't look suspicious to me.

**Comment by neandrake** [comment]
@Aekschen I think that's just missing functionality from libreboard. The forever error is just stating that it couldn't find a process that looks like the one that it's starting - since it's attempting to restart a service. If it's the first time running then it will show, but continuous runs will not show that error unless the service ends unexpectedly.

**Comment by JamborJan** [comment]
If you want to use it on your own server try the sandstorm.io package of Libreboard. I'm using it only that way on my own server (along with other apps like draw.io). @mquandalle is maintaining the package so you can be sure to have the best version available.

See: https://github.com/sandstorm-io/sandstorm

**Comment by mimoo** [comment]
Any news on a real documentation? I still can't get it to work. I installed meteor, docker and sandstorm but I'm stuck after that.

**Comment by ocdtrekkie** [comment]
@mimoo If you install Sandstorm, you just click the "Install apps" button on Sandstorm, go to LibreBoard, and click Install.

You only need to separately install Meteor if you want to run LibreBoard as a standalone application. The Sandstorm app is a separate version.

**Comment by mimoo** [comment]
I tried that, I can install the app through Sandstorm, create a libreboard and then... nothing. 

Firefox can't find the server at e8xjx76cy3rcb6orp7oz.myserver.com

**Comment by ocdtrekkie** [comment]
@mimoo That is more likely a Sandstorm.io configuration problem than a LibreBoard problem. @paulproteus would be the best to help you troubleshoot this, though he's at a conference so I am not sure when he may find this and join us here. Some issues like this: https://github.com/sandstorm-io/sandstorm/issues/114 might help you figure out what needs to be done. DNS configuration is currently one of the pain points yet to be fully resolved with Sandstorm.

**Comment by ePirat** [comment]
Added a wiki page about installing Libreboard: https://github.com/libreboard/libreboard/wiki/Install

**Comment by udee297** [comment]
hi,

how to update libreboard to newui

**Comment by judegimeno** [comment]
can i install it in a shared hosting ?

**Comment by ocdtrekkie** [comment]
@judegimeno I haven't heard of any shared hosting that lets you run Meteor apps. There might be one out there somewhere.

**Comment by paulproteus** [comment]
One possibility is meteor.com's hosting, that they provide as a service to
all Meteor users.

**Comment by mquandalle** [comment]
Thanks to @ePirat efforts you know have a wiki documenting Wekan installation. I plan to improve the state of documentation (probably using a [read the docs](https://readthedocs.org/) instance at docs.wekan.io) at a later release. You can also discuss these issues [in the forum](http://discuss.wekan.io).

**Comment by neandrake** [comment]
It would probably be a good idea to link to the Install wiki from the readme that shows on the project landing page.

**Comment by isdzulqor** [comment]
Hello guys, I am newbie in node js and meteor js..
I have a problem when understanding this wekan structure folder. I see that it's not like the Meteor structure folder. My question is what kind of structure folder of this app? And how could I install it in my localhost and re-structuring to be meteor structure folder??
thank you before.. I am sorry I still lay in this case..

**Comment by green-coder** [comment]
Hi, I am a Meteor newbie too. I think that Meteor doesn't have its own folder structure. Instead, it has some rules on the order in which the folders are used, and some [rules about which folder is used for the client and the server](http://docs.meteor.com/#/full/structuringyourapp).

I guess that Wekan is following those rules.

**Comment by kirancornelio** [comment]
Hey all I am getting this error when trying to install on my window machine anybody have any idea installation stuck here

[Window Title]
C:\Project_Files\MeteorProject\wekan-devel\client\components\cards\cardDetails.js

[Content]
There was a problem sending the command to the program.

On the commandprompt, i see the below command executing infinitely.
Downloading meteor-tool@1.3.5_1

**Comment by mahabatta** [comment]
https://rfq.alibaba.com/post.htm?activityCode=HRVPR&activityScene=old_new_buyer&tracelog=refer_link

mohamed ismail
