### ISSUE TITLE
"Unknown error" on register panel

### ISSUE THREAD

**Issue by NoodleBB** [wekan/wekan#921]
When the self registration is disabled and you invite people from Admin Panel, the invited persons can't register themselves with the invitation code in the Register Panel. 
When they filled the fields and register they just get an "Unknown error" message. 

![adminpanel](https://cloud.githubusercontent.com/assets/11850083/24075614/2bd57fca-0c1f-11e7-9b7d-ed962e2b9cad.png)
![email](https://cloud.githubusercontent.com/assets/11850083/24075617/30e69044-0c1f-11e7-97b1-a54a5aac18e6.png)
![register](https://cloud.githubusercontent.com/assets/11850083/24075619/37db817a-0c1f-11e7-8c9c-dc2e571b91c3.png)

**Comment by iAdanos** [comment]
@xet7, @lkisme, I think, it's the same problem: #910

**Comment by NoodleBB** [comment]
Yes. I think you're right. This seems to be the same error.

**Comment by xet7** [comment]
Moved to #910

**Comment by khba** [comment]
I'm afraid this issue is not solved yet. 

It was moved to #910 which is said to have been fixed at #943 but all what #943 does is say "Don't try to send emails if no smtp server configured."

Well I'm having the same pb and here the smtp server is configured and the user can even receive his invitation code. The whole pb is that after receiving his invitation code he can't register with it and get "Unknown error" on the register panel.  And there are no logs on the wekan-app or wekan-db side to help debug.

**Comment by xet7** [comment]
@khba 

Does this also happen on newest Meteor 1.4 Docker image?
https://github.com/wekan/wekan/wiki/Platforms

**Comment by khba** [comment]
It works with the image wekanteam/wekan:meteor-1.4 
Thanks !
