### ISSUE TITLE
Add Feature to Admin Panel: SMTP test, show possible errors on that test webpage

### ISSUE THREAD

**Issue by vampirefrog** [wekan/wekan#949]
Please enable logging (just output to stdout) of any email errors that occur. This would save people time if their emails aren't being sent. The SMTPClient (programs/server/npm/node_modules/meteor/email/node_modules/simplesmtp/lib/client.js) class has built-in logging, so you can easily use that. It can be disabled later. Perhaps you can add an environment variable such as MAIL_DEBUG=1 that is in the setup examples, I am sure that would save people a lot of time. It would have saved me 3 days of trying to get it to send emails. Thanks

**Comment by xet7** [comment]
@vampirefrog 

I changed issue topic for adding SMTP test to Admin Panel, so disk is not filled with logs.

**Comment by Zokormazo** [comment]
This has a problem.

To be able to send a mail with meteor, you must set MAIL_URL env variable with the new server config, there is no way to use a custom smtp server for a individual email.

So if we implement this, we'll have to change MAIL_FROM to the data on admin-panel for the test, and at that moment is posible to be someone else making somo action that send an email (invite, register...) so that other mail could go with the testing MAIL_FROM too.

**Comment by xet7** [comment]
Ok, seems that this is not possible currently because of Meteor.

**Comment by Zokormazo** [comment]
I was thinking about this. Althorught the proposed feature is not possible, it would be possible to add a button to send a test mail with the current setted settings.

Something like 'Send test email' that sends a mail to the admin user that uses?
