### ISSUE TITLE
SPK wekan

### ISSUE THREAD

**Issue by lolovoisin** [wekan/wekan#998]
Hi everybody,

I try to install wekan but unfortunatly I have no acccess to internet inside my company.
I'm looking for the spk to install it directly in sandstorm by downloading the application, but I did'nt find it.

Do you know if there is a place where I can download the final SPK to install it ?

thank a lots.

Lolo

**Comment by ocdtrekkie** [comment]
This is really a case of https://github.com/sandstorm-io/sandstorm-app-market/issues/100 rather than an issue for Wekan to solve.

But this is how you do it for all apps in the Sandstorm App Market:
1. Go to the app's page on the market: https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h
2. Click "Install". You probably need a Sandstorm server to appear here to do this, so you can add oasis.sandstorm.io or really any other URL as a Sandstorm server here.
3. Copy the URL from the Install on x server link, like this: https://oasis.sandstorm.io/install/5a4a7ae7adbcc0876bdab2b0216d6152?url=https://app-index.sandstorm.io/packages/5a4a7ae7adbcc0876bdab2b0216d6152
4. Grab the part of that URL after the url=, like this: https://app-index.sandstorm.io/packages/5a4a7ae7adbcc0876bdab2b0216d6152
5. That link will download the SPK file, though you may have to add the .spk to it.

Those are actually Wekan's URL's, so the last link will download the latest Wekan SPK as of this posting, but let me know if you have any questions about this workaround.

**Comment by lolovoisin** [comment]
Well, thank for this answer. I tried this solution but I think that the restricted access did'nt allow me to finish the install of the SPK.
I will search why, but once again thank for your help ;)

**Comment by soohwa** [comment]
@lolovoisin I don't know your operating system but if your are under linux, maybe you can take inspiration from this [installation](https://github.com/soohwa/sps/blob/master/example/docs/1/wekan.md) by downloading all packages in advance ?

**Comment by lolovoisin** [comment]
soohwa,

Thank or your answer. Unfortunately I think the issue come from the restriction indside my company, but anyway I will try to find a another way.

Thank to all guys
